### ISSUE TITLE
Feature Request: Parent product recipe ingredients: Show the effective product (and take costs/calories from that one)

### ISSUE THREAD

**Issue by ITguy3118** [grocy/grocy#1797] opened 2022-02-20 20:30 UTC
_**EDIT by @berrnd - long conversion below, conclusion / TODO for this request:**_
For parent product ingredients, somehow show the "effective current product" (based on the default consume rule) used and also take the costs and calories from that one.

Example: Parent product "Milk", that's not in stock, but the child product "Milkspecific1" is:
- Already the case:
  - Stock requirements are fulfilled
  - On consuming "Milkspecific1" is taken
- Not already the case / TODO:
  - Somehow show that currently "Milkspecific1" is used (instead of "Milk") and take the calories and costs from that child product

Related to #1241, #721 and #385.

-----

I've searched on this github and the reddit forum, I have seen mentions of this same issue in the past, but i have not seen any plausible solution for this. It would be nice if there was a way to relate similar items to each other for when the are used as ingredients in recipes. Just existing in the "Stock Overview" list it's not so much of a problem, but when making a recipe, using a specifc item and then having a variant to that item makes a lot of extra work to maintain accurate recipe stock as they relate to ingredients. 

Example 1:
Milk
In this screenshot I have 3 different kinds of milk that i have purchased over time... I typically purchase the first 2 types, but sometimes i have to purchase a different type of milk altogether (last on the list) 
![2022-20-02-14_17_26-Products _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/154862598-0f37b92c-02b5-4132-b9d1-2759141c3eda.png)

If I were to use one of these as an ingredient in one or even several recipes.... any time I would switch types/brands of milk, I would have to update each recipe that has used a specific type of milk and update the recipe to what is currently in stock. This creates a lot of extra work for me and anyone who has inventoried grocy in this way.  I have tried using the parent product option, but it doesn't work quite right when it comes to things like cost and calories being shown on the recipe card. 
It would be nice if there was a why to include additional logic that says " Product is the same as: milk 1, milk 2, milk 3, etc. or Product is like: milk 1, milk 2, milk 3. and creates a relationship between each similarly typed product that you would then use in a recipe, the recipe then populates the values of the current item in use. The trigger could be something like....marking the container as 'open' which then uses the values of the currently opened stock entry in the recipe. 

happy to further explain more of my thought process on this, but that is the gist of it.

**Comment by berrnd** [comment] 2022-02-20 21:09
> Product is the same as: milk 1, milk 2, milk 3, etc. or Product is like: milk 1, milk 2, milk 3. and creates a relationship between each similarly typed product that you would then use in a recipe,

Exactly that is what parent products are meant for and how they already work when adding them as a recipe ingredient. grocy uses the first in stock item of any child (default consume rule).

> marking the container as 'open' which then uses the values of the currently opened stock entry in the recipe

The default consume rule is `Opened first, then first due first, then first in first out` (mentioned on multiple places). So when using a parent product "Milk" and only one of any of the specific child products is currently open, exactly that will be picked.

About calories on parent product level a duplicate of #1241. For the rest, I don't see what doesn't work by using parent products.

Also related to #385 and #1459.

**Comment by ITguy3118** [comment] 2022-02-21 00:19
I'll reattempt setting up a parent product again for these, perhaps i didn't understand how it worked, i'll try again and circle back

**Comment by ITguy3118** [comment] 2022-02-21 00:38
Still not working for me, what did i miss? 

![2022-20-02-18_37_02-Recipes _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/154871992-314841f0-3e8f-4558-b0a1-dde07c973121.png)
![2022-20-02-18_37_20-Stock overview _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/154871993-ced66c6f-70cb-4214-9286-3c7f2164e752.png)
![2022-20-02-18_37_31-](https://user-images.githubusercontent.com/90217713/154871994-5d7c96b9-7941-4497-8156-86ac249d73ae.png)
![2022-20-02-18_37_56-Edit product _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/154871995-c3e51bfa-ca6c-4c63-bbe5-e70c9fe0cc46.png)
![2022-20-02-18_38_05-](https://user-images.githubusercontent.com/90217713/154871998-678be6a1-537a-46ea-9334-b6e669a8f415.png)
![2022-20-02-18_38_10-Edit product _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/154871999-589c00d7-0d9a-4b6f-919c-32205b696e9b.png)

**Comment by berrnd** [comment] 2022-02-21 07:36
Sorry, I'm unable to look behind screenshots.

If something doesn't work, please provide a reproducible example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b).

I've created one:
https://test-o9x464x4094mofi0gm144.demo.grocy.info/recipes?recipe=7

"Milk" is the parent product and not in-stock itself, "Submilk04" is in-stock and thus will be taken on consuming the recipe.

If it's still about the calories (and price) of the parent product - still a duplicate of / already tracked in #1241 (and #721). Or #385, which is just kind of another approach of the parent product idea.

**Comment by ITguy3118** [comment] 2022-02-21 13:43
I've created a private demo and copied over a basic example of what i'm experiencing, I've got as close as i can to my actual settings within reason.... the measurement table would be important here, so i've copied over a few basic ones related to milk. I'm still getting similar results, not sure what i'm not understanding or where i'm going wrong. I've looked at your example and also made a few test alterations and still i come up with the same blank values... again, not sure what i'm doing wrong 
[(https://test-1dte7avis0c77ayrvt1bbu.demo-prerelease.grocy.info/stockoverview)]

**Comment by berrnd** [comment] 2022-02-21 13:54
> same blank values

Would be great if you mention about what values you talk exactly, I guess calories/costs, those:

![grafik](https://user-images.githubusercontent.com/2161815/154968334-a8a4f93e-969f-48a8-a376-b80d543a1543.png)

Once again (the third time here): Duplicate of / already tracked in #1241 (and #721).

**Comment by berrnd** [comment] 2022-02-21 14:07
And just to clarify what you would expect for that example, since I'm not sure what you really want in the meantime:

Based on the example:
You want that the ingredient "1 Cup milk" shows the calories and costs of the product "Hy-Vee 2% Reduced Fat Milk - 1 Gal.", because that's the only child product of "milk" currently in-stock, right?

This would be exactly what the referenced other requestes are about...

**Comment by ITguy3118** [comment] 2022-02-21 18:07
Apologies for not being specific, yes, I would expect to see the cost of the price of 1 cup of milk in relation to what i had paid for the total gallon 
Example: 1 gallon of milk = $4.09 ...1 cup of that gallon of milk is 0.01 gal so it would display 0.04 cents since that is what the recipe consumes from that gallon of milk   and also show the amount of calories that 0.01 gallons of milk ( or 1 cup) is 
![2022-21-02-12_01_15-Recipes _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/155006795-e7795a79-5767-4ba8-b180-c4c3068a9555.png)

![2022-21-02-12_01_22-Recipes _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/155006797-adb9eaf7-c0f0-4c5c-bd4f-7497aa9859f7.png)

**Comment by berrnd** [comment] 2022-02-21 18:31
Well, I don't think we'll come to a point where we don't speak about just the same again and again...

Some just one more try based on https://test-1dte7avis0c77ayrvt1bbu.demo-prerelease.grocy.info:

You never purchased "milk" (the parent product), so it has no own price.

To verify that it, simply create another recipe (I did that => "miltest2") which has the child product (which was bought once, so has a price) directly as an ingredient - all what (I think) you expect works there:

![grafik](https://user-images.githubusercontent.com/2161815/155009499-80896993-64bc-48a6-9a35-62c4b8fcb62a.png)

I understand that you want that "milk" (the parent product, in recipe "milktest") just shows/behaves the same (for costs and calories) like when adding the child product directly. Again, that case is for parent products currently not handled, but tracked in the other requests referenced above.

**Comment by ITguy3118** [comment] 2022-02-22 00:46
#I understand that you want that "milk" (the parent product, in recipe "milktest") just shows/behaves the same (for costs and calories) like when adding the child product directly. Again, that case is for parent products currently not handled, but tracked in the other requests referenced above.

ok, i think this is what i've been driving at this whole time. What you've done in 'milktest2' is how i presently do things. Thank you for taking the time to explain. I believe you are correct, issue #721 is most closely related to what i am asking about.

**Comment by berrnd** [comment] 2022-02-22 07:53
> the software cannot presently categorize child products under a parent product and the parent product be used in a recipe that grabs data from the child products and display it in a recipe...is that correct?

There is currently no real difference between parent and child products, both are just products. The only special thing about parent products is on consuming, if the parent product itself is not in-stock, the next (based on the default consume rule) child product get consumed, no more relation or magic between parent/childs currently exists. It makes sense what you want and exactly that magic needs to be created.

> i am going to assume that you're working on a way for it to do that

Any progress is publicly tracked in the corresponding request, there are and never will be promises when something is ready ([README ref](https://github.com/grocy/grocy#roadmap)) - for the particular referenced requests nothing is started yet. But everyone can start implementing it.

> I will continue to update recipes with whatever ingredients i have in stock

Sounds like a lot of work - and what's the practical use case, just to have the costs and calories correct? I guess similiar products commonly have similar values. Consuming already works, that's what I personally use and the initial use case idea for parent products.

**Comment by ITguy3118** [comment] 2022-02-23 01:21
Thanks for confirming my thinking was correct...i was beginning to question my own intelligence lol.  I can appreciate that grocy is an open source project, but I am Devops for my work, I would like to just remain a user of it as i truly do think that you have a great tool here for home management and therefore happy to share my ideals as an end user to make features easier from an end  user perspective. I think you've got a great start on something that could be a real powerhouse of an app, just missing a few details (I hope this comes across as 'constructive'). I care enough to say something to pass on my experience or constructive feedbacks. 

It really is a lot of work  to switch ingredients based on brand,  to me, the entire idea of grocy is total pantry accuracy...I understand that some/most would prefer to simply state items as 'milk', 'sugar', 'chips'...but i like the idea of knowing every detail about what's in my house at any point in time, It helps with maintaining stocks of products, current $$ values of those products, how many calories per meal...all of these pieces presently exist, but they still are somehow treated as seperate entities within the same platform. Puzzling to me. 

a few examples of a practical use case for using generic names for recipes would be...
Milk - common field - used in a recipe 
Hy-Vee 2% Reduced Fat Milk - 1 Gal.  - related to the milk field 
Hy-Vee 2% Reduced Fat Milk - 1/2 Gal. - related to the milk field 
Prairie farms milk - 1 Gal. - related to the milk field 

Since i have started using grocy, I have purchased these different types of milk , the size/quantity i purchase them in is different and so is the brand, but they are all  'milk' 

Another example would be different types of pasta noodles, all used for virtually the same type of recipe, just different noodles  
Pasta 
Good Graces Elbows Gluten Free - 12 oz.
Good Graces Penne Gluten Free - 12 Oz.
Good Graces Rotini Gluten Free - 12 Oz

Another example, spaghetti sauces 

Another example would be Cereal...there would/could be a variance in box size or cereal type, but it's all cereal...
Cereal - common field - used in a recipe 
Fareway Rice Squares - 12oz. - related to the Cereal field and 
General Mills Chocolate Lucky Charms 11 Oz. - related to the Cereal field 
General Mills Lucky Charms with Magical Unicorn Cereal - 10.5 Oz. - related to the Cereal field 
Kellogg's Rice Krispies Cereal - 12oz. - related to the Cereal field 
Post Cocoa Pebbles Cereal, Family Size - 20.5 Oz. - related to the Cereal field 

Pasta Sauce - Common Field 
Full Circle Organic Roasted Garlic Pasta Sauce - 24oz. - related to the Pasta Sauce field 
Full Circle Organic Marinara Pasta Sauce - 24 oz. - related to the Pasta Sauce field 

I could go on and on with examples, but i think you would probably get the idea. 


I think it may help to understand by looking at how i've set up grocy, I've set you up as a test user, I'll leave this active for 1 week, unless geo-blocking occurs, you should be able to get to this site. 
www.shreddergrocy.com 
u: berrndtemp
p: TempPass123
Have a look for exploratory purposes and to gain understanding, but please do not change anything.

**Comment by ITguy3118** [comment] 2022-02-23 19:28
Thank you for looking out, I wasn't aware that it is still publicly available.

**Closed** 2022-04-02 09:54 UTC
Labels: enhancement

**Comment by berrnd** [comment] 2022-04-02 10:04
This is now done - changelog excerpt:

> When a parent product is used as an ingredient, which is currently not in stock itself, the substituted product (so the one which was already taken into account when consuming the recipe) is now displayed below the ingredient and the costs (and calories) are taken from that one, to reflect the current real costs even better

&nbsp;
Example based on the existing one from above:
> "Milk" is the parent product and not in-stock itself, "Submilk04" is in-stock and thus will be taken on consuming the recipe.

New pre-release demo instance:
https://test-xull8l9vdaaeqce0o2pj87.demo-prerelease.grocy.info/recipes?recipe=7

It's now shown that "Submilk04" is the current substitution product for "Milk" due to the parent product "Milk" is currently not in stock itself:

![grafik](https://user-images.githubusercontent.com/2161815/161378126-2ae9b64f-2103-490e-aa91-6ac8a829e8e6.png)

![grafik](https://user-images.githubusercontent.com/2161815/161378139-2cefd1ab-fe36-46cb-b772-3e292e1166ba.png)

Costs and calories are also taken from the substitution product "Submilk04".

**Comment by ITguy3118** [comment] 2022-04-15 15:08
Excellent, I'll check it out
