### ISSUE TITLE
Bug: Using international characters breaks API querying

### ISSUE THREAD

**Issue by duchenpaul** [grocy/grocy#1618] opened 2021-09-18 07:49 UTC
Related to this #1591, same version, same error.
It doesn't work for Chinese characters

curl command
```
curl -X 'GET' \
  'http://grocy.chenny.homes/api/objects/products?query%5B%5D=name~%E8%9E%BA%E4%B8%9D%20M2.5x30' \
  -H 'accept: application/json'
```

In swagger:
![image](https://user-images.githubusercontent.com/8120099/133880983-336373ad-b5ec-467e-9ea7-e0ad51964639.png)

Error:
```json
{
  "error_message": "Invalid query",
  "error_details": {
    "stack_trace": "#0 /app/grocy/controllers/BaseApiController.php(50): Grocy\\Controllers\\BaseApiController->filter()\n#1 /app/grocy/controllers/GenericEntityApiController.php(152): Grocy\\Controllers\\BaseApiController->queryData()\n#2 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\\Controllers\\GenericEntityApiController->GetObjects()\n#3 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#4 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#5 /app/grocy/middleware/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#6 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#7 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()\n#8 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#9 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#10 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#12 /app/grocy/middleware/AuthMiddleware.php(76): class@anonymous->handle()\n#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#14 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()\n#15 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#16 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()\n#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#18 /app/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()\n#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#20 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()\n#21 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#22 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\\App->handle()\n#23 /app/grocy/app.php(106): Slim\\App->run()\n#24 /app/grocy/public/index.php(45): require_once('/app/grocy/app....')\n#25 {main}",
    "file": "/app/grocy/controllers/BaseApiController.php",
    "line": 95
  }
}
```

**Comment by berrnd** [comment] 2021-09-18 17:48
Since #1591 is not yet part of any release, not a real surprise...

Please verify unreleased things via the `master` branch, running at https://demo-prerelease.grocy.info (like also [mentioned in README](https://github.com/grocy/grocy#give-it-a-try)) - your example works there / is therefore also fixed by #1591.

=> https://demo-prerelease.grocy.info/api/objects/products?query%5B%5D=name~%E8%9E%BA%E4%B8%9D%20M2.5x30

**Closed by berrnd** 2021-09-18 17:48 UTC
Labels: invalid

**Comment by duchenpaul** [comment] 2021-09-21 08:14
Thanks for the explaining, is there any date of release?

**Comment by berrnd** [comment] 2021-09-21 08:36
> is there any date of release?

I plan nothing about grocy, also that is [mentioned in README](https://github.com/grocy/grocy#roadmap).

Since everything is done in public, you can simply apply the patch for #1591 manually to have it now.

https://github.com/grocy/grocy/commit/14bb04d285a3c04508f4ba8b837a1de805fd2c34.patch

https://github.com/grocy/grocy/commit/14bb04d285a3c04508f4ba8b837a1de805fd2c34

**Comment by duchenpaul** [comment] 2021-09-22 04:51
I found that despite this fix can avoid the error message, but it doesn't return the correct value.
Here is how I reproduct it:
```
# Get the name of product
curl -X 'GET' \
  'https://demo-prerelease.grocy.info/api/objects/products?query[]=id=30' \
  -H 'accept: application/json' \
  -H 'GROCY-API-KEY: e3dkTKzfj2SxFiDpMW1P55NFcnpoWnza8hKlWCa68Ju5YGWcN6'

# print the name in Chinese charactor
echo -e "\u87ba\u6bcd nut M3"

# Search the name of product
curl -X 'GET' \
  'https://demo-prerelease.grocy.info/api/objects/products?query[]=name=螺母 nut M3' \
  -H 'accept: application/json' \
  -H 'GROCY-API-KEY: e3dkTKzfj2SxFiDpMW1P55NFcnpoWnza8hKlWCa68Ju5YGWcN6'

```

Returns empty, expect to have the same result of searching by product_id -- the 1st command

**Comment by berrnd** [comment] 2021-09-22 08:05
The default demo doesn't have a product with id `30` and the public pre-release demo instance get also resetted 10 minutes past every hour as [stated in README](https://github.com/grocy/grocy#localization).

So to be able to fully check nd persistently reproduce that, I would first create a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) - did that:
=> https://test-a8esm6e2e86rfpoq6v41x.demo-prerelease.grocy.info
=> Your product `螺母 nut M3` (has id `27` there): https://test-a8esm6e2e86rfpoq6v41x.demo-prerelease.grocy.info/product/27

==> Cannot be found via name `equals`: [/objects/products?query[]=name=%E8%9E%BA%E6%AF%8D%20nut%20M3](https://test-a8esm6e2e86rfpoq6v41x.demo-prerelease.grocy.info/api/objects/products?query[]=name=%E8%9E%BA%E6%AF%8D%20nut%20M3)
==> Can be found via name `LIKE`: [/objects/products?query[]=name~螺母](https://test-a8esm6e2e86rfpoq6v41x.demo-prerelease.grocy.info/api/objects/products?query[]=name~螺母)
==> Can be found via id: [/objects/products?query[]=name~螺母](https://test-a8esm6e2e86rfpoq6v41x.demo-prerelease.grocy.info/api/objects/products?query[]=name~螺母)

So turns out this as a completely other problem:
`query[]` values seem to be split by (the first) space, so only `螺母` is used when you provide `螺母 nut M3`. Despite using international characters or not.
=> Will be tracked in #1624.

And just for reference:
The `query[]` parameters are directly translated to corresponding SQL WHERE clause(s) [here](https://github.com/grocy/grocy/blob/14bb04d285a3c04508f4ba8b837a1de805fd2c34/controllers/BaseApiController.php#L104-L133).
So if something doesn't match, another check would be also to query the data manually first to verifiy it's found via that way.
