### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Artur2001** [grocy/grocy#2247] opened 2023-05-29 15:42 UTC
Hello,
I would like to use the software for a food stock. There are recommendations how much of each food group should be stored, e.g.: https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/ratgeber-notfallvosorge-checkliste.pdf?__blob=publicationFile&v=7 

Is it possible to add a parent field above the Product field - Main food group? The main food group consists of a few elements, e.g. "Fish, meat, eggs". Under this main food group are then the food groups, e.g.: tuna, soup, stew, sausage, liver sausage ... . The sense behind it is that one makes later an evaluation and sees whether one of the respective food main group porzentual enough stored according to the recommendations.

Perhaps one could also build the evaluation into the software, so that one enters for how many people one wants to create a stock and for how long. Then you choose the recommendation, e.g. the one from BKK. The software could then say that the main product group "cereals, cereal products, bread, potatoes, pasta, rice" is two kilos too low.

**Comment by berrnd** [comment] 2023-05-29 15:53
Please check existing requests before opening new ones and use the r/grocy subreddit for general usage questions, both is also mentioned on the request template and [in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

&nbsp;
> Is it possible to add a parent field above the Product field

You can add any field you want to any entity (= a product, a chore, a shopping list item, everything else) by utilizing Userfields.

&nbsp;
> main product group "cereals, cereal products, bread, potatoes, pasta, rice" is two kilos too low

Duplicate of #297.

**Closed by berrnd** 2023-05-29 15:53 UTC
Labels: invalid/unreproducible/missing-feedback
