### ISSUE TITLE
Server Error After Update

### ISSUE THREAD

**Issue by JackPala** [grocy/grocy#2410] opened 2023-12-23 16:27 UTC
Updating linuxserver.io docker container caused stock overview to stop working

Error source:
```
/app/www/packages/morris/lessql/src/LessQL/Database.php:110
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: active (View: /app/www/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /app/www/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/www/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/www/packages/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/www/packages/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /app/www/packages/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/www/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /app/www/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /app/www/controllers/StockController.php(123): Grocy\Controllers\BaseController->renderPage()
#10 /app/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->Overview()
#11 /app/www/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /app/www/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /app/www/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/www/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/www/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /app/www/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /app/www/app.php(112): Slim\App->run()
#30 /app/www/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.3",
        "ReleaseDate": "2023-09-02"
    },
    "php_version": "8.2.13",
    "sqlite_version": "3.41.2",
    "os": "Linux 5.13.0-52-generic #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64",
    "client": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/120.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment] 2023-12-23 16:34
> Updating linuxserver.io docker container

None of the community contributed apps/tools integrations are maintained here.

&nbsp;
Would be cool if you could be so kind and do at least a little search beforehand - duplicate of #2284 and #2281, #2325 and #2288 - quoting myself from https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049:

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

**Closed by berrnd** 2023-12-23 16:34 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by JackPala** [comment] 2023-12-23 16:49
> > Updating linuxserver.io docker container
> 
> None of the community contributed apps/tools/integrations are maintained here.
> 
>   Would be cool if you could be so kind and do at least a little search beforehand - duplicate of #2284 and #2281, #2325 and #2288 - quoting myself from [#2281 (comment)](https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049):
> 
> You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

You're right. Apologies - it appears that database migration fixed it, in fact it was running in the background and eventually fixed itself - I was unsure as there was no log output stating a migration in process. But it is good now. Thanks!

**Comment by berrnd** [comment] 2023-12-23 17:03
> in fact it was running in the background

Can't be the case, since nothing in Grocy runs automatically in the background and heals magically itself. It's all about visiting the root route / clicking the logo as [mentioned in README](https://github.com/grocy/grocy#database-migrations) - easy af, yet hard.

But since this request proofed once again that reading (and searching) is apparently too hard for more and more people, everything related to migration handling will be converted into a automatically executed magic job (ref #2384) in the future - since all those reports are just too frustrating for myself lately. So when anything goes wrong in a future release (and if there is even a future release at some point in time at all), it's only my fault, as always. Merry Christmas.

**Comment by JackPala** [comment] 2023-12-23 17:25
> > in fact it was running in the background
> 
> Can't be the case, since nothing in Grocy runs automatically in the background and heals magically itself. It's all about visiting the root route / clicking the logo as [mentioned in README](https://github.com/grocy/grocy#database-migrations) - easy af, yet hard.
> 
> But since this request proofed once again that reading (and searching) is apparently too hard for more and more people, everything related to migration handling will be converted into a automatically executed magic job (ref #2384) in the future - since all those reports are just too frustrating for myself lately. So when anything goes wrong in a future release (and if there is even a future release at some point in time at all), it's only my fault, as always. Merry Christmas.

Sorry to hear that the influx of reports are frustrating. I don't appreciate the condescention though. I only left the ticket because the software said to create an issue, and upon clicking the link it brought me here, so I copied and pasted my error code. I was instructed to do so by the software, and I did. Simple as. I was hoping the data could possibly be useful if anyone else had the same issue. To insinuate that reading is too hard for me? Well that's the type of gatekeeping that does nothing for anyone. I've been doing this for years, but imagine if I was a novice to open source? that type of disrespect would certainly keep any novice away from the community as a whole. Furthermore, I never said anything about it being "your fault"? It's a software bug. **No need to get rude about it.** Have a nice day, and Merry Christmas.
