### ISSUE TITLE
Inventory "OK" Button Unclickable when All Fields Are Populated

### ISSUE THREAD

**Issue by puffinmaster** [grocy/grocy#167] opened 2019-03-08 20:41 UTC
This UI-bug might be related to issue #36.  When entering data on the inventory page occasionally the green "OK" button either stays faded and un-clickable or becomes faded and un-clickable when all of the fields are populated.  I'm believe this issue is related to using tab to navigate between fields instead of clicking.  I rarely have the issue when I click between fields.  This issue is intermittent but frequent.

![grocy inventory error](https://user-images.githubusercontent.com/48361153/54054587-3aea6480-41b0-11e9-8187-7184d155429c.PNG)

**Comment by berrnd** [comment] 2019-03-08 21:28
I have reproduced one way:

![2019-03-08_21-53-42](https://user-images.githubusercontent.com/2161815/54056723-3befb600-41f1-11e9-9863-c8c43bca0a03.gif)

Which seems to be fixed now by the latest changes (try it in the [pre-release demo](https://demo-prerelease.grocy.info/inventory))...

Let me know when you find another reproducible way when this is a problem.

**Comment by puffinmaster** [comment] 2019-03-09 17:37
I found a new bug relating to this in the 2.1.0 release. My keystrokes in the following gif are:

- g
- r
- a
- t
- (Enter)
- 1
- (Tab)
- (Click on "Never Expires")

![v2-1-0-inventroy-bug](https://user-images.githubusercontent.com/48361153/54074989-fcf84980-425e-11e9-9531-cc75d2ef1e4a.gif)

If I click into the "Best Before Field" then click on the check box it registers as a population of that field.

**Comment by berrnd** [comment] 2019-03-09 18:20
Thanks.

Just as a hint: There is also a shorthand for "Never expires" - just type `x`...

**Comment by hauweg** [comment] 2019-05-22 18:24
you must choose a date, before clicking "never expires".

after you choose a date, the green button becomes clickable and stays like this, even if you than click on "never expires" 

if you click on "never expires" the green button stays unklickable as it would not have reseived data (which is mandatory).

good luck :)

**Comment by berrnd** [comment] 2019-05-22 18:43
Tried it, cannot reproduce it...

![2019-05-22_20-42-19](https://user-images.githubusercontent.com/2161815/58200076-3410bf80-7cd2-11e9-8df9-7a1dff3a8313.gif)

**Comment by hauweg** [comment] 2019-05-23 08:04
it happens on my linux computer on firefox and chrome latest version.
it happens on my friends computer with firefox and safari

**Comment by ASMfreaK** [comment] 2019-05-23 12:49
I have the same issue on Chrome on Android

**Comment by berrnd** [comment] 2019-05-23 14:32
Then let's try to improve this again...

I someone be able to make a GIF or describe the exact actions to reproduce this? Or is it just like in my GIF above (tested on latest stable Firefox)?

**Comment by berrnd** [comment] 2019-09-18 16:04
Tried that again and found no reproducible way, so closing this again for now.

Would be best if you could make a video/GIF how this can be reproduced if it happens again...

**Closed by berrnd** 2019-09-18 16:04 UTC
Labels: ui-bug
