### ISSUE TITLE
Feature Request: Add a minimum purchase amount and purchase unit.

### ISSUE THREAD

**Issue by evitaer** [grocy/grocy#2246] opened 2023-05-27 09:13 UTC
I would really like to see the ability to have a minimum inventory and a minimum purchase option. That way when you go below the minimum in the inventory, when it automatically adds it to the shopping list, it puts in a more useful figure for the amount that you want purchase.

It would be nice if you could choose the unit for the shopping list separate to the inventory unit. e.g. I eat by the bun, but purchase by the bag.

It is a really well thought out system, nicely balanced between complexity and usability, keep it up.

**Comment by berrnd** [comment] 2023-05-27 13:09
Duplicate of #1022 - please check existing requests before opening new ones.

&nbsp;

> It would be nice if you could choose the unit for the shopping list separate to the inventory unit.

That's already there, have a look at this product option (and also mind #1355):

![grafik](https://github.com/grocy/grocy/assets/2161815/9330b87e-914f-43c5-9699-dd224f7412f8)

**Closed by berrnd** 2023-05-27 13:09 UTC
Labels: duplicate
