### ISSUE TITLE
Product Image URL

### ISSUE THREAD

**Issue by arjes** [grocy/grocy#832] opened 2020-05-06 02:45 UTC
Got a request to add photo upload from PantryParty's UPC Databases. (https://github.com/PantryParty/pantry_party/issues/47)

The ideal workflow would probably be to have PantryParty send the URL to the Grocy API and let the backend perform the download.

-or-

just store the URL and _not_ download the image at all.

**Comment by berrnd** [comment] 2020-05-06 06:39
Duplicate of #580.

**Closed by berrnd** 2020-05-06 06:39 UTC
Labels: duplicate
