### ISSUE TITLE
Feature Request: Backup module

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2211] opened 2023-05-10 20:14 UTC
It's good if the Grocy have a easy Backup module.
Currently, it's possible with cp commands or scripts, but it's hard for non techs.
A module with option for export/import to zip file is a easy solution

**Comment by berrnd** [comment] 2023-05-10 20:29
Duplicate of #129 - please finally check existing requests before opening new ones. (!)

**Closed by berrnd** 2023-05-10 20:29 UTC
Labels: duplicate
