### ISSUE TITLE
Bug: Wrong unit conversions

### ISSUE THREAD

**Issue by barbax7** [grocy/grocy#1663] opened 2021-11-04 18:01 UTC
When adding new QU conversions inside product's datas, they don't work properly.

I'll do an example with pre-release demo

Define QU `liter`, `milliliter` and `gram` (already present on demo).
For `liter` define a QU conversion that is `1 liter = 1000 milliliters` and create also inverse QU conversion.

Now create a new product `milk` and set `Quantity unit stock` as `liter`
Add QU conversion `1 gram = 1,033 milliliter` (that is milk density)

Go to Inventory or Purchase function and add 1 gram of milk: it displays `This equals 1,033 Liters`
That's wrong! It should be 1,033 milliliters, so 0,001033 liters

I know, too low numbers, so let's try with 100 grams: it displays `This equals 103,3 Liters`, when it should be 103,3 milliliters, so 0,1033 liters

I hope that i was pretty clear, if you repeat these points you should get the same wrong result

Thanks for your attenction and for this great software!

**Comment by berrnd** [comment] 2021-11-04 18:16
That's because QU conversions are currently limited to 1 level, so closing this as a duplicate of #1360.

QU stock is always the base, so we need to go from Liters to Grams for that example:

Product stock QU _Liter_ **_Level 0_**
&nbsp;&nbsp;QU conversion _Liter_ <-> _Milliliter_ **_Level 1_**
&nbsp;&nbsp;&nbsp;&nbsp;Product-QU conversion _Milliliter_ <-> _Gram_ **_Level 2  <-- Currently not supported_**

Defining a conversion between Liters and Grams on the product should work.

**Closed by berrnd** 2021-11-04 18:16 UTC
Labels: duplicate

**Comment by barbax7** [comment] 2021-11-04 18:23
thanks for the explanation
