### ISSUE TITLE
Bug: Database migration problem V3.0.1 to V3.1.0

### ISSUE THREAD

**Issue by Gsyltc** [grocy/grocy#1590] opened 2021-08-21 21:14 UTC
Hi,
I have a problem when switching from V3.0.1 to V3.1.0 (docker linuxserver.io version).
After switching to the new version, the lists of stocks, recipes, products, locations, stores and formats are empty.
The migration of the database does not seem to be done when switching to the new version.

When returning to the old version, all data are present

Thanks

**Comment by berrnd** [comment] 2021-08-21 21:25
I'm sorry, but how do you think I or anyone should help without any details?

So please provide a reproducible example, any concrete error message or other details to track this down, otherwise any help is impossible. Maybe it's also a Docker related problem, then this is the wrong place. Or use the [subreddit](https://www.reddit.com/r/grocy), since that's the better place for general help ([mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests))

If you think database migrations are not applied, this is done when visiting the root route (so clicking on the grocy logo for example) like [mentioned in README](https://github.com/grocy/grocy#database-migrations).

Since [v3.1.1](https://grocy.info/changelog#v3.1.1) was just released with many bug fixes, maybe that' the solution.

Someone reported that also [there](https://www.reddit.com/r/grocy/comments/orzpok) (including a fix, well - clearing the `data/viewcache` directory is [part of the "normal" upgrade instructions](https://github.com/grocy/grocy#how-to-update)), also related to [linuxserver/docker-grocy](https://github.com/linuxserver/docker-grocy)

**Closed by berrnd** 2021-08-21 21:25 UTC
Labels: invalid
