### ISSUE TITLE
Bug: Integrity constraint violation: 19 Unsupported product nesting level detected

### ISSUE THREAD

**Issue by morganmay** [grocy/grocy#1636] opened 2021-10-03 16:55 UTC
When I log into grocy, the default page doesn't load. Instead, I get the following error message. I only get this message on the default page (`[grocyurl]/index.php`); other pages, such as `[grocyurl]/stockoverview` or `[grocyurl]/choresoverview` load and seem to work as expected so far.

Error source:
```
/app/grocy/services/DatabaseService.php:35
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 Unsupported product nesting level detected (currently only 1 level is supported)
```

Stack trace:
```
#0 /app/grocy/services/DatabaseService.php(35): PDO->exec()
#1 /app/grocy/services/DatabaseMigrationService.php(63): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /app/grocy/services/DatabaseMigrationService.php(33): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /app/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /app/grocy/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /app/grocy/app.php(106): Slim\App->run()
#24 /app/grocy/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.1.2",
        "ReleaseDate": "2021-09-27"
    },
    "php_version": "8.0.11",
    "sqlite_version": "3.35.5",
    "os": "Linux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:92.0) Gecko\/20100101 Firefox\/92.0"
}
```

**Comment by berrnd** [comment] 2021-10-03 17:11
>  I only get this message on the default page (`[grocyurl]/index.php`); other pages, such as `[grocyurl]/stockoverview` or `[grocyurl]/choresoverview`

Because database migrations run on the root route ([README ref](https://github.com/grocy/grocy#database-migrations)).

Duplicate of #1542, was fixed in v3.1.1 see [here](https://github.com/grocy/grocy/issues/1542#issuecomment-883697375) for more on this.

If you think that's another problem, please provide a reproducible way (like also mentioned the issue template) - sorry, but it's impossible to help without having something debuggable.

**Closed by berrnd** 2021-10-03 17:11 UTC
Labels: duplicate
