### ISSUE TITLE
Feature Request: Allow addition of location, store in the purchase form

### ISSUE THREAD

**Issue by tetele** [grocy/grocy#2111] opened 2023-01-17 21:47 UTC
I apologize if this idea was already posted, I searched for something similar and haven't found anything, but I may lack the proper jargon as I am a newbie to Grocy.

In the purchase form, I see a very nice popup whenever I type the name of a product which doesn't exist yet, inviting me to add one. I'd like to be able to add locations and stores the same way.

Admittedly, locations shouldn't change very often, but this would be welcome when setting Grocy up for the first time. Stores, on the other hand, can always change. I would like to be able to add a new store on the go, without having to manually go to the master data area.

I realize mandatory userfields may prevent this flow, but it would be a good experience if that's not the case.

I've noticed other places where this pattern would be useful (e.g. product groups when defining a product).

**Comment by berrnd** [comment] 2023-01-17 22:07
Duplicate of #1607, related to #1361, merged in to #584.

**Closed by berrnd** 2023-01-17 22:07 UTC
Labels: duplicate
