### ISSUE TITLE
Feature Request: Filter for "Show only out-of-stock products" on /products

### ISSUE THREAD

**Issue by cakee-ru** [grocy/grocy#2192] opened 2023-04-13 14:54 UTC
the problem:
I have previously bought a lot of niche items I'll never buy again in the future. currently they clog the search when I use purchase/consume. I'd like to delete all products that have no stock entries. preferably with review. or any means to do so, as of now I can't look up all products without stock to manually delete them.

**Comment by berrnd** [comment] 2023-04-13 15:03
Duplicate of #1020 - please check existing requests before opening new ones.

&nbsp;
> they clog the search when I use purchase/consume

Can't be true for [/consume](https://demo-prerelease.grocy.info/consume), since there only currently in-stock products are selectable/searchable.

**Comment by berrnd** [comment] 2023-04-13 16:09
>  that one is about batch edit

Please reread at least the title. It's about being able to edit and _delete_ multiple products at once, you've requested here to be able to delete multiple products, so that's more than obvious the same.

**Comment by berrnd** [comment] 2023-04-13 16:44
> how to find all entries out of stock

I've created a simple [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) snippet to support you right today with that - put the following into `data/custom_js.html`:
```html
<script>
if (Grocy.ActiveNav == "products")
{
	Grocy.Api.Get("stock",
		function(result)
		{
			$(".product-delete-button").each(function()
			{
				var productId = $(this).attr("data-product-id");
				var productNameCell = $(this).parent().parent().find("td").eq(productsTable.colReorder.transpose(1));

				var textColorClass = "text-danger";
				if (FindObjectInArrayByPropertyValue(result, "product_id", productId))
				{
					textColorClass = "text-success";
				}

				productNameCell.append(' <i class="fa-solid fa-circle ' + textColorClass + '""></i>')
			});
		}
	);
}
</script>
```

It will then show a red circle next to each product currently not in-stock on /products (and a green one otherwise) - will look like that:

![grafik](https://user-images.githubusercontent.com/2161815/231828280-b4e199b4-eca3-4f15-a86b-910969e044b3.png)

**Comment by cakee-ru** [comment] 2023-04-13 17:50
> least the title

whelp, I've read it completely multiple times and see no indication about ability to see out of stock items.

**Closed** 2023-04-13 18:36 UTC
Labels: enhancement

**Comment by berrnd** [comment] 2023-04-13 18:37
Changelog excerpt for this:
> - Added a filter option to only show currently out-of-stock products on the products list (master data) page

![grafik](https://user-images.githubusercontent.com/2161815/231852495-1f0f462c-ed1a-4fae-993e-c5e5ada03dce.png)
