### ISSUE TITLE
Feature Request: Allow to attach follow-up tasks to every task

### ISSUE THREAD

**Issue by CodingSpiderFox** [grocy/grocy#1945] opened 2022-07-13 19:03 UTC
As a user I want to automatically add follow-up tasks to tasks so that certain steps are not forgotten.

Example: 
* wash clothes should automatically assign a follow up task "put clothes into cabinet"

**Comment by berrnd** [comment] 2022-07-13 19:07
Guess you mean [chores](https://demo.grocy.info/choresoverview), not [tasks](https://demo.grocy.info/tasks) - then a duplicate of #339.

**Closed by berrnd** 2022-07-13 19:07 UTC
Labels: invalid
