### ISSUE TITLE
Bug: Stock journal doesn't show anything when asked for period of 12 months or more

### ISSUE THREAD

**Issue by Janovlk** [grocy/grocy#2371] opened 2023-11-06 21:31 UTC
Hello,

when I ask for stock journal longer than 6 months (like: https://en.demo-prerelease.grocy.info/stockjournal?months=12) the webpage never shows up. It's blank, no HTML code. In demo it does work, so it is most probably connected with large amount of data in my own database. But it shows no error in webpage or Php, Nginx logs. Processor of my server isn't loaded at all. When I open another page like Stock Overview it works okay again.

May I attach my database to investigate it further? It's 3.9MB. 

Does the system retains all transactions indefinitely? It's not necessary for me. It should do some "cleaning".

Thank you for your work.

JV

**Comment by berrnd** [comment] 2023-11-06 22:05
Sorry, I can't help with or fix anything without having a reproducible example or at least some concrete error messages, as mentioned on the issue template (and you're previous reports here). Closing this unless a reproducible example is provided.

Trying to (probably) display millions of rows of course could require a quite big amount of resources on the server and client, leading to timeouts and similar. That's also why the stock journal (and any journal) is limited to a reasonable time span by default.

&nbsp;
> May I attach my database to investigate it further?

If you have no problem with having your personal instance provided to each and everyone on this planet by that then, sure.

&nbsp;
> Does the system retains all transactions indefinitely?

Yes.

&nbsp;
> It should do some "cleaning".

No, it should definitely not, since the stock journal is the base for anything analysis (ref #64). But nobody is stopping you from deleting whatever you find useless, at least not Grocy. Storing (and querying) trillions of rows is not a general problem for any database, since they're made for exactly that. Properly displaying such an amount (so using paging, client side table rendering and so on) is currently a problem, since it's just not yet done for Grocy's web frontend - therefore the default real life reasonable time span filters.

When it's not necessary for you, the big question would by then why even trying to display such old stock journal entries? Not doing this most likely means not having this "problem".

**Closed by berrnd** 2023-11-06 22:05 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by berrnd** [comment] 2023-11-06 22:31
Here is a demo instance with a little more than 7k stock journal entries: https://test-8wcnf23fuy9t938nkpzw1f.demo-prerelease.grocy.info/stockjournal?months=9999

The stock journal page rendering all of those entries loads here in ~21 seconds (recent Firefox, average-fast desktop machine aka [my couch notebook](https://blog.berrnd.de/mein-netzwerk-oktober-2019-edition)). Of course not as fast as light, but works and any optimizations related to that are not subject to a Bug, more a Feature Request - as just said.

**Comment by Janovlk** [comment] 2023-11-06 22:39
It works for me here, too. It takes few seconds but before it displays anything the header of the Stockjournal is displayed. In my case it doesn't. Are there any means to check the database for errors? I know there is a tool to see all the databases in Sqlite3 file. But it doesn't show anything wrong or suspicious.

**Comment by berrnd** [comment] 2023-11-06 23:01
> Are there any means to check the database for errors?

Well, if I would know the exact reason for a pretty much unspecified problem, you can be sure I'd have told you already what I know or suspect. Can be anything, anywhere - I guess, at least I can't say something more specific on that all.

Just don't know how the first conclusion of so much people is that the database "has an error". Can't remember one case where it was about a broken database. But go on with whatever you think is most likely the cause. E.g. delete the whole stock journal (= the `stock_log` table) if any history (and average prices and everything else what's based on that) is useless for you and you think the origin for all problems lies there.
