### ISSUE TITLE
Feature request: Quick create unit from product add page

### ISSUE THREAD

**Issue by ArchdukeTim** [grocy/grocy#1361] opened 2021-02-20 04:28 UTC
Often times I'll be adding a product when I realize I haven't create the proper stock / purchase unit for it. Rather than having to save and edit later, it'd be nice to be able to create the new unit from the product add page

**Comment by Saturo78** [comment] 2021-02-20 07:53
Same for product group and location

**Comment by berrnd** [comment] 2022-04-09 18:00
Duplicate of #584.

**Closed by berrnd** 2022-04-09 18:00 UTC
Labels: duplicate
