### ISSUE TITLE
Feature Request: Roles for chores

### ISSUE THREAD

**Issue by pdbintheusa** [grocy/grocy#2540] opened 2024-05-21 00:57 UTC
The flexibility and functionality of the chores section is quite powerful, however, I'm wondering if roles could be added, even predefined "admin" and "others" where admins can do everything, while "others" can only see their own chores, check them complete, see the calendar of when they've completed their chores, and maybe a couple other things that would be helpful.

My idea is that
1) it would make for a cleaner view for all users once chores have been set up.
2) being able to have kids log in, only see chores (and any other categories the "admins" select, and not be able to delete their own chores off their list would be very nice.
3) only being able to see their own chores means each child can focus on their own chores, not see that their sibling hasn't done theirs yet, or the chore list of their parents, if the parents set up their own chores.
4) with the proper restrictions, kids could manage checking off their own chore list instead of it needing to be managed by the parent because the kids decide to delete everything

Also, I've spent several hours looking for a good self-hosted "chore" list for my kids and I haven't found any that are even semi close.  Yours is very close, and I think it's close enough to use, but it'll also be easy for tech savvy kids (like mine) to figure out how to delete their own chores, assign them to someone else, etc.

**Comment by berrnd** [comment] 2024-05-21 06:58
Grocy is built for your home and this basically includes trust rather than making every little detail riot proof. Parenting problems can never be solved technically (just IMHO). Maybe, really just maybe, forcing your kids on a technical solution is the problem itself which leads to destroying it (again, just IMHO).

Back to for what we're here:
Grocy already has a basic permission system ([manage users page](https://demo-prerelease.grocy.info/users), lock icon per user, [example](https://demo-prerelease.grocy.info/user/2/permissions)). Only give your kids the Chores / "Track execution execution" permission and they will already be unable to delete any master data item.

Filtering for your own chores on the [/choresoverview page](https://demo-prerelease.grocy.info/choresoverview) is possible via the assignment filter. Making this persistent is a duplicate of #1211.

Having a separate calendar for chores is a duplicate #1984 and/or #990.

#444 is also related (a thing I would have fun to implement, but unfortunately my general motivation is rather low currently due to many circumstances).

Closing this as a duplicate since I see nothing new, not already covered by the mentioned duplicates, here.

**Closed by berrnd** 2024-05-21 06:58 UTC
Labels: duplicate

**Comment by pdbintheusa** [comment] 2024-05-21 07:30
So, what you're saying is that Grocy already has the main topic of my comment, which was about permissions, which means that the comment about your assumption of my supposed parenting is moot.

The other things were just interesting features, but not critical things, I thought would be interesting and couldn't find how to do.

I do appreciate the swift response and the help you have provided.  I had gone looking for permissions for users and couldn't find it in the interface, nor on a google search.  I will have another look.

I do hope that circumstances sort themselves out for you, and that either the motivation comes back, or you find the next great thing to do.  From my limited experience with Grocy, you've doing a ton of great things, and your work is appreciated by many.
