### ISSUE TITLE
user permissions

### ISSUE THREAD

**Issue by klausmcm** [grocy/grocy#614] opened 2020-03-15 22:53 UTC
Are there any user permissions at all in grocy? I noticed that the account I created for myself and someone else, let's me change the password for any other account when I'm logged in. Intentional, feature, bug, still to be implemented?

**Comment by berrnd** [comment] 2020-03-16 07:55
No permission management currently, everyone can do everything - duplicate of #263.

**Closed by berrnd** 2020-03-16 07:55 UTC
Labels: duplicate
