### ISSUE TITLE
Bug: SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: period_interval > 0

### ISSUE THREAD

**Issue by LapinouJuteux** [grocy/grocy#1840] opened 2022-04-04 15:05 UTC
Hello,

I am using the grocy component in Home Assistant, I am on 0.17.0. There is an error when I try navigating to the login page. Please see details below, is there anything I could do to restore some standard config to get it back up and running?
I would not lose much so a reset would be ok.
I cannot really point to some sort of root cause, I do not quite know where to start looking.
Thanks
Yvan

Error source:
```
/var/www/grocy/services/DatabaseService.php:35
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: period_interval > 0
```

Stack trace:
```
#0 /var/www/grocy/services/DatabaseService.php(35): PDO->exec()
#1 /var/www/grocy/services/DatabaseMigrationService.php(63): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/grocy/services/DatabaseMigrationService.php(33): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /var/www/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /var/www/grocy/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /var/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /var/www/grocy/app.php(106): Slim\App->run()
#24 /var/www/grocy/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.2.0",
        "ReleaseDate": "2022-02-11"
    },
    "php_version": "8.0.16",
    "sqlite_version": "3.36.0",
    "os": "Linux 5.10.103-v8 #1 SMP PREEMPT Mon Mar 28 11:44:31 UTC 2022 aarch64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko\/20100101 Firefox\/98.0"
}
```

**Comment by berrnd** [comment] 2022-04-04 15:14
Please check existing issues first, duplicate of #1826.

Already "fixed", not yet released.

You have at least one chore with a period type `Dynamic regular` and a period interval of `0` (which makes absolutely no sense). Rectify that and the upgrade will work.

**Closed by berrnd** 2022-04-04 15:14 UTC
Labels: duplicate
