### ISSUE TITLE
Feature Request: How to view the number of products purchased filtered by date?

### ISSUE THREAD

**Issue by gaspe80** [grocy/grocy#2615] opened 2024-11-29 13:43 UTC
Good morning, 

In the software, I am unable to view a summary in terms of the number of products purchased during a specific period. If I go to **Reports -> Expenses**, I can see the total amount spent on each product (filterable by date), but I cannot see the actual number of items purchased.  

On the other hand, if I go to **Diary -> Diary Summary**, I can see the total number of items purchased, but I cannot filter them by date.  

How can I view (for example) the number of a specific product purchased in the last year?  

Thank you,  
Christian

**Comment by berrnd** [comment] 2024-11-29 13:56
> I go to Reports -> Expenses

Being crystal clear is essential to avoid confusion:
No menu or page is named like that, we have one called [Stock report / Spendings](https://demo-prerelease.grocy.info/stockreports/spendings).

&nbsp;
> if I go to Diary -> Diary Summary

And which page should be that? Please use the exact names, no single one is named "Diary".

&nbsp;
> How can I view (for example) the number of a specific product purchased in the last year?

When someone implements such a page / report.

&nbsp;
Duplicate of #64.

**Closed by berrnd** 2024-11-29 13:56 UTC
Labels: duplicate

**Comment by gaspe80** [comment] 2024-11-29 14:51
Sorry but in the Italian version they are called like this.
Now with the demo I looked for the correct names


In the software, I am unable to view a summary in terms of the number of products purchased during a specific period. If I go to Stock report / Spendings, I can see the total amount spent on each product (filterable by date), but I cannot see the actual number of items purchased.

On the other hand, if I go to Stock journal summary, I can see the total number of items purchased, but I cannot filter them by date.

How can I view (for example) the number of a specific product purchased in the last year?

Thank you,

**Comment by berrnd** [comment] 2024-11-29 14:57
> How can I view (for example) the number of a specific product purchased in the last year?

Please read what I just wrote above:

Not yet possible, someone needs to build such a page / report, already tracked / requested in #64.
