### ISSUE TITLE
Bug: Unable to modify stock entry due to "Integrity constraint violation" unless `opened` is selected

### ISSUE THREAD

**Issue by pjrt** [grocy/grocy#1423] opened 2021-03-24 14:02 UTC
Running v3.01 via the Hassio Addon.

See this gif:

![grocy](https://user-images.githubusercontent.com/1610164/112322683-7ff26e00-8c87-11eb-9197-681aa0d4744f.gif)

I am unable to modify the entry unless I tick the `opened` checkbox.

The error in the console is:

```
XMLHttpRequest { 
  onreadystatechange: onreadystatechange(), 
  readyState: 4, 
  timeout: 0, 
  withCredentials: false, 
  upload: XMLHttpRequestUpload, 
  responseURL: "https://grocy.pjrt.dev/api/stock/entry/41", 
  status: 400, 
  statusText: "Bad Request", 
  responseType: "", 
  response: "{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: open IN (0, 1)\"}" 
}
stockentryform.js:51:12
```

I checked https://demo.grocy.info/ and cannot reproduce it there. Not sure what this could mean.

**Comment by berrnd** [comment] 2021-03-24 14:25
Duplicate of #1268 (and #1284, and #1373, and #1390, and #1418), already fixed, not yet released - please check existing issues first before reporting and/or try to reproduce the problem first on the [pre-release demo](https://demo-prerelease.grocy.info/) (both is also mentioned on the issue template).

**Closed by berrnd** 2021-03-24 14:25 UTC
Labels: duplicate

**Comment by pjrt** [comment] 2021-03-24 14:29
I did check, but I guess I didn't enter the right set of words in the search :\

What confused me the most is that https://demo.grocy.info/ didn't have it either. But the fix makes sense, so it must be that indeed. Sorry and thanks!

**Comment by berrnd** [comment] 2021-03-24 14:34
https://demo.grocy.info is the demo of the current/stable release, https://demo-prerelease.grocy.info is the demo of the upcoming release, so including fixes already done but not yet released (also [mentioned on the README](https://github.com/grocy/grocy#give-it-a-try)).
