### ISSUE TITLE
Testing: Maximum of each item

### ISSUE THREAD

**Issue by userbradley** [grocy/grocy#1989] opened 2022-09-04 17:10 UTC
Hi,

My grocy is starting to get quite large (30 locations, 800 Products with upwards of 300 checked in items)

I was wondering at what point grocy will start to have a hard time with this, in terms of the sqlite database.

And then, if it will support an external Database like Postgres/ Mariadb. Falling that, what performance tweaks can be done?

**Comment by berrnd** [comment] 2022-09-04 17:28
How is this meant to be a bug?

Some pages will be of course slower with more data (like the product master data products page), others not.

The best performance tweak: A fast server and client.

In #1750 is an example demo instance with more than a lot of recipes.

I'm personally using my grocy instance for over 4 years, have about 650 products, 17.5K stock transactions, 1.2K tracked chore executions. The database is very big, a little over 4 MB. I don't face any problems regarding performance.

&nbsp;
> if it will support an external Database like Postgres/ Mariadb

No. Duplicate of #89.

When it's maybe just the general "SQLite is no real database"-fear some people, for whatever reason, have, maybe better don't use it. If there are specific and real performance problems, feel free to report them reproducibly here.

**Closed by berrnd** 2022-09-04 17:28 UTC
Labels: invalid

**Comment by userbradley** [comment] 2022-09-05 13:44
> How is this meant to be a bug?

Was more of a question, thanks for answering. 

>  If there are specific and real performance problems, feel free to report them reproducibly here.

Looking at hosting in on Kubernetes, and it will have to be a Stateful set, so was hoping to have multiple grocery front ends attached to one common Database on a High performance server. 

Thanks again @berrnd
