### ISSUE TITLE
Bug: Default quantity added to shopping list using REST API

### ISSUE THREAD

**Issue by andreheuer** [grocy/grocy#1741] opened 2022-01-10 08:21 UTC
I have created a product that has a different purchase QU (e.g. bottle) than default QU (e.g. ml, and 1 bottle = 1000ml). When adding this item to the shopping list using the UI, the purchase QU is selected by default (bottle).

However, the REST api does not support to select a QU during adding items to a shopping list using /stock/shoppinglist/add-product API. The expectation is (from my side) that the purchase QU (bottle) will be used by adding an item to a shopping list (as in the UI), but the default QU (ml) is used. So, if I am adding 1 item of the product to the shopping list, it adds 1ml to the shopping list instead of 1 bottle. From my point of view, it should either use the purchase QU as default or that the QU can be also selected by the REST api call.

This applies to the demo instance and is also tested with 3.1.3.

Happy to discuss.

**Comment by berrnd** [comment] 2022-01-10 08:44
Just to clarify generally: On any API endpoint any amount is related to the products QU stock.

For UI things a duplicate of #1355.

> the REST api does not support to select a QU during adding items to a shopping list using /stock/shoppinglist/add-product API

Not true. The UI uses the API for everything, so the best and most simple way to check how things are done is to utilize your Browsers developer tools and inspect the requests - sample:
```
curl -X 'POST' \
  'https://demo-prerelease.grocy.info/api/stock/shoppinglist/add-product' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "product_id": 27,
  "list_id": 1,
  "product_amount": 5,
  "qu_id": 12
}'
```

**Closed by berrnd** 2022-01-10 08:44 UTC
Labels: invalid

**Comment by andreheuer** [comment] 2022-01-10 09:00
I have checked the documentation of the API which then seems not to be up to date:
![image](https://user-images.githubusercontent.com/10393020/148740216-aa662f8b-a4a3-4a94-a886-594d17a8112d.png)
There is no qu_id parameter mentioned.
