### ISSUE TITLE
Bug: Meal planner not taking in to account total requirements

### ISSUE THREAD

**Issue by userbradley** [grocy/grocy#2020] opened 2022-10-10 18:53 UTC
When creating a meal plan for the week:

Meal `A` on monday has the requirements of `1 red pepper`

Meal `B` on Friday has the requirements of `1 red pepper` 

(The total red pepper count for the week is `2`)

In stock is `1 red pepper` and both meals show up in the planner as having all ingredients filled.

The issue now becomes that because there is a red pepper in stock (Because it's going to get used on sunday) When I click `Add all missing ingredients to shopping list` it does not add the required red peppers as they show up as being in stock, and fulfilling both recipes.

This causes me to compile the shopping list on a sunday, with items in stock (only one) and then as soon as I check the planner, meals are missing items.

I'm thinking it would make sense to add all the ingredients up (so `1 + 1` red pepper) and then check what's in stock and if that will fulfil the weeks requirements.

Let me know if this makes sense!

**Comment by userbradley** [comment] 2022-10-10 18:57
This could also just be an issue with how I am creating my meal plans, so please let me know where I'm going wrong here or if others are also having issues

**Comment by berrnd** [comment] 2022-10-10 19:18
> I'm thinking it would make sense to add all the ingredients up (so `1 + 1` red pepper) and then check what's in stock and if that will fulfil the weeks requirements.
> 
> Let me know if this makes sense!

Of course this makes sense and grocy does that currently and since the meal plan exists, when using the button in the header (which adds missing ingredients for the whole week).

And not a bug, but a feature request - a duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789, #1965 - please search existing requests first).

&nbsp;
Technical background why it is how it currently is, if you're interested:

https://github.com/grocy/grocy/issues/840#issuecomment-626286880:
> Currently the missing amount is only checked on per recipe level, so when 1 pack is already on the shopping list, that's already fulfilled for the second recipe...

https://github.com/grocy/grocy/issues/925#issuecomment-662279863:
> The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

**Closed by berrnd** 2022-10-10 19:18 UTC
Labels: duplicate
