### ISSUE TITLE
Bug: track_date_only chores track wrong day due to mishandling timezone

### ISSUE THREAD

**Issue by karwosts** [grocy/grocy#1799] opened 2022-02-26 01:14 UTC
When pygrocy calls track chores, it submits tracked time in UTC time (+00:00)

```
2022-02-25 16:56:59 DEBUG (SyncWorker_8) [pygrocy.grocy_api_client] -->	POST /chores/2/execute
2022-02-25 16:56:59 DEBUG (SyncWorker_8) [pygrocy.grocy_api_client] 		{'tracked_time': '2022-02-26T00:56:26.640992+00:00', 'done_by': 1}
2022-02-25 16:56:59 DEBUG (SyncWorker_8) [pygrocy.grocy_api_client] <--	200 for /chores/2/execute
2022-02-25 16:56:59 DEBUG (SyncWorker_8) [pygrocy.grocy_api_client] 		b'{"id":"14","chore_id":"2","tracked_time":"2022-02-26 00:00:00","done_by_user_id":"1","row_created_timestamp":"2022-02-25 16:56:59","undone":"0","undone_timestamp":null}'
2022-02-25 16:56:59 DEBUG (SyncWorker_7) [pygrocy.grocy_api_client] -->	GET //api/system/config
2022-02-25 16:56:59 DEBUG (SyncWorker_7) [pygrocy.grocy_api_client] <--	200 for //api/system/config
```

A chore which tracks date only just chomps off the front of the timestamp and stores that as the date, losing the timezone information. 

```
		if ($chore->track_date_only == 1)
		{
			$trackedTime = substr($trackedTime, 0, 10) . ' 00:00:00';
		}
```

Since my local timezone is 8 hours behind UTC, if I track a chore after 4PM on a given day, the chore is tracked tomorrow, not today. 

See log above where I called track chore at 4:56pm on 2/25, pygrocy converts to 12:56am 2/26 in UTC time, and then the date is truncated and becomes 2/26. 

Instead of truncating the tracked time, can it properly figure out the date for the users local time?

I'm not sure if the error is in pygrocy for submitting a timestamp with UTC timezone, or an error in grocy for how it handles the timestamp, so either a fix or some advice for how tracked_time needs to be submitted would be appreciated.

**Comment by berrnd** [comment] 2022-02-26 07:47
Not a bug and a duplicate of #214.

Timezones are currently not handled at all, therefore your server (system + PHP setting) and client need to have the same timezone to make time related things work. That should be the normal use case for any self hosted setup or should be easily solvable by adjusting the timezone settings accordingly, so no real problem.

**Closed by berrnd** 2022-02-26 07:47 UTC
Labels: duplicate

**Comment by karwosts** [comment] 2022-02-26 16:39
Both client and server are both in the same timezone, but the client formats the time in UTC time. So instead of reporting 16:56-08:00, it submits the time as 00:56+00:00.

**Comment by karwosts** [comment] 2022-02-26 16:50
I see, thank you very much for the explanation. My API endpoint does appear to report timezone unexpectedly as UTC.

This install is on Home Assistant with the addon, I know HAOS is set in my local time, I'm not sure if the other settings are accessible to me. I'll poke around and see if its possible to change it somehow.

**Comment by karwosts** [comment] 2022-02-26 16:59
Probably relevant: https://github.com/hassio-addons/addon-grocy/issues/274
