### ISSUE TITLE
Feature request: Combine like items, and round all items up on shopping list

### ISSUE THREAD

**Issue by Pwtucker** [grocy/grocy#1622] opened 2021-09-20 18:00 UTC
I want to start by saying that I've found grocy to be extremely helpful, and I really appreciate the hard work that has gone into the application! 

There is a feature that I would find useful. 

As a user, I would like a button in the shopping list window that combines like items, and rounds all items up to the next default purchase amount. so that I don't have to spend time manually combing and rounding up. 

This would be a small time saver for me.

The flow of how this would be used.  Today vs after feature

Today
1. Create Meal Plan
2. Add all missing items to the shopping list
3. Go through the shopping list and manually combine and round-up for all items
    In this example, I go through and combine the lemons to one line item for 3 lemons (can't buy .17 lemons) default purchase 
    amount is set to 1 piece
![image](https://user-images.githubusercontent.com/25910903/134050326-ccf16284-acb0-4fab-8d1a-5467ba847ac5.png)

4. shop for items 
5. click add to stock button from the shopping list for 3 lemons

After
1. Create Meal Plan
2. Add all missing items to the shopping list
3. On shopping list click button to combine and round-up 
4. shop for items 
5. click add to stock button from the shopping list for 3 lemons

let me know if there is anything I can do to help clarfiy!

**Comment by berrnd** [comment] 2021-09-20 18:20
Duplicate of #1122, also kind of related to #840 and #925 - please check existing requests before opening new ones.

**Closed by berrnd** 2021-09-20 18:20 UTC
Labels: duplicate

**Comment by Revanas** [comment] 2023-07-28 10:00
I have the same requirement regarding "round-up".
 @berrnd you marked that as a duplicate but I found this "round-up" function in non of the related entries.
The idea is if I need 0,5 packs of sugar, the shopping list will round this up to 1 pack of sugar as it is quiet hard to buy only half a pack.
Should I open a new request?

**Comment by berrnd** [comment] 2023-07-28 10:50
> The idea is if I need 0,5 packs of sugar, the shopping list will round this up to 1 pack of sugar as it is quiet hard to buy only half a pack.

We had this topic more than often and I just don't understand the practical problem. Grocy does the math (correctly). When I stay in the supermarket of choice and seeing "0.5 Packs Sugar" on my Grocy shopping list (and they surprisingly don't sell half packs), is it practically really that hard to just pick the whole pack without cutting it into two pieces right there? I never had a practical problem with all that (but I only use Grocy a bit longer than it's published publicly, so of course my practical experience is somehow limited).

Tracking/purchasing sugar in Grams is another option, but of course practically then even harder - imagine there are 126 Grams sugar on your Grocy shopping list and they only sell 1 kg Packs - a scenario worse than your worst nightmare I guess.

To protect you from those nightmares immediately, here is a [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) snippet (for `data/custom_js.html`) which rounds up each and every shopping list item to the nearest full number (it doesn't change data, rounding is applied only for displaying):

```html
<script>
if (Grocy.CurrentUrlRelative == "/shoppinglist")
{
	$(".locale-number.locale-number-quantity-amount").each(function(index)
	{
		var n = Number.parseFloat($(this).text());
		n = Math.ceil(n);
		$(this).text(n.toFixed(0));
	});
}
</script>
```

**Comment by Revanas** [comment] 2023-07-29 07:40
> > The idea is if I need 0,5 packs of sugar, the shopping list will round this up to 1 pack of sugar as it is quiet hard to buy only half a pack.
> 
> We had this topic more than often and I just don't understand the practical problem. Grocy does the math (correctly). When I stay in the supermarket of choice and seeing "0.5 Packs Sugar" on my Grocy shopping list (and they surprisingly don't sell half packs), is it practically really that hard to just pick the whole pack without cutting it into two pieces right there? I never had a practical problem with all that (but I only use Grocy a bit longer than it's published publicly, so of course my practical experience is somehow limited).
> 
> Tracking/purchasing sugar in Grams is another option, but of course practically then even harder - imagine there are 126 Grams sugar on your Grocy shopping list and they only sell 1 kg Packs - a scenario worse than your worst nightmare I guess.
> 
> To protect you from those nightmares immediately, here is a [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) snippet (for `data/custom_js.html`) which rounds up each and every shopping list item to the nearest full number (it doesn't change data, rounding is applied only for displaying):
> 
> ```
> <script>
> if (Grocy.CurrentUrlRelative == "/shoppinglist")
> {
> 	$(".locale-number.locale-number-quantity-amount").each(function()
> 	{
> 		var n = Number.parseFloat($(this).text());
> 		n = Math.ceil(n);
> 		$(this).text(n.toFixed(0));
> 	});
> }
> </script>
> ```

I will try to explain it in German:

Hi Bernd,
vorab, ich bin tief beeindruckt von Grocy, ich finde du hast da etwas unglaublich gutes erschaffen!
Entschuldige bitte, ich wollte dir mit der Anfrage nicht zu Nahe treten. Dann liegt es vermutlich daran, dass ich Grocy noch nicht vernünftig nutze. Ich erkläre mal kurz wie ich es aktuell verwende und wäre sehr dankbar für einen Tipp wie ich das besser machen kann.

1. Rezepte pflegen
2. Tagesplan erstellen
3. Die Zutaten aus den Rezepten in die Einkaufsliste übertragen
4. Einkaufen und dabei alles in den Bestand übernehmen was gekauft wurde (dabei werden dann die 0,5 Packungen Mehl übernommen)
5. Im Tagesplan die gekochten Rezepte "verbrauchen"

Ich vermute ich hab die Funktion "add this item to stock" in der Einkaufliste falsch verstanden. Für mich hat die in dieser Form keinen Sinn gemacht außer ich passe die Einkaufliste nach Schritt 3 noch einmal manuell an und Runde alles auf ganze Packungen.
Natürlich kann man beim Einkaufen die richtige Menge kaufen, dann müsste ich es aber danach extra erfassen wo ich es doch einfach auf der Einkaufsliste "abhaken/übertragen" könnte. Wie machst du das?

**Comment by berrnd** [comment] 2023-07-29 08:12
> die Funktion "add this item to stock"
> Für mich hat die in dieser Form keinen Sinn gemacht außer ich passe die Einkaufliste nach Schritt 3 noch einmal manuell an

Diese Funktion / dieser Button macht doch nix anderes als [/purchase](https://demo.grocy.info/purchase) vorausgefüllt (Produkt/Menge) zu öffnen. Das MHD muss man (fast) immer sowieso manuell ergänzen, die Menge (ggf.) zu korrigieren dauert geschätzt 0,3 Sekunden länger. Ich mach das so. Ist das jetzt echt ein praktisches Problem? Ich glaube kaum, zumindest für mich nicht. Ich würde aber auch nie auf die Idee kommen den Einkaufszetteleintrag erst noch zu bearbeiten um dann vorausgefüllt die richtige Menge drin stehen zu haben, umständlich, funktioniert aber natürlich genauso, dauert aber geschätzt 10 mal so lang wie einfach genau dort die Menge eben kurz korrigieren.

Aber wie auch immer, nimm doch das Custom JS Snippet von oben und schon hast deine gewünschte Aufrundung. Was wenn jetzt aber 1,8 Pack (bzw. dann gerundet 2) Zucker auf dem Einkaufszettel stehen und du stehst im Rewe und da gibts grad ein "Nimm 3 Zahl 2"-Angebot und du nimmst das? Ich wills mir ja gar nicht ausmalen, da muss man ja dann schon wieder dieses aufwändige Spiel mit der Mengenkorrektur treiben. Ohje.

Noch ein Bericht aus der (meiner) Praxis: Nach dem Einkaufen werf ich alles auf die Küchenarbeitsplatte, dort [hängt ein Notebook](https://grocy.info/img/kitchen-terminal-de.jpg) mit [/purchase](https://demo.grocy.info/purchase) offen. Ich scanne einfach alles und ergänze kurz Menge/MHD. Dauert praktisch nur wenig länger als das, was im Supermarkt an der Kasse passiert. Easy. Schnell. Und wenns an der Kasse mal wieder länger dauert, starte ich diese Aktion oft schon direkt dort vom Smartphone aus.

Ich fokussiere mich für Grocy auf die praktischen Probleme, nicht die theoretischen. Das von dir beschriebene ist genau das, ein theoretisches. Und mit Grocy geht es ja auch generell ums Tracking, also Daten erfassen. Macht man wohl, weils einem irgendwie Spaß macht. Das braucht so oder so mehr Zeit, also wenn mans nicht macht. Die meisten Leuten haben ihren Kühlschrank komplett ohne Grocy unter Kontrolle. Soll heißen: Grocy braucht nicht jeder.
