### ISSUE TITLE
Feature Request: small but effective UI improvements (mostly for dark mode)

### ISSUE THREAD

**Issue by CWempe** [grocy/grocy#1681] opened 2021-11-10 23:25 UTC
I am completely new to grocy and have no experience with UI and design.  
But maybe this qualifies me to give some feedback from a user perspective. 😄 

## recipes

When I first opened grocy I thought: "Other tools like [Tandoor Recipes](https://github.com/TandoorRecipes/recipes) look much better."

## dark mode

Especially the dark mode (which I immediately activated) looks kind of outdated.
I think it looks just a little to "washed".

Here is my quick and dirty try to fix this:

![image](https://user-images.githubusercontent.com/1270359/141202349-255662d7-f9f9-4c2d-ae8c-432b4c9f22a4.png)

I only changed background color, font color and red and green.
It is based on https://material.io/design/color/dark-theme.html.

<details>
  <summary>grocy_night_mode.css diff</summary>

```diff
3,4c3,4
<       color: #c1c1c1;
<       background-color: #333131;
---
>       color: #dddddd;
>       background-color: #121212;
12,13c12,13
<     color: rgba(255, 255, 255, .5);
<     border-color: rgba(255, 255, 255,.1);
---
>       color: rgba(255, 255, 255, .5);
>       border-color: rgba(255, 255, 255,.1);
25c25
<       color: #6c757d;
---
>       color: #246dad;
29c29
<       color: #c1c1c1;
---
>       color: #dddddd;
35c35
<       color: #c1c1c1;
---
>       color: #dddddd;
43c43
<       color: #c1c1c1 !important;
---
>       color: #dddddd !important;
47c47
<       border-color: #c1c1c1;
---
>       border-color: #dddddd;
60c60
<       color: #c1c1c1;
---
>       color: #dddddd;
66c66
<       color: #c1c1c1;
---
>       color: #dddddd;
72,74c72,74
<       color: #c1c1c1;
<       background-color: #6f1b23;
<       border-color: #6f1b23;
---
>       color: #dddddd;
>       background-color: #C62828;
>       border-color: #C62828;
78,80c78,80
<       color: #c1c1c1;
<       background-color: #17642a;
<       border-color: #17642a;
---
>       color: #dddddd;
>       background-color: #2E7D32;
>       border-color: #2E7D32;
87c87
<       color: #c1c1c1;
---
>       color: #dddddd;
94c94
<       background-color: #333131;
---
>       background-color: #121212;
103c103
<       background: #333131;
---
>       background: #121212;
108c108
<       background-color: #333131;
---
>       background-color: #121212;
137c137
<       background-color: #333131;
---
>       background-color: #121212;
143c143
<       background-color: #333131;
---
>       background-color: #121212;
147,149c147,149
<       color: #c1c1c1;
<       background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='4' height='5' viewBox='0 0 4 5'%3e%3cpath fill='%23c1c1c1' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right .75rem center/8px 10px;
<       background-color: #333131;
---
>       color: #dddddd;
>       background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='4' height='5' viewBox='0 0 4 5'%3e%3cpath fill='%23dddddd' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right .75rem center/8px 10px;
>       background-color: #121212;
154,155c154,155
<       background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3e%3cpath fill='%23c1c1c1' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right .75rem center/8px 10px;
<       background-color: #333131;
---
>       background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3e%3cpath fill='%23dddddd' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right .75rem center/8px 10px;
>       background-color: #121212;
161c161
<       background-color: #333131;
---
>       background-color: #121212;
165,166c165,166
<       color: #c1c1c1;
<       background-color: #333131;
---
>       color: #dddddd;
>       background-color: #121212;
170,171c170,171
<       color: #c1c1c1;
<       background-color: #333131;
---
>       color: #dddddd;
>       background-color: #121212;
175c175
<       background-color: #333131;
---
>       background-color: #121212;
188c188
<       background-color: #333131;
---
>       background-color: #121212;
194c194
<       background-color: #333131;
---
>       background-color: #121212;
199c199
<       background-color: #333131;
---
>       background-color: #121212;
205c205
<       background-color: #333131;
---
>       background-color: #121212;
209c209
<       background-color: #333131;
---
>       background-color: #121212;
213c213
<       background-color: #333131 !important;
---
>       background-color: #121212 !important;
220c220
<       background-color: #333131 !important;
---
>       background-color: #121212 !important;
226c226
<       background-color: #333131 !important;
---
>       background-color: #121212 !important;
231c231
<       background-color: #333131;
---
>       background-color: #121212;
245c245
<       color: #c1c1c1 !important;
---
>       color: #dddddd !important;
253c253
<       color: #c1c1c1 !important;
---
>       color: #dddddd !important;
270c270
<       background-color: #333131;
---
>       background-color: #121212;
274,275c274,275
<       color: #c1c1c1;
<       background-color: #333131;
---
>       color: #dddddd;
>       background-color: #121212;
279c279
<       background-color: #333131;
---
>       background-color: #121212;
283c283
<       background-color: #333131;
---
>       background-color: #121212;
288c288
<       background-color: #333131;
---
>       background-color: #121212;
292c292
<       background-color: #333131;
---
>       background-color: #121212;
```
</details>

## table alignment

Another think that bothers me and looks not as professional as grocy is: The buttons in the stock table could be aligned better.
I guess this is not trivial. But maybe some web developer knows some fancy way to fix this. 😇

## too many (white) lines

Especially in the dark mode there are to many while lines/table borders.
I think this is part of the reason why the dark mode does not look as clean as the light mode.

![image](https://user-images.githubusercontent.com/1270359/141204542-19b0c5df-3f05-4581-9448-c65d7208039f.png)

The same goes for the planer:

![image](https://user-images.githubusercontent.com/1270359/141207334-eb347b04-83e5-4839-91f0-26ab7443acc3.png)

Maybe the lines just need to be a little thinner?

## action buttons

The button on the top do not look nice.  
In my opinion it looks "old" that the buttons only have border lines and no fill color.

![image](https://user-images.githubusercontent.com/1270359/141204890-b4fa792a-e0aa-4619-a64f-cc99addea71b.png)

I think this is because the lines work as "shadows" in light mode but in dark mode you need to use a different shade of black to "elevate" the buttons.

![image](https://user-images.githubusercontent.com/1270359/141205134-b29ee6a6-11a7-4363-b988-2f3c1912a993.png)

And it is hard to distinguish between enabled and disabled buttons. (light and dark mode)  
A different background color (light grey?) could make these buttons look more "deactivated".

## search bars

In light mode it looks ok:

![image](https://user-images.githubusercontent.com/1270359/141205310-2b1690a6-0329-49c3-989e-7b1a110a73bd.png)

In dark mode it looks like the darker background behind the icon looks smaller in height than the text field.

![image](https://user-images.githubusercontent.com/1270359/141205413-e0b79e98-bc70-4b72-903b-3674bdd29ab8.png) 
![image](https://user-images.githubusercontent.com/1270359/141205487-6c3c8274-47b1-4b83-a9fa-b6534d765b3c.png)

GitHub fixed this by adding a border around the icon area and making the input field even darker.

![image](https://user-images.githubusercontent.com/1270359/141205929-21ff3d92-0bf0-4a02-9c5e-8f774a68d885.png)

The lines are also thinner.

## inconsistent placement of buttons

Is there a reason, why the buttons for `Save` and `Close` are placed at different areas?

I would place them next to each other.  
Common practice would be the bottom right, I guess.

This is especially annoying when you have to scroll, just to get to the save button.

![image](https://user-images.githubusercontent.com/1270359/141206698-bff574a7-e2bf-49cf-b07a-3426fe28ac84.png)

## filter buttons

![image](https://user-images.githubusercontent.com/1270359/141207951-3bc346f9-6f3d-47d3-9c8c-3b2add29d9ee.png)

I have a few notes:

* Do we need the more saturated line on top of the buttons?  
  I think this does not fit the over all design.
  And it looks like some css gone wrong and did not cover the whole button.
* Should the colors be represented in the table, too?  
  ![image](https://user-images.githubusercontent.com/1270359/141208707-c93d524b-dee1-4cba-bc8f-bc5160898967.png)
  This works for grey, but the blue does not match at all and confused me.
  I have not checked red and yellow, yet.
* This is too much text for just four buttons!
  You do not want to read this every time to find the correct button. (Yes, you will get used to it by time)
  We might not get rid of the text, but I would suggest to add icons in front of the text. Like in the menu on the left.
  People can recognize icons much faster, I think.

## end

This issue got longer than expected. 😄   
But I hope some of these ideas will help to improve this great project.

**Comment by berrnd** [comment] 2021-11-11 07:51
Thanks for all the ideas, but in general, that's all about personal preferences. Something that looks outdated for you is just taste, seems that you prefer material design and dark mode - I'm personally not that much.

So about the dark mode things:
Feel free to just tweak [`grocy_night_mode.css`](https://github.com/grocy/grocy/blob/master/public/css/grocy_night_mode.css), I will merge anything which improves that as is.

Personally I'm prefering a productive UI above UI sugar - and also I'm not so into CSS, that's why grocy's frontend pretty much looks/is plain [Bootstrap](https://getbootstrap.com/), which is still pretty much ok I think.

> Is there a reason, why the buttons for `Save` and `Close` are placed at different areas?

Duplicate of #1367.

So thanks again a lot, but as said, that's mostly about personal taste - you can also use [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to fit any color how you prefer it better.

**Closed by berrnd** 2021-11-11 07:51 UTC
Labels: question

**Comment by berrnd** [comment] 2021-11-11 08:16
When looking at an [old screenshot](https://raw.githubusercontent.com/grocy/grocy/v2.6.0/publication_assets/dashboard.png) (v2.6.0), some things you mentioned where there at that time - taste and preferences also change over time...

**Comment by OmgImAlexis** [comment] 2021-11-11 10:11
Honestly most of what @CWempe has suggested kinda look like accessibility issues.

**Comment by berrnd** [comment] 2021-11-11 11:17
> Honestly most of what @CWempe has suggested kinda look like accessibility issues.

Well, what I read is mainly about (dark mode) colors, how thick lines should be, if a button should be outlined or not, how "clean" or outdated something looks or not - that's all about taste and personal preference. The current state is not unusable.

All fair requests, but the decision is to use (plain) Bootstrap - currently not completely true, some things were customized (by contributors, thanks for that) to make things look "nicer" - I would not do that again, since at the end it looks not uniform.

Accessibility is mostly about ARIA, which is a whole other topic and also practically not existent in grocy as of now.

**So in conclusion:**
- Dark mode: Personally don't care about it, any contriubition (thanks again) will be accepted as is (like before)
- Anything else: Plain Bootstrap is the reference, the goal is to create a uniform and productive UI, nothing more

And honestly, I'm loosing myself too often those time consuming detail-discussion lately, this needs to change again - there are so much more interesting feature requests for grocy which would make it 100 times more useful than having a different looking button or a thicker line somewhere...

**Comment by OmgImAlexis** [comment] 2021-11-11 19:49
I myself find issues with the contrast. It IS an accessibility issue.

Here's a quick lighthouse tests which confirms what I'm saying.


![image](https://user-images.githubusercontent.com/6525926/141359546-8c4fec77-358f-4bb5-b3cd-c5272bfe7bec.png)

**Comment by CWempe** [comment] 2021-11-11 23:54
@OmgImAlexis 

Thanks for backing me up. 😉 👍 

I fully understand @berrnd , too.
If you do not want to spend time on this, you do not have to.

If I decide to use grocy in the long run, I will think about crating a PR for some simple changes.
But I have no experience in this either.

I think the best case would be if a web developer/designer would spend some time to improve the UI.
It is unlikely someone with skill will stumble upon this issue by change, I guess.
Is there a way to ask for help in the user base?
Does anybody have experience with https://issuehunt.io/, https://www.bountysource.com/ etc.? 😄

**Comment by berrnd** [comment] 2021-11-12 07:18
But please keep in mind:
> Plain Bootstrap is the reference, the goal is to create a uniform and productive UI, nothing more

It's not only about a one-shot change to make something look sexy, it's also about maintaining that in the long run. Again, I'm thankful for any contribution - however, my experience (not only for this project) is that maintaining introduced changes does not (or very very rarely happen), so at the end and for grocy this was so far always me, since (however), I'd like to care that things work.

So completely individual/complex things (like the design change for the recipes page), are kind of unmaintainable if you haven't built it yourself from ground up - most likely something like won't be merged again.

**Comment by CWempe** [comment] 2021-11-13 21:05
I totally understand and agree.

Don't worry.
I will not make any complex changes, if any. 😅
