### ISSUE TITLE
Feature Request: asset tracking 

### ISSUE THREAD

**Issue by mr4hughz** [grocy/grocy#1985] opened 2022-08-27 23:37 UTC
instead of "batteries" and "appliance", have a (left) menu item called "assets" and allow total overview of assets and filter per "battery or appliance" (filter that might be directly accessible via (left) menu 

Since every item is store bought, has a receipt, might have a manual, (new price + remaining value (value diminishes over time)), the current options within Grocy should be sufficiant (including "userfields/objects)

**Comment by berrnd** [comment] 2022-08-28 06:43
> the current options within Grocy should be sufficiant (including "userfields/objects)

Well, you named it, it's already possible, so don't know how this should be a Feature Request.

I've took the time and created an example for you, if maybe that's the problem: https://test-wtk3k5ezbwqt2ddxn5idea.demo-prerelease.grocy.info/userobjects/assets

> filter per "battery or appliance" (filter that might be directly accessible via (left) menu

Create separate Userentities if you want to separate that in that way. Searching via the generic search field above each table is possible also for Userentity-lists. Having a filter dropdown per Userfield is a duplicate of #1850.

**Closed by berrnd** 2022-08-28 06:43 UTC
Labels: invalid
