### ISSUE TITLE
Feature request: Receipe Import from Website

### ISSUE THREAD

**Issue by 13hannes11** [grocy/grocy#1156] opened 2020-12-06 13:44 UTC
I am currently using the Nextcloud cookbook and this has a useful import feature where recipes can be imported via URL.
I think it would be useful to have similar functionality for grocy.

Basically for each supported website there could be a custom crawler that gets the needed details for recipes for easier recipe creation.

Possibly the code for the Nextcloud cookbook could be of help: 
https://github.com/nextcloud/cookbook/blob/1b607481298d24cd7afd945993e670f7f61e11b7/lib/Service/RecipeService.php#L779

https://github.com/nextcloud/cookbook/blob/1b607481298d24cd7afd945993e670f7f61e11b7/lib/Service/RecipeService.php#L414

**Comment by berrnd** [comment] 2020-12-06 13:54
Duplicate of #445 and #210, please search existing requests first, thanks.

**Closed by berrnd** 2020-12-06 13:54 UTC
Labels: duplicate
