### ISSUE TITLE
Bug: cannot change stock location via "Edit stock entry" form

### ISSUE THREAD

**Issue by AlesAlitis** [grocy/grocy#1418] opened 2021-03-17 19:53 UTC
Stock entry location cannot be changed with "Edit stock entry" form.

Steps:
1. In Stock overview, click on a product.
2. Click Stock entries.
3. Click edit stock entry.
4. Change location.
5. Click "OK".
6. Inputs will get disabled for a moment, but entry won't get updated.

Grocy version: 3.0.1
Deployment: Grocy 3.0.1, Ubuntu 20.04, Apache 2.4.41, PHP 8.0.3, php-sqlite3 2:8.0+82
Client: Windows 10 Pro 20H2 build 19042.867, Google Chrome 91.0.4442.4 (Official Build) dev (64-bit)

![request](https://user-images.githubusercontent.com/13307869/111527736-87ce8180-8760-11eb-94df-09d872606f07.png)
![response](https://user-images.githubusercontent.com/13307869/111527733-8735eb00-8760-11eb-93bc-4c298cdc0c89.png)

**Comment by berrnd** [comment] 2021-03-17 20:31
Duplicate of #1268 (and #1284, and #1373, and #1390), already fixed, not yet released - please check existing issues first before reporting and/or try to reproduce the problem first on the [pre-release demo](https://demo-prerelease.grocy.info/) (both is also mentioned on the issue template).

**Closed by berrnd** 2021-03-17 20:31 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2021-03-17 20:39
Security hint: Your screenshot above shows a public grocy instance with a currently valid session cookie - if you don't want that anybody who sees this can access your grocy instance I would recommend to quickly invalidate that session...

**Comment by AlesAlitis** [comment] 2021-03-18 09:55
I'm sorry for the spam. Thank you for replaying that fast anyway. I'll make sure to do a better issue search in the future.
