### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by gaspe80** [grocy/grocy#2483] opened 2024-03-01 10:26 UTC
Hello, when i am in stock overview and I select a location, in amount column i see the total pieces of that product (present in all location) and not only the pieces that are in selected location

In example I have 4kg of product "BURRO DI CACAO", 

- 1kg on CASA CHRI location
- 3kg in GELATERIA location

But when I'm filtering from location GELATERIA or CASA CHRI, I see always total kg: 4kg

![WhatsApp Image 2024-03-01 at 11 21 40](https://github.com/grocy/grocy/assets/64086837/a0b15b4c-3c5f-4352-8173-cb5f8acd68fd)
![WhatsApp Image 2024-03-01 at 11 21 58](https://github.com/grocy/grocy/assets/64086837/019d73ac-c129-4912-aa3e-d51e7d52ae99)
![WhatsApp Image 2024-03-01 at 11 22 11](https://github.com/grocy/grocy/assets/64086837/a6932c13-dda3-4a4a-a9cd-126503a41e6f)

Thanks for attention

**Comment by berrnd** [comment] 2024-03-01 11:04
Not a bug and a duplicate of #1531, #1259, #2133, https://www.reddit.com/r/grocy/comments/g44dm2 and https://www.reddit.com/r/grocy/comments/10mkuk7 (and probably more).

The story repeated in short words again here:
- [/stockentries](https://demo-prerelease.grocy.info/stockentries) shows each individual stock entry at each location.
- [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) is the "high level overview" of the total amount in stock per product.

Please be so kind and do it least a little search beforehand.

**Closed by berrnd** 2024-03-01 11:04 UTC
Labels: duplicate

**Comment by gaspe80** [comment] 2024-03-01 11:15
Thanks for rapid replay and sorry if i didn't find the article :(

In desktop is perfect, but with the android app can I see stockentries list or only stockoverview list?

**Comment by berrnd** [comment] 2024-03-01 11:18
> with the android app 

None of the community contributed tools/apps/integrations are maintained here and I personally even don't use any of that (my smartphone has a Browser where Grocy works exactly the same as on any Desktop Browser), so can't help with that at all.
