### ISSUE TITLE
Feature Request: Use Product Name as Quantity Unit

### ISSUE THREAD

**Issue by lakefire** [grocy/grocy#2623] opened 2024-12-24 19:52 UTC
I have been trying to figure out how to setup Quantity Units for items that are their own unit like Apples, Bananas and Eggs for example.  Nothing makes sense at least in English. Piece/Pieces doesn't work as 5 Pieces of Apples means something very different than 5 Apples and 5 pieces of eggs doesn't work at all. Item/Items kind of works, but it still feels awkward to say or read. The counter noun for these items is the item name itself so the only way right now would be to add a quantity unit for every type of product like this. That is potentially a massive amount of entries and very inefficient/duplicate data.  I was thinking an option to select the special case \<use product name\> in the drop down for the Quantity types and an optional field for the singular noun. I think for this type of item the plural would make most sense for the product name and then a singular option for display when there is only 1. Although the other way around would be OK if needed.

**Comment by valadas** [comment] 2024-12-24 20:06
I use Unit/Units

**Comment by berrnd** [comment] 2024-12-24 22:10
That's a very theoretical problem, Grocy (so I) only cares about the practically relevant ones. Technically any unit works, how you name them is up to you - fulfilling a kind of visual fetish around that is definitely a problem out of this project's scope. I personally simply use Piece for all the mentioned items apples/bananas/eggs.

Practically oriented already working workaround:
Create a unit containing only a blank/space character.
Live showcase of that:
=> https://test-g30hyl6m0gxrdlw9c3s0c.demo-prerelease.grocy.info/quantityunit/4
=> https://test-g30hyl6m0gxrdlw9c3s0c.demo-prerelease.grocy.info/stockoverview

Plural handling of product names is a duplicate of #1913 (and at the end exactly the same, don't know if I personally ever "work" on that).

**Closed by berrnd** 2024-12-24 22:10 UTC
Labels: wontfix/out-of-scope

**Comment by badnetmask** [comment] 2024-12-26 13:40
> I use Unit/Units

I suggest using Unit/Units as well. Works for everything, and you don't have to think about how that thing is named.
