### ISSUE TITLE
Feature Request: Enhancement of shopping list

### ISSUE THREAD

**Issue by fideco1981** [grocy/grocy#1694] opened 2021-11-23 12:44 UTC
Just started using Grocy, and I love it!

One feature request is this:

When an item is below minimum stock, when you add it to the shopping list, it will only add amount missing from minimum stock.
Eg. you have 4 eggs minumum stock, you use two eggs, two eggs will be added to the shopping list. 

I'd like to be able to add "phurcase amount" to the products, so that I can add eg. 6 eggs automatic when below minimum.

**Comment by berrnd** [comment] 2021-11-23 12:58
Duplicate of #1355.

**Closed by berrnd** 2021-11-23 12:58 UTC
Labels: duplicate
