### ISSUE TITLE
Bug: PHP fatal error after upgrade from 3.3.1 to 3.3.2

### ISSUE THREAD

**Issue by nihochuha** [grocy/grocy#2044] opened 2022-11-19 16:50 UTC
Grocy installed to LXC container with Debian 11
HTTP server: Apache/2.4.54
PHP 7.4.30

Trying to upgrade grocy with update.sh script. Update is successful, but after update some pages including Stock Overview become unformatted.
Got this messages at error.log:
```
[Sat Nov 19 16:32:05.027340 2022] [php7:error] [pid 230] [client 192.168.8.8:64599] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://192.168.8.20/stockoverview
[Sat Nov 19 16:32:08.260900 2022] [php7:error] [pid 390] [client 192.168.8.8:64601] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://192.168.8.20/stockoverview

```

**Comment by berrnd** [comment] 2022-11-19 16:54
Not a bug and also a duplicate of #2038.

You use PHP 7.4, only PHP 8.0 is supported ([README ref](https://github.com/grocy/grocy#how-to-install)) since [v3.1.0](https://grocy.info/changelog#v3.1.0) (so since nearly 1.5 years).

**Closed by berrnd** 2022-11-19 16:54 UTC
Labels: invalid
