### ISSUE TITLE
Feature Request: location-based inventory mode to remove products

### ISSUE THREAD

**Issue by qay21** [grocy/grocy#2107] opened 2023-01-16 15:09 UTC
Currently, the inventory mode is capable of adding products to a specific storage location, which is good.

However, when the accounted amount is lower than the expected stock of a given storage location, the only way to remove missing products from stocks at this specific storage location is to virtually consume as many goods as necessary.

This is inconvenient, since in stock journal it doesn't make sense to report a missing product as "consumed". Being able to select the storage location in which missing products are removed from stocks would be handy.

Note : I think this issue might be a duplicate, since it seems that such a feature would already be included in the scope of https://github.com/grocy/grocy/issues/1988#issuecomment-1360287273. However, I wasn't sure such a use case was identified, so I opened this new feature in order to avoid asking irrelevant questions to #1988. If this is indeed a duplicate, feel free to close :)

Thanks for this very convenient product !

**Comment by berrnd** [comment] 2023-01-16 15:36
Duplicate of #1988, as you already noted.

**Closed by berrnd** 2023-01-16 15:36 UTC
Labels: duplicate
