### ISSUE TITLE
Feature request: selectable "opened product"

### ISSUE THREAD

**Issue by corbolais** [grocy/grocy#1669] opened 2021-11-06 12:10 UTC
Hi,

Some products are long storage ones. In case I have two items of the same product with distinct due dates and I need to select one item as "opened" it is currently not possible to select the item with the specific due date to mark it as "opened".

It is important to be able to select an item with a specific due date when marking it as "opened".

**Comment by berrnd** [comment] 2021-11-06 12:23
Of course that's already possible (since [v1.23.0](https://grocy.info/changelog#v1.23.0)):
- Using the [/stockentries page](https://demo.grocy.info/stockentries) and the "Mark as opened"-button there
- Using the "Use a specific stock item" dropdown on the [/consume page](https://demo.grocy.info/consume)

The [/stockoverview page](https://demo.grocy.info/stockoverview) is supposed to give an overview and quick access, so there the default consume rule "Opened first, then first due first, then first in first out" would be used when consuming / marking something as opened there.

Also a duplicate of #62 and #86.

(Just want to note that [README mentions](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) the [subreddit](https://www.reddit.com/r/grocy) as the place for general usage questions.)

**Closed by berrnd** 2021-11-06 12:23 UTC
Labels: question

**Comment by corbolais** [comment] 2021-11-06 13:03
> (Just want to note that [README mentions](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) the [subreddit](https://www.reddit.com/r/grocy) as the place for general usage questions.)

Actually, this was no question. But thanks for the pointer.

**Comment by corbolais** [comment] 2021-11-06 13:08
> * Using the [/stockentries page](https://demo.grocy.info/stockentries) and the "Mark as opened"-button there

Never seen that page before. How can I get there w/o direct link?

> * Using the "Use a specific stock item" dropdown on the [/consume page](https://demo.grocy.info/consume)

Oh. I overlooked the gray button. Only noticed the OK button in conjunction w/ consume. And that was not what I wanted to achieve/looked for.

Thank you.

**Comment by berrnd** [comment] 2021-11-06 13:14
> > * Using the [/stockentries page](https://demo.grocy.info/stockentries) and the "Mark as opened"-button there
> 
> Never seen that page before. How can I get there w/o direct link?

- Context/more menu of any line on the stock overview page
- Top right corner of the stock overview page
- "Stock entries"-button of the product card

![grafik](https://user-images.githubusercontent.com/2161815/140610974-cb996f9b-20b0-4508-a47e-0af2bedb8838.png)

![grafik](https://user-images.githubusercontent.com/2161815/140610981-2812692e-6b95-48ef-b9d4-d574ca621cf0.png)
