### ISSUE TITLE
Bug: Edit Stock Entry Fails when saving

### ISSUE THREAD

**Issue by michaelschramel** [grocy/grocy#1284] opened 2021-01-23 12:38 UTC
Open Stock entry
edit price
ok
=> no error
=> no values changed
400 error in chrome console 
/api/stock/entry/<ID>

**Comment by berrnd** [comment] 2021-01-23 13:41
Duplicate of #1268, already fixed, not yet released - please check existing issues first before reporting.

**Closed by berrnd** 2021-01-23 13:41 UTC
Labels: bug, ui-bug
