### ISSUE TITLE
Feature Request: Allow Master Data to Serve as Pick List for Custom Field

### ISSUE THREAD

**Issue by skinnerstein** [grocy/grocy#2055] opened 2022-11-29 15:01 UTC
When adding a user field, I can create a single or multi-select from a list, which is very useful, however, the list of values must be maintained with the user field. If, instead, I could associate the user field to an element of master data (e.g. Products) then I would not need to enter the list of values twice if it is already maintained as master data.

**Comment by berrnd** [comment] 2022-11-29 18:37
Duplicate of #335 - please check existing requests before opening new ones.

**Closed by berrnd** 2022-11-29 18:37 UTC
Labels: duplicate
