### ISSUE TITLE
Feature Request: add cooking duration to recipes and option to automatically add task to prepare recipe in time

### ISSUE THREAD

**Issue by CodingSpiderFox** [grocy/grocy#1944] opened 2022-07-13 16:51 UTC
When I add a recipe I want to be able to optionally enter how long it takes to prepare the meal.
Based on the meal plan, I want to be able to bulk-create tasks for preparing each meal that takes longer than n minutes

**Comment by berrnd** [comment] 2022-07-13 19:05
> When I add a recipe I want to be able to optionally enter how long it takes to prepare the meal.

You can add any field to any object (like recipes) by utilizing Userfields (ref #176).

Similar questions #324, #1126, #1930.

&nbsp;
> Based on the meal plan, I want to be able to bulk-create tasks for preparing each meal that takes longer than n minutes

Duplicate of / generally requested in #553.

**Closed by berrnd** 2022-07-13 19:05 UTC
Labels: duplicate
