### ISSUE TITLE
recipe scrapper via url. 

### ISSUE THREAD

**Issue by nealhamiltonjr** [grocy/grocy#1909] opened 2022-06-05 22:43 UTC
Can the devs take a look at the following project and implement the awesome recipe scrapper / import via url.

https://nightly.mealie.io/

That project is so good at what it does that you should team up with him and pull it into grocy. I'd rather use grocy due to the inventory tracking in general but also cause when you make a recipe it can check that you have everything, add stuff to the list and pull it out of inventory. Also the barcoding to scan things in and out. But, the recipe section is archaic and like copying and pasting to a wiki. The project mentioned scraps the url and gets rid off all the advertising and then pulls in the recipe with pictures and then setups a step by step action. You can then print it off or share it etc. It also has awesome ability to add categories and tags so you can apply Italian or Mexican etc then tag it as Taco's or pulled pork or cornbread. The search feature to pull up what you want is on point and easy. It's beta so the dev might be willing to work with you guys.

**Comment by berrnd** [comment] 2022-06-06 06:37
Duplicate of #210.

Maybe have a look at [recipe-buddy](https://github.com/georgegebbett/recipe-buddy).

**Closed by berrnd** 2022-06-06 06:37 UTC
Labels: duplicate
