### ISSUE TITLE
Feature Request: Get child entries on parent stock entry and journal

### ISSUE THREAD

**Issue by fuhraih** [grocy/grocy#2017] opened 2022-10-04 07:52 UTC
I am creating a parent product (example : chocolate) that is only managed by children products (milk chocolate, dark chocolate,...).
I have disabled the own stock of the parent and never show on stock overview the children products.
When I click on Stock entry for my parent product Chocolate, there is nothing, even if I have entries for children. Same things for Journal.
I can change the filters on the screen, but only 1 product can be selected at a time.
It might be interesting to have a way to display the entries and journal for children products too.
It could be done with a checkbox "Display children entries" or by multiselection of products in the filters.

**Comment by berrnd** [comment] 2022-10-04 08:05
Duplicate of #449.

**Closed by berrnd** 2022-10-04 08:05 UTC
Labels: duplicate
