### ISSUE TITLE
Feature request: Native Product Lookup Integration

### ISSUE THREAD

**Issue by jamesgeddes** [grocy/grocy#1454] opened 2021-04-19 12:25 UTC
As a Grocy user, I want Grocy to natively integrate with a public product database so that when I add a new product by barcode, all fields are completed automatically.

Alternatively, would it be possible for all Grocy users to share their product catalogues to a central community product database? This would allow all of us to benefit from each-others setup. It could be done on a per-instance opt-in basis, with the ability to optionally mark specific products as private. For example, one might be happy to share the barcode, product name and expiry of their butter, bread and frozen pizzas, but might not want everyone to know about their [secret carrots](http://www.carrotmuseum.co.uk/record.html)!

**Comment by Forceu** [comment] 2021-04-19 12:39
Although it is not native, [Barcode Buddy for Grocy](https://github.com/Forceu/barcodebuddy/) does exactly that.

It supports barcode lookup with multiple providers and if you agree to join Barcode Buddy Federation, you can lookup a barcode and get the assigned product names of other Grocy users.

**Comment by berrnd** [comment] 2021-04-19 13:12
As already mentioned by @Forceu, Barcode Buddy already provides everything you mentioned.

In general just a duplicate of #158, so closing this.

Just repeating myself - but I still think that depends heavily on how you use/organize your products in grocy - I personally for example only using generic grocy, not brand specific ones, so my generic products all have multiple barcodes attached, probably wouldn't fit for anyone else, also means I very rarely need to add new products...
Technically the "hardest" part is mapping things like quantity units to the ones in grocy...

**Closed by berrnd** 2021-04-19 13:12 UTC
Labels: enhancement

**Comment by jamesgeddes** [comment] 2021-04-19 14:33
Thanks all. While I do appreciate all the work that has been done on Barcode Buddy, a native plugin or similar would (IMO) be preferable.

@Forceu Is this something you might consider for Barcode buddy?
