### ISSUE TITLE
Feature Request: allow syncing nextcloud cookbook recipies

### ISSUE THREAD

**Issue by meichthys** [grocy/grocy#2037] opened 2022-11-11 20:43 UTC
I have been using Nextcloud Cookbook for a while now to keep track of recipes. It would be really nice to be able to pull the nextcloud recipes into Grocy.

**Comment by berrnd** [comment] 2022-11-11 21:15
Duplicate of #210.

Maybe have a look at [recipe-buddy](https://github.com/georgegebbett/recipe-buddy).

**Closed by berrnd** 2022-11-11 21:15 UTC
Labels: duplicate

**Comment by meichthys** [comment] 2022-11-11 22:40
@berrnd this is a different request. I'm requesting that we integrate with nextcloud cookbook rather than scraping from public websites. 

If this is out of scope, that's fine too.

**Comment by berrnd** [comment] 2022-11-12 07:45
> I'm requesting that we integrate with nextcloud cookbook rather than scraping from public websites.

Please read more than the title, #210 is about a generic way to scrape/integrate external websites (just like what recipe-buddy does). I tend to solve things by a generic approach, rather than focusing on a very specific integration. If the Nextcloud Cookbook App provides the same [schema.org structured metadata](https://schema.org/Recipe), it already works. If not, that's simply missing there.

So yes, integration for a specific app/service/whatever is always out of scope and more something like for an add-on/companion tool like recipe-buddy.
