### ISSUE TITLE
Bug: Recipes don't add the right amount to the shopping list if ingredients are already on it.

### ISSUE THREAD

**Issue by 13hannes11** [grocy/grocy#1848] opened 2022-04-09 12:55 UTC
Suppose you want to make two meals that both contain ingredient A.

Meal 1 needs 1.2 kg of A for 1 serving.
Meal 2 needs 1 kg of A for 1 serving.

You are planning to shop for both recipes and want to do one serving of Meal 1 and two Servings of Meal 2:

1.  Add missing ingredient A for Meal 1 to the shopping list.
2.  Change serving size for Meal 2 to two servings and add ingredient A as well.
3. An incorrect amount is added for Meal 2 (0.8 kg even though it shoulb be 2 kg).

To recreate on the prerelease instance simply copy the pizza recipe, add missing pizza dough to the shopping list.
Chose **two** servings for **Pizza Copy** and add the missing ingredients to the shopping list. The shopping list **should now contain 3 packs** of pizza dough but it actually only contains 2.

**Comment by berrnd** [comment] 2022-04-09 13:00
Not a bug.

Duplicate of #840.

**Closed by berrnd** 2022-04-09 13:00 UTC
Labels: duplicate
