### ISSUE TITLE
Bug: Add new Barcode open an empty modal

### ISSUE THREAD

**Issue by strausmann** [grocy/grocy#2454] opened 2024-01-29 15:54 UTC
I am using Grocy version 4.0.3 and have the following problem. When I open different products for editing, I can't use functions that use a modal window. 
Neither the button to add a new barcode, edit a unit of measure or the "About Grocy" call works.

![image](https://github.com/grocy/grocy/assets/4519228/579041d9-5338-4608-9692-4d8c959c5f93)

I get the following error message in the Browser Developer Console when I want to use the button to add a barcode, for example.

![image](https://github.com/grocy/grocy/assets/4519228/569c7fe5-be71-4c58-a5e2-f742fe4b6ad6)

It has worked before, but I can't say exactly when the problem started because I usually use the Android app.

**Comment by strausmann** [comment] 2024-01-29 15:58
Another short update, the whole thing is used as a Docker container, Traefik v2 is used as a reverse proxy.

**Comment by berrnd** [comment] 2024-01-29 16:34
Duplicate of #2421 (and #2453) - please be so kind ([once again](https://github.com/grocy/grocy/issues/2249)) and do a little search beforehand.

&nbsp;
> It has worked before, but I can't say exactly when the problem started

I can: Since you updated to Firefox 121.

&nbsp;
> I get the following error message in the Browser Developer Console

Nothing on your screenshots shows errors, only warnings and none of them are related to the problem mentioned.

**Closed by berrnd** 2024-01-29 16:34 UTC
Labels: duplicate

**Comment by strausmann** [comment] 2024-01-29 16:36
Thanks for the tip with the search, of course it only works if you know what to look for.
Of course I tried the search first.

**Comment by berrnd** [comment] 2024-01-29 16:44
> Thanks for the tip with the search, of course it only works if you know what to look for.

Even more ideas for next time:
- Trying to reproduce problems first on the [pre-release demo](https://demo-prerelease.grocy.info) (that's even mentioned on the issue template), you would have noticed that this problem is already solved there
- Checking [closed Bug reports labeled with `vNEXT`](https://github.com/grocy/grocy/issues?q=is%3Aissue+milestone%3AvNEXT+is%3Aclosed+label%3Abug) ([README ref](https://github.com/grocy/grocy#roadmap))

But of course not doing all that is still also a valid option for next time too - makes me happy and ensures that all my "Grocy time" goes into request management instead of fixing bugs or creating cool new stuff (exactly that happens since weeks/months).
