### ISSUE TITLE
Feature Request:  Functions I miss

### ISSUE THREAD

**Issue by PhuzerPhuzer** [grocy/grocy#2238] opened 2023-05-20 12:25 UTC
## Englisch

I've been playing around with Grocy a bit now.

Functions that I somehow miss are:
- Distribute tasks to multiple users at the same time (larger tasks that take a lot of time).
- Set task times (user cannot be assigned another task in the time he is doing one task)
- If a person is not at home (working) all day, he should not be assigned a task.
- Email dispatch (task assigned, shopping list new product added, ...)

Maybe this will be taken into account in the next update.

My English is not very good I use DeepL to translate.

## German

Ich habe jetzt ein wenig mit Grocy herumgespielt.

Funktionen die ich irgendwie vermisse sind:
- Aufgaben an mehrere Benutzer gleichzeitig verteilen (größere Aufgaben die viel Zeit in Anspruch nehmen)
- Aufgaben Zeiten einstellen (Benutzer kann in der Zeit in der er eine Aufgabe macht nicht noch eine Aufgabe zugewiesen bekommen)
- Wenn eine Person den ganzen Tag nicht daheim (arbeiten) ist sollte sie keine Aufgabe zugewiesen bekommen.
- Email Versand (Aufgabe zugewiesen, Einkaufsliste neues Produkt hinzugefügt, ...)

Vielleicht wird das bei dem nächsten Update mit berücksichtigt.

Mein Englisch ist nicht besonders gut ich verwende DeepL zum Übersetzen.

**Comment by berrnd** [comment] 2023-05-20 14:35
Please keep it to one topic per request (as mentioned on the request template), everything else is untrackable and please also check existing requests before opening new ones (as also mentioned at the same place).

&nbsp;
> Distribute tasks to multiple users at the same time (larger tasks that take a lot of time).

Duplicate of #1935.

&nbsp;
> Set task times (user cannot be assigned another task in the time he is doing one task)

Chores don't have a timespan, the same goes for tasks. Both is meant to help keeping track of something, nothing more. Practically, the world doesn't end when something is overdue (at least so far). Feel free to open a separate request with some more elaboration about how this should work generically for Grocy.

&nbsp;
> If a person is not at home (working) all day, he should not be assigned a task.

Practically tracking somewhere if a user is at home or not is essentially the same as simply reassigning the corresponding chore...

&nbsp;
> Email dispatch (task assigned, shopping list new product added, ...)

Duplicate of #156.

&nbsp;
> I've been playing around with Grocy a bit now.

From my experience with any software, using it practically instead of only theoretical brings you more into it, and most of the time it turns out that things are just working fine when having more (practical) experience with it. It's impossible to implement everything in exactly your personal comfort zone way. [Custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) is an option to customize everything to your very personal taste.

**Closed by berrnd** 2023-05-20 14:35 UTC
Labels: invalid/unreproducible/missing-feedback
