### ISSUE TITLE
Feature Request: Master Data editor should allow creating new entries by duplicating existing

### ISSUE THREAD

**Issue by jackbradach** [grocy/grocy#1816] opened 2022-03-13 23:30 UTC
I'm entering a large number of descriptors for my shelving (eg, GC2A-R -> "Garage Cabinet #2, shelf A, right side") and realized it'd be useful if I could duplicate an existing entry and then change a few characters.  Even better would be a generator that would let me describe shelving units and then produce the different locations.

**Comment by berrnd** [comment] 2022-03-14 07:58
"Master Data" is kind of everything, guessing you're referring to locations. For that mostly a duplicate of #1607 and/or #1349.

Or practical example how I would do it: Copy/Paste/change the character(s).
I guess the amount of shelving units is not endless and therefore that's a one-time action...

**Closed by berrnd** 2022-03-14 07:58 UTC
Labels: duplicate
