### ISSUE TITLE
Feature Request: Second home support

### ISSUE THREAD

**Issue by fjaraujo** [grocy/grocy#2534] opened 2024-05-05 19:15 UTC
The request consists on to add a parent entity "home_id" to reflect the status of several homes. This entity would affect to entities like inventory, tasks or batteries, but not to the master files like products or barcodes.

**Comment by berrnd** [comment] 2024-05-05 19:35
Duplicate of #644 - please be so kind and do a little search before opening new requests.

**Closed by berrnd** 2024-05-05 19:35 UTC
Labels: duplicate
