### ISSUE TITLE
Option to ignore Stock while adding to shopping list 

### ISSUE THREAD

**Issue by luglda** [grocy/grocy#2150] opened 2023-02-25 16:42 UTC
Hi Guys,
as I understand it is only possible to add missing products from a recipe or a meal plan to the shopping list. 

That´s a good idea but as I want to directly exchange stock products by new products, it would be helpful to get an second button which does ignore the stock products and will add all entrys of a selected receipe. If adding a button is to much, maybe also a global flag "ignore stock at adding to shopping list" or something that way would be helpful.

BR, Daniel

**Comment by berrnd** [comment] 2023-02-25 16:53
Duplicate of #686 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-02-25 16:53 UTC
Labels: duplicate
