### ISSUE TITLE
User Roles and Division of Ownership

### ISSUE THREAD

**Issue by Garonic** [grocy/grocy#2018] opened 2022-10-07 20:41 UTC
I would like to define user roles and an ability to divide ownership of data in Grocy, such that the Permissions screen would look like the following:
=======================================================================
    Roles & Permissions for user Garonic

		Roles:
		    [Account Owner:  Easy Street (My House)]
		     Shopper:  Elegant Place (Parents)
		     Sales Supervisor:  Big Mart - Consumer Avenue (Work)
		     Stock/Warehouse Manager:  Big Mart - Consumer Avenue (Work)
		     Merchandiser:  Big Mart - Consumer Avenue (Work)

		Facilities:
		     Easy Street (My House)
		     Elegant Place (Parents)
		     Big Mart - Consumer Avenue (Work)

		Stock Locations:
		     My House >
		     My Parents >
		     My Work >

		Permissions for Account Owner:  Easy Street (My House):
		    [x] All permissions
			[_] User management
			    [_] Create users
				[_] Edit users (including passwords)
				    [_] Show users
			[_] Edit own user data / change own password
			[_] Stock
			    [_] Purchase
			    [_] Consume
			    [_] Inventory
			    [_] Transfer
			    [_] Open products
			    [_] Edit stock entries
			[_] Shopping list
			    [_] Add items
			    [_] Remove items
			[_] Recipes
			    [_] Meal plan
			[_] Chores
			    [_] Track execution
			    [_] Undo execution
			[_] Batteries
			    [_] Track charge cycle
			    [_] Undo charge cycle
			[_] Tasks
			    [_] Undo execution
			    [_] Mark completed
			[_] Equipment
			[_] Calendar
			[_] Edit master data
=======================================================================

By default (at installation), there is one owner with all permissions that the initial user would ordinarily have over all data in the system.

That initial user can add new users (as they can now).  However, a default role will be assigned to the new user unless the role is otherwise specified by the initial user.

The roles determine the default permissions for each user.  Permissions may be modified for each user before (and after) creation of each user in the system.  Any permission may be delegated.

Users can specify default permissions for any roles from which they wish to delegate.  And those default permissions will only affect users to which they delegate (not other users).

Division of ownership will allow a user to assign responsibility (or transfer of ownership) over a portion of the user's data domain to another user.

If any of the Roles, Locations, or Stock Locations are selected on the above page, the relevant permissions will be shown (along with any location, role, or facility overrides below the main permissions):

=======================================================================
[All of the Roles & Permissions stuff as shown above, but for a different user would appear here]
[Then, the following location, facility, and role overrides...]

	Easy Street (Garonic's House) Facility:
			[-] User management
			[-] Edit own user data / change own password
			[+] Stock
	Garonic's House > Upstairs Pantry Location:
			[+] Stock
			    [-] Consume
	Shopper Role:
		    [-] All permissions
			[_] Stock
			    [+] Purchase
			    [-] Consume
=======================================================================

This change go towards facilitating:
- Feature Request: Multiple Homes #644
- Feature Request: User Rights Assignment #263

**Comment by berrnd** [comment] 2022-10-07 21:01
So is it about having roles (something like a group of permissions) you would like to assign to users?

Or is it about having the "Edit master data" split up to Products/Locations and so on?

grocy currently doesn't have multiples homes / facilities, that's a duplicate of #644, as you already mentioned. Running multiple instances is a easy workaround to have that now.

Sorry, I don't get what you want from what you described above. So please split this up into smaller and concise requests per topic. And also keep in mind that grocy is about managing your fridge and home, not your business. If in such an environment excessive restrictive permissions are necessary I don't know if grocy should solve that...

The example roles mentioned above kind of indicate a business use case which is clearly out of scope of this project.

**Closed by berrnd** 2022-10-07 21:01 UTC
Labels: invalid

**Comment by berrnd** [comment] 2022-10-07 21:10
And just to clarify "default permissions for new users":

This is not fixed "All permissions" (`ADMIN`), you can configure that in `data/config.php`:

https://github.com/grocy/grocy/blob/e8f76e5694f2defb69435bccfaeb8de96870322c/config-dist.php#L93-L96

**Comment by Garonic** [comment] 2022-10-08 01:33
The "business" looking portion of it is from me considering how to get businesses to share the data that they have about their stores / products / etc., so that it is easier for people to get current information without having to type it all in themselves.
