### ISSUE TITLE
Feature request: Giant database of product barcodes

### ISSUE THREAD

**Issue by KTibow** [grocy/grocy#1325] opened 2021-02-13 01:38 UTC
For most products, when you Google their barcode, there's a result. It would be nice to have a "pull from web/database" option, so when you scan a barcode, it could auto-create a product with a pre-filled barcode and name.

**Comment by RubenKelevra** [comment] 2021-02-13 03:26
I don't think Googling is a good solution, but maybe requesting the data from openfoodfacts.org is an option? :)

**Comment by berrnd** [comment] 2021-02-13 08:00
More or less a duplicate of #158.

It's already possible to implement that yourself using a [BarcodeLookupPlugin](https://github.com/grocy/grocy#barcode-lookup-via-external-services).

Maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

**Closed by berrnd** 2021-02-13 08:00 UTC
Labels: duplicate
