### ISSUE TITLE
Consumption Bug (Consumption Quantity Does Not Match Actual Quantity Removed)

### ISSUE THREAD

**Issue by klausmcm** [grocy/grocy#974] opened 2020-08-29 20:25 UTC
**Observed behavior**

1. Add product into inventory that has multiple weight, volume, etc units (ex. **g**)
2. Go to the **Stock entries** page for the new entry.
3. Click on **Consume** button (tooltip will indicate that **1 g** will be removed)
4. Entire entry is removed instead of just **1 g**.

![image](https://user-images.githubusercontent.com/14914359/91645511-6d1e0080-e9fa-11ea-8a3c-00dd31b3f6c8.png)

---

**Expected behavior**

Either

* remove **1 g** from the **Amount** for the entry

or

* fix the tooltip to say that the entire entry will be removed - I'm ok with this as my current worfklow is to mark an entry as **Opened** and then I hit the **Consume** button to remove the entire entry.

**Comment by berrnd** [comment] 2020-08-29 20:36
This is already fixed in https://github.com/grocy/grocy/commit/6867057b6eb71cf6f6c8d6d1483db6b9e880700d#diff-63c91cfe19fe67c614b0cb140ee13ba8, included since v2.7.0.

So you most probably use a version < v2.7.0, please always try to reproduce problems first on the [pre-release demo](https://demo-prerelease.grocy.info) before reporting, thanks.

**Closed by berrnd** 2020-08-29 20:36 UTC
Labels: invalid

**Comment by klausmcm** [comment] 2020-08-29 20:43
> This is already fixed in [6867057](https://github.com/grocy/grocy/commit/6867057b6eb71cf6f6c8d6d1483db6b9e880700d) included since v2.7.0.
> 
> So you most probably use a version < v2.7.0, please always try to reproduce problems first on the [pre-release demo](https://demo-prerelease.grocy.info) before reporting, thanks.
> 
> Duplicate of #621.

Sorry, I was just going to add the version I'm using. I'm observing this on **Version 2.7.1**.

**Comment by klausmcm** [comment] 2020-08-29 21:01
> > This is already fixed in [6867057](https://github.com/grocy/grocy/commit/6867057b6eb71cf6f6c8d6d1483db6b9e880700d) included since v2.7.0.
> > So you most probably use a version < v2.7.0, please always try to reproduce problems first on the [pre-release demo](https://demo-prerelease.grocy.info) before reporting, thanks.
> > Duplicate of #621.
> 
> Sorry, I was just going to add the version I'm using. I'm observing this on **Version 2.7.1**.

Ignore that. I read through the upgrade instructions again and after removing *data/viewcache*, I see the updated UI. All is working. Thanks,
