### ISSUE TITLE
Bug: Purchase/Consume a product by Grocycode and when Scan Mode is on is not possible

### ISSUE THREAD

**Issue by cahir1987** [grocy/grocy#2571] opened 2024-08-23 21:25 UTC
Consuming the product with barcode causes an error "This must between 0,01 and 0 and needs to be a valid number with max. 2 decimal places"

When using barcode (example): grcy:p:29 and next TAB or ENTER key from keyborad / barcode sufix cause an error.

When you type in the product name or select from the drop-down list everything works as expected

https://test-5viya3q9bz5abwad6pnt6r.demo.grocy.info
![image](https://github.com/user-attachments/assets/c84671fb-ecc1-4770-a22f-2764bda52a34)
![image](https://github.com/user-attachments/assets/cf030dda-0415-4257-92b3-b7303c51722e)

**Comment by cahir1987** [comment] 2024-08-23 21:42
Error shows on PHP 8.3.6 on PHP 8.0 is supported

**Comment by cahir1987** [comment] 2024-08-23 22:04
Instalation of PHP8.0 not helps:

 Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.0.30

**Comment by berrnd** [comment] 2024-08-24 06:25
It's not about consuming with scanning a barcode generally, it's specifically to when using a Grocycode and when Scan Mode is on - I've updated the title of this issue accordingly. Is reproducible, so can be fixed by anyone who is interested in doing that.

&nbsp;
> Found information that need PHP8.0

Don't know where you found that exactly, [README mentions](https://github.com/grocy/grocy/tree/release?tab=readme-ov-file#platform-support) clearly that PHP 8.2 and 8.3 is supported as of Grocy v 4.2.0. All the demo instances use PHP 8.3. This problem is a frontend problem only and therefore unrelated to the PHP version used.

&nbsp;
> Instalation of PHP8.0 not helps

Of course not, since this problem is unrelated to the PHP version used anyways and downgrading to an unsupported runtime version can never help, even beyond Grocy.

**Comment by berrnd** [comment] 2024-08-24 09:29
Also affects the purchase page in the same way

**Closed** 2024-08-24 16:22 UTC
Labels: bug

**Comment by cahir1987** [comment] 2024-08-27 11:01
@berrnd Is it possible to implement by own these changes before the official release of the new version? If yes then how?

By the way, thank you for a great job on this application, **it's great!**

**Comment by berrnd** [comment] 2024-08-27 11:13
> @berrnd Is it possible to implement by own these changes before the official release of the new version? If yes then how?

Of course. Every single bit I change on Grocy is publicly visible and transparently linked above. So simply have a look at d5dacb1053509ef9ed1b0f1fed634ebafd391b26 and 1246f402e5a27ac6e19e48200db65f3d1e33cdae and do the same / apply those changes. However, you should at least know a bit know what you're doing, at least I won't provide any kind of support if fiddling with stuff manually goes wrong and it maybe also can affecting future upgrades to work correctly ([README ref](https://github.com/grocy/grocy#database-migrations)).
