### ISSUE TITLE
Bug: Add Missing Products to Shopping List (Common Products don't sum up)

### ISSUE THREAD

**Issue by 4nner** [grocy/grocy#1789] opened 2022-02-16 15:26 UTC
Hello, I believe I've found a bug related to the Add Missing Products to Shopping List function.
I have successfully managed to replicate the same bug on the preview-version.

Scenario:
We have Recipe N1 that requires 3 eggs, and Recipe N2 that requires 1 egg.
We have no eggs in our stock, therefore we will click on "Add missing products to the Shopping List" from the Meal Plan view on Recipe N1.
Now we won't be able to do the same with Recipe N2 because grocy will say that there are already 3 eggs in the shopping list. However these eggs should be considered "reserved" for the recipe we have added them to the shopping list for.

Expected behaviour:
"Add missing products to the Shopping List" should be clickable for Recipe N2, and the eggs in the shopping list should either sum up or display two entries (one for each recipe)

**Comment by berrnd** [comment] 2022-02-16 15:45
Not a bug, but a feature request - and a duplicate of #840 (and #402, #1622, #1621, #925 - please search existing requests first).

Also already works for a whole meal plan week when using the button in the header.

**Closed by berrnd** 2022-02-16 15:45 UTC
Labels: duplicate

**Comment by 4nner** [comment] 2022-02-16 16:34
However the button in the header of the meal plan also adds the missing ingredients of recipes marked as "Done".
It this the intended behaviour?
