### ISSUE TITLE
Meal Plan Recipe with Sub-Recipes Incorrectly Displays "Enough in Stock"

### ISSUE THREAD

**Issue by Wordna1** [grocy/grocy#923] opened 2020-07-21 17:13 UTC
I have a recipe in my Meal Plan which includes 2 sub-recipes.  Neither of the sub-recipes have all their ingredients in stock, but the combined recipe displays "Enough in Stock" from the Meal Plan view.

Upon further investigation, it seems like this issue may only occur when the sub-recipes are also included individually in the Meal Plan.

**Comment by berrnd** [comment] 2020-07-22 06:48
I was not able to reproduce that on the current demo:
Not all ingredients of the recipes Pizza and Pancakes are in stock, combined into another recipe "2SubRecipes", added all of that recipes to the meal plan, all recipes have "Not enough in stock"...

https://en.demo.grocy.info/mealplan

![grafik](https://user-images.githubusercontent.com/2161815/88143762-1867b880-cbf8-11ea-855f-ba3bf8bf6c09.png)

![grafik](https://user-images.githubusercontent.com/2161815/88143789-21f12080-cbf8-11ea-9ce0-b34caafe2689.png)

**Comment by berrnd** [comment] 2020-08-18 15:45
Closing this for now, if you have a concrete reproducible example, feel free to reopen it.

**Closed by berrnd** 2020-08-18 15:45 UTC
Labels: question
