### ISSUE TITLE
Bug: Meal Plan Stuck

### ISSUE THREAD

**Issue by B1ue-W01f** [grocy/grocy#2419] opened 2024-01-03 16:39 UTC
Hi all,

I am looking for a little help debugging a bug.

I was creating this weeks Meal Plan, I added a number (around 7) of days of meals, deleted one. Now when I move back and forth between weeks the dates on the top left change, but the tabled days do not. Additionally no buttons on the one meal entry visible function - no response is seen. (Note how the dates on the top left show next week, but the days below are still this week)

![Grocy1](https://github.com/grocy/grocy/assets/32985875/2d730525-367f-4221-8881-62e715b0918f)
![Grocy2](https://github.com/grocy/grocy/assets/32985875/a618c152-b00b-4204-a4f8-37700623d731)

I went to check the API browser but there doesn't appear to be any options for Meal Plan?

I'm still able to interact with Products / Recipes, etc including saving changes to them.

I've tried restarting the container with no change.

I'm running the linuxserver v4.0.3 image.

The test instance does not show the issue, however neither has my instance for the better part of a few years. I appreciate this may or may not be a bug and would be more than eager to delete this issue if it turns out not to be.

**Comment by berrnd** [comment] 2024-01-03 16:52
> I am looking for a little help debugging a bug.

This is not the community forum, it's the tracker for Feature Requests and reproducible Bugs ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests), additionally also mentioned on the issue template, please don't ignore that) - you haven't provided anything reproducible.

&nbsp;
> I'm running the linuxserver v4.0.3 image.

None of the community contributed apps/tools/integrations/Docker images are maintained here.

&nbsp;
> I went to check the API browser but there doesn't appear to be any options for Meal Plan?

Of course there are, the web frontend uses the API for everything, so everything what you can do there is then of course part of the API - simple example to get all meal plan items:
`GET /objects/meal_plan`
https://demo-prerelease.grocy.info/api/objects/meal_plan

&nbsp;
Most likely simply a duplicate of #2333 - already fixed, not yet released, even a workaround is mentioned there - please do a little search beforehand. Otherwise please provide a reproducible example.

**Closed by berrnd** 2024-01-03 16:52 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by B1ue-W01f** [comment] 2024-01-03 17:12
> > I am looking for a little help debugging a bug.
> 
> This is not the community forum, it's the tracker for Feature Requests and reproducible Bugs ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests), additionally also mentioned on the issue template, please don't ignore that) - you haven't provided anything reproducible.
> 
>  
> 
> > I'm running the linuxserver v4.0.3 image.
> 
> None of the community contributed apps/tools/integrations/Docker images are maintained here.
> 
>  
> 
> > I went to check the API browser but there doesn't appear to be any options for Meal Plan?
> 
> Of course there are, the web frontend uses the API for everything, so everything what you can do there is then of course part of the API - simple example to get all meal plan items: `GET /objects/meal_plan` https://demo-prerelease.grocy.info/api/objects/meal_plan
> 
>   Most likely simply a duplicate of #2333 - already fixed, not yet released, even a workaround is mentioned there - please do a little search beforehand. Otherwise please provide a reproducible example.

Okay so it was a demonstrable bug with the fundamental app code then, and one where a fix is already completed just not released - seems like the perfect place to raise the question then, unfortunately I just failed to find the similar issue (despite absolutely searching for them). 

RE the API: that's what I assumed but it doesn't appear to be documented on the API Browser (i.e. at /api)?

Thanks for providing the answer and apologies I couldn't find the other issue.

**Comment by berrnd** [comment] 2024-01-03 17:17
> but it doesn't appear to be documented on the API Browser (i.e. at /api)?

Well...

![grafik](https://github.com/grocy/grocy/assets/2161815/aaffd19a-6279-4e24-baec-54ee86523bda)

&nbsp;
Another real easy way to find out how API stuff works is to simply do the corresponding action on the web frontend, while also having a look at the magic behind via your Browser's developer tools - as just mentioned: The web frontend uses the API for each and everything you can do there.

**Comment by B1ue-W01f** [comment] 2024-01-03 17:38
> https://demo-prerelease.grocy.info/api/objects/meal_plan

Got that now cheers, did a search for meal_plan in the main browser window but unfortunately it only 'finds' if you already opened the entity window - just needed to realise meal_plans were a 'generic entity' - compared to how products etc work.

Unfortunately the workaround - clearing cache, checking config and running migrations doesn't work in this instance - which I guess makes sense as I didn't delete all meal plan items like the other issue.

But I have now confirmed the API appears correct - or at least provides recipes assigned to both this week and next (which arent visible in the meal plan).

Ill await the new release in the hopes it does capture this issue too or create a post on reddit if not. For now, back to old school paper meal planning.

**Comment by berrnd** [comment] 2024-01-03 17:44
> just needed to realise meal_plans were a 'generic entity' - compared to how products etc work.

Everything is a "generic entity" (it's not about that entities are generic, it's called "generic entity _interactions_" there, so the actions are meant to be generic), including products:

![grafik](https://github.com/grocy/grocy/assets/2161815/25964356-d838-447c-a5cc-d24e9aae0717)

&nbsp;
> Unfortunately the workaround - clearing cache, checking config and running migrations doesn't work in this instance

Then maybe try the most simplest workaround mentioned [there](https://www.reddit.com/r/grocy/comments/16ahkyt/comment/jz8lkqe/?context=3):
_Adding a recipe from Recipes to Meal Plan solved it for me._

**Comment by berrnd** [comment] 2024-01-03 17:46
Or maybe just have a look at your Browser developer tools / Browser console to probably get a hint what the real issue could be - unfortunately I can't look behind screenshots to say anything detailed, all I've said here is only based guessing.

**Comment by B1ue-W01f** [comment] 2024-01-03 17:52
> > just needed to realise meal_plans were a 'generic entity' - compared to how products etc work.
> 
> Everything is a "generic entity" (it's not about that entities are generic, it's called "generic entity _interactions_" there, so the actions are meant to be generic), including products:
> 
> ![grafik](https://private-user-images.githubusercontent.com/2161815/293988401-25964356-d838-447c-a5cc-d24e9aae0717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDQzNDksIm5iZiI6MTcwNDMwNDA0OSwicGF0aCI6Ii8yMTYxODE1LzI5Mzk4ODQwMS0yNTk2NDM1Ni1kODM4LTQ0N2MtYTVjYy1kMjRlOWFhZTA3MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMTc0NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVkZTUzOTIwY2E5ZTAzMGU5OTc0N2ExZDUzMDE4NzA2NzhjNGQ0MWE1OTU0OWIyNjA4MTg2Yzc3YTAyODkzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7G9AjHVXSP0aUUFsvuHTFCl5Ubw8V-w2GBFilMmBPGk)

Got it now cheers. Just couldn't see the wood for the trees whilst trying to get the food shop in.


> > Unfortunately the workaround - clearing cache, checking config and running migrations doesn't work in this instance
> 
> Then maybe try the most simplest workaround mentioned [there](https://www.reddit.com/r/grocy/comments/16ahkyt/comment/jz8lkqe/?context=3): _Adding a recipe from Recipes to Meal Plan solved it for me._

Delightful lateral thinking! I was trying to 'reset' the meal plan from the API (hence the original query) but didn't realise that was an option and its got it perfect thanks!

> Or maybe just have a look at your Browser developer tools / Browser console to probably get a hint what the real issue could be - unfortunately I can't look behind screenshots to say anything detailed, all I've said here is only based on guessing.

Appreciated, wasn't intending someone else to do all the hard work, just looking for the tools to debug myself but you've nailed it.
