### ISSUE TITLE
Feature Request: Amend purchases in the journal

### ISSUE THREAD

**Issue by Akeboshiwind** [grocy/grocy#391] opened 2019-09-26 10:59 UTC
If I make a mistake when adding a purchase currently I have to do the following:

1. Add the incorrect purchase
2. Go to the journal page and revert it
3. Re-add the purchase with the correct information (remembering what was originally added)

I think it would be simpler if it were possible to amend the entry in the journal

**Comment by berrnd** [comment] 2019-09-26 11:29
Duplicate of #313 and partially of https://github.com/grocy/grocy/issues/191#issuecomment-473299770.

If you notice it directly during adding the purchase, there is also an undo button in the success message, see this GIF: https://grocy.info/#input-productivity

**Closed by berrnd** 2019-09-26 11:29 UTC
Labels: duplicate
