### ISSUE TITLE
Bug: Last price should ignore `0` (or `null`) prices

### ISSUE THREAD

**Issue by MariusSchenkluhn** [grocy/grocy#2470] opened 2024-02-13 08:58 UTC
I still experience a similar issue as described by @Forceu in #2106 using Grocy 4.0.3.

When adding a product via the API without the price parameter the price of the new entry is set to 0 including the last price of the entry. However, the graph and average price are not affected.

**Context**
I use a Barcode Scanner via [Barcode Buddy](https://github.com/Forceu/barcodebuddy) to add products quickly after shopping. This call to Grocy's ```api/stock/products/ID/add``` endpoint does not pass a price in the request body.

Currently, this issue makes prices unusable for this use case as every stock item has a price of 0, the overall stock value is 0 and each recipe has costs of 0. It would be great if these resulting calculations would consider the last price if the price of the stock item is 0 (if this is not the case already). I would argue that this is a better approximation than assuming the price to be 0.

I performed the same steps to reproduce:

1. Create product
2. Add amount through the webinterface with a price
3. Add amount through API without a price

Thank you very much in advance and for your efforts with Grocy in general!

**Comment by berrnd** [comment] 2024-02-13 09:22
It's only about the product's last price, the average price and price history chart works as fixed by #2106.

&nbsp;
> Currently, this issue makes prices unusable for this use case as every stock item has a price of 0, the overall stock value is 0 and each recipe has costs of 0. 

Can't follow that. If all of your stock entries have a price of `0` (or `null`) of course the total value is `0`. If you have a single stock entry with a price of `2.99`, adding `0` doesn't change the total value, since `2.99 + 0` is simply `2.99`.

&nbsp;
> It would be great if these resulting calculations would consider the last price if the price of the stock item is 0 (if this is not the case already)

How recipe prices are calculated is described more than detailed:

![grafik](https://github.com/grocy/grocy/assets/2161815/38a55ec2-07a7-40cb-af05-a6576ccb7e69)

&nbsp;
Since only one topic per request is tracked (as mentioned on the issue template), this here will be about fixing the regression that the last price should ignore `0` / `null` prices, nothing else.

**Comment by MariusSchenkluhn** [comment] 2024-02-13 09:39
Thank you for your quick reply!

> Can't follow that. If all of your stock entries have a price of 0 (or null) of course the total value is 0. If you have a single stock entry with a price of 2.99, adding 0 doesn't change the total value, since 2.99 + 0 is simply 2.99.

Let me elaborate: When creating a new product, I manually add it in Grocy including its price. Thus, last price, avg price, etc. are > 0. For each subsequent purchase I use the barcode scanner for convenience. Thus, the total value does not account for the additional items (with ```price=0```). Using the last price for items with a price of 0 would be a better approx. in my opinion.
Therefore, I would argue that the issue does not only relate to the last price but the calculation based on 0/null prices.

Thank you for the description of the recipe price calculation. This makes sense and should work as expected when the last price issue is fixed.

**Comment by berrnd** [comment] 2024-02-13 09:47
All what you said again concludes again to that the single issue that a product's last price shouldn't consider `0` / `null` prices (which was already fixed for v4.0.0 as #2106 tracks, but regressions happen).

Otherwise please simply provide a concrete example where it's not about a `0` / `null` product's last price ([persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there to not talk about stuff in theory, but in reality).

**Comment by MariusSchenkluhn** [comment] 2024-02-13 09:59
I don't know how the calculation of the product stock value and the total stock value is implemented. If they already account for the last price if prices are ```0``` / ```null``` then I agree.

I created a [persistent demo](https://test-m01ew1v4jqt3k4czfqhqe.demo.grocy.info/stockoverview) as suggested where I created a product, added 10 items without a price and then 10 items with a price of 1. The product stock value is now 10, thus, only accounting for the last 10 items with a price. I suggest that for the items without a price (or price = 0), the stock value should be calculated based on the last price. The product stock value would then be 20.

I hope this makes it clearer.

**Comment by berrnd** [comment] 2024-02-13 10:25
> I don't know how the calculation of the product stock value and the total stock value is implemented. If they already account for the last price if prices are ```0``` / ```null``` then I agree.

It's of course real rocket science, something like "SUM(All stock entries of product xy)".
Example: `1.99 + 2.99 = 4.98`
Let's do this again while having an arbitrary amount of additional stock entries with an empty / 0 price:
`1.99 + 0 + 0 + 2.99 + 0 = 4.98` (surprise)

&nbsp;
> The product stock value is now 10, thus, only accounting for the last 10 items with a price. I suggest that for the items without a price (or price = 0), the stock value should be calculated based on the last price. The product stock value would then be 20.

As just appointed out, the stock value of a product is a simple summarization of what's currently in stock. There is no exception for "take the last price if the price of a stock entry is empty or 0" as part of this summarization - and this also won't be changed. You said that the corresponding stock entry doesn't cost anything, so simply correct that or (IMHO even more simple) set the price on the initial (purchase) transaction.

To make this easier and also since how reality does that too, on [/purchase](https://demo-prerelease.grocy.info/purchase) the last price gets prefilled after selecting a product, means you effectively only have to enter something there if the corresponding price has changed. So sounds for me that's maybe the missing part (for your workflow) on the Barcode Buddy side, but I personally don't use that.

This here will still be about fixing the regression that the last price should ignore 0 / null prices, nothing else.

**Comment by MariusSchenkluhn** [comment] 2024-02-13 10:44
Exactly, I would love to have the price set on the purchase transaction. However, a barcode scanner cannot do that.
Thus, the best way for this workflow would be the same behavior as you described for the /purchase view: Prefilling the last price. For the API this would mean that if no price is set as parameter in the request body the last price should be used instead.

Of course, Barcode Buddy could request the last price before adding the product but I argue that it would be a generally useful behavior of Grocy's ```api/stock/products/ID/add``` endpoint.

**Comment by berrnd** [comment] 2024-02-13 10:57
> However, a barcode scanner cannot do that.

You're referring to a barcode scanner which uses [Grocy's API](https://demo-prerelease.grocy.info/api) and that API can do that, in fact Grocy's web frontend even uses exactly this API too to do everything.

&nbsp;
> For the API this would mean that if no price is set as parameter in the request body the last price should be used instead.

No. If you want to set a price, set a price, it's easy as that.

&nbsp;
> I argue that it would be a generally useful behavior of Grocy's ```api/stock/products/ID/add``` endpoint.

It would be a breaking change for everybody, "fixing" your personal workflow only. Fun fact: I also use barcode scanners to add stuff to my Grocy and don't have that problem.

&nbsp;
>If you would prefer me to open a new issue for this, I am happy to do so.

Not needed, since nothing about the API related to that will be changed.

**Comment by MariusSchenkluhn** [comment] 2024-02-13 11:10
As stated above, I use the barcode scanner via Barcode Buddy to avoid the need of opening the Grocy frontend each time I want to scan something or restricting myself to use the scanner only with one device. A barcode scanner is not capable of setting prices.

It is not only my personal workflow but the default for everyone using Barcode Buddy where this issue has been mentioned before by other users (and thus leading to the original issue #2106). As the issue does not seem to affect you and your workflow, I'll open an issue in the Barcode Buddy repo and suggest pulling the last price there. Still, thank you for your time and considering the issue.

**Comment by berrnd** [comment] 2024-02-13 11:21
> A barcode scanner is not capable of setting prices.

But Grocy's API is and everybody who uses that just needs to take care of whatever is useful, or not. Barcode Buddy is obviously a client which does that workflow detail (taking the product's last price for a purchase transaction if not provided) not like you expect it, Grocy's web frontend does it how you expect it. Plot twist.

&nbsp;
> As the issue does not seem to affect you and your workflow, I'll open an issue in the Barcode Buddy repo and suggest pulling the last price there. 

Having a problem / feature request for a third party tool and requesting the corresponding thing there - what an idea!

&nbsp;
I'm going to lock this since enough off-topic added. What this is about (fixing the regression that the last price should ignore `0` / `null` prices) is crystal clear.

**Closed** 2024-02-13 12:13 UTC
Labels: bug
