### ISSUE TITLE
Shopping list no longer loading

### ISSUE THREAD

**Issue by Mills79** [grocy/grocy#1541] opened 2021-07-20 19:20 UTC
when everI attempt to load the shopping list I get an error saying, A server error occured while processing your request.
`Error source:
```
/data/grocy/viewcache/9824808439d99d221e85f10d4894bb8316305544.php:243
```

Error message:
```
Unsupported operand types: string * string (View: /var/www/grocy/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(179): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(202): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(368): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ShoppingList()
#11 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /var/www/grocy/app.php(106): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('...')
#31 {main}
```
I'm not sure what caused this as the only change I had made was removing some of stock items I had used that day.

**Comment by berrnd** [comment] 2021-07-20 20:24
Sorry, but I really can't help unless that's reproducible.

Are you able to reproduce it on the demo instance (like mentioned on the issue template)?
Have you maybe updated and not cleared `data/viewache`?

I'm also open to offer that you can send me your database if that's ok for you and there is no other way to track this down / make it reproducible.

Closing this for now until it's reproducible.

**Closed** 2021-07-20 20:24 UTC
Labels: invalid

**Comment by berrnd** [comment] 2021-07-20 20:26
One rough guess:

Replace line [235 of `views/shoppinglist.blade.php`](https://github.com/grocy/grocy/blob/d871ed7b53bd9fafa1ecc9846b14569bf04d15d8/views/shoppinglist.blade.php#L235) with the following and try if that helps:
```
$listItem->amount = floatval($listItem->amount) * floatval($productQuConversion->factor);
```

**Comment by Mills79** [comment] 2021-07-21 13:24
Hi
I have grocy installed as an addon to home assistant installed via the official install for an Intel nuc.  Please could you let me know how to clear the data/viewcache.
Also do I back up the data base and access it to send to you?

Thanks



Sent from my Galaxy



-------- Original message --------
From: Bernd Bestel ***@***.***>
Date: 20/07/2021 21:24 (GMT+00:00)
To: grocy/grocy ***@***.***>
Cc: Mills79 ***@***.***>, Author ***@***.***>
Subject: Re: [grocy/grocy] Shopping list no longer loading (#1541)


Sorry, but I really can't help unless that's reproducible.

Are you able to reproduce it on the demo instance (like mentioned on the issue template)?
Have you maybe updated and not cleared data/viewache?

I'm also open to offer that you can send me your database if that's ok for you and there is no other way to track this down / make it reproducible.

Closing this for now until it's reproducible.

**Comment by berrnd** [comment] 2021-07-21 13:39
Sorry, can't help with "anything Home Assistant" since I don't use that and therefore have zero experience with it...
