### ISSUE TITLE
Bug: Wrong Stock amount in Parent product when using unit conversion in Child

### ISSUE THREAD

**Issue by 13hannes11** [grocy/grocy#1146] opened 2020-11-30 09:59 UTC
Setup (also added it to demo server -> see Cereal Parent, Cereal Child A, Cereal Child B)

* Parent Product is in Grams
* Child A and Child B use Quantity Pack
* Child A converts one Box to 350 g
* Child B converts one Box to 450g

The Stock overview should now show 800g of Parent in Stock (aggregated) if we have one product of Child A and Child B.

![image](https://user-images.githubusercontent.com/9381167/100595175-dd3e6a00-32fa-11eb-8257-5a0985e25fb3.png)

![image](https://user-images.githubusercontent.com/9381167/100595272-fba46580-32fa-11eb-984f-c8e30b8e00d4.png)

![image](https://user-images.githubusercontent.com/9381167/100595318-0b23ae80-32fb-11eb-9a2b-d172145653ae.png)

**Comment by berrnd** [comment] 2020-11-30 10:03
Duplicate of #938, already fixed, not yet released.

Please always try to reproduce bugs on the [pre-release demo](https://demo-prerelease.grocy.info) first, thanks.

**Closed by berrnd** 2020-11-30 10:03 UTC
Labels: duplicate
