### ISSUE TITLE
Feature request: update API for userfields

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1633] opened 2021-09-29 20:40 UTC
Hi,

can you enhance the Generic entity interactions?

    "error_message": "SQLSTATE[HY000]: General error: 1 no such column: userfields_id"

I would like to add/update also userfield related content during insert or update.

curl -X 'POST' \
  'https://en.demo.grocy.info/api/objects/products' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": "1",
  "name": "Cookies",
  "description": null,
  "location_id": "4",
  "qu_id_purchase": "3",
  "qu_id_stock": "3",
  "qu_factor_purchase_to_stock": "1.0",
  **"userfields" :{"color":"red"}**
}'

BR
Phil

**Comment by berrnd** [comment] 2021-09-29 20:46
Userfields have their own endpoint [`PUT /userfields/{entity}/{objectId}`](https://demo.grocy.info/api#/Generic%20entity%20interactions/put_userfields__entity___objectId_).

Question-duplicate of #1021.

**Closed by berrnd** 2021-09-29 20:46 UTC
Labels: question
