### ISSUE TITLE
Feature Request: Allow selection of subset of members to rotate chore assignment between

### ISSUE THREAD

**Issue by Govuliel** [grocy/grocy#2461] opened 2024-02-09 05:50 UTC
I have an account on a shared computer that I don't want chores to be assigned to. I'd like to either be able to mark certain users as not eligible for chore assignment or select the list of assignable users per chore. The random assignment functions should then honor these flags and not select certain members when randomly assigning a chore.

This could also be useful for certain chores that only an adult can do or only tall household members or only those with certain skills.

**Comment by berrnd** [comment] 2024-02-09 07:51
Duplicate of #1934 - please be so kind and check existing requests before opening new ones.

**Closed by berrnd** 2024-02-09 07:51 UTC
Labels: duplicate

**Comment by MadcapJake** [comment] 2024-02-09 11:19
Thanks! I actually did search tickets first but I didn't read through this one carefully enough.

**Comment by Govuliel** [comment] 2024-02-10 11:42
I did actually look through the tickets but apparently not extensively enough. My apologies!
