### ISSUE TITLE
Bug: Fatal error: Uncaught Error: Undefined constant "Grocy\Controllers\GROCY_USER_ID"

### ISSUE THREAD

**Issue by byalpel** [grocy/grocy#1279] opened 2021-01-21 08:15 UTC
Latest version of Grocy 3.0.1
PHP8

Everything was working well with PHP 7.x and Grocy v2.6.2

Since the update, I got this error:

`Fatal error: Uncaught Error: Undefined constant "Grocy\Controllers\GROCY_USER_ID" in /Users/david/Sites/www/grocy/controllers/BaseController.php:162 Stack trace: #0 /Users/david/Sites/www/grocy/controllers/BaseController.php(196): Grocy\Controllers\BaseController->render(Object(Slim\Http\Response), 'errors/500', Array) #1 /Users/david/Sites/www/grocy/controllers/ExceptionController.php(77): Grocy\Controllers\BaseController->renderPage(Object(Slim\Http\Response), 'errors/500', Array) #2 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(127): Grocy\Controllers\ExceptionController->__invoke(Object(Slim\Http\ServerRequest), Object(PDOException), true, false, false) #3 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(109): Slim\Middleware\ErrorMiddleware->handleException(Object(Slim\Http\ServerRequest), Object(PDOException)) #4 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #5 /Users/david/Sites/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest)) #6 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #7 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest)) #8 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest)) #9 /Users/david/Sites/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest)) #10 /Users/david/Sites/www/grocy/app.php(94): Slim\App->run() #11 /Users/david/Sites/www/grocy/public/index.php(45): require_once('/Users/david/Si...') #12 {main} thrown in /Users/david/Sites/www/grocy/controllers/BaseController.php on line 162`

This error cannot be ignored in php.ini like advised previously...

**Comment by byalpel** [comment] 2021-01-21 08:25
When I disabled the authentication ie `Setting('DISABLE_AUTH', true);`, I get another page:

`Deprecated: Required parameter $cachePath follows optional parameter $viewPaths in /Users/david/Sites/www/grocy/vendor/philo/laravel-blade/src/Blade.php on line 45

Warning: file_put_contents(/Users/david/Sites/www/grocy/public/../data/viewcache/d5619f605ecca38ecead0a2594298dde4444df36.php): Failed to open stream: Permission denied in /Users/david/Sites/www/grocy/vendor/illuminate/filesystem/Filesystem.php on line 122

Warning: include(/Users/david/Sites/www/grocy/public/../data/viewcache/d5619f605ecca38ecead0a2594298dde4444df36.php): Failed to open stream: No such file or directory in /Users/david/Sites/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php on line 43

Warning: include(): Failed opening '/Users/david/Sites/www/grocy/public/../data/viewcache/d5619f605ecca38ecead0a2594298dde4444df36.php' for inclusion (include_path='.:/usr/local/Cellar/php/8.0.1_1/share/php/pear') in /Users/david/Sites/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php on line 43`

I think grocy did not like the php8 upgrade... 
Maybe restrict the versions to 7.x and no upper in the documentation?

**Comment by berrnd** [comment] 2021-01-21 08:40
Duplicate of #1220, PHP 8 is not supported.

README [clearly mentions](https://github.com/grocy/grocy#how-to-install) that currently everything is only tested against PHP 7.4 and SQLite 3.27.2.

**Closed by berrnd** 2021-01-21 08:40 UTC
Labels: question

**Comment by berrnd** [comment] 2021-07-05 16:17
Just to note that also here: PHP 8 will be supported in the next release (ref https://github.com/grocy/grocy/commit/b0d38b87de07f4ae117dd7e8e437aac2e8d842b1).
