### ISSUE TITLE
Sensible order quantities on shopping list?

### ISSUE THREAD

**Issue by danq8** [grocy/grocy#2091] opened 2023-01-02 20:04 UTC
Hi.
Really like Grocy, but am having real issues when trying to get realistic order quantities on a shopping list.

Example 1:
(Using a private pre-release demo)
Steps to reproduce:
1) Remove all milk from stock.
2) Add 21 servings of Chocolate sauce.
3) Add missing items to shopping list.
Result: 4.2 bottles of milk on shopping list.
Is there any way to get the sensible result of 5 bottles?

Example 2:
(Found on my own instance running version 3.3.2 of Grocy on home assistant)
I have a recipe that needs two cloves of garlic.
The only quantity I can buy in my local store is a bag with 3 Bulbs of garlic.
So I created a unit of measure of 1 garlic clove,
another unit of measure as 1 garlic bulb with approximately 8 cloves in a bulb.
and finally a pack of 3 Bulbs equivalent to the product.
I created a product as 3 Bulbs of garlic.
Then added a recipe that needed 2 cloves of garlic to the menu planner, and clicked the button to add products not in stock to the shopping list.
I've tried every variation I can think of, but never get the right result.
From example 1, I guess there's work that needs to be done if Grocy is meant to order quantities that are available in a store from the menu planner? Or I could just not be getting the config right, I can't find any help to get it working the way I would expect it to work..
Thanks for taking a look.

Cheers

Dan.

**Comment by berrnd** [comment] 2023-01-02 20:21
Duplicate of #1355 (and and #1615, and #1694, and #1980) - please check existing requests before opening new ones.

&nbsp;
> Result: 4.2 bottles of milk on shopping list.
> Is there any way to get the sensible result of 5 bottles?

Personal unpopular opinion: grocy does the math (right) and picking 5 bottles when there are 4.2 on my shopping list is not that hard practically.

**Closed by berrnd** 2023-01-02 20:21 UTC
Labels: duplicate
