### ISSUE TITLE
[Feature Request] Backup and Restore Data

### ISSUE THREAD

**Issue by dibyadip-das** [grocy/grocy#884] opened 2020-06-04 19:30 UTC
While running GORCY via a docker container, it is difficult to make timely backup of your data. I wish there was a backup restore functionality via REST API or UI allowing us to export and import data. I am in so love with GROCY although I am struggling to make many GROCY a per ERP tool for my home You guys rock 🥇

**Comment by berrnd** [comment] 2020-06-05 06:30
Duplicate of #129.

**Closed by berrnd** 2020-06-05 06:30 UTC
