### ISSUE TITLE
Feature Request: "OK" and "Close"-Button in same Row

### ISSUE THREAD

**Issue by dabenzel** [grocy/grocy#1916] opened 2022-06-11 10:14 UTC
Would it be Possible to change the position of the "OK"-Button in the same row as the "Close"-Button?

Like here:
![image](https://user-images.githubusercontent.com/2480235/173183635-c16f2d8b-da27-4eeb-9762-92265f18db08.png)

If it's a thing you are okay with, I'd have a look at this and submit a PR.

**Comment by berrnd** [comment] 2022-06-11 10:36
Duplicate of #1367.

&nbsp;
> If it's a thing you are okay with, I'd have a look at this and submit a PR.

Sure, feel free to do so - why it is how it currently is, is also mentioned in #1367.

**Closed by berrnd** 2022-06-11 10:36 UTC
Labels: duplicate
