### ISSUE TITLE
Feature Request: Consume multiple items in a chore and select the unit type

### ISSUE THREAD

**Issue by miguelbernadi** [grocy/grocy#2599] opened 2024-10-29 07:48 UTC
I found this idea already mentioned in #860 but I don't see it implemented yet (that suggestion had many different topics).

I'm new to Grocy and I was trying to set up a chore to do laundry. In my case, laundry involves detergent and fabric softener (2 different products). Right now it seems the chore can only consume one product instead of 2, so this should be expanded.

Also I have a problem with units:

I have different brands of detergent and different sizes of the detergent bottle, so I want to use a generic detergent parent product with multiple childs per brand/size. I track the inventory at the bottle unit, and convert to doses based on bottle size for consumption. I could also use milliliters or other fluid units, but track the bottles.

When I try to assign products to the chores it picks up the inventory unit for consumption, not the consumption unit, meaning that it consumes a bottle instead of a dose (a bottle has 30-60 doses). I think it should use the consumption unit, or allow to select the unit for the product.

Possible bug:

I tried to specify a decimal amount of bottle corresponding to a dose as a workaround, but the system says that I'm not inputting a number, despite it being bigger than 0.001 (the value appearing in help text) and having less decimals than stated (4 decimals). I tried initially with 0.0164 and then 0.016 with no success.

**Comment by berrnd** [comment] 2024-10-29 08:02
> Right now it seems the chore can only consume one product instead of 2, so this should be expanded.

I agree. Already tracked in / a duplicate of #1886 - please be so kind and check existing requests before opening new ones.

&nbsp;
> that suggestion had many different topics

So you noticed that and additionally the request template explicitly mentions to keep it to one topic per request (since everything else is simply untrackable and creates nothing but clutter) and now this is another request with multiple topics, cool. That said, I'm going to ignore all the other mentioned stuff. Create a clear and concise reproducible example in per topic separate requests if you really think that's something to cover here, or rather use the community forum for general usage questions ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)).

&nbsp;
> I don't see it implemented yet

This is a hobby project, driven by desire and (free) time only, the amount of requests is irrelevant.

**Closed by berrnd** 2024-10-29 08:02 UTC
Labels: duplicate
