### ISSUE TITLE
Feature Request: Treatment of return pledge

### ISSUE THREAD

**Issue by strausmann** [grocy/grocy#2249] opened 2023-06-06 12:46 UTC
At the purchase and consumption it should be possible to manage the treatment of return of deposit. How much deposit has a product, possibly also a quantity of units has an additional deposit.

Example drinks in deposit bottles and a box.

The deposit in turn must be stored somewhere, so you need a storage location for it again.

Return of deposit when making a purchase.

**Comment by berrnd** [comment] 2023-06-06 12:49
Duplicate of #1356 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-06-06 12:49 UTC
Labels: duplicate

**Comment by strausmann** [comment] 2023-06-06 13:14
Oh sorry, I had been looking for pledge. I didn't get anything displayed for that.
