### ISSUE TITLE
Feature Request: track chore button for when chore is done.

### ISSUE THREAD

**Issue by bbrendon** [grocy/grocy#2423] opened 2024-01-06 19:32 UTC
It seems strange that when you press the green button it tracks the chore being done on a different day than it was actually done.  Right now you have to open a context menu etc. Can there be a button to track when the chore was done? I never want to track when a chore was scheduled to be done. I want to track when it was actually done.

I was actually looking to replace grocy with something else because of this weird behavior but today I found it under the sub menu so at least it's tolerable now, but still very strange IMO.

**Comment by berrnd** [comment] 2024-01-06 19:43
Duplicate of #2311 (and #2313, and #2326) - please be so kind and do little search before opening new requests.

https://github.com/grocy/grocy/issues/2311#issuecomment-1678780624 proposes even a solution that you don't need to open context menu on [/choresoverview](https://demo-prerelease.grocy.info/choresoverview), if you insists on tracking chores from there.

&nbsp;
> I was actually looking to replace grocy with something else because of this weird behavior

That's fine, I would personally always use that solution that covers my personal use case best and that doesn't necessarily need to be Grocy.

**Closed by berrnd** 2024-01-06 19:43 UTC
Labels: duplicate

**Comment by bbrendon** [comment] 2024-01-06 19:46
Sorry, I didn't search closed. Thanks anywy.

**Comment by bbrendon** [comment] 2024-01-06 19:48
Also, I was thinking it would make more sense to have this feature not as a button, but as an option for each chore. Some chores you may want to track on a specific schedule, and some not. So can we reopen the feature request for this instead?

**Comment by bbrendon** [comment] 2024-01-06 19:58
Hm. JS solution worked but removes the way to schedule on the schedule. Seems like this is a valid feature request in some fashion.

**Comment by berrnd** [comment] 2024-01-06 20:06
> So can we reopen the feature request for this instead?

To stop this endless discussion, I did that: #2424

Don't know if I'll ever work on that, if it's so important for you, I recommend implementing it yourself right away.

&nbsp;
> but removes the way to schedule on the schedule.

Maybe simply think outside the box and discover [/choretracking](https://demo-prerelease.grocy.info/choretracking), where you can track any chore for any point in time you want (btw. since ever).

**Comment by berrnd** [comment] 2025-01-14 18:50
There is now this new settings (chores settings / top right corner settings menu) to swap the "Track next chore schedule" / "Track chore execution now" buttons/menu items on the chores overview page:

![grafik](https://github.com/user-attachments/assets/b8e2846d-c0f5-4f14-9bd1-d709014e8aec)
