### ISSUE TITLE
Bug: Can not add to cart duplicate recipies from meal plan

### ISSUE THREAD

**Issue by rebenkoy** [grocy/grocy#2626] opened 2024-12-29 18:17 UTC
## intro
I like to cook for several days ahead, but I would like my meal plan to describe what I eat and not what I cook. So I found myself in a situation where I have same recipe for breakfast in 2 consecutive days. If I click "add to shopping list" button for the recipe in the first day it also becomes disabled for the recipe. int the second day.

## Screenshots
Shopping list before
![2024-12-29-215511_1665x217_scrot](https://github.com/user-attachments/assets/e643074f-8384-4461-ba8f-54c776877ddf)
Meal plan before
![2024-12-29-215528_537x417_scrot](https://github.com/user-attachments/assets/36c1ff45-1517-4dd3-9c88-a8362a064f5d)
Shopping list after
![2024-12-29-215548_1663x288_scrot](https://github.com/user-attachments/assets/e70ec07d-11b0-4d1b-b586-758bcca52561)
Meal plan after
![2024-12-29-215656_1680x429_scrot](https://github.com/user-attachments/assets/f0dc1669-6ad2-46e7-905e-62ea9eb9bcc2)
My recipe for a good day :) 
![2024-12-29-215834_1664x375_scrot](https://github.com/user-attachments/assets/47079ddf-dfc5-4c5a-b114-fb9191a8b21f)

## Steps to reproduce:
create an **ingredient**
create a **recipe** using **ingredient**
add **recipe** to 2 different days in meal plan
click "Add to shopping list" button in the first day
refresh
"Add to shopping list" does not work in the second day.

easily reproduced with Pizza  recipe in demo installation
https://demo-prerelease.grocy.info/mealplan?start=2024-12-29

## Speculations
(I have not yet found relevant code, both due to NY holidays and my very low php level)
I think this behavior is due to items in shopping list having only recipe as a "foreign key" as a reason why they were added to the shopping list. And when a cell in meal plan checks if ingredients were already added to the shopping list it checks only against this recipe name. Thus once i add recipe once it always counts as added.

## Plausible Fixes
(same disclaimer as in Speculations)
If my speculations are correct - one would just need to add some unique meal plan cell-id to the shopping list entry.

If any maintainer can show me ~~the world~~ where the relevant code is located I can try to make a PR (I am very rusty with JS and have nearly no php experience though).

**Comment by berrnd** [comment] 2024-12-29 19:04
> Speculations
> I think this behavior is due to items in shopping list having only recipe as a "foreign key"

There is no such a "foreign key" on a shopping list item at all as of today.

&nbsp;
> And when a cell in meal plan checks if ingredients were already added to the shopping list it checks only against this recipe name

Only amounts (per product) are compared as of today.

&nbsp;
> one would just need to add some unique meal plan cell-id to the shopping list entry.

As always and everywhere, think out an end-to-end concept, then implement it - at least that's how I normally do stuff.

&nbsp;
> If any maintainer can show me ~the world~ where the relevant code is located

I'm pretty much the only one, this is Open Source, so here you go: https://github.com/grocy/grocy

&nbsp;
# Conclusion:
Not a bug, but a feature request - a duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789, #1965, #2020, #2174, #2418 - please be so kind and search existing requests beforehand, that's also mentioned on the request template).

&nbsp;
Technical background why it is how it currently is, if you're interested:

https://github.com/grocy/grocy/issues/840#issuecomment-626286880:
> Currently the missing amount is only checked on per recipe level, so when 1 pack is already on the shopping list, that's already fulfilled for the second recipe...

https://github.com/grocy/grocy/issues/925#issuecomment-662279863:
> The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

**Closed by berrnd** 2024-12-29 19:04 UTC
Labels: duplicate
