### ISSUE TITLE
some kind of export

### ISSUE THREAD

**Issue by mbattistini** [grocy/grocy#1571] opened 2021-08-09 23:39 UTC
Please add some kind of export readable offline, csv, pdf, text file, the database backup is one thing, a printable and immediately readable offline backup is another!

Thanks

**Comment by berrnd** [comment] 2021-08-10 06:39
Duplicate of #129 - checking existing requests before opening new ones (like mentioned on the feature request template) would be great.

**Closed by berrnd** 2021-08-10 06:39 UTC
Labels: duplicate

**Comment by mbattistini** [comment] 2021-08-10 09:02
seen, but I think it is right to reiterate the concept again.

thanks.
