### ISSUE TITLE
Meal Plan's "Put Missing Items on Shopping List": Use cumulative amounts

### ISSUE THREAD

**Issue by Wordna1** [grocy/grocy#925] opened 2020-07-22 05:42 UTC
As far as I can tell, the Meal Plan's "Put Missing Items on Shopping List" button is calculating the Shopping List needs incorrectly when an ingredient is used in more than 1 recipe.

This problem is first evident when reviewing the Meal Plan's helpful "Enough in Stock" labels.  It appears each recipe is evaluated independently rather than cumulatively.  In other words, if I have 5 items in stock and Monday requires 4 and Tuesday requires another 3, then I would suggest that the Tuesday recipe should be marked as "Not Enough in Stock."  This cumulative stock management would be most helpful if "consumed" recipes (see #924 ) and expired/past recipes were ignored during these calculations.

If my testing is correct, this issue also ultimately (and more problematically) affects how many items are added to the Shopping List.  If I have 5 items in stock and Monday requires 6 and Tuesday requires 3, the Shopping List should show 6+3-5 = 4 items.  However, I believe it currently only shows 6-5 = 1 item.

Not sure if this is related to the Recipe checkbox "Do not check against the shopping list when adding missing items to it"?

_Likely related to #840 and somewhat related to #402_

**Comment by berrnd** [comment] 2020-07-22 06:59
This is mainly covered in #840.
But let's leave this open as this is explicitly about cumulative amounts of recipes when using the meal plan.

The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

**Comment by Aicho3oi** [comment] 2020-11-05 10:21
I'm just chiming in to say that an automated shopping list based on cumulative recipe plan amounts, would be a killer feature, from my perspective. 

I'm no programmer, but I'm wondering if it could be figured like this: 

> Cumulative needed amount for meal plan [6+3=9] - stock amount [5] = meal plan's automated contribution to shopping list amount [4].
> 
> Plus any automated contribution to the shopping list from the minimum stock amount. 
> 
> Plus any manually added shopping list amounts/adjustments.
> 
> Total of above = final amount summarised on shopping list.

That's different from "needed amount - stock amount" if "Do not check against the shopping list when adding missing items to it" is checked: because for example, if the first recipe needs 6, and there are 4 in stock, then the shopping list would correctly show 2. But if the second recipe needs a further 3, then "needed amount [3] - stock amount [4]" would add nothing to the list and leave us short of stock we need. Likewise with the 3rd recipe, and so on.

I think "Put missing items on shopping list" in the header of the meal plan page, runs into the same issue.

I really wish I knew how to help implement something like this idea, but nope. I don't even know if it's the right way to think about it.  

Anyway, while I'm commenting: this is amazing software: thank you!

**Comment by berrnd** [comment] 2022-02-09 21:55
Duplicate of / merged into #840.

**Closed by berrnd** 2022-02-09 21:55 UTC
Labels: duplicate
