### ISSUE TITLE
Feature Request: Edit multiple products at once

### ISSUE THREAD

**Issue by martin-braun** [grocy/grocy#2090] opened 2023-01-02 14:51 UTC
For instance, I want to change the default due date offset in days or the product group for multiple products.

Afaik I have to edit each product one by one.

Adding a checkbox field to the left and having an edit button for the selection would be very nice.

**Comment by berrnd** [comment] 2023-01-02 15:03
Duplicate of #1020 (and #1831, and #2049, and #2067, and #2071) - please check existing requests before opening new ones.

**Closed by berrnd** 2023-01-02 15:03 UTC
Labels: duplicate

**Comment by martin-braun** [comment] 2023-01-02 15:20
@berrnd Sorry, I searched for "multiple products" and failed miserably. I will improve my searching for the next time. Thank you.
