### ISSUE TITLE
Bug: Editing a stock entry does not save the edited value

### ISSUE THREAD

**Issue by Anwen747** [grocy/grocy#1390] opened 2021-02-27 19:10 UTC
I have some items which need updated due dates, and I am unable to correct them.

From the Stock Overview page, click the hamburger menu next to an item and choose Stock Entries in the list.
On the Stock Entries popup, click the Edit button (blue icon)
Change the due date (or any other field)
Click OK
The edit is not saved.  There is no error message, but no confirmation pop-up occurs, and if I go back to look at the item, the data has not been updated.  There is an entry in the stock journal for "Stock entry edited (old values)" but none for the new values.

The same thing happens if I go the the Stock Entries page from the Stock Overview page using the button in the top right corner.

I have tried this in the Grocy demo, my installation of Grocy Desktop on Windows, and in the Home Assistant Grocy add-on.  The same behavior happens in all cases.    It has actually worked a very few times, never more than once in a row.  I do not know why it very occasionally succeeds.  I can follow the exact same steps down to the key presses and it will fail repeatedly.

If I can provide any other information that will help, please let me know.  Thank you very much.

**Comment by berrnd** [comment] 2021-02-27 19:22
Duplicate of #1268 (and #1284, and #1373), already fixed, not yet released - please check existing issues first before reporting and/or try to reproduce the problem first on the [pre-release demo](https://demo-prerelease.grocy.info/) (both is also mentioned on the issue template).

**Closed by berrnd** 2021-02-27 19:22 UTC
Labels: duplicate

**Comment by Anwen747** [comment] 2021-02-27 19:42
Apologies, I did search open issues, should have searched closed ones as well.  I did not see the part about reproducing the issue on the pre-release demo, will remember that if I should have an issue in the future. Thanks for a great piece of software.
