### ISSUE TITLE
Feature request: Some suggestions on "quick use functions"

### ISSUE THREAD

**Issue by Michael-Linz** [grocy/grocy#1265] opened 2021-01-09 23:38 UTC
First of all, Grocy is an awesome piece of code! Nether the less I’d like to suggest some ideas correlation with each other:
(1) Choose override unit for quick consumption amount,
(2) always mark whole items as opened, 
(3) consume rest of already opened item first when using quick consumption button, and
(4) also transfer enhancements to receipt consumption.

In detail:
**Choose override unit for quick consumption amount:**
I’d like to choose an overridden unit for the quick consumption amount to see on the quick consumption-buttons. Here some use case for it:
* I usually buy and store garlic in bulb’s or a multiples of it. 
* In consumption I usually just use cloves of the garlic. By the way, statistically each bulb contains 12 cloves.
* I’d prefer to see “1 clove” on the button, and not “0,083 bulbs”.

**mark whole items as opened:**
Would be great if the “quick mark as open” button would mark the rest of an just opened item as opened as well, so if I consume a whole receipt with e.g. 0,5 l of milk, it would mark the second half of the 1-liter-milk carton as well. So it should open whole items all the time. I'd hardly be able to just open an half carton of milk.

**consume rest of already opened item first when using quick consumption button:**
Sometimes when you’re cooking it happens, that you run out of something but you're missing just a little of the usual amount you’d use usually. But who would open a fresh item for e.g. 5 ml of milk?
So it would be great if the first click on the “quick consumption”-button would first use the rest of the already opened item when it’s less then your standard quick amount, and only the second click should "open" the next item and subtract the missing rest for your standard amount OR a should start to subtract a whole standard amount again.

**receipt consumption**
The considerations above could be implemented on the consumption of receipts as well.  Ask the use if he will shorten his consumption a little, not to be forced to open a fresh item if it would be necessary otherwise. Also allow to consume a receipt although not all ingredients are available in stock, and ask the user if he’d maybe substituted the product. It would be a great improvement paired with the one asked for under #385. Always mention, you’d never buy e.g. a whole carton of milk for just 5 ml missing. ... maybe a button at the receipt to call this function manually
This even might be a little easier to implement first, as it just would need a popup-window for example, , where you are able to enter the actually used amounts and the actually used substitutes as well, maybe in a simple table-format like this:
| Label: Receipt ingredient | Input: actually used amount | selection: substitute | input: used amount |

Maybe you’ll like some of the ideas. 😊
and please excuse my slightly insufficient English.

**Comment by berrnd** [comment] 2022-04-09 18:40
Multi-topic requests are more than hard to track, so just checking/splitting this up:

&nbsp;

> Choose override unit for quick consumption amount

Will be covered in / duplicate of #1845.

&nbsp;

> mark whole items as opened

If only whole units get opened (which of course is the only way which makes practically sense I guess) is dependent on how you configure your product units and the "Quick consume amount" product option. grocy doesn't enforce that.

&nbsp;

> consume rest of already opened item first when using quick consumption button

The default consume rule is "Opened first, then first due first, then first in first out". So opened stock entries will be already consumed first, when not providing something else explicitly (e.g. via the "Use a specific stock item" option on the /consume page or when consuming a specific stock entry directly).

&nbsp;

> receipt consumption

When consuming a recipe the exactly same rules, as when consuming from any other place, take place.

**Closed by berrnd** 2022-04-09 18:40 UTC
Labels: duplicate, question
