### ISSUE TITLE
Group meals in meal planner

### ISSUE THREAD

**Issue by deliantwo** [grocy/grocy#1395] opened 2021-03-02 18:01 UTC
Currently the daily meals are ordered by name within the day, bringing some confusion when I share it with my family (what are we going to eat for lunch?).
It would be nice to group them by "dinner" or "launch", for example (maybe not predefined).

**Comment by berrnd** [comment] 2021-03-02 18:03
Duplicate of #370 - please check existing requests before opening new ones (also mentioned on the request template).

**Closed by berrnd** 2021-03-02 18:03 UTC
Labels: enhancement
