### ISSUE TITLE
Super market API or scraper based on EAN

### ISSUE THREAD

**Issue by svh1985** [grocy/grocy#585] opened 2020-02-29 13:34 UTC
Is it possible to automatically get the image and description of an unknown scanned product from a supermarket?

Example:
https://www.coop.nl/product/8710847902963
The last part of the URL is the EAN, here we could scrape the image and product description.

**Comment by Forceu** [comment] 2020-02-29 13:44
The plugin [Barcode Buddy](https://github.com/Forceu/barcodebuddy/) already has a lookup function using openfoodfacts.org, you might be interested in that.

**Comment by berrnd** [comment] 2020-02-29 17:11
For the rest closing this as a duplicate of all the other issues about importing data.

**Closed by berrnd** 2020-02-29 17:11 UTC
Labels: duplicate
