### ISSUE TITLE
Bug: no unit displayed in recipe if plural form not filled in

### ISSUE THREAD

**Issue by Browed** [grocy/grocy#1895] opened 2022-05-22 09:33 UTC
Hello,
I noticed that if no unit plural existed, the display in recipes was not correct.
As you can see hereunder, I added a plural to the unit "g" (which is also "g" :) ) and the display is correct;
![Plural OK](https://user-images.githubusercontent.com/106012002/169688806-eb5f1acc-e706-4384-8555-cf2755b694e2.png)

However, when no plural is entered, the unit display is just empty:
![Plural NOK](https://user-images.githubusercontent.com/106012002/169688861-8e85ec0e-215a-4694-a2b0-3004273dd438.png)

Expected behaviour (for me at least) would be to display the singular form of the unit if the plural form doesn't exist.

**Comment by berrnd** [comment] 2022-05-22 10:12
Duplicate of #1878, already "fixed", not yet released.

Can also easily verified by trying to reproduce an "issue" first on the [pre-release demo](https://demo-prerelease.grocy.info) as also mentioned on the issue template.

And another super easy "fix" for this is to just fill out your quantity unit plural forms, most probably that's faster than creating this issue here...

**Closed by berrnd** 2022-05-22 10:12 UTC
Labels: duplicate

**Comment by Browed** [comment] 2022-05-22 12:42
My bad, I missed this one.
And as [schnillerman](https://github.com/schnillerman), it's not because of lazyness, it's just I wasn't aware of the impact of not adding a plural form when I added the units ;).
To be honest, I first thought there was something wrong with my install as I didn't see the unit in the recipe and it was after investigation that I understood that it came from the missing plural form.

Have a good one,

Jonathan
