### ISSUE TITLE
Feature Request: Linking Equipment & Chores

### ISSUE THREAD

**Issue by cannibalflea** [grocy/grocy#2087] opened 2023-01-01 02:57 UTC
**Edit: this might be the same as #1558 so feel free to close it**

I am wondering if any thought has been given to linking chores/tasks to the equipment. Tracking equipment inspection, maintenance and repair tasks is one of the use cases that I have been investing some time in and think it could really benefit from a tighter integration between these two feature.

I think it would be amazing to see a maintenance log book for each piece of equipment so you can go back and track all the work you have done on each equipment.

**Comment by berrnd** [comment] 2023-01-01 08:33
Duplicate of #1558 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-01-01 08:33 UTC
Labels: duplicate
