### ISSUE TITLE
Feature Request: Edit database in table format / en-mass

### ISSUE THREAD

**Issue by Payne530** [grocy/grocy#2442] opened 2024-01-14 16:25 UTC
I am in the process of adding a user field to my database. I have already been working with grocy for awhile and have some data in the database. Rather than having to edit all the data in the database manually, I'd like to be able to edit it in the form of a spreadsheet.

I looked at possibly using the REST api, but I don't have any experience with it. Thought it would be nice if there was a way to export the data, do my edits and then import the changes back into the program.

**Comment by berrnd** [comment] 2024-01-14 16:33
Please be so kind and do at least a little tiny search beforehand, that's also mentioned on the request template.

Duplicate of #129 (and #2165, #2043, #895, #1756, #1660) for import/export.

Duplicate of #1020 (#1831, #2049, #2067, #2071, #2090, #2343) for mass editing master data on the web frontend.

**Closed by berrnd** 2024-01-14 16:33 UTC
Labels: duplicate
