### ISSUE TITLE
Multiple Products - one Barcode

### ISSUE THREAD

**Issue by Offi83** [grocy/grocy#2187] opened 2023-04-01 09:04 UTC
It would be nice to support multiple products with one barcode.

For example all wheat flour from my grain mill has the same barcode regardless from the grain type (All-Purpose Flour, Whole Wheat, ...), they only differ the barcode by type of grain.

**Comment by berrnd** [comment] 2023-04-01 10:31
The headline contradicts the mentioned example...

Related to the headline: A barcode is an alias for a product, so one barcode, one product. Practically for e.g. chocolate of different flavors which all have the same barcodes, since sold for the same price, this is the classical use case where most grocy users use the "generic parent product + child per flavor. Or simply use the stock entry notes field for that. Or a custom Userfield. Or don't care about it and only trick it as the generic product. The flavor can't be read from the barcode, since it's the same. Related other Feature Request: #1846

Related to the example: I read as it's the _not_ the same barcode per grain type. So most probably a duplicate of #1013 - please have a look at existing requests before opening new ones.

**Closed by berrnd** 2023-04-01 10:31 UTC
Labels: duplicate
