### ISSUE TITLE
Bug: Journal undo not working

### ISSUE THREAD

**Issue by Zerwin** [grocy/grocy#267] opened 2019-05-23 18:50 UTC
OS: Debian 9.9
System: x86
Version: [LinuxServer Docker Version of grocy ](https://github.com/linuxserver/docker-grocy), which should be the latest version

Bug: Sometimes after purchasing and consuming multiple pieces of the same item, if you then try to undo the actions in the journal, it will do so for the first few items, but will stop after a few and simply do nothing when you press the undo button. I noticed this behaviour first on my local install, and later confirmed it on the demo version and on the offical (the not LinuxServer version) docker image. (Not sure how long the demo is up, but currently I can't undo chips)
![gimp-grocy](https://user-images.githubusercontent.com/46265592/58278091-794cf400-7d9b-11e9-8e50-49f1e7c81805.png)

I noticed in the console of my docker image that if the undo works, this line will appear 

`23/May/2019:18:47:47 +0000 "POST /index.php" 204` 

while at a failed, a 
`23/May/2019:18:47:54 +0000 "POST /index.php" 400`
will appear. 

I guess the last code is the http response code, indicating that the undo doesn't work because of a missing page ?

**Comment by berrnd** [comment] 2019-05-23 19:51
The API gives a proper response / error message, but that's not shown - will be fixed.

The problem is:
`{"error_message":"Booking has subsequent dependent bookings, undo not possible"}`

E. g. when you book a purchase, then consume the product, the purchase booking cannot be undone then (sure it could also undo the whole "tree of bookings", but that's another topic...).

**Comment by Zerwin** [comment] 2019-05-23 20:55
Thanks for the answer

**Comment by berrnd** [comment] 2019-05-24 06:37
I think we keep this open until it's fixed (show the problem properly in the UI)... :)

**Closed** 2019-06-08 14:54 UTC
Labels: ui-bug
