### ISSUE TITLE
Feature Request: quick direct editing of master data 

### ISSUE THREAD

**Issue by Shadowex3** [grocy/grocy#2067] opened 2022-12-17 23:48 UTC
It would be nice if it were possible to quickly and directly edit master data like the Products list as if it were a spreadsheet. Even without true spreadsheet behavior of copy/pasting to bulk populate fields it would still be very nice to be able to edit some of the exposed fields without needing to fully open each item individually.

**Comment by berrnd** [comment] 2022-12-18 07:36
Duplicate of #1020 (and #1831, and #2049) - please check existing request before opening new ones.

**Closed by berrnd** 2022-12-18 07:36 UTC
Labels: duplicate

**Comment by Shadowex3** [comment] 2022-12-18 08:17
Okay that's strange, I specifically searched for "Batch" and came up empty handed.
