### ISSUE TITLE
Bulk change of product properties

### ISSUE THREAD

**Issue by Sectorchan** [grocy/grocy#2343] opened 2023-09-17 20:23 UTC
Hi,

I've added all my products from my storage, but after adding them I found some parts that I've done wrong.
A bulk change of product properties would be great.

Sample: Chgangfe the next due date on multiple items of a category.

**Comment by berrnd** [comment] 2023-09-17 20:37
Duplicate of #1020 (and #1831, and #2049, and #2067, and #2071) - please be so kind and give the search function a little visit before opening new requests.

**Closed by berrnd** 2023-09-17 20:37 UTC
Labels: duplicate

**Comment by Sectorchan** [comment] 2023-09-17 20:58
it seems that i've searched the wrong way. sorry
