### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by maniackatzentier** [grocy/grocy#2046] opened 2022-11-19 19:09 UTC
I installed grocy on ngnix with Debian 11 and php 7.4, but some page don't load correctly

I got the following error in my nginx-log:
`2022/11/19 17:25:54 [error] 411#411: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Ramsey\Uuid\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312" while reading response header from upstream, client: 192.168.X.X, server: _, request: "GET /stockoverview HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.X.X"`

/etc/nginx/sites-available/default:

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        #Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/grocy/public;

        # Add index.php to the list if you are using PHP
        index index.html index.php index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                try_files $uri /index.php$is_args$query_string;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        location ~ /\.ht {
                deny all;
        }
}
```

any idea, what could be causing this?

Thank you!
![error](https://user-images.githubusercontent.com/75715432/202867465-45619924-f247-4535-a3de-3b78b2ef749f.JPG)

**Comment by berrnd** [comment] 2022-11-19 19:15
You use PHP 7.4, only PHP 8.0 is supported ([README ref](https://github.com/grocy/grocy#how-to-install)) since [v3.1.0](https://grocy.info/changelog#v3.1.0) (so since nearly 1.5 years).

Not a bug and a duplicate of #2038 and #2044 - searching beforehand would be super cool.

**Closed by berrnd** 2022-11-19 19:15 UTC
Labels: duplicate
