### ISSUE TITLE
Feature-Request : place of purchase

### ISSUE THREAD

**Issue by aaruni96** [grocy/grocy#490] opened 2020-01-11 18:18 UTC
It'd be really nice if while making a purchase, we can record what shop/supermarket the thing was purchased at, and the price tracker tracked prices per store.

So, if I sometimes purchase product from store A, and sometimes from store B, I want to see two graphs in the price tracker : one for store A and one for store B

**Comment by berrnd** [comment] 2020-01-12 08:24
Duplicate of #447.

**Closed by berrnd** 2020-01-12 08:24 UTC
Labels: duplicate
