### ISSUE TITLE
Feature Request: OAuth Authentication

### ISSUE THREAD

**Issue by quqkuk** [grocy/grocy#1626] opened 2021-09-26 22:18 UTC
The issue is self-explanatory. I'd like to log into grocy using my Nextcloud credentials, preferably by using OAuth (which is open and can be used with other platforms).
I could work on it, although I can't guarantee that I'll have something done quickly (mainly because my PHP knowledge is rusty).
Thank you for your feedback in advance!

**Comment by berrnd** [comment] 2021-09-27 08:06
Authentication is done by a configurable middleware, see [data/config.php](https://github.com/grocy/grocy/blob/04d826943cd39720a4591d9879b1f4f87658ec0b/config-dist.php#L72-L74).

Some others use this for example with [Authelia](https://www.authelia.com/) (and `ReverseProxyAuthMiddleware` in grocy), maybe have a look at the [subreddit](https://www.reddit.com/r/grocy).

About the Nextcloud integration: Duplicate of #406.

**Closed by berrnd** 2021-09-27 08:06 UTC
Labels: question
