### ISSUE TITLE
Feature Request: Remove QU conversions when removing QU

### ISSUE THREAD

**Issue by blue-hound** [grocy/grocy#1796] opened 2022-02-20 17:30 UTC
Private Demo: https://test-rt54hdmt6jpg63sfdc31v.demo-prerelease.grocy.info/

While investigating #1795, I also discovered this as well. I used the same test instance to demonstrate.

Using product: Coffee Beans

Steps to reproduce:

1. Create a products and use grams from both QU stock and default QU purchase. Leave everything else as default.
2. Go to Manager Master Data -> Quantity Units and add Kilograms with a default conversion to grams.
3. Check the coffee beans product. The default conversions are listed as expected.
4. Go back and delete the kilograms extry (accidents happen).
5. Go back to the coffee beans product and we have an orphaned entry that can't be deleted.
6. Going back to grams the default conversion to kg still exists and can be deleted.
7. The orphaned entry still exists in coffee beans product.

**Comment by berrnd** [comment] 2022-02-20 17:52
Have you checked if this has any effect? It won't have any, so just a theoretical and cosmetical problem. I don't care about both of them that much for grocy.

Duplicate of #https://github.com/grocy/grocy/issues/1770#issuecomment-1027869454.
The only "solution" would be to prevent to delete a anywhere referenced QU.

But ok, let's add to delete any conversions on deleting a quantity unit if that theoretical problem seems to be important.

**Closed** 2022-02-20 18:34 UTC
Labels: enhancement
