### ISSUE TITLE
Bug:  ERROR

### ISSUE THREAD

**Issue by DevEDVColin** [grocy/grocy#1635] opened 2021-10-03 16:20 UTC
This Error is since the Update came...

Error source:
```
/app/grocy/services/LocalizationService.php:76
```

Error message:
```
abs(): Argument #1 ($num) must be of type int|float, string given (View: /app/grocy/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /app/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/grocy/controllers/BaseController.php(179): Slim\Views\Blade->render()
#8 /app/grocy/controllers/BaseController.php(202): Grocy\Controllers\BaseController->render()
#9 /app/grocy/controllers/StockController.php(368): Grocy\Controllers\BaseController->renderPage()
#10 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ShoppingList()
#11 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /app/grocy/app.php(106): Slim\App->run()
#30 /app/grocy/public/index.php(45): require_once('...')
#31 {main}
```

**Comment by berrnd** [comment] 2021-10-03 17:04
Duplicate of #1629, already fixed, not yet released, see [here](https://github.com/grocy/grocy/issues/1629#issuecomment-929910248) if you want to have this now.

Would be great if you can check existing issues before opening new ones.

**Closed by berrnd** 2021-10-03 17:04 UTC
Labels: duplicate
