### ISSUE TITLE
Add Receipt to Equipment

### ISSUE THREAD

**Issue by shadow7412** [grocy/grocy#968] opened 2020-08-29 02:07 UTC
It would be useful to store an image (or pdf) containing the receipt for a given piece of equipment, so that it can be quickly and easily found if required.

Such a field could either be accessed as a file download link, or in a tab with a viewer, similar to how manuals are currently viewed.

**Comment by berrnd** [comment] 2020-08-29 06:23
Duplicate of #441.

**Closed by berrnd** 2020-08-29 06:23 UTC
