### ISSUE TITLE
[Bug] Landing page is set to Equipment if FEATURE_FLAG_BATTERIES = false

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#309] opened 2019-07-10 08:30 UTC
Version 2.4.4

If FEATURE_FLAG_BATTERIES = false is set in config.php, the landing page is for some reason set to Equipment instead of Stock Overview. Even worse, when equipment is disabled as well, the home page gives a "Page not found" error with a "Visit the Home Page" link which does not work.

Tested with production instance and a completely new instance, both show the same behaviour.

Might be related to #294

**Comment by berrnd** [comment] 2019-07-10 08:47
Yes, duplicate of #294, all problems about this will be covered in #290 by @nielstholenaar...

**Closed by berrnd** 2019-07-10 08:47 UTC
Labels: duplicate

**Comment by Forceu** [comment] 2019-07-10 09:48
I am not sure if this is actually a duplicate, as only the **Battery** flag is disabled. It should still show the regular stockoverview page

**Comment by berrnd** [comment] 2019-07-10 09:51
The whole logic about the entry page with disabled feature flags needs to be rethought, including a new option to set a custom entry page - is all part of #290...
