### ISSUE TITLE
Bug : After clicking save on 'add ingredients' page grocy hangs

### ISSUE THREAD

**Issue by jwhite** [grocy/grocy#1490] opened 2021-05-26 04:02 UTC
When creating a recipe, and adding an ingredient, the browser hangs with a spinning disc after clicking save.

Ingredient is in fact added, but browser never returns to the recipie.

**Comment by jwhite** [comment] 2021-05-26 04:03
Might be related/same as issue : https://github.com/grocy/grocy/issues/1302

**Comment by berrnd** [comment] 2021-05-26 07:09
Please provide the exact steps (like also mentioned on the issue template) to reproduce that, works in general on the demo instances, can't guess the rest...

If Userfields are involved, than that's a duplicate of #1302.

**Closed by berrnd** 2021-05-26 07:09 UTC
Labels: invalid

**Comment by jwhite** [comment] 2021-05-27 03:16
It does seem to work on the demo instance.
I'm running the home assistant integration (3.0.1)

Here is my workflow (with screenshots)

1) click recipes
![image](https://user-images.githubusercontent.com/473577/119760387-046aa280-befe-11eb-84e8-2b3d5cc7cc5f.png)

2) click korean chicken edit button

3) click add ingredient
![image](https://user-images.githubusercontent.com/473577/119760502-3da31280-befe-11eb-9a82-561e97f8a6e2.png)

4) Pick an existing ingredient (note that you can't see the save button)
![image](https://user-images.githubusercontent.com/473577/119760560-56132d00-befe-11eb-8598-6c2dbd6bb329.png)

5) Select the amount of 1.

6) Hit Save
(at this point the dialog goes grey, and control never returns to the user.  Spinning disk on winodows 10)

![image](https://user-images.githubusercontent.com/473577/119760664-8064ea80-befe-11eb-959b-a96bc0b894d1.png)

**Comment by jwhite** [comment] 2021-05-27 03:17
@berrnd Can you re-open please?

**Comment by berrnd** [comment] 2021-05-27 06:41
Then please check the browser console or the webserver logs for errors - most probably something on saving the recipe ingredient via the API goes wrong...

> Can you re-open please?

This here is the issue tracker, so for reproducible bugs - the better place for general help is the [subreddit](https://www.reddit.com/r/grocy) like also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests). But also there I guess it's hard to help without any insights (means logs, etc.) - or how do you think I should know what's going on behind the scenes in detail by only having the screenshots? ;D

**Comment by jwhite** [comment] 2021-05-27 20:52
This is what I am seeing in the browser console.  I think it might have something to do with how it is containerised?

![image](https://user-images.githubusercontent.com/473577/119895462-ec446300-bf91-11eb-8c8c-38bf0405552b.png)

Any idea what the remedy is?  Nginx configuration maybe?

**Comment by berrnd** [comment] 2021-05-28 06:59
That's about that your [`BASE_URL` setting](https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/config-dist.php#L50-L53) is wrong (don't know where to configure this in Home Assistant).

Any dialog is technically an `iframe`, communication between the dialog and the "parent window" (recipe edit page here) happens via [`window.postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) which needs the current URL in the mentioned `targetOrigin` parameter for security reasons.

You can also check the configured `BASE_URL` via the Browser Console - it's stored in `Grocy.BaseUrl` (just paste that into the console to show the current value).

**Comment by morrolinux** [comment] 2022-04-05 19:45
I'm having the same issue. The `BASE_URL` variable is correct in my case (checked via `Grocy.BaseUrl` in the console) but an error pops up: 
`Uncaught ReferenceError: RPMGetInnerMostURI is not defined`

**Comment by berrnd** [comment] 2022-04-05 20:04
> `Uncaught ReferenceError: RPMGetInnerMostURI is not defined`

Have you tried at least two different browsers? Quickly googling that clearly leads to some not so old Firefox bugs...

Beside that, can still only be a problem about a wrong `BASE_URL` and this here is still the issue tracker for reproducible bugs, not the place to discuss individual setup problems.

**Comment by morrolinux** [comment] 2022-04-08 17:33
Yes, I did try more than one browser. Firefox and Chrome behave the same. 
I'm sorry if this is not the place, but just to be sure it's not an unhandled corner case: what should be the value of `BASE_URL` if grocy is to be accessed on the base domain but only on a different port? (e.g: `mysite.com`) I could not find any example on the docs.

**Comment by berrnd** [comment] 2022-04-08 17:58
`BASE_URL` is just used to build URLs, for example `/stockoverview` is appended, so it needs to be whatever needs to be in front of `/stockoverview` to build a for your setup valid URL.

If grocy runs on a "root domain" (so `example.com` or `grocy.example.com`, means not in a subdirectory) and regardless if it's a standard port or not, the default value `/ ` is enough to have a fully working setup - mentioned also on the [config.php comment](https://github.com/grocy/grocy/blob/e9421e9102e78eca519fd16d53592b6a57f22f66/config-dist.php#L55-L57). I use that daily in my development setup without any problems, so definitely not any "unhandled corner case".

If it's about the home assistant integration, things most probably behave differently there, because t[hey apply some own patches](https://github.com/hassio-addons/addon-grocy/blob/main/grocy/rootfs/patches/fix_braindamage.patch) regarding `Grocy.BaseUrl` (for whatever reason, I don't know and use anything of that).

A simple setup, root-/subdomain, no subdirectory, no custom port, not using any of the "integrated" packages is IMHO the most headache-free way to run grocy. I always don't get why people so often prefer the hard way.
