### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Mstrrlm** [grocy/grocy#286] opened 2019-06-18 03:18 UTC
Adding ability to select ingredients and search local and internet recipes that match your ingredients selected. Also maybe a recipe category such breakfast, lunch, Dinner, snack, dessert check box them it searches local and internet for recipes for your selection and that you have all the ingredients in inventory

**Comment by berrnd** [comment] 2019-06-18 06:59
As already mentioned in #285:

- Duplicate of #210 and #158
- Add categories to recipes by using Userfields (see #176)

**Closed by berrnd** 2019-06-18 06:59 UTC
Labels: question
