### ISSUE TITLE
Feature request: Set a default price for a product

### ISSUE THREAD

**Issue by ditmarvisser** [grocy/grocy#1614] opened 2021-09-16 13:11 UTC
I would like to set a default price for a product, which can get used in the total price that is displayed in a recipe. Right now when you don't have an ingredient, that ingredients price does not get added in the recipies total price. If we can set a default price to which Grocy can fall back that will be solved. Then we can also add prices for product that we don't have in stock.

**Comment by berrnd** [comment] 2021-09-16 13:20
Duplicate of #779.

**Closed by berrnd** 2021-09-16 13:20 UTC
Labels: duplicate
