### ISSUE TITLE
Bug: Stock overview "Due within x days" not always working 

### ISSUE THREAD

**Issue by davidecalza** [grocy/grocy#1400] opened 2021-03-07 12:53 UTC
I tried adding this product called "Panna da cucina", with "ml" as default unit, and purchased 200 units of it (i.e. 200 ml).
While purchasing I set the due date to the 2021-03-09.
In the stock overview it is correctly highlighted in yellow but the counter on top is not incremented.
I would expect it to tell me that one product will be due within 5 days. 

**Notes:**
- The stock was empty at the moment of the test.
- I tried with other products and it is working fine, but I couldn't figure out the issue with this particular use case.

**Steps to reproduce:**

1. Add a product called "Panna da cucina" with the following settings and the other fields set to their default values:
<br />![Step 1](https://i.postimg.cc/qqkcTZr6/2021-03-07-132933-1154x869-scrot.png)

2. Purchase 200 ml of the product setting due date in 2 days
<br />![Step 2](https://i.postimg.cc/3RjjzQsH/2021-03-07-133031-765x667-scrot.png)

3. Go to the stock overview and you will find the due soon counter is still equal to 0. However, as you can notice, the product is highlighted in yellow, so it is somehow recognized as "due soon".
<br />![Step 3](https://i.postimg.cc/zvjszMRs/2021-03-07-134759-1011x279-scrot.png)

**Comment by berrnd** [comment] 2021-03-07 13:32
Duplicate of #1372, already fixed, not yet released - please check existing issues first and/or try to reproduce your problem on the [pre-release demo](https://demo-prerelease.grocy.info/) before reporting (both is also mentioned on the issue template).

> I tried with other products and it is working fine, but I couldn't figure out the issue with this particular use case.

The difference is the product option `Due date type`.

**Closed by berrnd** 2021-03-07 13:32 UTC
Labels: duplicate
