### ISSUE TITLE
Feature Request: 'Full or individual section' Import / Export.

### ISSUE THREAD

**Issue by Aliyah-Sophia** [grocy/grocy#1660] opened 2021-11-01 21:26 UTC
Hi, Love your all the hard work you put into making your vision a reality. I have thought about doing something like this for years. I only just heard about grocy from YouTube. I have recently become obsessed with self hosing on my Raspberry Pi and that is how I came to find out about it.
I have two questions:

1. Is there a way to export import? I have a couple of reasons why I feel it would add great value to Grocy. Fist it would be a way to backup data. I'm not a programmer and not sure how PHP databases work. But I was thinking you could have one way of export / import fro each database. i.e. Products / Stores / other. Or you could have the whole thing with a check box to available fields when importing.  But my main reason for the import / export suggestion is so I can export from your demo account then import to my live data. Then I will just make updates as needed.
2. The second is having a barcode scanner that will find actual products from an external source. I'm not sue if this is possible all ready. I did read something about it linked to a fee. But I'm not sure how to set it up on my Raspberry Pi and I would love to support it like that.

Thank you,
Chris
ChrisDePasquale@gmail.com

**Comment by berrnd** [comment] 2021-11-01 22:26
This is not the right place for general usage questions, please use the [subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

About import/export: Duplicate of #129 - as of now you can use the API, manually editing the database is also an option.

About backup: Simply backup the whole `data` folder (or the whole grocy directory) - not different than doing backups as for any other web app.

About barcode lookup: Already possible by implementing a barcode lookup plugin ([README ref](https://github.com/grocy/grocy#barcode-lookup-via-external-services)), however, most who need that are using [Barcode Buddy](https://github.com/Forceu/barcodebuddy) I would say.

**Closed by berrnd** 2021-11-01 22:26 UTC
Labels: invalid
