### ISSUE TITLE
Bug: Shopping List Add to Stock Button

### ISSUE THREAD

**Issue by morgan2233** [grocy/grocy#2261] opened 2023-06-23 03:12 UTC
I've installed 3.3.2 three times and get the same issue; when on the shopping list, if I press the "add this button to stock" it shows a blank box:

<img width="610" alt="chrome_W3bF2Wy2Px" src="https://github.com/grocy/grocy/assets/17581221/dcbd3026-2ee6-4b83-a73b-52cd12a24567">

however, if I then resize the browsers even a tiny bit, it shows up. I took a video to showcase this and attached below:

https://github.com/grocy/grocy/assets/17581221/69fd8dc8-1ebb-44ef-879b-291db3cbdcd9

Using Version 3.3.2 and using the Chrome Browser.

**Comment by berrnd** [comment] 2023-06-23 06:08
Can't reproduce this using 114.0.5735.134 on https://demo.grocy.info and neither on https://demo-prerelease.grocy.info - please always try to reproduce problem first on the demo instances (as mentioned on the issue template).

Does it also happen there? Have you tried it by disabling all Browser add-ons first? More than often a some of them interfere with things...

**Comment by berrnd** [comment] 2023-06-24 19:33
Closing this until a reproducible example is provided - it's impossible to fix anything without having it reproducible.

**Closed by berrnd** 2023-06-24 19:33 UTC
Labels: invalid/unreproducible/missing-feedback
