### ISSUE TITLE
Bug: stock entries can not be changed 

### ISSUE THREAD

**Issue by phatair** [grocy/grocy#1373] opened 2021-02-21 14:59 UTC
I use the current version 3.0.1 and i tested it on in my personal installation and in the demo installation. 

If I try to edit a existing stock entry I can not change for example best before date or the amount. 
If I  change it and click OK, close it and reopen it,  it is not saved. 

Maybe I'm doing something wrong or it is a bug.
Thanks

**Comment by Ape** [comment] 2021-02-21 15:01
This has already been fixed: https://github.com/grocy/grocy/blob/master/changelog/62_UNRELEASED_xxxx-xx-xx.md

Please test here to confirm: https://en.demo-prerelease.grocy.info/

**Comment by phatair** [comment] 2021-02-21 15:14
Thanks ape, I did not found this info.
So to fix this problem, I have to install the unreleased version?

**Comment by berrnd** [comment] 2021-02-21 15:44
Yes, duplicate of #1268 - please always check existing issues before reporting like also mentioned on the issue template.

> I have to install the unreleased version?

Of course you can do that, but please keep in mind that database migrations most of the time only work between releases, not between any commit in the master branch.

**Closed by berrnd** 2021-02-21 15:44 UTC
Labels: duplicate, ui-bug
