### ISSUE TITLE
Feature request: Don't allow item to be added twice to shopping list (instead sum up quantities)

### ISSUE THREAD

**Issue by AllesMeins** [grocy/grocy#1122] opened 2020-11-07 13:58 UTC
If one product is already on the shopping-list I would find it useful to either get a warning when trying to add the same item again or automatically increase the quantity instead of adding the same item twice.
So if I've already 2 packs of butter on my list and some days later try to add another butter currently I end up with two items on my list instead of Grocy just grouping it to 3xButter.

**Comment by berrnd** [comment] 2020-11-07 14:14
That's already the case when add the item from the stock overview page (context menu of each row) and when using "Add products that are below defined min. stock amount".

To do this also for recipes (including the meal plan) is already tracked in #925 and #840.

If you add a product manually, I would say it's ok to add another item to the shopping list because that's what you just explicitly did - however, we can add an option to group/sum them always.

**Comment by berrnd** [comment] 2022-02-10 19:57
Duplicate of / merged into #840.

**Closed by berrnd** 2022-02-10 19:57 UTC
Labels: duplicate
