### ISSUE TITLE
Bug: Entering inventory quantities ending in zero, truncates the zero

### ISSUE THREAD

**Issue by stripler675** [grocy/grocy#1370] opened 2021-02-21 03:14 UTC
Grocy 3.0.1-ls94
docker image linuxserver/grocy:latest
Entering initial inventory or purchase qty such as 50, creates an inventory amount of 5. 51 works, 49 works, 50 becomes 5. 60 becomes 6, etc.
As a workaround, entering 51 first, then consuming 1 does reduce to 50.
![2021-02-20 22_10_17-Inventory _ grocy - Brave](https://user-images.githubusercontent.com/79389032/108614464-9ecfbd00-73c8-11eb-901a-09bc238d660d.png)

**Comment by berrnd** [comment] 2021-02-21 08:21
Please provide the exact steps and product information to reproduce this or better: Reproduce it on a private demo instance as mentioned on the issue template.

I have no clue how to help and can't reproduce it without any context of QU conversion assigned to the product and so on...

**Closed by berrnd** 2021-02-21 08:21 UTC
Labels: invalid

**Comment by berrnd** [comment] 2021-02-21 08:23
If it's about the [/inventory](https://demo.grocy.info/inventory) page and you enter 50 Bottles there this would be simply correct, when currently 45 Bottles are in stock, hence the /inventory page is supposed to correct the current stock amount, so removes or adds something based on the new entered amount.

In contrast, the [/purchase](https://demo.grocy.info/purchase) page always adds the amount entered there, the [/consume](https://demo.grocy.info/consume) page always removes the amount entered there.
