### ISSUE TITLE
Bug: Unit conversion floating point error

### ISSUE THREAD

**Issue by libklein** [grocy/grocy#1769] opened 2022-02-01 21:22 UTC
Hi!

I've noticed an issue with finite float precision when consuming products with wierd conversion factors. See the screenshots for details. Here, 1 pack == 750 grams and grams is used as product's quantity unit in stock such that the conversion factor equals 1/750. 

![image](https://user-images.githubusercontent.com/42714034/152052037-99404a15-c7d0-4c67-b6a9-9f3551df499b.png)

![image](https://user-images.githubusercontent.com/42714034/152052052-e2307c59-a020-495d-91bb-e295644cfac4.png)

![image](https://user-images.githubusercontent.com/42714034/152052069-b691227c-6123-43d3-9a78-f3d13d466224.png)

The problem is in https://github.com/grocy/grocy/blob/7e6efb4a14700374adbc456fb50e5a551c39ba76/public/viewjs/consume.js#L667. 

As a quick fix, i'd suggest rounding max/min values to a precision proportional to the largest/smallest conversion factor of the units defined for the product. I'd be happy to prepare a PR if you agree with that. From my understanding, the API should handle any rounding on the frontend just fine if done such that min/max is not exceeded (https://github.com/grocy/grocy/blob/7e6efb4a14700374adbc456fb50e5a551c39ba76/services/StockService.php#L409).

I suppose this is related to https://github.com/grocy/grocy/issues/389.

**Comment by berrnd** [comment] 2022-02-01 21:39
Any amount is rounded (at reasonable places, not limited to the frontend or backend; mostly the backend/API doesn't handle anything about rounding) based on the [stock setting `Decimal places allowed for amounts`](https://demo.grocy.info/stocksettings#group-stock_decimal_places_amounts).

This is generally a duplicate of #389.
Everything, except using real fractions which #389 is about, is just a workaround.
The products stock QU is always the base any conversion.

Practical sense of that example:
Du kaufst ein TK-Fertiggericht in 750g Packungen und trackst dann wirklich jedes Gram? Verrückt...

**Closed by berrnd** 2022-02-01 21:39 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2022-02-01 22:03
> As a quick fix, i'd suggest rounding max/min values to a precision proportional to the largest/smallest conversion factor of the units defined for the product.

And just out of curiosity, how should the best-fit-rounding-guessing happen? I guess it would always end up to round `max` by zero decimal places and `min` by a lot - so we could also do just that. Or remove the min/max limitation for amount inputs completely, which is mostly form validation sugar - the API of course doesn't allow to consume more than present in stock.
