### ISSUE TITLE
slim application error

### ISSUE THREAD

**Issue by blakkmaan** [grocy/grocy#119] opened 2018-11-30 21:02 UTC
hey, i just wanted to try out grocy but i can't get it to run. my server is a centos 7.5 server with apache + php 7.2 installed as well as the pdo extensions. i nano'd the config.php to my needs and then if i pull up my url i got the following displayed:

Slim Application Error
The application could not run because of the following error:

Details

Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 table recipes_nestings already exists
File: /var/www/grocy/services/DatabaseService.php
Line: 45
Trace

#0 /var/www/grocy/services/DatabaseService.php(45): PDO->exec('CREATE TABLE re...')
#1 /var/www/grocy/services/DatabaseMigrationService.php(47): Grocy\Services\DatabaseService->ExecuteDbStatement('CREATE TABLE re...')
#2 /var/www/grocy/services/DatabaseMigrationService.php(23): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded(43, 'CREATE TABLE re...')
#3 /var/www/grocy/controllers/LoginController.php(70): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 [internal function]: Grocy\Controllers\LoginController->Root(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/grocy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /var/www/grocy/middleware/SessionAuthMiddleware.php(26): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/grocy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/grocy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/grocy/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/app.php(71): Slim\App->run()
#19 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy...')
#20 {main}

**Comment by blakkmaan** [comment] 2018-11-30 21:10
i did make a fresh install again, same slim application error, but another message:
Message: SQLSTATE[HY000]: General error: 1 near "WITH": syntax error

i think the message above is resulting due to multiple reloads of the page

**Comment by BlizzWave** [comment] 2018-11-30 23:39
Duplicate of #104 it seems.

**Comment by berrnd** [comment] 2018-12-01 07:31
Yes, seems to be the same problem as in #104, you need SQLite >= 3.8.3 as mentioned there and in README - thanks @BlizzWave.

**Closed by berrnd** 2018-12-01 07:31 UTC
Labels: question
