### ISSUE TITLE
Feature Request: Create a storage system for equipment

### ISSUE THREAD

**Issue by Gagonjh** [grocy/grocy#2005] opened 2022-09-25 08:00 UTC
For me the equipment tab is not as usefull as I hoped, so my suggestion would be add inventory management to equipment tab.

Every equipment should have a quantity and a location. In adition for easy handling the location and equipment need a barcode to change the location. And it would be nice if a location can be child of a location. As an example a box in the basement.

Many thanks to all developers for the great work.

**Comment by berrnd** [comment] 2022-09-25 08:09
Utilize Userfields to attach any field you want to any entity you want (ref #176).

I've created a simple example for you: https://test-clkrwp16wagxh5gpunyjpe.demo.grocy.info/equipment

![grafik](https://user-images.githubusercontent.com/2161815/192134253-85abc070-ea73-43e1-ad29-c1626b9eed54.png)

&nbsp;
To be able to re-use built-in objects (Location) for Userfields is a duplicate of #335.

&nbsp;
> And it would be nice if a location can be child of a location

Duplicate of #481.

&nbsp;
> a barcode to change the location.

Duplicate of #1872.

**Closed by berrnd** 2022-09-25 08:09 UTC
Labels: duplicate
