### ISSUE TITLE
Feature Request: Schedule chores via API

### ISSUE THREAD

**Issue by logdou** [grocy/grocy#2048] opened 2022-11-20 20:39 UTC
It would be nice to have the ability to schedule chores via the API, especially for chores set to Manual.  That way, another tool (such as Home Assistant) could create an entry for that chore based off something being detected, for instance, the dishwasher is running, so when it finishes running, schedule a chore as a reminder to unload the dishwasher.

**Comment by berrnd** [comment] 2022-11-20 22:43
Everything what the web frontend is able to do, is possible via the API, because the web frontend uses the API for everything. A very simple way to find out how things work is to use the UI, while also having a look at your favorite browsers developer tools and see what actually happens.

Example request to reschedule and reassign a chore:
```
curl -X 'PUT' \
  'https://demo-prerelease.grocy.info/api/objects/chores/1' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "rescheduled_date": "2025-01-05",
  "rescheduled_next_execution_assigned_to_user_id": "2"
}'
```
Also a duplicate of #2042 - searching beforehand would be super cool.

**Closed by berrnd** 2022-11-20 22:43 UTC
Labels: duplicate
