### ISSUE TITLE
Feature request: the use of objects in userfield types

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1157] opened 2020-12-06 18:54 UTC
I'm wondering if it would be possible to use objects_products/locations/stores in the as Types in userfeilds. 

its possible to manually create with lists but I have to situations this could be used. 

1) assigning a store or a stock_log ID to a receipt image uploaded to a user entity

2) when we log walk-in freezer and cooler temps, we could select from a list of locations instead of a manually built list (even though our storage locations dont ever change)

![image](https://user-images.githubusercontent.com/65983438/101289248-e62eb000-37c0-11eb-92b6-47391ef10877.png)

**Comment by berrnd** [comment] 2020-12-06 19:44
Duplicate of #335.

**Closed by berrnd** 2020-12-06 19:44 UTC
Labels: duplicate
