### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Camrais** [grocy/grocy#1550] opened 2021-07-29 18:05 UTC
I wanted to update grocy manually since my NAS doesn't have unzip installed which is needed for the update.sh. So i replaced everything with the newest release files and cleaned the data/viewcache loaded the website and clicked onto the logo to make the migration of the databases and then this error came. I didn't do anything on the database and before upgrading grocery worked just fine.

My NAS is a Synology NAS Diskstation 718+. I installed grocy into the WebStation and setup an Virtual Host which points to the web/grocy/public folder. Im using PHP 7.4.

Error source:
```
/volume1/web/grocy/services/DatabaseService.php:35

```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 Unsupported product nesting level detected (currently only 1 level is supported)
```

Stack trace:
```
#0 /volume1/web/grocy/services/DatabaseService.php(35): PDO->exec('ALTER TABLE pro...')
#1 /volume1/web/grocy/services/DatabaseMigrationService.php(63): Grocy\Services\DatabaseService->ExecuteDbStatement('ALTER TABLE pro...')
#2 /volume1/web/grocy/services/DatabaseMigrationService.php(33): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded(130, 'ALTER TABLE pro...')
#3 /volume1/web/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /volume1/web/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#5 /volume1/web/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#6 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#7 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#8 /volume1/web/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#9 /volume1/web/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#10 /volume1/web/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#11 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#12 /volume1/web/grocy/middleware/AuthMiddleware.php(31): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#13 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#14 /volume1/web/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#15 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#16 /volume1/web/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#17 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#18 /volume1/web/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#20 /volume1/web/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 /volume1/web/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#22 /volume1/web/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#23 /volume1/web/grocy/app.php(106): Slim\App->run()
#24 /volume1/web/grocy/public/index.php(45): require_once('/volume1/web/gr...')
#25 {main}
```

**Comment by berrnd** [comment] 2021-07-29 18:55
Duplicate of #1542 - already fixed, not yet released - please check existing issues (like also mentioned on the issue template) before reporting.

**Closed by berrnd** 2021-07-29 18:55 UTC
Labels: duplicate

**Comment by Camrais** [comment] 2021-07-30 08:18
Fascinating. I searched the bugs reports for 'migration' but it didn't give me this one. Sorry for that.
