### ISSUE TITLE
Feature Request: Allow custom user fields to show up on the consume screen

### ISSUE THREAD

**Issue by me-ssaxena** [grocy/grocy#2620] opened 2024-12-14 07:52 UTC
Requirement: It would be great if we can have the ability for custom user fields to show up on the consume page. 

While consuming something, sometimes we like to add a custom note or some additional data like reason for consumption or spoilage. Allowing custom user fields to consume page will allow us to add some additional information without affecting existing workflows. This is great to then look at the journal and quickly find out the reason for consumption/spoilage.

**Comment by berrnd** [comment] 2024-12-14 12:11
Duplicate of / merged into #2156.

**Closed by berrnd** 2024-12-14 12:11 UTC
Labels: duplicate
