### ISSUE TITLE
UI freezes clicking in Purchase screen

### ISSUE THREAD

**Issue by dibyadip-das** [grocy/grocy#882] opened 2020-06-02 05:22 UTC
# Problem/Motivation
On the Purchase tab, after I make the selection and click on the OK button, the UI hangs.

## Expected behavior
Should have added the product to inventory.

## Actual behavior
Screen hangs

I tried to even investigate the logs but cannot see any error messages.

Got the below error from Chrome Dev Console:
![image](https://user-images.githubusercontent.com/47345141/83413608-c1d0d000-a439-11ea-8a3d-b0b369a2f96f.png)

## Log (Error msg in 3rd and 5th Line)
```
[01/Jun/2020:21:43:12 +0530] 204 192.168.1.13, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36)
[01/Jun/2020:21:44:13 +0530] 200 192.168.1.13, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36)
2020/06/01 21:44:13 [error] 1293#1293: *262 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: nextInputSelector in /data/grocy/viewcache/23b0f6eb24ccc18da3d06dcd04960ed02aab5979.php on line 10PHP message: PHP Notice:  Undefined variable: hintId in /data/grocy/viewcache/23b0f6eb24ccc18da3d06dcd04960ed02aab5979.php on line 11" while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-grocy, request: "GET /purchase HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "192.168.1.200:8123", referrer: "http://192.168.1.200:8123/api/hassio_ingress/Crhgx51-Y3A31URZ5d9pBkzQIQig-OIk_wMU8lLeZAY/purchase"
[01/Jun/2020:21:44:13 +0530] 200 192.168.1.13, 172.30.32.1(172.30.32.2) GET /purchase HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36)
2020/06/01 21:44:13 [error] 1293#1293: *262 open() "/var/www/grocy/public/node_modules/bootstrap-switch-button/css/bootstrap-switch-button.css" failed (2: No such file or directory), client: 172.30.32.2, server: a0d7b954-grocy, request: "GET /node_modules/bootstrap-switch-button/css/bootstrap-switch-button.css?v=2.7.1 HTTP/1.1", host: "192.168.1.200:8123", referrer: "http://192.168.1.200:8123/api/hassio_ingress/Crhgx51-Y3A31URZ5d9pBkzQIQig-OIk_wMU8lLeZAY/purchase"
[01/Jun/2020:21:44:13 +0530] 404 192.168.1.13, 172.30.32.1(172.30.32.2) GET /node_modules/bootstrap-switch-button/css/bootstrap-switch-button.css?v=2.7.1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36)
```

**Comment by berrnd** [comment] 2020-06-02 06:43
I cannot reproduce this, so the exact steps done would be needed (or maybe better a short screenvideo).

**Comment by dibyadip-das** [comment] 2020-06-02 08:04
@berrnd  I have uploaded a video on Youtube. I hope it helps  👍 
https://youtu.be/2WO2Zs4bnfc

**Comment by berrnd** [comment] 2020-06-02 11:05
Thanks, still just guessing:
`FEATURE_FLAG_STOCK_LOCATION_TRACKING` is set to `false`?

Maybe that's the problem - please post all configured feature flags (`data/config.php`).

**Comment by dibyadip-das** [comment] 2020-06-02 14:48
inside config.php I could see these 2 lines.
```
<?php
# Yeah it is an empty file ;)
```
Anywhere else you want me to look into?

**Comment by berrnd** [comment] 2020-06-02 19:33
Cannot be the case, at least store tracking is disabled as the field is missing on the purchase page in your screenvideo, or this is an old version (?), or do you use any integrated setup (like a Docker image or the Home Assistant integration) where settings may get set in a different way?

**Comment by dibyadip-das** [comment] 2020-06-03 05:43
Yes, I am using Home Assistant integration.

**Comment by berrnd** [comment] 2020-06-03 06:59
Ok, so it would still be interesting how the feature flag settings are set (don't know where this is done there) and which version you are using - because we already had this before v2.7.0 in #685.

**Comment by SamKr** [comment] 2020-06-03 13:14
I'm having the same issue with my Home Assistant Grocy integration. Used to be working, now I get a freeze when purchasing items, with the same error as reported by @dibyadip-das.

I didn't have FEATURE_FLAG_STOCK_LOCATION_TRACKING enabled, but after enabling it, the problem remains.

This is my current configuration:

![grocy](https://user-images.githubusercontent.com/1439763/83640797-edc09280-a5ac-11ea-87e5-4b40dd097450.png)

**Comment by SamKr** [comment] 2020-06-03 13:21
> I'm having the same issue with my Home Assistant Grocy integration. Used to be working, now I get a freeze when purchasing items, with the same error as reported by @dibyadip-das.
> 
> I didn't have FEATURE_FLAG_STOCK_LOCATION_TRACKING enabled, but after enabling it, the problem remains.
> 
> This is my current configuration:
> 
> ![grocy](https://user-images.githubusercontent.com/1439763/83640797-edc09280-a5ac-11ea-87e5-4b40dd097450.png)

Update: I set all 'stock_*' config options to 'true', and the others as follows:

![grocy](https://user-images.githubusercontent.com/1439763/83641372-bd2d2880-a5ad-11ea-8c8e-792bd671f8df.png)

This caused the addon to start working again, as in I can purchase items. 

Would be nice if this could get fixed, because it adds clutter to the screen that I don't use. But I'm happy I can use your tool again :) Thanks for the hard work!

**Comment by dibyadip-das** [comment] 2020-06-03 15:15
Thanks @SamKr I did the same but still, I am getting the same error. Any thoughts on this @berrnd

**Comment by berrnd** [comment] 2020-06-03 16:44
Which grocy version uses the Home Assistant Add-on (see the right upper edge settings menu/about)?

**Comment by dibyadip-das** [comment] 2020-06-03 16:56
My Addon is up to date. No updates as of now in Supervisor of HomeAssistant
![image](https://user-images.githubusercontent.com/47345141/83665513-28e0b700-a5e9-11ea-8774-d879e5c7f0b6.png)

**Comment by dibyadip-das** [comment] 2020-06-03 20:30
Also as a side effect, I guess none of my recipes are able to calculate cost 😔 Let me know if my guess is correct? Also, I would be relieved if there is a workaround for this.

**Comment by sinclairpaul** [comment] 2020-06-03 21:26
I just want to add here that the settings in the Home Assistant Addon are configured by environment  variables
.
Possibly more importantly they aren't set if not configured.  Although personally I can't duplicate the issue, I'm wondering if it is upgrade related without the settings configured?

**Comment by dibyadip-das** [comment] 2020-06-04 06:29
Hi @sinclairpaul,
Below is the configuration that I have set for my HA Groccy Addon:

![image](https://user-images.githubusercontent.com/47345141/83722521-bf998c00-a65a-11ea-8cd8-0c3d4dc461de.png)


As per the code shared by you **FEATURE_FLAG_STOCK_LOCATION_TRACKING** maps to **stock_location_tracking** which I have set to true as seen in the config above.

Still facing the same issue. Thank you all for your support!

**Comment by berrnd** [comment] 2020-06-04 06:59
I will try to reproduce this by the shared settings, thanks.

But strange is that in the shared screenvideo above on the purchase page the "Store" field is missing (see [the demo](https://en.demo.grocy.info/purchase) as a reference, all feature flags have the defaults set there).

Here are the default settings configured which are also used for undefined (in `data/config.php or not set via env vars) settings:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/config-dist.php#L133-L161

The Store field on the purchase page is part of `FEATURE_FLAG_STOCK_PRICE_TRACKING`...

**Comment by berrnd** [comment] 2020-06-04 07:01
> But strange is that in the shared screenvideo above on the purchase page the "Store" field is missing 

And that's also the error message, as it's about to set that field there:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/public/viewjs/purchase.js#L155

**Comment by dibyadip-das** [comment] 2020-06-04 07:11
I was wondering if the problem will get resolved on re-installing the addon. But I don't want to lose the data. It took me a lot of time to do the stock entries.

**Comment by Anwen747** [comment] 2020-06-05 22:24
I had problems after updating the Home Assistant Grocy addon recently, including Purchasing not working and not seeing the store field under Purchase.  I also couldn't edit Stock Entries.  The thing that fixed it for me was to set all the add-on configuration options to default and restarting the add-on.  After that it works properly, and I was able to put my configuration options back the way I had them before and keep functionality.

**Comment by dibyadip-das** [comment] 2020-06-06 20:32
@Anwen747 It didn't solve for me 👎 

![image](https://user-images.githubusercontent.com/47345141/83954006-e7f3d700-a862-11ea-9b36-7c22e178b264.png)

Still stuck at the same issue

**Comment by dibyadip-das** [comment] 2020-06-06 22:52
I now did a fresh installation to resolve the error and backuped my all data using rest api.

Although I can now get calls on my groccy server but POST seems to be not working:
![image](https://user-images.githubusercontent.com/47345141/83955983-660da900-a876-11ea-9270-503669a55561.png)

**Comment by Anwen747** [comment] 2020-06-07 01:59
I am sorry it is still not working for you.  There is definitely something wrong if you are seeing the wrong version of the UI (without the Store field in Purchase).  I don't know why setting the addon config back to default fixed it for me, or why it doesn't work for you ☹️

**Comment by fusion44** [comment] 2020-06-11 19:45
I'm having the exact same problem, but I'm not using the HomeAssistant addon. I'm using stock docker version.

**Comment by dibyadip-das** [comment] 2020-06-12 18:52
@fusion44 I resolved it by reinstalling the newer version of groccy but at the cost of losing all my stock data. At least I managed to take a backup of my products and categories using the rest API and scripts written Python. I guess this is mostly an upgrade issue.

**Comment by SamKr** [comment] 2020-06-15 08:00
If there isn't an official way to backup the data, I'd be very interested in those scripts @dibyadip-das if you'd be willing to share them?

**Comment by dibyadip-das** [comment] 2020-06-15 09:20
> If there isn't an official way to backup the data, I'd be very interested in those scripts @dibyadip-das if you'd be willing to share them?

Sure, I will try to upload the scripts to github and share the link here.

**Comment by SamKr** [comment] 2020-06-22 12:10
Thanks @dibyadip-das  :) Also opened a [feature request](https://github.com/grocy/grocy/issues/895) for a potential official implementation.

**Comment by berrnd** [comment] 2020-08-18 15:44
Closing this for now, if this is somehow reproducible (outside the HA integration), feel free to reopen it.

Still not reproducible for me here...

**Closed by berrnd** 2020-08-18 15:44 UTC
Labels: question

**Comment by fusion44** [comment] 2020-09-05 10:52
Deleting all the `.php` files in the `path_to_grocy_config/viewcache` folder fixes this.

**Comment by ami232** [comment] 2021-01-01 17:59
I am experiencing the same issue on a fresh grocy 3.0.0 installation. 
When I click OK to add a new purchase, the UI freezes and a similar JS error occurs
![image](https://user-images.githubusercontent.com/16015401/103443827-025c2a80-4c63-11eb-930f-9a324733fde0.png)

I have tried all the solutions proposed above, but they don't fix the issue.
Any thoughts?

**Comment by berrnd** [comment] 2021-01-01 19:02
@ami232 please open new issues for new problems, this is maybe about the same end result, but totally unrelated to what's mentioned above.

And no, I cannot reproduce this (please also always try the demo instances first to ensure that's nothing about a configuration problem on your side) but optimized the if statement in https://github.com/grocy/grocy/commit/fe665ac7668906de943d7b2ef4a342e46b40bfcd.

**Comment by Alvarito2201** [comment] 2024-02-14 08:40
> > I'm having the same issue with my Home Assistant Grocy integration. Used to be working, now I get a freeze when purchasing items, with the same error as reported by @dibyadip-das.
> > I didn't have FEATURE_FLAG_STOCK_LOCATION_TRACKING enabled, but after enabling it, the problem remains.
> 
> Update: I set all 'stock_*' config options to 'true', and the others as follows:
> 
> ![grocy](https://user-images.githubusercontent.com/1439763/83641372-bd2d2880-a5ad-11ea-8c8e-792bd671f8df.png)
> 
> This caused the addon to start working again, as in I can purchase items.
> 
> Would be nice if this could get fixed, because it adds clutter to the screen that I don't use. But I'm happy I can use your tool again :) Thanks for the hard work!


> > I'm having the same issue with my Home Assistant Grocy integration. Used to be working, now I get a freeze when purchasing items, with the same error as reported by @dibyadip-das.
> > I didn't have FEATURE_FLAG_STOCK_LOCATION_TRACKING enabled, but after enabling it, the problem remains.
> 
> Update: I set all 'stock_*' config options to 'true', and the others as follows:
> 
> ![grocy](https://user-images.githubusercontent.com/1439763/83641372-bd2d2880-a5ad-11ea-8c8e-792bd671f8df.png)
> 
> This caused the addon to start working again, as in I can purchase items.
> 
> Would be nice if this could get fixed, because it adds clutter to the screen that I don't use. But I'm happy I can use your tool again :) Thanks for the hard work!



this solved for me
