### ISSUE TITLE
Feature Request: use partnums.com for new products

### ISSUE THREAD

**Issue by sund** [grocy/grocy#1318] opened 2021-02-12 19:28 UTC
Use https://partnums.com/ for populating new products.

**Comment by berrnd** [comment] 2021-02-12 19:46
More or less a duplicate of #158.

It's already possible to implement that yourself using a [BarcodeLookupPlugin](https://github.com/grocy/grocy#barcode-lookup-via-external-services).

Maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

**Closed by berrnd** 2021-02-12 19:46 UTC
Labels: duplicate

**Comment by sund** [comment] 2021-02-12 19:51
My search didn't show this as an existing request.
