### ISSUE TITLE
Bug: Products on stockentries page stay hidden when custom field is present

### ISSUE THREAD

**Issue by keriati** [grocy/grocy#706] opened 2020-04-07 18:54 UTC
When accessing the stockentries page and a custom field is added to the products, we get an error from dataTables and the products stay hidden.

**Cause**
The custom field for the product is added in the thead as <th>, however in the tbody the matching <tr> fields are missing.

**Error message in console**

        Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined

        Ja | @ | jquery.dataTables.min.js?v=2.6.2:24
        | O | @ | jquery.dataTables.min.js?v=2.6.2:16
        | (anonymous) | @ | jquery.dataTables.min.js?v=2.6.2:17
        | (anonymous) | @ | jquery.min.js?v=2.6.2:2
        | map | @ | jquery.min.js?v=2.6.2:2
        | map | @ | jquery.min.js?v=2.6.2:2
        | oa | @ | jquery.dataTables.min.js?v=2.6.2:17
        | e | @ | jquery.dataTables.min.js?v=2.6.2:93
        | b | @ | jquery.dataTables.min.js?v=2.6.2:74
        | Lb | @ | jquery.dataTables.min.js?v=2.6.2:74
        | (anonymous) | @ | jquery.dataTables.min.js?v=2.6.2:93
        | each | @ | jquery.min.js?v=2.6.2:2
        | each | @ | jquery.min.js?v=2.6.2:2
        | n | @ | jquery.dataTables.min.js?v=2.6.2:83
        | h.fn.DataTable | @ | jquery.dataTables.min.js?v=2.6.2:166
        | (anonymous) | @ | stockentries.js?v=2.6.2:1

**Reproduce**
Access the stockentries page

**Version**
grocy 2.6.2
php 7.3

**Comment by berrnd** [comment] 2020-04-07 19:00
Duplicate of #677.

**Closed by berrnd** 2020-04-07 19:00 UTC
Labels: duplicate
