### ISSUE TITLE
Feature request: Build conversion tables into the app 

### ISSUE THREAD

**Issue by ITguy3118** [grocy/grocy#1611] opened 2021-09-11 18:54 UTC
![09-11-2021 -  13_47_53 - Recipes _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/132958310-ead11f00-6ed8-4b93-886d-3defbcfed12b.png)
Considering that groceries is this apps primary function I am surprised that conversion tables are not implemented into this. Seems like this should be a priority item and upon setup, ask the user to select either US units of measurement or imperial. 
I get the above result when entering in 1/2 or .5 cups of milk. This should either round to .5 or change to 1/2, not .5 with 4 additional decimal points. In this case it's pretty easy to dicern that the app means .5 cups, but there are other cases where this is not so strait forward. and makes it difficult for an end user to read while cooking. Haveing the calories rounded would be nice also, but not so imperative as cooking measurements.  Please fix this defect.

**Comment by berrnd** [comment] 2021-09-11 19:20
About fraction support:
Duplicate of #389.

If that all sounds "pretty easy" for you, feel free to implement #389.

About built-in unit conversions:
Duplicate of #451 (and #870).

At the end, those conversions are personal (and locale and locality dependent) preference, I personally setup them years ago and (very very) rarely touched them after that. Don't get me wrong, but I think if that's too much to do for you, grocy isn't what you need, since it's all about data tracking/maintenance. 5 (or 15) minutes one-time for unit conversions setup is definitely the smallest part of all (source: >4 years experience of real world daily grocy usage). If I wouldn't have fun with all that, I really wouldn't use (or even build) such things...

Someone also shared their conversions in an importable way not long ago on the subreddit: https://www.reddit.com/r/grocy/comments/m06nzd

_If you can search a little bit for existing requests before, would be [still](https://github.com/grocy/grocy/issues/1603) a super great thing..._

**Closed by berrnd** 2021-09-11 19:20 UTC
Labels: duplicate
