### ISSUE TITLE
Bug: Filter by location in stock overview displays total amount, not location total

### ISSUE THREAD

**Issue by ami232** [grocy/grocy#1259] opened 2021-01-05 21:20 UTC
I have cans of coke in the fridge and in a separate cupboard location. I usually buy more than I can fit in the fridge, so I usually have 3 or so in the fridge and the rest go in the cupboard until the ones in the fridge are consumed.

When I filter by the fridge location in the stock overview, the Amount column shows all the cans in stock, not the number of cans in the fridge, which I would expect to see. The same applies for the opened amount next to the total.

**Comment by berrnd** [comment] 2021-01-05 21:35
Duplicate of #682.

This is not a bug, the stock overview page is supposed to show _one_ line per product (so the summarized amount per product, regardless of how much stock entries are behind).

The stock [/stockentries](https://demo.grocy.info/stockentries) page shows the "raw" stock entries.

**Closed by berrnd** 2021-01-05 21:35 UTC
Labels: duplicate

**Comment by ami232** [comment] 2021-01-06 18:11
I can see that the feature proposed in #682 can fix this, but I don't think it's a duplicate of this. 

The issue I'm describing here is that currently when filtering by location, the amount is not updated to show the amount of product in the location selected, which still is _one_ row per product. For me this is a bug because this behaviour is unexpected, as I would expect the filter to be applied before the aggregation, not after. I think most people that have filtered a table on a UI or used excel subtotals before would expect this behaviour too.

By the way, this issue also occurs when filtering by status, which won't be fixed by #682 as stated.

If there's not a quick fix for this (or still not a bug), I think it's worth making this behaviour explicit. A warning on filtering by location or status saying "Amount column displays total in stock, not filtered total" should be enough.

**Comment by berrnd** [comment] 2021-01-06 19:29
> By the way, this issue also occurs when filtering by status

It works the same for all tables with filters and aggregations.

> used excel subtotals before would expect this behaviour too

We don't have subtotal (rows), so this comparison hinks.

However, this behaves like that since ever, nobody complained before, for me personally it's fine how it is.
#682 will give you a better stock overview page by location.
The /stockentries page (which is also accessible from the "more menu" on the stock overview page) gives you that (in a slightly other view) already, the same goes for the /locationcontentsheet page.

You can also always customize it yourself, the API endpoint `/stock/products/{productId}/locations` gives you the amount per product and location.
