### ISSUE TITLE
Feature Request: Expected buying price

### ISSUE THREAD

**Issue by Makhuta** [grocy/grocy#2338] opened 2023-09-14 15:12 UTC
An optional field for expected product price which will be recommended later on as buying price if set, otherwise use last price as normal.
The expected product price will only be saved until item exist in shopping list (or used as buying price obviously) and not used in product average. If multiple prices are used and product was not selected via barcode (or does not have one saved) it will use the lower expected price.
If it would be possible to be expected price per shop like:
"Shop 1": "Price 1"
"Shop 2": "Price 2"
.
.
.
"Add expected price +"

Shops will be from "Shop list" and will be added with button "Add expected price" with price field next to them

**Comment by berrnd** [comment] 2023-09-14 15:46
You can add any field to any entity (= a product, a shopping list item, everything) you want by utilizing Userfields.

Beside that, the product's last price is already available as a column on the shopping list - there can be no other/better magically calculated "expected price"...

Generally a duplicate of #1653.

**Closed by berrnd** 2023-09-14 15:46 UTC
Labels: duplicate
