### ISSUE TITLE
Feature Request: Make recipes taggable

### ISSUE THREAD

**Issue by 26thmeusoc** [grocy/grocy#1126] opened 2020-11-14 10:21 UTC
Currently, all recipes are shown and listed next to each other. As soon as there is a larger collection of recipes, it gets tough to select recipes of a given category (e.g. vegetarian dishes, cakes recipes, side dishs, spreads, etc.). It would be great, if recipes could get sorted by a category and/or (even better) filtered by their tags.
If tags could also get excluded, it would be easier to ignore recipes that need ingredients, which are only available at certain seasons.

A simple workaround is possible, by simply adding the tags in the recipe name, but an extra input field for tags and/or a categorization would be great.

**Comment by berrnd** [comment] 2020-11-14 10:41
Question-duplicate of #324, see https://github.com/grocy/grocy/issues/324#issuecomment-513479539 and have a look at Userfields.

For specific recipe categories (don't know if we need them as we have Userfields): Duplicate of #553, already started (but outdated) in #560.

**Closed by berrnd** 2020-11-14 10:41 UTC
Labels: duplicate, question
