### ISSUE TITLE
Feature Request: `store` and `price` fields for Shopping List entries

### ISSUE THREAD

**Issue by jhale1805** [grocy/grocy#1899] opened 2022-05-25 03:06 UTC
## Use Case
Each week, my wife and I go through the ads from the local grocery stores and compile a list of things we want to buy in a generic notetaking app. Our workflow looks like this.
1. Open a specific store's weekly ad
2. Make a section in our note app for the store
3. Add a bullet point for each item we want to buy 
   - We list the item's `name`, `price`, and some other small notes.
4. Repeat for each store.
5. If any items are offered at multiple stores, we generally remove the more expensive duplicates; however, on occasion we keep a slightly more expensive version if it's at a more convenient store.

At the end, we have a per-store shopping list we can use to go from store to store and know that we are getting the best prices on everything.

## Current Limitations
Grocy already supports tracking individual items in a shopping list (called **products**), but does not have support for associating those shopping list entries with a specific store(s) or price(s) unless one creates custom **userfields**.

## Proposed Implementation: Add `store` and `price` fields to the `shopping_list` entity.
On the `shopping_list` entity add the following fields
- `store_id` : A link to one of the existing stores configured by the user (optional) (defaults to the "Default Store" on the related product)
- `price` : A monetary type field containing the price the user expects to pay for the item. (optional) (defaults to the last price the user paid for the product)

From there, the shopping list view could be updated to show these extra columns with the same sort/filter options as the other columns throughout the UI.

For bonus points, the store/price could be used to further auto-populate the stock entry created from marking a shopping list item as purchased.

### Benefits
- Fully covers the use case above and issue #1357
- Should be relatively simple to implement since it is a small, strictly additive change.

### Cons
- Doesn't allow for capturing prices at multiple stores for a specific product on a specific date without purchasing them all.

## Alternative Implementation: New Price History Table
Create a new `product_price_history` **entity** with the following fields:
- `product_id`: A link to a specific product (required)
- `store_id`: A link to a specific store (required)
- `unit_id`: The unit associated with the product (required)
- `price_per_unit`: The price of the product per unit (required)
   - Alternatively, you could store the `price` and `quantity` separately...
- `date`: The date on which the product had this specific price (required)
   - This can be optional on the API side and default to the current date.
- `shopping_list_id`: A link to a specific shopping list entry (optional)
- `stock_log_id`: A link to the stock entry created when the associated product is purchased (optional)
   - stock_log seemed like the most likely place for stock entries to be stored when I was glancing through the list of entities in the **Userfields** settings. If that is an incorrect assumption, then this field name should be renamed to reference the correct entity.

From there, when adding something to the shopping list there can be an option to add a `store`/`price` pair (this can default to a single entry of the product's default store and last purchase price for automated additions) which creates a related record on the new `product_price_history` table. One of these pairs (by default the cheapest) can be selected as the "chosen pair" to show on the shopping list.

Finally, the shopping list can be updated to show the sortable/groupable/filterable `store` column.

### Benefits:
- Fully covers the use case above and issues #1357 and #1653 
- Allows for more sophisticated price tracking over time per store, even if a purchase wasn't actually made.

### Cons:
- Lots of work. An entire new table to implement plus updates to many other tables, API endpoints, and UI Pages.
- Most users are probably fine with/expect a single store/price pair, so the option for multiple could be confusing.

## Closing Thoughts
I, like you, am a professional software engineer that enjoys coding in my limited free time. I hope that my taking the time to draft an implementation specification for this feature request makes it easier for this feature to become a reality.

I am willing to take a stab at implementing this myself, but, since I have zero experience with Blade and PHP, I would really appreciate it if you could review/critique this implementation proposal and/or point me to the right files where this feature would likely be implemented.

**Comment by berrnd** [comment] 2022-05-25 06:36
Thanks for your ideas. Closing this as a duplicate of the other requests you mentioned - this is not a new feature request, so nothing to track here.

How to do things technically is most of the time not rocket science and at the end kind of personal preference, which of the 100 possible ways to go. Beside that, it just takes time, that's why not so much is going on for grocy from my side all the time.

And sorry, I also don't have the time to explain in every little detail where and how to do what for this. When doing this, I can also just start right away implementing it myself, since it's the same amount of time needed at the end.

**Closed by berrnd** 2022-05-25 06:36 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2022-05-25 06:39
Just a technical note: There is entirely no need for a new "price history table" in any case. We already have the stock journal (table `stock_log`) which is essentially just that.

**Comment by zunami** [comment] 2023-08-03 10:24
i would also like to see this function for the shopping list.

1. field input **which store** - So you can filter the shopping list in which store you stand and buy.
2. field input with **the current prices** (from the advertising / action eg).

**Comment by berrnd** [comment] 2023-08-03 10:32
@zunami you can add any field you want to any entity (= a product, a chore, a shopping list item, everything) by utilizing Userfields.

Being able to reuse/reference existing objects (like Stores defined in master data) is tracked in #335. Having table filters for Userfields is tracked in #1850.
