### ISSUE TITLE
Feature Enhancement: Unit conversion propagation

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#774] opened 2020-04-20 12:25 UTC
**Introduction**

In general, when you define a unit conversion there is an inverse conversion that is also true.

**Example**

1 tbsp = 3 tsp
1 tsp = 1/3 tbsp

**Current functionality**

The unit conversion needs to be defined in both directions.

**Proposed functionality**

When adding a unit conversion, the proposed inverse conversion will be show, with a checkbox to create it.

If the box is checked, a unit conversion will be added to the second unit for the inverse calculation. This will save time and ensure accuracy.

**Comment by berrnd** [comment] 2020-04-20 16:04
Duplicate of #388.

**Closed by berrnd** 2020-04-20 16:04 UTC
