### ISSUE TITLE
Allow a single chore to be assigned to multiple users (independently)

### ISSUE THREAD

**Issue by slikrik98** [grocy/grocy#2375] opened 2023-11-10 13:56 UTC
Currently, when you assign a chore to multiple people, if any one of those assignees completes the chore, it's completed for _everyone_. Nearly all of the chores in my household need to be done, every day, by each child. Making their beds, cleaning their rooms, etc.

It's inconvenient to have to create separate and identical chores for each child so that they can be completed independently.

**Comment by berrnd** [comment] 2023-11-10 14:33
Duplicate of #1415 (even with the exact same example use case) - please be so kind and do a little search before opening new requests.

**Closed by berrnd** 2023-11-10 14:33 UTC
Labels: duplicate
