### ISSUE TITLE
Feature Request: Integration with Vorwerk Cookido

### ISSUE THREAD

**Issue by BassXT** [grocy/grocy#2562] opened 2024-08-08 09:54 UTC
I think it would be fantastic if we could transfer recipes from the Vorwerk Cookido app to Grocy via an interface. For example, the Bring! app already supports this functionality. It would be great if users could collect their favorite recipes in Grocy and also directly sync their shopping lists.

**Comment by berrnd** [comment] 2024-08-08 10:02
Please be so kind and do a little search beforehand - duplicate of #210 (and #2370, and #1909, and #1156, and #1798, and #1909, and #286) - maybe have a look at [recipe-buddy](https://github.com/georgegebbett/recipe-buddy).

**Closed by berrnd** 2024-08-08 10:02 UTC
Labels: duplicate
