### ISSUE TITLE
Feature Request: various small wishes with problems

### ISSUE THREAD

**Issue by zunami** [grocy/grocy#1751] opened 2022-01-16 16:23 UTC
hello!

i just got into grocy but i am already a fan.

### **Quantity units - Feature Request**
it takes the fun out of it when you have to enter standard units of measure. grams decagrams kilograms. milliliters liters ... these units should be 

![2022-01-16 16_49_48-Edit quantity unit _ grocy](https://user-images.githubusercontent.com/4697822/149667181-faeac6cd-4096-4e35-a483-16f675a041db.png)

### **Purchase - Feature Request**
i would like to see a "from purchase date". i only enter the purchases a few days later with the invoice.

### **Inventory - BUG**
inventory causes a price error when converting units. 
Example:
Article with a conversion unit grams to 300 grams tin can. i buy the article and enter eg 900 grams and go to total price input 5 euro. this works perfectly. but if you inventor the article now eg 3 tin cans then takes the is taken as conversion factor grams and this then causes an error. to see in the stock overview

### **inventory - BUG**
there is an error but i could not find out where it comes from. i enter an item with grams but with a strange message. but when i enter 750.0 now the error is gone. i don't know what affects the decimal place.

![2022-01-16 17_08_48-Inventory _ grocy](https://user-images.githubusercontent.com/4697822/149667990-2c724dc6-c64e-42d6-9f08-23d0ce07e47f.png)
### 
**Products - Feature Request**
at products enter a unit as basic price marking. so as to compare products.
you buy a product per gram packed in a tin can but you compare prices with a basic price such as kilogram.
Example
this tin costs for example 1,99 but and in the tin are 300 grams. so base price are kilograms that are then € 6,633 per kilo

### **Products**
in order to get products faster, a connection to e.g. https://fddb.info/ with an API would perhaps be possible
or
A separate grocy server where everyone can upload products with basic where others can use the data. each user enters the data himself.

**Comment by berrnd** [comment] 2022-01-16 16:59
**Please create one ticket per request/issue, multi-topic requests are untrackable.**

Please also search existing requests/issues first (also noted on the issue template) and the better place for general usage questions is the [subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

However, I'll try it:

&nbsp;
> #### Quantity units - Feature Request
> it takes the fun out of it when you have to enter standard units of measure. grams decagrams kilograms. milliliters liters ... these units should be

Duplicate of #912 and has also been discussed quite often. There is no standard. Localization, location, personal preference dependent. Do it once, done, forever - I don't get the problem.

&nbsp;
> #### Purchase - Feature Request
> i would like to see a "from purchase date". i only enter the purchases a few days later with the invoice.

Already possible, check the [stock setting `Show purchased date on purchase and inventory page`](https://demo.grocy.info/stocksettings#show_purchased_date_on_purchase).

&nbsp;
> #### Inventory - BUG
> inventory causes a price error when converting units.

Please provide the exact steps (unit conversions involved and all the rest, [persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are best for that as mentioned on the issue template) and note that unit conversion hirarchy is currently limited to 1 level (ref #1360).

&nbsp;
> #### inventory - BUG
> there is an error but i could not find out where it comes from. i enter an item with grams but with a strange message. but when i enter 750.0 now the error is gone. i don't know what affects the decimal place.

On /inventory the amount entered cannot be < 0 and match the current stock amount, that's what the error message says. The amount of decimal places can be configured by the [stock setting `Decimal places allowed for amounts`](https://demo.grocy.info/stocksettings#group-stock_decimal_places_amounts).

&nbsp;
> #### Products - Feature Request
> at products enter a unit as basic price marking. so as to compare products.

When I understand what you mean, a duplicate of #1743 and related to #1653 (your own request).

&nbsp;
> #### Products
> in order to get products faster, a connection to e.g. https://fddb.info/ with an API would perhaps be possible
> or
> A separate grocy server where everyone can upload products with basic where others can use the data. each user enters the data himself.

Duplicate of #158 and already possible by using [Barcode Buddy](https://github.com/Forceu/barcodebuddy).

**Closed by berrnd** 2022-01-16 16:59 UTC
Labels: question
