### ISSUE TITLE
Bug: 502 Bad Gateway after upgrade with Docker

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2299] opened 2023-08-07 20:45 UTC
My Grocy 3.3.2 run on a linux Docker container (image linuxserver/grocy).
Following "Install Guide":
- Empty the data/viewcache directory
- chmod +x update.sh (container terminal)
- run update.sh (it backups current grocy and download latest version. All fine)

When I try to access http://<grocy>, after seconds (migrating db?), I receiver error "502 Bad Gateway nginx"

Any idea?

**Comment by berrnd** [comment] 2023-08-07 20:58
> Any idea?

Yes, searching.

Duplicate of / related to:
- #2284
- #2281
- #2288
- #2296
- #2297
- https://www.reddit.com/r/grocy/comments/15jq2qx/comment/jv2kx7x/?context=3
- https://www.reddit.com/r/grocy/comments/15fknbl
- https://www.reddit.com/r/grocy/comments/15enu9o

&nbsp;
> 3.3.2 run on a linux Docker container (image linuxserver/grocy).

None of the community contributed apps/tools/integrations are maintained here.

**Closed by berrnd** 2023-08-07 20:58 UTC
Labels: duplicate
