### ISSUE TITLE
Feature Request: Mass Update of Product Attributes

### ISSUE THREAD

**Issue by schnillerman** [grocy/grocy#2071] opened 2022-12-20 11:50 UTC
Changing product attributes like units, product category etc. is very time consuming because the product needs to be opened and edited one by one.
A mass update feature (check products > select attribute > change) would be very helpful.

**Comment by berrnd** [comment] 2022-12-20 11:54
Duplicate of #1020 (and #1831, and #2049, and #2067) - please check existing requests before opening new ones.

**Closed by berrnd** 2022-12-20 11:54 UTC
Labels: duplicate
