### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by daffgn** [grocy/grocy#1849] opened 2022-04-09 13:50 UTC
Wonder is there is a way to add email / telegram notifications to some features
When a task / chore is due or for any other reason (product out of date,....)

Looking as well to an extension of the battery module to keep track of my electric bike battery charge
Date - Mileage - Battery % before charge - Charge Duration - Battery % after charge

Dafranlu

**Comment by berrnd** [comment] 2022-04-09 14:15
Would be super cool if you could use those super great search functions provided by GitHub and kind of every platform a little bit before, that's not only also mentioned on the feature request template, which you bypassed.

Duplicate of #156.

Someone build that: https://github.com/markusressel/grocy-telegram-bot

A lot others use Home Assistant for notification stuff: https://github.com/custom-components/grocy

Also related: https://www.reddit.com/r/grocy/comments/qfk65p/grocy_weeklydaily_alerts/

Also related: https://github.com/dgarcoe/grocy-telegram-bot

**Closed by berrnd** 2022-04-09 14:15 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2022-04-09 14:17
Also a way for notifications (already there since v2.0.0): #141
