### ISSUE TITLE
Bug: Duplicate QU conversion in parent product if conversion already specified in QU master data

### ISSUE THREAD

**Issue by InToSSH** [grocy/grocy#1307] opened 2021-02-09 11:29 UTC
Assuming we have two QU master data: Litre and Millilitre - which specify conversions on QU level 1L=1000ml (and inverse).

Demo instance: [https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/](https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/)

Products: [Kofola](https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/product/27), [Kofola 1.5L](https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/product/28)

Steps to reproduce:
1. Create parent product with unit Litres
2. Create child product with unit Bottles
3. Set product level QU conversion: 1 Bottle = 1.5L
4. Also set product level QU conversion: 1 Bottle = 1500ml
5. Purchase 3 bottles of child product.
6. Stock overview shows that we have **4 500 004,5 Litres in stock**.

Screenshots:
![2021-02-09_12-28-12](https://user-images.githubusercontent.com/6452373/107357415-4fd57e00-6ad2-11eb-946b-08a338a0f585.png)

![2021-02-09_12-27-22](https://user-images.githubusercontent.com/6452373/107357437-58c64f80-6ad2-11eb-8eaf-be69d489997e.png)

![2021-02-09_12-27-46](https://user-images.githubusercontent.com/6452373/107357442-59f77c80-6ad2-11eb-93d7-6dbe3278d053.png)

**Comment by berrnd** [comment] 2021-02-09 12:25
Duplicate of #1264.

**Closed by berrnd** 2021-02-09 12:25 UTC
Labels: duplicate
