### ISSUE TITLE
Feature Request: Allow Products to be added to mulitple Stores

### ISSUE THREAD

**Issue by tennr** [grocy/grocy#2441] opened 2024-01-14 02:01 UTC
Products can usually purchased at multiple Stores, and having a shopping list that filters based on the Store you are currently at would then present the list of items that could be shopped for there.  

I have added a user field (Stores) that allows for multiple selections for this to Products and Shopping Lists, but it does not work well for two reasons.  1. The field does not synchronize / populate the from Products into Shopping Lists.   2. There is no way to filter the view for a user field (Stores) and product group at the same time.

**Comment by berrnd** [comment] 2024-01-14 08:35
> 1. The field does not synchronize / populate the from Products into Shopping Lists. 

Well, product Userfields are shown on the shopping list, no need for "synchronizing", it just shows any product Userfield there too - so don't know what you mean with that.

I even created a demo for you to showcase that practically: https://test-5qf76jkjkwu648j2dhelc.demo-prerelease.grocy.info/shoppinglist

&nbsp;
> 2. There is no way to filter the view for a user field (Stores) and product group at the same time.

Already requested (generically for Userfields) in #1850, so closing this as a duplicate of that since when having that everything you want is possible.

&nbsp;
A separate shopping list per store, instead of searching/filtering, makes maybe even more sense and also that is already tracked in #1357.

**Closed by berrnd** 2024-01-14 08:35 UTC
Labels: duplicate
