### ISSUE TITLE
Bug: Something in a release after 3.0.0 still allowed #1542 (nested product) to happen.

### ISSUE THREAD

**Issue by VNRARA** [grocy/grocy#2401] opened 2023-12-11 00:47 UTC
Tried to migrate to v4 but got the:  "19 Unsupported product nesting level detected (currently only 1 level is supported)"
Found one record made with patzly/grocy-android (I don't use the frontend OR any other API tools to access the database). 

![image](https://github.com/grocy/grocy/assets/3942672/edff3eba-0fe3-48b1-8e55-d5f95ef4b7fa)

I checked my database with:

```
SELECT * FROM PRODUCTS WHERE id IN (
	SELECT
		p_child.id
	FROM products p_parent
	JOIN products p_child
		ON p_parent.parent_product_id = p_child.id
	WHERE p_parent.parent_product_id IS NOT NULL
	)
	AND parent_product_id IS NOT NULL;
```
The only stuff I've used to access the database is the patzly/grocy-android app so something in the API must still allow something unwanted to happen. 

![image](https://github.com/grocy/grocy/assets/3942672/624cc601-56a6-4185-999b-cc6d0afb9099)

**Comment by berrnd** [comment] 2023-12-11 07:39
Quoting myself from your other misused [thread](https://github.com/grocy/grocy/issues/1097#issuecomment-1849473214): 

_Since #1542 was resolved for [v3.1.1](https://grocy.info/changelog#v3.1.1), it's really not a surprise that this could have happened for any version before, including [v3.0.0](https://grocy.info/changelog#v3.0.0)._
 
_I doubt that this can happen any longer, since it's prevented on database level - otherwise provide a reproducible example and open another proper issue and it will be fixed, as always._

So just again in other words, since we all know reading is more than hard:
- No surprise that this could happen after v3.0.0, since it was only fixed for v3.1.1
- If it's still happening (I doubt it), provide a reproducible example and it will be fixed - I can't help without having something reproducible

**Closed by berrnd** 2023-12-11 07:39 UTC
Labels: invalid/unreproducible/missing-feedback
