### ISSUE TITLE
Feature Request: Better message when recipe cannot be consumed

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2399] opened 2023-12-09 17:06 UTC
Sometimes we are met with this message which tells something but not a lot. It would be nice if it also tells what ingredient is the issue and maybe what location.

![image](https://github.com/grocy/grocy/assets/7229627/107d2c1b-8e5c-4161-b117-e569e4cea747)

**Comment by berrnd** [comment] 2023-12-09 20:19
Recipe consumption shouldn't be possible when the stock isn't fulfilled - so provide a reproducible example on how to get that and it will be fixed, as always.

The API error message is originally generated by the endpoint [`/stock/products/{productId}/consume`](https://demo-prerelease.grocy.info/api#/Stock/post_stock_products__productId__consume) - no need for more clarification there, since the details in question are already known as part of the corresponding API request.

**Closed by berrnd** 2023-12-09 20:19 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by alkuzman** [comment] 2023-12-10 08:00
It clearly happens if in the preferred location, there is not enough in stock of some ingredient. I will make an example once I am on my pc, but I never meant it to be fixed (that is another issue). In case the product consumption more info would not hurt, in case of recipe it will help a lot.

**Comment by berrnd** [comment] 2023-12-10 08:41
> In case of product consumption, more info would not hurt. In case of recipe, it will help a lot.

Again: Recipe consumption shouldn't be possible when there is not enough in stock. That's the problem which can be fixed (once a reproducible example is provided), the API error message originates from a different area where more clarification is not required, as also already pointed out above.

**Comment by alkuzman** [comment] 2023-12-10 08:47
[demo](https://test-dp2utua7lu20nzrabtd3m.demo.grocy.info/recipes#) try consuming Chocolate sauce

**Comment by alkuzman** [comment] 2023-12-10 09:17
I understand that, but what you ignore is that I have no clue what the issue is, and I am going blind searching for issue in recipe that has over 20 ingredients and the issue can be anything with any of them. So, it will make the issue reporting process easier if the message was indeed present. I spent 1 hour without running a debugger and I am not able to find the issue. So I have to start the debugger. But not everyone can do that. That is my point.

Funny story: i was able to breafly reproduce the issue on a private demo, but then, after a while, the recipe started saying out of stock. I have no clue why, either. 

I understand your point, but better messaging even in unexpected places would allow people to spot the issue better, which in turn will lower your headaches with crappy feature and bug requests. Again, assuming that not everyone can run a debbuger on his database.

**Comment by berrnd** [comment] 2023-12-10 09:38
Step through all the invalid/duplicate reports here and notice that nothing will stop people from reporting bullshit, a big majority even doesn't read error messages popping up by any chance beforehand, more blindly copy/paste them, investing no single minute into helping finding the root cause - I then just put the exact same amount of effort into the corresponding response.

And also again, now the third time: Recipe consumption shouldn't be possible when there is not enough in stock. I doubt that adding a random info to a random error message will help on that at all, but if you think it will help, change [line 404 of `StockService.php`](https://github.com/grocy/grocy/blob/c9bc10820dddc6534d7a8d29c4f90a2eaef95f2b/services/StockService.php#L404-L404) to this (no specific location is used on recipe consumption, so the product is the only single more info maybe helpful):
```
throw new \Exception('Amount to be consumed cannot be > current stock amount (if supplied, at the desired location) Product: ' . $productDetails->product->name);
```

&nbsp;
> Obviously, anyone would give up and just throw a crappy issue your way.

To be super honest: If this happens for 0.1% percent of all Grocy users sometimes and nobody want to properly reproduce that, I (and obviously everybody else then too) don't care.
