### ISSUE TITLE
mysql-Database

### ISSUE THREAD

**Issue by amarradi** [grocy/grocy#2503] opened 2024-03-18 10:40 UTC
Hello everyone,

I would like to use grocy for my whole family.
So we as a family want to use it. My brother and family and my sister too? I have a web server and do not want to install the application 3 or more times. Since sqlite is not multiuser capable, here is the feature request to change the installation and the application to mysql, so that several different users and groups can be created.

**Comment by berrnd** [comment] 2024-03-18 10:53
Duplicate of #89 (and #2335) - please check existing requests before opening new ones.

&nbsp;
> sqlite is not multiuser capable

How do you came to that conclusion? Concurrent reads are technically possible, concurrent writes are lock-handled (practically we talk about milliseconds here). Unless you have a household with thousands of members concurrently and heavily hammering Grocy, using it is practically no issue - have you gave it a practical try before claiming all that? I guess it's just about the "SQLite is no real database"-fear some people (for whatever unintelligible reason) have - if that's the big breaking point for you, Grocy is not the software you want.

&nbsp;
> and do not want to install the application 3 or more times.

Not required, nowhere mentioned and of course this doesn't make any sense when using Grocy for one family. Separate instances are only needed / useful for separate households, means when you want to manage separate stock, chores and so on.

**Closed by berrnd** 2024-03-18 10:53 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2024-03-18 11:48
Still don't get how "multiple households in one database" is related to the DBMS used (that's about logic, not about limitations SQLite have and MySQL doesn't or the other way round) and it's then just another duplicate of #644.

&nbsp;
> that's a shame but not a bad thing

A real shame but practically not that much a problem, you just need to step out of your MySQL comfort zone and overcome the SQLite fear I guess. [I personally host about 1.6k (demo) instances](https://www.reddit.com/r/grocy/comments/15lm1he) without any issues, serving more than 2k daily page views generated by about 150 users - if your family across all the mentioned houseolds is just a little smaller than that it should pretty much fit.

**Comment by amarradi** [comment] 2024-03-18 12:32
What I mean is whether the application is client-capable. Then I can set it up once and each household can set up and manage its own grocy. Then it would also be cleanly separated. Perhaps that would also be a service that could be offered professionally. But that's another topic.

**Comment by berrnd** [comment] 2024-03-18 12:42
> Then I can set it up once and each household can set up and manage its own grocy.

Exactly what the mentioned duplicate #644 is about. The request was declined, so this is not going to happen here. Spinning up multiple instances is as easy as cooking multiple pots of rice instead of just a single one. You are of course free to implement that yourself if you think the easy way of running multiple instances is too easy.

&nbsp;
> Perhaps that would also be a service that could be offered professionally.

Also that is not going to happen here (remember that Grocy is just one of my hobbies). You can also do that yourself in unison to the license under which I've published Grocy, if you feel that's what the world needs (and if you're technically capable of that, based on all that here that doesn't really sound that that's the case to me).

&nbsp;
> Then it would also be cleanly separated

Nothing can be as clean as completely separated instances.

&nbsp;
Just a personal recommendation: Just try stuff before moaning around, it doesn't really sound you've done that already.

In any case, everything on- and off-topic has been said, so were done here.
