### ISSUE TITLE
Bug: Undo consumed products removes shop

### ISSUE THREAD

**Issue by Uatschitchun** [grocy/grocy#1433] opened 2021-03-30 17:43 UTC
Consuming 5 packs of cheese and undo results in loosing the shop
This is the journal:
https://test-hvbrcmwdi7lbovbx7zqu3a.demo-prerelease.grocy.info/stockjournal
And this is the stock entries page:
https://test-hvbrcmwdi7lbovbx7zqu3a.demo-prerelease.grocy.info/stockentries

As one can see, the shop is empty.

I would add #634 and #1343 to this, as they (afaics) all belong to the recently added "stock entries" page. Although #634 is closed, imho the "stock entries" page needs some more love...

**Comment by berrnd** [comment] 2021-03-30 17:51
Duplicate of #1408.

**Closed by berrnd** 2021-03-30 17:51 UTC
Labels: duplicate

**Comment by Uatschitchun** [comment] 2021-03-30 18:10
Oh my... searched and read the issues for 20 minutes prior to posting this... ;(
