### ISSUE TITLE
Bug: deleting parts of items for a meal from the shopping list disables button to readd ingredients

### ISSUE THREAD

**Issue by viktor-c** [grocy/grocy#2418] opened 2024-01-01 01:19 UTC
Start with the example from #2091 
Then imagine another user deletes Milk from the shopping list.
Now check the meal plan, but you cannot add the missing items.

Delete chocolate from the shopping list and you can add everything again.

It gets stranger, start over, delete milk from stock and add missing ingredients for the 21 servings. Now go to the shopping list, delete chocolate and go to the meal plan, this time you can add missing items, but milk gets added with 4,1958 Bottles.
So you have 1xchocolate and 2xMilk. [Current state on demo server](https://test-wczd5q1pjop04ss2st7se71.demo.grocy.info/shoppinglist).

Maybe check to see if items are already added?

And if you add chocolate sauce another time as a meal plan, on Wednesday for example for a dinner, you cannot click the button to add missing items and they don't get updated in the shopping list.

BR

**Comment by berrnd** [comment] 2024-01-01 08:55
Not a bug, but a feature request - a duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789, #1965, #2020, #2174 - please search existing requests first).

&nbsp;
Technical background why it is how it currently is, if you're interested:

https://github.com/grocy/grocy/issues/840#issuecomment-626286880:
> Currently the missing amount is only checked on per recipe level, so when 1 pack is already on the shopping list, that's already fulfilled for the second recipe...

https://github.com/grocy/grocy/issues/925#issuecomment-662279863:
> The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

**Closed by berrnd** 2024-01-01 08:55 UTC
Labels: duplicate

**Comment by viktor-c** [comment] 2024-01-01 09:42
> Not a bug, but a feature request - a duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789, #1965, #2020, #2174 - please search existing requests first).
> 
>   Technical background why it is how it currently is, if you're interested:
> 
> [#840 (comment)](https://github.com/grocy/grocy/issues/840#issuecomment-626286880):
> 
> > Currently the missing amount is only checked on per recipe level, so when 1 pack is already on the shopping list, that's already fulfilled for the second recipe...
> 
> [#925 (comment)](https://github.com/grocy/grocy/issues/925#issuecomment-662279863):
> 
> > The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

I read through the mentioned issues, you have been working for a long time on this project and probably you are the only one ever to understand every aspect of it. 
I still don't understand why deleting chocolate from the shopping list lets me add the needed ingredients  (and milk is added as 4,1598 instead of 4,2 bottles), but after deleting Milk you cannot click the button again? None of both small buttons work, this happens even if you have only one recipe added and the UI shows it has not enough stock for it.

**Comment by berrnd** [comment] 2024-01-01 10:01
Everything is already described more than detailed in all the above linked duplicate requests, but since reading is hard (haven't we talked about that just now related to READMEs?), I gladly explain it once again in the most simplest words I can find:

The "Put missing products on shopping list"-button is enabled when a recipe's need isn't fulfilled, means when not everything needed is in stock. If everything is in stock or not and also the related amounts already on the shopping list are only checked per recipe - means two recipes needing 2 eggs each doesn't mean 4 eggs in total are needed/considered - the first recipe doesn't know anything about the other one. And everything you see on the meal plan is internally handled by hidden recipes per day/week to let it do it's magic - so everything just said also applies there.

&nbsp;
> and milk is added as 4,1598 instead of 4,2 bottles

Rounding errors related to fractional amounts can always and naturally happen, would be the same cosmetic solution as when talk about showing everything related to QU purchase on the shopping list (also ref #389).

&nbsp;
> you have been working for a long time on this project and probably you are the only one ever to understand every aspect of it.

Most likely true, since I created Grocy - also just natural for any software on this planet that the one(s) initially creating it most likely have the best understanding of it. But everything I did is done publicly, so everyone can dive in, you most likely just need a lot of time for it - also just natural and believe it or not, I've invested multiple full-time months of my time into Grocy over the years (even if lately the vast majority of time goes into frustrating discussions about everything and the life).

**Comment by viktor-c** [comment] 2024-01-03 11:37
> The "Put missing products on shopping list"-button is enabled when a **recipe's need isn't fulfilled**, means when not everything needed is in stock.

I will post a short video to see what I mean.
After clicking on the "Put missing products on shopping list"-button, delete chocolate, you can click again on this button, as expected. 
However after deleting milk from the shopping list, you cannot click it anymore. The recipe shows (as expected) it has not enough stock.

https://github.com/grocy/grocy/assets/20207125/1805d1df-31b7-49db-8617-e39276634cba

Hope I didn't stress you too much on the first day of the year. My description was not clear enough in the first post.

**Comment by berrnd** [comment] 2024-01-03 12:09
Then simply reconsider why you've enabled this ingredient option for Milk, disable it and be surprised that stock fulfillment check handling then works like you obviously expect it:

![grafik](https://github.com/grocy/grocy/assets/2161815/15ec71bb-96bf-4f06-8fcb-0d2cdb4468ae)

Furthermore and since in your screenvideo a German/English mix is used, triple check that all components involved (PHP runtime, OS for SQLite and your Browser) uses the same timezone - that's required to make time related things (e.g. the header buttons on the meal plan to consume / put on the shopping list everything for one week) work (also ref #808 and #1708, #516 - also mind the all the official demo instances use the `Europe/Berlin` timezone server side).

**Comment by viktor-c** [comment] 2024-01-03 22:22
Now I understand the problem, thank you! This was and is also happening on the demo server as well. The recipe comes with this option enabled for milk.  :+1:

**Comment by berrnd** [comment] 2024-01-04 08:06
> This was and is also happening on the demo server as well. The recipe comes with this option enabled for milk.

It's just random demo data, nothing more or less and I still don't see anything that doesn't work as defined.
