### ISSUE TITLE
Feature Request: Shopping list - save & next button

### ISSUE THREAD

**Issue by hermann-san** [grocy/grocy#2031] opened 2022-10-31 14:41 UTC
Hi,
when I put together my shopping list, I do open the shopping list.
Then click "add item" , a pop-up window opens, I enter the product and click save. The pop-up closes again.  Then I have to repeat this process for every item.
For me it would be more convenient (i.e. speed up populating the list) if there would be 2  buttons to save an entry. 
One with "save & next" and one with  "save & close"
Also it would be nice if it wouldn't be hidden, so that I have to scroll down to be able to click it.

### Save & Next  mock up

![grafik](https://user-images.githubusercontent.com/7679654/199034757-ed13c4a6-e6d9-4cbe-9dd8-3d6c707fdb88.png)

### Save button missing

![grafik](https://user-images.githubusercontent.com/7679654/199033910-41f81301-ddae-4540-b7b0-69ce368ed800.png)

**Comment by berrnd** [comment] 2022-10-31 14:46
Duplicate of #716.

>  Also it would be nice if it wouldn't be hidden, so that I have to scroll down to be able to click it.

Please keep it to one topic per request, but that's another duplicate of #1367 anyways.

**Closed by berrnd** 2022-10-31 14:46 UTC
Labels: duplicate
