### ISSUE TITLE
Feature Request: Display/switch QU conversions on recipe ingredients

### ISSUE THREAD

**Issue by RaitaroH** [grocy/grocy#1752] opened 2022-01-17 12:20 UTC
Have a product such as flour where you define the QU conversion between CUPS and GRAMS. Say `1 cup = 125 grams` thus `1 gram = 0.008 Cups`. 

Inside a recipe we reference Flour in cups. For instance `1 cup` for 4 servings.

This request is to be able to switch on the fly between cups and grams through the interface. Changing the servings amount will increase the amount in cups or grams. 
![image](https://user-images.githubusercontent.com/19552720/149763360-9495a12c-c22f-45eb-8b81-0ec5e36484be.png) ![image](https://user-images.githubusercontent.com/19552720/149763313-3526c542-d511-42c3-9ed6-61a1c63edb3a.png)

At the moment I use one unit (grams) and add a note to display the other unit for the standard servings size. Of course increasing the servings size will not update the comment. The other way would be to edit the recipe, then ingredient and change the unit.

**Comment by berrnd** [comment] 2022-01-17 12:48
Mostly a duplicate of #1132, merging this into #1132.

**Closed by berrnd** 2022-01-17 12:48 UTC
Labels: duplicate
