### ISSUE TITLE
Feature Request: Configure behavior of Chores overview track button

### ISSUE THREAD

**Issue by SirIndubitable** [grocy/grocy#2313] opened 2023-08-17 03:11 UTC
The green button on the chores overview page changed recently to a behavior I have never needed, and I almost always want to use the "Track chore execution now" behavior.  It's really awkward that the most accessible button is not useful to me.

It would be really nice to be able to configure if the green button tracks the chore now, or at the next estimated execution time.  And both options were in the drop down menu, so that either one is always accessible.

For an idea of my use case, all of my chores are set with a period of Days, so that if I do a chore either early or late, it is always scheduled the same time away.
Say I have a chore that is due on September 1st, with a period of 15 days, no matter when I do the chore, the green button will set the next due date to September 16th, not 15 days after the chore gets done.

**Comment by berrnd** [comment] 2023-08-17 06:04
Duplicate of #2311, please check existing requests before opening new ones.

See [here](https://github.com/grocy/grocy/issues/2311#issuecomment-1678780624) to get what you want right now by utilizing [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself).

**Closed by berrnd** 2023-08-17 06:04 UTC
Labels: duplicate

**Comment by SirIndubitable** [comment] 2023-08-17 14:40
@berrnd  This is not a duplicate of #2311 
The request was for a configuration option so users can choose their default, that request is just asking for it to be flipped for everyone.

Having to make custom JS is not a good solution, especially since the mobil apps follow the UX behavior of the web UI.

**Comment by berrnd** [comment] 2023-08-17 14:52
> Having to make custom JS is not a good solution

This solution works if you need/want it to behave like before and it's a 5 second copy & paste action. I don't see the problem.

&nbsp;
> especially since the mobil apps follow the UX behavior of the web UI

Nobody forces anyone to do that, especially when you think it's just crap how I do it.

&nbsp;
Whatever, I'm tired of discussing any little change endlessly, so I'm going to close this here. Staying with v3.3.2 or not using Grocy is always another option, if that's the biggest pain point of v4.0.0 for you and using custom JS (for whatever unintelligible reason) is not an option at the same time.

**Comment by berrnd** [comment] 2024-01-06 20:14
Follow-up: #2424 was created to track adding some configuration options to make possible what was mentioned here.

**Comment by berrnd** [comment] 2025-01-14 18:49
There is now this new settings (chores settings / top right corner settings menu) to swap the "Track next chore schedule" / "Track chore execution now" buttons/menu items on the chores overview page:

![grafik](https://github.com/user-attachments/assets/b8e2846d-c0f5-4f14-9bd1-d709014e8aec)
