### ISSUE TITLE
Feature Request: Import recipes from external service

### ISSUE THREAD

**Issue by TokinRing** [grocy/grocy#1798] opened 2022-02-24 03:30 UTC
Would it be possible to add an import function to the recipes area of Grocy? I would like to be able to pull ingredients and preparation from an externally provided recipe, in my case Mealie. 

My thought is to add an additional if/else to the recipesform blade file to accommodate an "import" mode that only requests a URL. A regex to swap the end user URL with the API URL will allow requesting recipe JSON data to import into a new Grocy recipe. 

I'm curious to know if this is a feasible feature to add.

**Comment by berrnd** [comment] 2022-02-24 07:26
Duplicate of #210 (and #286, and #445, and #1156, and #247 - would be cool if you check a little bit the existing requests before opening new ones).

**Closed by berrnd** 2022-02-24 07:26 UTC
Labels: duplicate
