### ISSUE TITLE
Feature Request: QR Codes and Product Page for individual items

### ISSUE THREAD

**Issue by b3nd1k** [grocy/grocy#2500] opened 2024-03-17 15:09 UTC
Hey,

The option Barcodes is great, but I would love to se an option where Grocy can automatically create a QR code for each product. The QR would contain a link to the item page for that product. Let's say I I have the QR code taped to the place in the fridge where I keep the milk, my cabinet where I keep my sugar oOr on a box that contains screws or bolts (See #2499). 

When I need to replenish the item, I scan the QR-code. That takes me to a product page for the item in Grocy where I can see the stock, quickly edit the stock and click a button to be taken to a website where I can buy the item I need to replenish. The should be able to be added during creation of the product.

**Comment by berrnd** [comment] 2024-03-17 15:22
> option where Grocy can automatically create a QR code for each product

Grocy does that, it's called a Grocycode and visible on various places, e.g. the product edit page ([demo example](https://demo-prerelease.grocy.info/product/12)):

![grafik](https://github.com/grocy/grocy/assets/2161815/39b4236f-7422-4b2b-9f68-7c003e394675)

This code can be used like any other product barcode.

&nbsp;
> The QR would contain a link to the item page for that product. Let's say I I have the QR code taped to the place in the fridge where I keep the milk

Don't get how an external link + a "location barcode" is related, but that's then a duplicate of #1872. Beside that, you can add any field you want to any entity you want (= products, chores, a shopping list item, everything) by utilizing Userfields. This includes of course pictures and barcodes are essentially pictures.

&nbsp;
Please check existing requests first before opening new ones and use the [r/grocy subreddit](https://www.reddit.com/r/grocy) for general usage questions as [mentioned in README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests).

**Closed by berrnd** 2024-03-17 15:22 UTC
Labels: duplicate, invalid/unreproducible/missing-feedback
