### ISSUE TITLE
Feature request: Possibility to move items/change date in mealplan

### ISSUE THREAD

**Issue by AllesMeins** [grocy/grocy#1163] opened 2020-12-07 19:57 UTC
It sometimes happens that I've to reorganize our mealplan for the week - usually if there are some left-overs we eat the next day, pushing the rest of our planned meals one day into the future. Currently this is quite cumbersome because there is no way to just change the date of an entry - instead I've to recreate every entry/note. It would be much easier if you could just click "edit" and change the date.

**Comment by berrnd** [comment] 2020-12-07 20:54
Duplicate of #775.

**Closed by berrnd** 2020-12-07 20:54 UTC
Labels: duplicate
