### ISSUE TITLE
Feature request: Have you seen Receipt Manager?

### ISSUE THREAD

**Issue by AjayShanker-geek** [grocy/grocy#1143] opened 2020-11-26 07:24 UTC
"A supermarket receipt parser written in Python using tesseract OCR" from their Github page. 
Project link: https://github.com/ReceiptManager/Parser 

They have create a flutter app which I find it convience to take snap of a receipt and get states on the purchases. Is possible to use their [python module](https://pypi.org/project/receipt-parser-core/#description)(receipt-parser-core 0.1.3)? It will be great idea to further improve grocy.

**Comment by berrnd** [comment] 2020-11-26 08:01
grocy is not a python application, for the rest: Duplicate of #404.

**Closed by berrnd** 2020-11-26 08:01 UTC
Labels: duplicate, question
