### ISSUE TITLE
Bug: Can't change items in stock

### ISSUE THREAD

**Issue by damiantje99** [grocy/grocy#1389] opened 2021-02-27 19:08 UTC
If I want to change a item in stock (through Stock Entries) it won't let me enter the OK button. At least, I can press it but nothing happens. I wan't to change the expire date to none and I've tried several other options to change in the stock entries but without success.

I'm not sure it this was already reported or maybe its a bug only occurring in my instance, but any help would be appreciated.

I'm running the latest stable Grocy version (3.0.1) and i'm running it as a docker in UnRaid.

**Comment by Anwen747** [comment] 2021-02-27 19:12
Apparently you and I were filing a bug report for the same issue at the same time!  See issue #1390.

**Comment by berrnd** [comment] 2021-02-27 19:23
Duplicate of #1268 (and #1284, and #1373), already fixed, not yet released - please check existing issues first before reporting and/or try to reproduce the problem first on the [pre-release demo](https://demo-prerelease.grocy.info/) (both is also mentioned on the issue template).

**Closed by berrnd** 2021-02-27 19:23 UTC
Labels: duplicate
