### ISSUE TITLE
Feature request: show userfield of stock_log in Purchase form or Edit stock entry form

### ISSUE THREAD

**Issue by Bonerserk** [grocy/grocy#1280] opened 2021-01-21 13:58 UTC
### Nice to have
I'd like to have a "production lot" field (the production code of the product) when I purchase a product, so in case of some problem with that product I'm able to know that code to comunicate with the producer.
### What I've done
I have created a userfield for the entity stock_log.
### What I'd expect
I'd expect to see my userfield in the Purchase form and/or in the Edit stock entry form
### What is appening
I can't see my userfield

### Grocy Info
Version 3.0.1
Released on 2021-01-05
PHP Version 7.3.26
SQLite Version 3.32.1
Docker version  linuxserver/docker-grocy on RPI 3B

**Comment by berrnd** [comment] 2021-01-21 15:28
Duplicate of #443.

The general approach of Userfields doesn't fit here, "purchase" is a transaction, not simply editing a (`stock`) object/row...

**Closed by berrnd** 2021-01-21 15:28 UTC
Labels: enhancement
