### ISSUE TITLE
Feature request: Optional and substitute ingredients in recipes

### ISSUE THREAD

**Issue by minecraft2048** [grocy/grocy#920] opened 2020-07-20 08:45 UTC
Take this recipe for example: https://www.youtube.com/watch?v=GcWYXQ5vILs

```
5 pounds of chicken legs and/or thighs (makes enough for dinner plus leftovers for tikka masala)
salt
2 tablespoons Kashmiri chili powder (or some combination of cayenne pepper [hot] and paprika [not hot], depending on how hot you want it)
Juice of 1 lemon
1/2 cup full-fat Greek yogurt
2-3 tablespoons ginger-garlic paste, prepackaged or freshly peeled and grated
red food coloring (optional)
```
I want to be able to tell grocy recipe that red food coloring is optional, and garlic and ginger can be substituted by ginger-garlic paste, or by ginger paste and garlic paste. I also want to describe that I can use either chicken legs or thighs or both, but I'm not sure how to implement that

**Comment by berrnd** [comment] 2020-07-20 09:00
Duplicate of #385 and/or #548.

There is currently the ingredient option `Disable stock fulfillment checking for this ingredient` to not check stock fulfillment - if you need that for optional ingredients.

**Closed by berrnd** 2020-07-20 09:00 UTC
Labels: duplicate
