### ISSUE TITLE
Bug: Chores due in the future that are "executed" today still show as due on their due date

### ISSUE THREAD

**Issue by smenzer** [grocy/grocy#2242] opened 2023-05-23 13:49 UTC
I have entered several recurring tasks (some weekly, some monthly) that I have set up. Often times, I will see the chore as upcoming and may take care of it before the due date. I "execute" the task and it shows "last tracked" as "today" and it shows up in the chore journal. However, the chore still stays in the list as "due" with the "next estimated tracking" as the original date.

Here are several examples...I've set weekly recurring tasks that are due on a given day of the week. On different days prior to the due date, I executed the task...but they still show as due. The only time it moves on to the next execution (a week later) is if I execute the task on the due date.

<img width="1129" alt="image" src="https://github.com/grocy/grocy/assets/624392/e1ce04ee-f0fd-4f58-8d58-7f6cf5cea66b">

I would expect that when I execute a task, then it would show the next due date as the next occurence. 

Is the current behavior expected? Am I doing something wrong? Or could this be improved by allowing you to execute and move on to the next due date?

**Comment by berrnd** [comment] 2023-05-23 14:28
Please always provide a reproducible example on a [persistent/private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) as mentioned on the issue template - I can't look behind screenshots and most of the there is more around than described.

So some guessing:
You've not used [/choretracking](https://demo-prerelease.grocy.info/choretracking) for tracking the execution, but the green button on [/choresoverview](https://demo-prerelease.grocy.info/choresoverview).

That green button uses _today_ as the tracked date in the current release v3.3.2 and the chore's _Next estimated tracking_-date in the next release - a duplicate of #2186.

Related [preview changelog](https://grocy.info/changelog#preview) excerpt:
- _Changed the handling of the tracking buttons on the chores overview page:_
  - _The green button now tracks an execution of the corresponding chore on the next scheduled time, rather than for now/today_
  - _New context-/more menu option "Track chore execution now" to track an execution for now/today (so the same what the green button did before)_
- _Removed the limitation on the chore tracking page that the tracked time couldn't be in the future_

Feel free to reopen this if my guess is wrong, but please then also provide a reproducible example and more details.

**Closed by berrnd** 2023-05-23 14:28 UTC
Labels: duplicate

**Comment by smenzer** [comment] 2023-05-23 15:03
@berrnd thanks for the information. i've been using the API and setting the execution date as "now" (whenever I make the call). it sounds like i need to set the execution date to when it is actually scheduled due instead, in which case i'll get the behavior i want. does that sound right?

(and next time i'll make sure to use the private demo instance...sorry!)
