### ISSUE TITLE
Bug: PHP Fatal error: Undefined constant "Grocy\\Controllers\\GROCY_USER_ID "

### ISSUE THREAD

**Issue by kaikli** [grocy/grocy#1398] opened 2021-03-06 16:20 UTC
I get the following PHP error by trying to access the web page with a new installation on version 3.0.1.

```
PHP Fatal error:  Uncaught Error: Undefined constant "Grocy\\Controllers\\GROCY_USER_ID" in /srv/http/grocy/controllers/BaseController.php:162
Stack trace:
#0 /srv/http/grocy/controllers/BaseController.php(196): Grocy\\Controllers\\BaseController->render()
#1 /srv/http/grocy/controllers/ExceptionController.php(77): Grocy\\Controllers\\BaseController->renderPage()
#2 /srv/http/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(127): Grocy\\Controllers\\ExceptionController->__invoke()
#3 /srv/http/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(109): Slim\\Middleware\\ErrorMiddleware->handleException()
#4 /srv/http/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()
#5 /srv/http/grocy/middleware/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#6 /srv/http/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()
#7 /srv/http/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\\Http\\Serve\\RequestHandlerInterface@anonymous->handle()
#8 /srv/http/grocy/vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle()
#9 /srv/http/grocy/vendor/slim/slim/Slim/App.php(199): Slim\\App->handle()
#10 /srv/http/grocy/app.php(94): Slim\\App->run()
#11 /srv/http/grocy/public/index.php(45): require_once('...')
#12 {main}\n  thrown in /srv/http/grocy/controllers/BaseController.php on line 162
```

**Comment by berrnd** [comment] 2021-03-06 16:32
When this is an error, you most probably use PHP 8 - only PHP 7.4 is currently supported, [check the README](https://github.com/grocy/grocy#how-to-install).

Beside that, this is a duplicate of #1267, already fixed, not yet released - please check existing issues before reporting (that's also mentioned on the issue template).

**Closed by berrnd** 2021-03-06 16:32 UTC
Labels: bug, ui-bug

**Comment by beetle442002** [comment] 2021-05-20 00:33
In case anyone else runs into this I was having it show up on PHP 7.4 

"Warning: Use of undefined constant GROCY_USER_ID - assumed 'GROCY_USER_ID' (this will throw an Error in a future version of PHP) in /var/www/controllers/BaseController.php on line 162" 

it was just missing quotes but seems to be already fixed thank you @berrnd
