### ISSUE TITLE
Feature Request: Warn when part of recipe is in freezer

### ISSUE THREAD

**Issue by userbradley** [grocy/grocy#2021] opened 2022-10-10 19:13 UTC
It would be nice to have a warning on meals in the planner that an item is in the freezer, and when you click in, it highlights it as being in the freezer.

I've had a few times when an item is in stock, but in the freezer so needs to be defrosted

**Comment by berrnd** [comment] 2022-10-10 19:22
Duplicate of #371 - would still be cool if you can search existing requests first.

**Closed by berrnd** 2022-10-10 19:22 UTC
Labels: duplicate

**Comment by userbradley** [comment] 2022-10-11 08:22
@berrnd I did search but the title was not aptly named...

![image](https://user-images.githubusercontent.com/41597815/195037652-357d61ae-8e27-4348-b9d9-70e897ae0957.png)

Do you know when this feature will be worked on?
