### ISSUE TITLE
Feature Request: full inventory management system

### ISSUE THREAD

**Issue by alex01at** [grocy/grocy#2474] opened 2024-02-18 12:37 UTC
Hello

I hope my feature request isn't asked before. 
It would be "great" if I can manage different locations with different places like:
kitchen -> place 1, place 2, place 3 etc.
And, that's the point, I can generate a barcode for grocy and stick it on place.
So I scan code with grocy and see what is inside. 
Or other way, I search for something and grocy told me where can I find it. 
So feature request is:

**Add sub-children and generate barcode with inventory of sub-child.**

please :-)

**Comment by berrnd** [comment] 2024-02-18 12:43
> I hope my feature request isn't asked before.

Having hope is great, simply being so kind a doing at least a little search beforehand would be even greater: Duplicate of #481 and #1872.

**Closed by berrnd** 2024-02-18 12:43 UTC
Labels: duplicate
