### ISSUE TITLE
Feature Request: Display more Message accurate when Recipe fails to be consumed

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2310] opened 2023-08-15 10:16 UTC
If the recipe fails to be consumed the message is generic saying that some ingredient is missing. It would be nice if the message pointed to the ingredient(s) in question.
![image](https://github.com/grocy/grocy/assets/7229627/af1cd85e-3288-4645-9ba4-d71f626fe290)

Note: in this case, the Server Error was mapped incorrectly in the missing ingredient error.
API Response:
```
HTTP/1.1 500 Internal Server Error
Server: nginx/1.24.0
Date: Tue, 15 Aug 2023 07:12:53 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/8.1.22
```

**Comment by berrnd** [comment] 2023-08-15 10:33
Stock fulfillment is checked and displayed per ingredient, so normally pretty easy to determine which ones are missing: All those marked with "Not enough in stock".

Related to / a duplicate of #386 and #2078.

&nbsp;
> Note: in this case, the Server Error was mapped incorrectly in the missing ingredient error.

The missing ingredients are not returned by the API and in any case something like will never be handled by a `500` response - an internal server is always something unexpected. So I can only guess something else went wrong here (since currently also the "Consume this recipe"-button is disabled when not everything is in stock), a reproducible example would be needed to look into it, as always.

The API also returns the error message, stack trace and so on for any unhandled exception. It can be the case that the frontend displays (another; unrelated) generic error message when that happens, since it's just something unexpected.

**Comment by alkuzman** [comment] 2023-08-15 15:01
I guess you are right. The missing Ingredients are listed in the recipe. My only issue was with the message. Maybe I should have reported this issue as a bug e.g. 500 mapped into a misleading message.

I believe it is due to slow conversions, resulting in Timeout. The browser says nothing more. 

I want to check where the issue originates but I am not sure where to find detailed logs. The only think I can find in the container log is this:

```
[15-Aug-2023 14:52:42] WARNING: [pool www] child 494 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/services/DatabaseService.php on line 20"
```

**Comment by berrnd** [comment] 2023-08-15 15:31
> Maximum execution time of 30 seconds exceeded

There can never be anywhere a proper error message when the PHP process is simply killed. Increase the timeout to get more details, don't know why obviously so much people prefer such pretty tight values for max execution time, max post size, memory limit, and all the rest.

Quantity unit conversion resolving is also involved when displaying a recipe. So when displaying works properly, I doubt it's the known problem about QU resolving (and since v4.0.1 all that is also cached, so even less likely related to that problem).

**Closed** 2023-08-15 16:51 UTC
Labels: enhancement

**Comment by berrnd** [comment] 2023-08-15 16:56
> Maybe I should have reported this issue as a bug e.g. 500 mapped into a misleading message.

I fixed that "bug". So in case of killed PHP process due to timeout settings or in any other case the server just cannot respond with anything (and therefore there is no error information at all), the error message is now as detailed as it can be:

![grafik](https://github.com/grocy/grocy/assets/2161815/ed960986-0fc5-43bb-9921-090a3d6b4065)

![grafik](https://github.com/grocy/grocy/assets/2161815/dbae33bb-903e-491e-b7d2-4bb22df4097f)

Brings nothing (for this here so far), but "fixes" the very critical bug, so voila.
