### ISSUE TITLE
Feature Request: Integration to Open Prices (Open Food Facts)

### ISSUE THREAD

**Issue by duhow** [grocy/grocy#2407] opened 2023-12-20 13:59 UTC
Separated from #158 , there's this new service named **Open Prices** from **Open Food Facts** https://github.com/openfoodfacts/open-prices

Price can be retrieved by store (OpenStreetMaps location ID).

The feature request would be:
- Exporting price data from store to Open Prices
- Import / query price data available from products in Open Prices

```
https://prices.openfoodfacts.org/api/v1/prices?product_code=8422410818044
```

**Comment by berrnd** [comment] 2023-12-20 15:26
In general, a specific implementation for a specific external service will never ever be integrated into Grocy - if, then in a "plugin way" like we already have for barcode lookups ([README ref](https://github.com/grocy/grocy#barcode-lookup-via-external-services)).

Grocy's price history (and the average price and so on) is based on past purchase transactions you did. So what do you expect what should happen with such an imported price at all? Also always sounds easier than it will be practically, just think about unit conversions and everything related to that...

Definitely more something for an external tool, feel free to start building that - Grocy has [an API](https://demo-prerelease.grocy.info/api) most likely already capable of handling everything needed for this.

Also related to (partly a duplicate of, I guess): #1653 (and #2338, #2277, #2009, #1805).

**Closed by berrnd** 2023-12-20 15:26 UTC
Labels: wontfix/out-of-scope
