### ISSUE TITLE
Bug: Product editing form quantity units

### ISSUE THREAD

**Issue by JRingelstein** [grocy/grocy#2523] opened 2024-04-16 09:40 UTC
Grocy Version 4.2.0

I used the[ iOS-App for Grocy](https://github.com/supergeorg/Grocy-SwiftUI) to create a new product. Required fields seem to not be enforced there.

I then tried to edit the newly created product in the standard browser environment. But a few of the required dropdowns were empty.

![Bildschirmfoto 2024-04-16 um 11 25 21](https://github.com/grocy/grocy/assets/10738364/dccba026-a2b6-4a7d-ac09-746e4084a325)
![Bildschirmfoto 2024-04-16 um 11 25 14](https://github.com/grocy/grocy/assets/10738364/0da7d28f-8617-412f-99e6-3db8add705a9)

I think this goes back to how `referencedQuantityunits` is handled in `/controllers/StockController.php` line 196.
I don't understand php, but it looks to me like the list of `quantity_units` expects to have a value. 
In the line above for `quantityunitsStock` there is a `OR NOT EXISTS` which seems to solve the problem, as that dropdown has all the values.

**Comment by berrnd** [comment] 2024-04-16 09:58
> I used the[ iOS-App for Grocy](https://github.com/supergeorg/Grocy-SwiftUI) to create a new product.

None of the community contributed apps/tools/integrations are maintained here.

&nbsp;
> Required fields seem to not be enforced there.

That's the problem, not entirely new and pretty much a duplicate of #2063 - please check existing requests before opening new ones.

&nbsp;
Still nothing to fix here - if you use the API don't input bullshit and everything will work.

**Closed by berrnd** 2024-04-16 09:58 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by JRingelstein** [comment] 2024-04-16 10:40
Okay, thank you. 
I seem to have used the wrong keywords to search.
