### ISSUE TITLE
Feature Request: Date format

### ISSUE THREAD

**Issue by xels1969** [grocy/grocy#2226] opened 2023-05-15 13:35 UTC
Possibility to set the used date format for the region.
So that it is possible to enter the date as "dd.mm.yyy" for european regions (in my case, Austria)

**Comment by berrnd** [comment] 2023-05-15 13:39
Duplicate of #1348 (and #2220) - please check existing requests before opening new ones.

**Closed by berrnd** 2023-05-15 13:39 UTC
Labels: duplicate
