### ISSUE TITLE
Bug: "n products are overdue"-status header on /stockoverview also includes stock entries due today or tomorrow

### ISSUE THREAD

**Issue by Janovlk** [grocy/grocy#2341] opened 2023-09-15 13:36 UTC
Hello,

the grey "# products are overdue" header now behaves differently than before. Seemingly it counts expired products (which is logical) plus products due today (in example from the demo version I added the product Milk which is due today) plus a products which are due in a day. Now there is a discrepancy in color coding of products. This new algorithm is misleading me. I can imagine it can be beneficiary for some users if it would be optional.

PP

![Grocy due dates](https://github.com/grocy/grocy/assets/140972046/09e30af8-faa4-4110-8fbd-0e0cd8cba331)

**Comment by berrnd** [comment] 2023-09-15 13:42
Please create a [private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) if you want to provide a reproducible example, the public instances are used by hundreds of people daily and get therefore also reseted multiple times a day - it's impossible to share scenarios there persistently.

**Comment by berrnd** [comment] 2023-09-15 13:49
> now behaves differently than before

Would be cool if you could specify what "before" refers to exactly.

&nbsp;
> the grey "# products are overdue" header now behaves differently than before. Seemingly it counts expired products (which is logical) plus products due today

Of course this makes no sense and any intended change is, as always, documented on [the changelog](https://grocy.info/changelog). Is reproducible, will be fixed for the next release.

**Comment by Janovlk** [comment] 2023-09-15 13:50
Hello,

okay, I created it in a Private Demo: https://test-42cvxut103tkp0ra9zwp9m.demo-prerelease.grocy.info/stockoverview
It behaves the same as well as my 4.0.3 production version on my server.

![image](https://github.com/grocy/grocy/assets/140972046/f08e6faa-f534-4e9f-a1cd-deb3321aca4a)

**Comment by berrnd** [comment] 2023-09-15 14:10
> In version 4.0.2 and lower it didn't behave like this

Can't be true. It's caused by using PHP 8.1 or 8.2, which is a requirement and only supported since Grocy v4.0.0 - means this problem first occurred in Grocy v4.0.0, not v4.0.2

**Comment by Janovlk** [comment] 2023-09-15 14:22
Today I switched from a server with v4.0.2 to a new one with v4.0.3, migrated database and config and when I reregistered the Android app to a new server (I changed a subdomain name) I immediately noticed change in "products are overdue" number.

**Comment by berrnd** [comment] 2023-09-15 14:40
Then you have simply not noticed it before. Recreate the same example on v4.0.2 and notice that the problem also already exists there. It's about how data types are handled when retrieving data from the database, which has changed since PHP 8.1. There was no change between v4.0.2 and v.4.0.2 in that area.

But whatever, let's simply fix this instead of getting lost in philosophizing where this was introduced exactly.

**Closed** 2023-09-15 15:24 UTC
Labels: bug
