### ISSUE TITLE
Bug: Problem on "Add to Shopping list", scanning a product Barcode

### ISSUE THREAD

**Issue by pedrommcouto** [grocy/grocy#2006] opened 2022-09-25 17:37 UTC
On scanning a barcode on " Create shopping list item"  Product field, I always get an "A product or a note is required" and "This product is not in stock", even after I add the product to barcode.
Checking on "productpickerblade.php", noticed that the "foreach" is never runned. Strangely, the same code works perfectly on "Purchase" and "Consume".
Any help?

**Comment by berrnd** [comment] 2022-09-25 17:47
Issue template excerpt:
_Please also try to reproduce the problem on the pre-release demo: => https://demo-prerelease.grocy.info_

[Pre-release changelog](https://grocy.info/changelog#preview) excerpt:
_Shopping list: Fixed that products could not be added to the shopping list via barcode scanning_

Conclusion:
Duplicate of #1940, already fixed, not yet released.

**Closed by berrnd** 2022-09-25 17:47 UTC
Labels: duplicate
