### ISSUE TITLE
Feature Request: Input Prices in Different Currencies, Display in a Fixed Base Currency

### ISSUE THREAD

**Issue by Tursu311** [grocy/grocy#2592] opened 2024-10-15 17:04 UTC
Hello, I am currently using Grocy while traveling in a van, and I often move between different countries. This means I regularly encounter different currencies when purchasing groceries. To streamline my workflow, I would like to request a feature that allows users to input prices in the local currency but have all values consistently displayed in a set base currency (in my case, euros).

**Suggested Workflow:**
- Allow users to input prices in a different currency (e.g., NOK, USD, etc.) at the time of purchase.
- To keep Grocy's current philosophy of simplicity, this feature would not involve automatic currency conversions.
- Instead, there could be an option in the settings to input a manual exchange rate for the current local currency to the base currency.
- When entering a new price, Grocy would use the user-provided exchange rate from the settings to convert the input currency to the base currency (e.g., EUR) automatically.
- All values would then continue to be displayed in the base currency, providing consistency across the application.

**Why This is Helpful:**
- This feature is especially useful for travelers who frequently change locations and deal with different currencies.
- It keeps the system simple, avoiding automatic exchange rate updates, while allowing users to manage their input in a more flexible way.
- It provides a straightforward method for handling varying currencies without needing to convert values manually each time.

Thank you for considering this request!

**Comment by berrnd** [comment] 2024-10-15 17:28
Duplicate of #1656, please be so kind and check existing requests before opening new ones.

&nbsp;
> This feature is especially useful for travelers who frequently change locations

Every project / tool / software needs a defined target use case and the one of Grocy is to help getting stuff done at home, not in your van - trying to be the tool for each and everything on this planets always ends in a mess (maybe try a SAP ERP product) and that's the simple reason to not add that.

**Closed by berrnd** 2024-10-15 17:28 UTC
Labels: duplicate

**Comment by Tursu311** [comment] 2024-10-15 19:16
Thank you for your quick response. I’ve read issue #1656 before posting, and understand the perspective presented there, which was a business case. However, I thought my case was within Grocy's scope since my van is, indeed, my home. It feels a bit dismissive to suggest otherwise. 

Seeing your message, I now acknowledge that Grocy is primarily designed for the very specific use case of a non-moving home, and I understand that.

Thanks!

**Comment by berrnd** [comment] 2024-10-15 19:28
> my van is, indeed, my home. It feels a bit dismissive to suggest otherwise.

Have I done that anywhere above? Come on. 🙄 What's generally meant with "at home" is everywhere on this planet crystal clear, regardless of your very personal life situation which is, don't get me wrong again, just irrelevant for any target use case decision of this hobby project.

&nbsp;
> Grocy is primarily designed for the very specific use case of a non-moving home

Just wow. I guess all those, most likely 99.x % or so, of humans on this planet living such a specific niche life should read that as a bit dismissive.
