### ISSUE TITLE
Bug: Incorrect ingredient quantity displayed in recipe

### ISSUE THREAD

**Issue by esclear** [grocy/grocy#2039] opened 2022-11-13 21:57 UTC
I configured a [demo instance](https://test-n4a1oa5u94vqeaehk7ot.demo-prerelease.grocy.info/) to highlight the issue.

I added [baking powder](https://test-n4a1oa5u94vqeaehk7ot.demo-prerelease.grocy.info/product/27) as a product, with a stock quantity unit of `pack`s and configured the following unit conversions:

![image](https://user-images.githubusercontent.com/7432848/201545937-79beed05-2a53-4a61-8773-05c9b316efa6.png)

In a [recipe](https://test-n4a1oa5u94vqeaehk7ot.demo-prerelease.grocy.info/recipe/7) I added two tea spoons of baking powder as ingredients.

![image](https://user-images.githubusercontent.com/7432848/201545991-20ca0812-1a04-4eac-aa8d-4fa57e9d7f55.png)

As you can see, the conversion is off, both in the blue text below the amount field, and in the ingredients table:
2 tea spoons = 2 * 4 g = 8 g, but not 8 packs nor 8 tea spoons.

I find this surprising, as grams are neither one of the units specified there nor the stock / purchase quantity unit.
Though there are some issues related to quantity conversions / recipes, I haven't found any that are open and/or seem to be related to this problem.

**Comment by berrnd** [comment] 2022-11-13 22:30
I don't find this surprising and it's not a bug, it's about #1360 - QU hierarchy is currently limited to one level.

Let's take your provided demo instance as the maybe 54th example about that here:

QU stock is always the base, so we need to go from _Pack_ to _Tea Spoon_ for that example:

Product stock QU _Pack_ **_Level 0_**
&nbsp;&nbsp;Product-QU conversion _Pack_ <-> _Gram_ **_Level 1_**
&nbsp;&nbsp;&nbsp;&nbsp;Product-QU conversion _Gram_ <-> _Tea Spoon_ **_Level 2  <-- Currently not supported_**

Create a direct conversion between _Pack_ and _Tea Spoon_ and everything will work.

&nbsp;
> Though there are some issues related to quantity conversions / recipes

Feel free to create a reproducible example for any issue and it will be fixed for the next release, at least this was the case for any reported problem in the last 5 years.

**Closed by berrnd** 2022-11-13 22:30 UTC
Labels: invalid

**Comment by esclear** [comment] 2022-11-13 22:52
> I don't find this surprising and it's not a bug, it's about #1360 - QU hierarchy is currently limited to one level.
> 
> Let's take your provided demo instance as the maybe 54th example about that here:
> 
> QU stock is always the base, so we need to go from _Pack_ to _Tea Spoon_ for that example:
> 
> Product stock QU _Pack_ **_Level 0_**   Product-QU conversion _Pack_ <-> _Gram_ **_Level 1_**     Product-QU conversion _Gram_ <-> _Tea Spoon_ **_Level 2 <-- Currently not supported_**
> 
> Create a direct conversion between _Pack_ and _Tea Spoon_ and everything will work.

Thanks for the reference to #1360 and explanation of the underlying cause.

> 
> > Though there are some issues related to quantity conversions / recipes
> 
> Feel free to create a reproducible example for any issue and it will be fixed for the next release, at least this was the case for any reported problem in the last 5 years.

I was referring to GitHub issues here. I am currently not aware of any problems with grocy itself.

**Comment by esclear** [comment] 2022-12-03 00:34
Hey @berrnd,

I had a look at [your comment](https://github.com/grocy/grocy/issues/1360#issuecomment-1263789676) in #1360 and started to implement this.
For now, I adjusted the `quantity_unit_conversions_resolved` view so that it also supports transitive conversions.
(It assumes that conversions are non-contradictory, but that coincides with your garbage in - garbage out policy.)

I haven't quite figured out the frontend part of it yet, as the user interface, e.g. in recipes, doesn't display correct conversions yet.

Would you be willing to help out with the frontend part?
If so, shall I open a WIP PR with the proposed database migration?

**Comment by berrnd** [comment] 2022-12-03 08:50
> If so, shall I open a WIP PR with the proposed database migration?

As mentioned in your referenced comment, everything is welcome - so feel free to do whatever you think is useful.

The frontend does essentially this `SELECT` on `quantity_unit_conversions_resolved` to get a conversion factor:
Example for [demo product "Cheese"](https://demo-prerelease.grocy.info/product/10) to get the conversion factor for its QU stock (Pack) from Slices:
```sql
SELECT factor
FROM quantity_unit_conversions_resolved
WHERE product_id = 10
	AND from_qu_id = 3 -- Pack
	AND to_qu_id = 12 -- Slice
LIMIT 1; -- View is already ordered by "source"
```

So the view would need to return a proper conversion "from any to any QU" of the corresponding product, when it's done like I proposed in #1360 and in that case I don't think any change for the frontend is needed at all at the end. Of course there are possible other approaches to solve this (like a function to do the "multi step resolving"), but currently the general decision is to do most of the logic directly in SQL, unless really not possible.

**Comment by Saturo78** [comment] 2022-12-18 20:15
> Create a direct conversion between _Pack_ and _Tea Spoon_ and everything will work.

I think this did not work proper when there a parent product is substituted by a child product.
I have created a demo:
https://test-k4fca4sqi68ad7ay5c8k4m.demo.grocy.info/

Have a look at the calories of the recipe "oil soup".
https://test-k4fca4sqi68ad7ay5c8k4m.demo.grocy.info/recipes?recipe=7

**Comment by esclear** [comment] 2022-12-18 20:20
Please note that while #2056 has been merged, it *has not been released yet*, as @berrnd also mentioned in https://github.com/grocy/grocy/issues/2066#issuecomment-1356391853.

Your demo is using the stable (i.e. released version) of grocy, where this is expected.
I'd suggest creating a demo instance with the *unstable* version of grocy for trying to recreate the problem.

(Also, it  issue to continue the discussion from #2066.)

**Comment by berrnd** [comment] 2022-12-18 20:29
@Saturo78

As already pointed out by @esclear, it would be really cool if you could please:
- Not spam unrelated threads
- Only report problems reproduced on the current development version (= the [pre-release demo](https://demo-prerelease.grocy.info), as also mentioned on the issue template - you've successfully ignored that 3 times in the last 24 hours)

Thanks.
