### ISSUE TITLE
Feature Request: Multiple attachments per equipment

### ISSUE THREAD

**Issue by iikkamerilainen** [grocy/grocy#2376] opened 2023-11-13 15:56 UTC
The Equipment list allows attaching a PDF instruction manual, and notes allow attaching images. Would it be possible to attach more PDFs, e.g. the equipment's receipt?

**Comment by berrnd** [comment] 2023-11-13 16:24
Duplicate of #441 (also references #978), possible since [v3.0.0](https://grocy.info/changelog#v3.0.0) (so since nearly 2 years) - please be so kind and do a little search beforehand.

[v3.0.0 changelog](https://grocy.info/changelog#v3.0.0) excerpt:
> - It's now possible to add multiple files (PDFs / manuals) to each equipment
>    - Define as many Userfields for the entity `equipment` and use the type `File`
>    - => Each of those File-Userfields will be shown as a separate tab on the equipment page

**Closed by berrnd** 2023-11-13 16:24 UTC
Labels: duplicate
