### ISSUE TITLE
Feature Request: Adding 'minimum purchase quantity' for a Product

### ISSUE THREAD

**Issue by SplinterHead** [grocy/grocy#2332] opened 2023-09-04 15:33 UTC
I'm quite new to Grocy, but I have looked through all the settings
When creating a Product, I would like the abilty to set the minimum purchase quantity for a product
Example: Bread is only available in a "Loaf" of 20 "slices", Eggs are only available in a "Box" of 6 or 12.

This information should then be used by the Meal Planner to add the Purchase Quantity to the Shopping List
Example from the [PreRelease Demo](https://demo-prerelease.grocy.info/):
1. Have 2 Eggs in stock
2. Add Pancakes to the Meal Plan (requires 4 Eggs)
3. Click "Add missing Items" from the Meal Planner
4. Shopping List says to get 2 Eggs, whereas it would be great to add 1 "Box" of Eggs to the shopping list

**Comment by berrnd** [comment] 2023-09-04 15:47
Duplicate of #1355 (and and #1615, and #1694, and #1980, and #2091) - please check existing requests before opening new ones.

&nbsp;
> Shopping List says to get 2 Eggs, whereas it would be great to add 1 "Box" of Eggs to the shopping list

Just my personal practical experience of using Grocy longer that it exists publicly:
It's not that hard to simply take whatever package your supermarket of choice has available when your Grocy shopping list says it needs 2 eggs, but they surprisingly only sell 10 egg packages once again. Grocy does the math (correctly), let's don't turn off our brain completely (for now, of course this can be changed as mentioned in referenced existing other feature request).

**Closed by berrnd** 2023-09-04 15:47 UTC
Labels: duplicate
