### ISSUE TITLE
When more than 500 recipes, the pages doesn't load anymore

### ISSUE THREAD

**Issue by donk7413** [grocy/grocy#1027] opened 2020-10-02 14:05 UTC
I have extract 10000+ recipes from the website marmiton.org (french).

From this list, I have extracted, sorted, distincted every ingredient of the site.

So i have a list of 1700+ ingredients, and i import it  in Grocy, it's run fine.

Now i make a little software who make API-formatted recipes json and post it.

Theses recipes are linked to a database product who exist and have some userfield too.

Example of json who work post to the api https://DNS/api/objects/recipes :  
`{
		
		"name": "Tarte brocolis camembert",
		"description": "<p>Precuire la pate feuilletee au four.</p><p>Cuire les bouquets de brocolis a la vapeur pendant 25 mn.</p><p>Melanger creme fraiche, oeufs, sel, poivre et muscade.</p><p>Disposer les bouquets de brocolis sur la pate, recouvrir de tranches de camembert et verser dessus la preparation.</p><p>Faites cuire 30 mn au four prechauffe a 200degC.</p>",
		"picture_file_name": "",
		"base_servings": "4",
		"desired_servings": "4",
		"not_check_shoppinglist": "0",
		"type": "normal",
		"product_id": "",
		
	}`

When i post a recipe objet to the grocy API, it's returning a createditem ID. ("id": "839",)
So I post userfields connected to this recipe

Example who work post to the api (PUT) https://DNS/api/userfields/recipes/839 :

`" {
			"budget": "bon marche",
			"commentNb": "61",
			"cooktime": "25 min",
			"difficulte": "tres facile",
			"note": "4.7",
			"preptime": "25 min",
			"totaltime": "40 min"
		}`

foreach ingredients of the recipe, i make a json and post it to https://DNS/api/objects/recipes_pos

When i post a recipe objet to the grocy API, it's returning a createditem ID. ("id": "1")

I post one userfield to this recipes_pos
{
  "grammage":"kg"
}

Everythong is ok, the server returning OK after every API CALL

Now this is my problem : 
When i try to call GET /api/objects/recipes_pos

I have now a error 500.

How i can get the log or go to the database to see if some data are corrupted or something else ?

because i can't know why i have this error. Too much data ? Too much link ?

**Comment by berrnd** [comment] 2020-10-02 14:59
> I have extract 10000+ recipes

We had that before.
Technically: Cool
Practically: Does this really make sense? I doubt it.

It's a known issue with big lists, as all pages are currently rendered server side, without paging or anything.
But in reality, I don't think it's a problem (beside the journal pages, which of course get longer and longer).

So most probably just a timeout and/or memory exception.
Check your webserver/PHP logs.

> How i can get the log or go to the database to see if some data are corrupted or something else ?
The database is a plain SQLite database stored in `data/grocy.db`.

Partly a duplicate of #695.

Paging/Filtering for (most) API routes is possible since #985 (not yet released).

**Closed by berrnd** 2020-10-02 14:59 UTC
Labels: question

**Comment by donk7413** [comment] 2020-10-02 15:09
> > I have extract 10000+ recipes
> 
> We had that before.
> Technically: Cool
> Practically: Does this really make sense? I doubt it.
> 
> It's a known issue with big lists, as all pages are currently rendered server side, without paging or anything.
> But in reality, I don't think it's a problem (beside the journal pages, which of course get longer and longer).
> 
> So most probably just a timeout and/or memory exception.
> Check your webserver/PHP logs.
> 
> > How i can get the log or go to the database to see if some data are corrupted or something else ?
> 
> The database is a plain SQLite database stored at `data/grocy.db`.
> 
> Partly a duplicate of #695.
> 
> Paging/Filtering for (most) API routes is possible since #985 (not yet released).

I use it because I connect it to my home automation system. In fact the goal is to have a virtual recipe book and when "I ask what can I cook" or "I want to cook xxx" it can answer me with suggestions.

And when I say "I cook xxx"
It's enumerate the steps of the recipe.
Actually it's work great with grocy on 20 recipes.
But since I import mass recipes, I run into 500 internal server for recipe and planning. When I ask the api, I can't get recipe_pos. Now I try to find if :
- data is corrupt and need to fixed it 
- the errors in log

**Comment by berrnd** [comment] 2020-10-02 15:22
The recipes page does stock fulfillment checking for each single ingredient, basically the same what the API endpoint `/recipes/{recipeId}/fulfillment` does. I can imagine that this takes long for a couple of thousand recipes...

grocy has no own log, but probably somethings lands in the default PHP logs, depending on how you have configured the log levels.

Execute `/recipes/{recipeId}/fulfillment` for single recipes to check if it works.

Let's continue general recipe page improvements in #695.
