### ISSUE TITLE
Bug: Automatic add to shopping list wrong unit

### ISSUE THREAD

**Issue by tieu1991** [grocy/grocy#1980] opened 2022-08-26 19:34 UTC
I use the automatic add to shopping list when stock is below minimum stock quantity. The problem is when that happen it add the minimum stock quantity to the shopping list instead of the default buy quantity. Here is an exemple of what happen.

Product : Eggs
Default purchase unit : pack
Default stock unit: piece
Factor purchase to stock : 12
Minimum stock unit : 4

When the number of eggs in the stock fall below 4, 4 eggs is added to the shopping list. I would expect 1 pack of eggs to be added to the shopping list. 

Grocy version 3.3.1

**Comment by berrnd** [comment] 2022-08-26 19:45
Not a bug.

Duplicate of #1355 (and #1615, and #1694, and #1837 - please check existing request before opening new ones).

**Closed by berrnd** 2022-08-26 19:45 UTC
Labels: duplicate
