### ISSUE TITLE
Feature Request: Make Standard unit  and unit conversions ubiquitous across the app

### ISSUE THREAD

**Issue by Dracozny** [grocy/grocy#2155] opened 2023-03-03 15:54 UTC
I guess you can argue this is a two for but it requires one to support the other.  Let me know if I should break it up though I think it makes more sense to keep them together. 
### Problem:
Adding standard units and their conversions on multiple items makes the app excessively time consuming especially for initial setup. 
### Proposed Solution
It would be best to make standard mass or volume conversions as well as their respective common used units prebuilt into the app so that if you select a mass unit for a product it will automatically provide the appropriate mass conversions for any other potential use. 

The QU Entry process currently on the platform is best used for non-standard conversions that would require knowledge of the product to determine. such as converting a volume to a mass. E.G. a cup of cereal equals 53g.

**Comment by berrnd** [comment] 2023-03-03 19:42
Duplicate of #912 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-03-03 19:42 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2023-03-03 19:44
And see also #1360, which is already done and will be part of the next release.

**Comment by Dracozny** [comment] 2023-03-04 16:57
Thank you very much for your efforts. 
FYI, I did search first but alas here we are. the fun of trying to match word choices.
