### ISSUE TITLE
Feature Request: Allow multiple amounts of products to be automatically added to the shopping list

### ISSUE THREAD

**Issue by troycarpenter** [grocy/grocy#2364] opened 2023-10-27 21:27 UTC
I would like to see a "default shopping list amount", defaulted to 1, which is used when an item is automatically added to the shopping list.

Example: I have 5 units of an item.  I set the minimum stock amount to 3.  When the stock amount drops below 3, I want to add 3 of the item to the list, not just one (because consuming one would leave two, but when I purchase, I want 5 total).

To make it more complicated, have there be a "purchase up-to" amount.  In the above example if this proposed setting was "purchase up to 5", then if there are 4 units, and 3 are consumed, then put 4 items on the shopping list to get back to 5.

I can also see where both proposed settings would be useful, put I would prefer the latter "purchase up to" setting.

**Comment by berrnd** [comment] 2023-10-28 07:05
Duplicate of #1022 (and #2246) - please check existing requests before opening new ones.

**Closed by berrnd** 2023-10-28 07:05 UTC
Labels: duplicate
