### ISSUE TITLE
Feature Request: Ability to tie the Location Master Data to Equipment

### ISSUE THREAD

**Issue by Lncstoddart** [grocy/grocy#2440] opened 2024-01-14 00:49 UTC
Hello,

Love the product so far! Maybe there is already a way to do this, but can the Location master data be used as a field in the Equipment group? I know I can create a custom user field, but I would prefer to just use the data I have already entered into the Locations master data.

Thank you!
Lance

**Comment by berrnd** [comment] 2024-01-14 08:23
Duplicate of #335.

**Closed by berrnd** 2024-01-14 08:23 UTC
Labels: duplicate

**Comment by Lncstoddart** [comment] 2024-01-16 20:21
> Duplicate of #335.

Thank you for the response berrnd. I have seen this post as well as many others. Sorry, but I am still confused on how to use the already provided Locations master data in another object (in my case, equipment). It seems as though #335 shows how to create another userfield with the type "Reference Object", however I am not seeing the "Reference Object" in the type drop down list and then being able to refer it back to the Locations master data. I have seen requests that talk about creating another userentity and add userfields to that entity, but that seems like way too much work for a form that already exists and data that already exists in another master data field. Can someone please show me the steps on how to just map that Location master data to the equipment form?

**Comment by berrnd** [comment] 2024-01-16 20:45
> however I am not seeing the "Reference Object" in the type drop down list

Not that much a surprise since that's exactly what #335 is about. Kindly note that this request is still open = not yet implemented in any way. This applies to any other _open_ Feature Request here (and mostly any other project) too.
