### ISSUE TITLE
Feature Request: "Add" button on Chore Overview page

### ISSUE THREAD

**Issue by dr-quack** [grocy/grocy#1765] opened 2022-01-26 10:07 UTC
I cannot see in existing feature requests. The suggestion is to put a simple "Add" button onto the Chore Overview page which essentially is a shortcut to Master Data in the same way as the button exists for tasks. This will create a more integrated feel for the feature.

**Comment by berrnd** [comment] 2022-01-26 10:30
> I cannot see in existing feature requests

I do. Duplicate of #824.

**Closed by berrnd** 2022-01-26 10:30 UTC
Labels: duplicate
