### ISSUE TITLE
Feature Request: stock entries/journal for parent products

### ISSUE THREAD

**Issue by qguv** [grocy/grocy#2558] opened 2024-08-01 10:25 UTC
When visiting the stock entries or journal pages for a parent product, it would make sense to see (or to have an option to see) the entries for child products. There currently seems to be no way to show all child products on the same page.

**Comment by berrnd** [comment] 2024-08-01 10:42
For the stock entries page a duplicate of #2152 (please be so kind and check existing requests before opening new ones).

Merged into #2152.

**Closed by berrnd** 2024-08-01 10:42 UTC
Labels: duplicate
