### ISSUE TITLE
Feature Request: Not forget previous filters data

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2212] opened 2023-05-10 20:24 UTC
Ex: I filter the phrase "milk" in the master data/products.
I open "Leite ABC", make some updates and click on "Save and return to products".
The data entered in the filters is erased.
I suggest keeping the already typed filters

**Comment by berrnd** [comment] 2023-05-10 20:30
Duplicate of #1211 - please finally check existing requests before opening new ones. (!)

**Closed by berrnd** 2023-05-10 20:30 UTC
Labels: duplicate
