### ISSUE TITLE
Bug: Userfields in new product don't work well in Firefox

### ISSUE THREAD

**Issue by KTibow** [grocy/grocy#1341] opened 2021-02-16 02:15 UTC
In Firefox, when I create a new product, the userfields are pre-filled to the last value. Even if I change it, it doesn't submit at all. Once I hit "Save & continue", they're empty, and it works.
Reproduce:
- Install Firefox (I use 85.0.2)
- Add a userfield to products
- Create a new product, and put something in the userfield
  - First behavior: When you hit save and continue, the thing you put there isn't saved
- Create another product
  - Second behavior: The thing you previously put there is there
- Put something different in the userfield and confirm
  - First behavior again

This probably has something to do with how Firefox keeps form content on reload.

**Comment by berrnd** [comment] 2021-02-16 08:49
Unrelated to Firefox, duplicate of #1302 - please check existing issues before reporting.

**Closed by berrnd** 2021-02-16 08:49 UTC
Labels: duplicate
