### ISSUE TITLE
Feature Request: Use Camera for barcode scanning?

### ISSUE THREAD

**Issue by blakkmaan** [grocy/grocy#102] opened 2018-10-28 07:46 UTC
as its stated on the homepage grocy is kind of a barcode reader. the option to use the camera  (Laptop or mobile) for scanning a barcode would be great. so it would be that easy to add items.

**Comment by berrnd** [comment] 2018-10-28 07:55
grocy is just a web page, so it would need a browser API to support this - currently no major browser has this...

Maybe it would work with some third party service which does the barcode recognition, but then this would be against the "selfhosted" principal...

And just from my personal experience: I would say "scanning" a barcode with a camera can never be faster than using a normal laser scanner, if you would like to use this in the kitchen, I think that's far better, also wireless laser scanners (with USB dongle) are pretty cheap...

**Comment by Jab2870** [comment] 2018-10-31 08:11
Actually, most modern browsers do support this. The feature is called media streams: https://caniuse.com/#feat=stream

I don't have much free time at the moment but I would be happy to take a look at implementing this in a couple of weeks if you like. I would suggest looking at using something like this:

https://github.com/serratus/quaggaJS

**Comment by berrnd** [comment] 2018-10-31 08:42
Cool, I knew of course that you can access the device camera by JS, but have not found a library which does the barcode recognition client side (I meant that the barcode recognition itself should be a browser API above).

You're very welcome to implement this. :)
Currently the "barcode-to-product-resolving" is done in ["on blur" of the product picker input field](https://github.com/grocy/grocy/blob/960ee919f986cbfadebc0b5e9399c7272b47311c/public/viewjs/components/productpicker.js#L93-L100), so the regonized barcode only needs to be "typed" in the input field and the rest should work the same way - let me know if you have any questions.

(I just personally don't see that this will save time for booking purchases compared to manual (auto-completed) input or a good old laser scanner...)

**Comment by Jab2870** [comment] 2018-10-31 09:11
Like I said, I won't have time to do this for at least a couple of weeks but if nobody has done it by then, I'll have a crack at it and create a PR. If someone wants to have a go at it beforehand though, go ahead.

**Comment by Jab2870** [comment] 2019-01-03 13:05
@Braintelligence 
My Appologies, not yet. I'll see what I can do this weekend

**Comment by berrnd** [comment] 2019-01-12 07:10
For custom file imports or similar the API could be used - barcode scanning is currently possible on all places where you select a product, there are basically just one or more strings attached to each product, when this string is typed into the product select, it is resolved to the corresponding product - these typing is normally performed just as normal keyboard inputs by a standard USB barcode laser scanner...

Furthermore there will be a popup when you enter something unknown in a product select input and it will ask if you would like to attach the unknown string to an already existing product (or create a new product) - this helps maintining the master data directly in the daily workflow...

**Comment by HydrelioxGitHub** [comment] 2019-03-01 12:36
I'm just following this issue. Can someone point at me what kind of hardware is needed for doing barcode scan ?

**Comment by berrnd** [comment] 2019-03-01 12:50
When you mean the laser scanner way (not "scanning" by camera, which this issue covers) - I think every cheap USB laser scanner has keyboard (HID) emulation, so when you scan a barcode it types the scanned characters where the cursor currently is - that's how it works.

I personally use a "Inateck 2.4GHz Laser Barcode Scanner Wireless P6"

https://www.inateck.com/de/neue-produkte/laser-barcodescanner-2-4-ghz-2600-mah-akku-60-m-reichweite-automatisch-abtasten-drahtlos-kabellos-gelb-p6.html

https://www.inateck.com/uk/barcode-scanner/inateck-p6-yellow.html

(Was on Amazon(.de) for about 30 EUR some time ago...)

**Comment by Torgrima** [comment] 2019-03-13 16:20
You can use a app for this. Some barcode scanners is integrated into the keyboard. e.g:
https://play.google.com/store/apps/details?id=com.nikosoft.nikokeyboard&rdid=com.nikosoft.nikokeyboard

I hope SwiftKey also will support barcode scanning soon.

**Comment by ytilis** [comment] 2019-05-05 02:07
Just wanted to add that there are 3rd party JS libraries which actually already do a lot of the heavy lifting available to potentially integrate. QuaggaJS in particular comes to mind, since it already supports finding barcodes in live video streams:
https://serratus.github.io/quaggaJS/

Live video stream example can be found here:
https://serratus.github.io/quaggaJS/examples/live_w_locator.html

**Comment by Braintelligence** [comment] 2019-05-05 08:04
This was contributed already 6 months ago:

https://github.com/grocy/grocy/issues/102#issuecomment-434597284:

**Closed** 2019-09-19 10:48 UTC
Labels: enhancement

**Comment by berrnd** [comment] 2019-09-19 10:52
I've implemented this just now by using the above mentioned library [QuaggaJS](https://github.com/serratus/quaggaJS). :)

Looks like that at the end: https://www.youtube.com/watch?v=Y5YH6IJFnfc

> - Available on any barcode-enabled field (so currently only for picking products) - a new camera button at the right of side the text field
> - Implemented using [QuaggaJS](https://github.com/serratus/quaggaJS) - camera stream processing happens totally offline / client-side
> - Please note due to browser security restrictions, this only works when serving grocy via a secure connection (`https://`)
> - There is also a `config.php` setting `DISABLE_BROWSER_BARCODE_CAMERA_SCANNING` to disable this, if you don't need it at all

Try it on the pre-release demo: https://demo-prerelease.grocy.info

**Comment by stefandbt** [comment] 2020-09-08 14:22
Hi Bernd,

when will this feature be available in the stable release?

**Comment by berrnd** [comment] 2020-09-08 14:36
It's included since about a year, so since version 2.5.0, as mentioned above. (?)

**Comment by stefandbt** [comment] 2020-09-08 19:01
Thanks Bernd for the quick reply. It was my fault: I am using the HASSIO Addon of Grocy. In the documentation of the addon is written that the product bar code lookup is not yet supported.

**Comment by codingcatgirl** [comment] 2021-06-09 13:36
Jep, in Hassio it's seems to be nowhere to be found. Anyone have an idea how to activate it?

**Comment by Deedikjupijn** [comment] 2022-07-23 18:33
in Hassio I am able to find it, when I click the button a box appears but no camera. There isnt any pop up where I am able to allow the camera to the grocy server.
![image](https://user-images.githubusercontent.com/67846839/180618428-abfd7ff0-2268-4018-a109-d693aa21e995.png)

**Comment by berrnd** [comment] 2022-07-23 19:01
Camera barcode scanning is powered by [quagga2](https://github.com/ericblade/quagga2) which uses the [JS Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) - supported in every major browser since a long time: https://caniuse.com/stream

Browsers apply various security restrictions for camera access, e.g. that the site must be served via a secure connection (`https://`), that's also [noted in README](https://github.com/grocy/grocy#barcode-readers--camera-scanning) and the most common problem when this was reported for grocy.

Beside that, I cannot say if the Home Assistant integration does something special - never used that personally. Maybe the better place to get a help about this is not here.

**Comment by meistermolli** [comment] 2023-01-12 22:58
@berrnd do i understand it the right way?
When I use grocy via https I can use my iPhone to scan the Grocy codes.
Is there any planning to choose QR codes in the Future as a Grocy code?

**Comment by berrnd** [comment] 2023-01-13 08:12
>  When I use grocy via https I can use my iPhone to scan the Grocy codes.

That using your device's is only possible via a secure connection is not a limition of grocy, it's a security restriction of every current web browser.

&nbsp;
> Is there any planning to choose QR codes in the Future as a Grocy code?

I don't know what you mean. grocycodes are self-generated QR- or Barcodes ([config option ref](https://github.com/grocy/grocy/blob/995df64054370a7d964197d8ff2d9bc1d428d2aa/config-dist.php#L98-L99)) for Products/Chores/Batteries/Stockentries. So for products it's just another code which can be used to select/scan a product, just like any "external" barcode.

&nbsp;
> now the Battery Grocy Code has a text grcy🅱️1 but if you don't know which battery you have it could be a problem.

The purpose grocycodes (and any barcode) is to select a product (or another object) instead of manually typing / searching for it. It's not meant to provide human readable information, since for what. If you need to put text information on a product/battery/whatever, print the text. The stock entry label exactly does that for the due date, example: https://demo-prerelease.grocy.info/stockentry/36/label

&nbsp;
The better place for help and general usage questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests). This here is the tracker for Feature Requests and reproducible Bugs.

**Comment by meistermolli** [comment] 2023-01-13 09:38
Thank you for your quick detailed answer. Then I couldn't use the scanner because the Homeassistant app and the browser didn't have https access either, I think. Then I install Grocy in my own VM.

Ok I looked at the demo, apparently the Homeassistant addon differs from the normal Grocy. The code with the additional information would be helpful for me, does it come in the new release? Where can I choose that I want to print the text? That's currently not possible or at least I can't find anything about it. Sorry, I'll keep looking somewhere else. But not every user is a hardcore IT employee.

meine codes sehen so aus
![grocycode](https://user-images.githubusercontent.com/55836556/212287691-27f6610c-fafa-4505-b4b7-c3e38e285df4.png)
s.

**Comment by berrnd** [comment] 2023-01-13 10:01
> Ok I looked at the demo, apparently the Homeassistant addon differs from the normal Grocy.

I can't say what they do differently, I don't get the sense of re-implementing stuff (if that's really the case), but I also don't maintain (and use) any of the community contributed apps / integrations, since for me personally everything needed is provided by the web frontend.

&nbsp;
> The code with the additional information would be helpful for me, does it come in the new release? Where can I choose that I want to print the text?

Printing stock entry labels is nothing unreleased, it's possible since [v3.1.0](https://grocy.info/changelog#v3.1.0), so since about 1.5 years. What's printed/shown on the pre-rendered label is currently not configurable, to make that somehow possible is already tracked in #1623. Label printing is generally up to your WebHook receiver ([doc ref](https://github.com/grocy/grocy/blob/master/docs/label-printing.md)), so it's up to that what gets printed when printing directly on a label printer.

&nbsp;
> Sorry, I'll keep looking somewhere else. But not every user is a hardcore IT employee.

That's perfectly fine, my aim is not to fulfill everyones needs for every possible use case on this planet and if something doesn't fit, I would personally also not bother with it, since it just doesn't fit then.
