### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by xBlady** [grocy/grocy#2616] opened 2024-12-01 14:15 UTC
Minimal amount of any product within product category. For example I always want to have any kind of meat at home, but whether it's chicken, turkey, beef or pork it doesn't matter and I don't want to set minimal amount on product level, cause I'd have turkey, pork and beef missing even when I have chicken currently in my fridge so I have meet for a dinner, but grocy would show me I don't have some of the meet.

**Comment by berrnd** [comment] 2024-12-01 14:22
Already solvable by utilizing parent/child products and the product option "Accumulate sub products min. stock amount".

And a duplicate of #297 - please be so kind and do a quick and easy search before opening new requests as mentioned on the request template.

**Closed by berrnd** 2024-12-01 14:22 UTC
Labels: duplicate
