### ISSUE TITLE
Feature Request: Import list of products (with or without prices)

### ISSUE THREAD

**Issue by drjudegd** [grocy/grocy#1244] opened 2021-01-01 20:41 UTC
I can't see this feature, so sorry if I've missed it.
When I get online shopping, I get an email from the supermarket telling me what will be in the order. Can I have an way to add that info automatically please (either cut and paste direct, or via a cvs file)?

**Comment by berrnd** [comment] 2021-01-01 22:55
Duplicate of all the other requests about import stuff (at least #445, #210, #158).

**Closed by berrnd** 2021-01-01 22:55 UTC
