### ISSUE TITLE
Bug: Checkbox "Show only in-stock products" losing mark

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2232] opened 2023-05-17 19:07 UTC
In Products overview, when I select checkbox “Show only in-stock products”, the check loses its mark after refresh

**Comment by berrnd** [comment] 2023-05-17 19:14
Duplicate of #1211 - checking existing requests before opening new ones was not only a thing of last week, it's still one for this week too,

**Closed by berrnd** 2023-05-17 19:14 UTC
Labels: duplicate

**Comment by albarreto** [comment] 2023-05-17 19:22
Sorry again. But I swear to you that I tried search this string.
