### ISSUE TITLE
Bug: Check if any amount is in stock does not work when stock <1

### ISSUE THREAD

**Issue by wrybind** [grocy/grocy#1354] opened 2021-02-18 16:53 UTC
The "Only check if any amount is in stock" option for an ingredient in a recipe leads to unwanted behaviour if the amount of the ingredient in stock is larger than 0 but smaller than 1. It displays that the ingredient is missing when it actually is in stock.

How to recreate the bug:

1. Create product "test product" with QU "container".
2. Set stock of "test product" to "0.4 container"
3. Create recipe with "test product" as an ingredient
4. Check the "Only check if any amount is in stock" box for test product in the recipe
5. Recipe overview displays "Not enough in stock (not included in costs), 0.6 missing"

I think the problem is, that the availability check tests whether there is at least 1 QU of a product. However, it should test for larger than 0.

**Comment by berrnd** [comment] 2021-02-18 17:18
Duplicate of #1337, please check existing issues before reporting.

**Closed by berrnd** 2021-02-18 17:18 UTC
Labels: duplicate
