### ISSUE TITLE
Feature Request: Option to disable (active flag) locations/stores/units/etc.

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2222] opened 2023-05-12 18:14 UTC
Currently, master table components such as units, locations, stores, groups, task categories, batteries, user fields, entities cannot be disabled. Excluded only.

As with products, it would be important to allow disabling them.

**Comment by berrnd** [comment] 2023-05-12 18:40
Duplicate of your own (really come on now!) request #2210 (and #1446, and #1278).

Of course the corresponding master data menu items are also hidden when disabling a Feature Flag.

For even more customization, use [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself).

**Comment by berrnd** [comment] 2023-05-13 07:26
Turns out this is about having an "active" flag for locations/stores/units/etc. (like already for products/chores/batteries).

**Closed** 2023-05-13 12:25 UTC
Labels: enhancement
