### ISSUE TITLE
Feature Request: Inherit unit conversions from parent product

### ISSUE THREAD

**Issue by Lykos153** [grocy/grocy#2012] opened 2022-09-29 21:41 UTC
I would like sub-products to start out with the unit conversion list of the parent product, but retain the possibility to overwrite them individually.

One example use case is wine. There can be huge differences between to different bottles, so I want to see them as distinct products in my stock overview. But I still want to group them into parent products, because I alos want an overview over how much eg. red wine I have. When adding a new wine to the product list, I'd love it to inherit the bottle -> liter conversion from the parent by default because most wine bottles are the same size.

**Comment by berrnd** [comment] 2022-09-30 06:48
Duplicate of #1304.

**Closed by berrnd** 2022-09-30 06:48 UTC
Labels: duplicate
