### ISSUE TITLE
Feature request: Barcode scanning - lookup in open product databases

### ISSUE THREAD

**Issue by cr0ssmind** [grocy/grocy#1136] opened 2020-11-18 08:51 UTC
Hello,

It would be nice If the application could look after product details in different opensource product databases ( openfoodfacts, openbeautyfacts, etc...).

**Comment by berrnd** [comment] 2020-11-18 09:00
Duplicate of #158.

See also: https://github.com/grocy/grocy#barcode-lookup-via-external-services

**Closed by berrnd** 2020-11-18 09:00 UTC
Labels: duplicate
