### ISSUE TITLE
Feature Request: Grammatical cases for item names in a recipe for Czech

### ISSUE THREAD

**Issue by sebastianjagr** [grocy/grocy#2434] opened 2024-01-10 14:25 UTC
Hi there,

I would love if there was a feature for Czech to insert an alternative name for products (in this case in 2nd, genitive case). These would be used in recipes.

For example "flour" is "mouka" in Czech. But when you have "200 g flour" in a recipe, it should read "200 g moukY".

This feature would make a huge difference for every language that uses some more extensive case system.

Anyway, thank you for consideration and keep up the great work!

Sebastian

**Comment by berrnd** [comment] 2024-01-10 14:28
What's the problem then naming your product "flour" "moukY" instead?

What would be the rule to get "moukY" from a product named "flour"?

Probably a duplicate of #1066.

**Comment by sebastianjagr** [comment] 2024-01-10 14:36
Well, the problem is that it's not "mouky" but "mouka". It's "mouky" only when used in a recipe.

I know it may look like a small thing, but to us it's basically as if you had no plural functionality in English. You'd have 3 tomato, 2 bottle vinegar etc. Horrible to look at.

Yeah, I don't know how much extra work that would be. As I see it, it's just one extra field in a product and a checkbox in settings that pulls this alias instead of the product name into recipes view, but I have zero idea how much work it actually encompasses 😄

**Comment by sebastianjagr** [comment] 2024-01-10 14:39
> 
> What would be the rule to get "moukY" from a product named "flour"?
> 

There is no simple rule. It depends on the actual word. We have paradigms for that (14 I think), but I don't think it can be easily programmed. People would have to fill that in themselves if they wanted to use it.

**Comment by berrnd** [comment] 2024-01-10 15:12
> You'd have 3 tomato, 2 bottle vinegar etc. Horrible to look at.

Horrible, yet understandable - it's just about beauty. There is even currently no "product name pluralization" (ref #1913) in Grocy, works still pretty well for years practically, I guess for many other recipe management software / websites it's just exactly the same.

In any cause, still looks just as a duplicate of #1066 and/or #1913. Feel free to add further ideas there. Also someone would have to define what's technically needed in a generic way - Grocy doesn't understand Czech or any other language, it's just about strings and the goal is always to make it work for this whole planet, not only a small portion of it.

**Closed by berrnd** 2024-01-10 15:12 UTC
Labels: duplicate

**Comment by sebastianjagr** [comment] 2024-01-10 15:25
I had a look at the 2 issues you referenced and this is not a duplicate of those. I understand Grocy doesn't understand languages, but for example when I switched to Czech from English, all of a sudden there was an option to write down several different plural forms for units of measurement that was not present in the English version (thank you for that, by the way, it made my day).

What is needed in a generic way is basically extra field "Product ingredient alias" with an explanation "The alias in this field will be shown in a list of ingredients for a recipe instead of the product name." If it's filled in, it would be used as a name of the ingredient in the list of ingredients of a recipe. If left blank, the actual name would be used.

This way everyone could decide how this would work for them / their language.

**Comment by berrnd** [comment] 2024-01-10 15:59
Then simply put exactly this into another proper, generic (not specific for Czech or any language) and easily understandable Feature Request, if you think it's not already covered.

Based on reality and to not create false illusions: Those other requests are nearly 2 and 4 years old. Both bothers me personally not really, so unless someone who this bothers more starts to work on it, there is a high chance it's never going to happen anyway.

&nbsp;
> all of a sudden there was an option to write down several different plural forms for units of measurement

That's simply outsourced magic, the localization tool of choice (Transifex) provides the number of plural forms for each language and the translation framework used (GNU gettext) handles any pluralization rules based on that.

**Comment by sebastianjagr** [comment] 2024-01-10 16:05
> That's simply outsourced magic…
Well, it's magic nonetheless! :)

Anyway, I get it, it's too much work. But there is actually a nice workaround: swap the amount and ingredient in the list of ingredients and add a semicolon. That way the issue would be gone and it would look great. I guess a toggle in recipe settings would be needed.

250 g Hladká mouka (wrong capitalization, wrong case)
becomes
Hladká mouka: 250 g (perfect)

Would that be viable enough to turn it into a request?

Also thank you for taking the time to reply to this all!

**Comment by berrnd** [comment] 2024-01-10 17:05
You can put each and everything into a Feature Request, so feel free to do it - if it's ever done or not is just and always the other question, as already mentioned here. The fastest way is always to do it yourself, the later mentioned idea is most likely only little bit of custom [JS fiddling](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself), practically pushing some already visible text around.

**Comment by berrnd** [comment] 2024-01-10 18:26
> only a little bit of [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) fiddling, practically pushing some already visible text around

Here is such a snippet (for `data/custom_js.html`):
```html
<script>
if (Grocy.View == "recipes")
{
	$(".ingredients .list-group-item").each(function()
	{
		var ingredientLine = $(this).find("span").eq(0);
		var ingredientTextParts = ingredientLine.text().replace(/\t|\n/g, " ").split(" ").filter(item => item);
		var newText = ingredientTextParts.slice(2).join(" ") + ": " + ingredientTextParts.slice(0, 2).join(" ");
		ingredientLine.text(newText);
	});
}
</script>
```

It turns this

![grafik](https://github.com/grocy/grocy/assets/2161815/e0c7e4aa-1cdf-4d10-86db-8e0446a62596)

into that

![grafik](https://github.com/grocy/grocy/assets/2161815/39394493-8833-45d5-acb5-82d01095f8d2)

and so makes Grocy less horrible and more beautiful as it ever was, while not changing anything practically.

**Comment by sebastianjagr** [comment] 2024-01-11 07:45
OMG, this would be the perfect solution, but I didn't manage to make it work. Do I get it right that I create a file named custom_js.html, copy the snippet into it and save it in the data folder of my Grocy Docker container? Because I did that and nothing happened :(

**Comment by berrnd** [comment] 2024-01-11 08:00
> Do I get it right that I create a file named custom_js.html, copy the snippet into it and save it in the data folder

Exactly, just as I mentioned it here above - the same folder where the file `grocy.db` is located.

Also make sure you're running Grocy v4.0.3, the current release, since it can only work with that.

**Comment by sebastianjagr** [comment] 2024-01-11 08:05
<img width="799" alt="image" src="https://github.com/grocy/grocy/assets/145137781/1add6108-5c1c-48ac-8605-9b645ff46f14">

Well then I don't know what I am doing wrong. I am running v4.0.3 as you can see from the screenshot. You can actually see the snippet in the screenshot as well showing at the bottom.

**Comment by berrnd** [comment] 2024-01-11 08:09
Can't look behind screenshot and therefore say what exactly happened, just make sure the file only contains exactly the snippet from above, nothing more or less - I additionally attach the file in a ZIP below.

[custom_js.zip](https://github.com/grocy/grocy/files/13899411/custom_js.zip)

**Comment by sebastianjagr** [comment] 2024-01-11 08:17
OMG, THANK YOU! I guess there was something wrong with the formatting because your file works! But there is an issue now. When there is a unit with 2 words it breaks:

<img width="249" alt="image" src="https://github.com/grocy/grocy/assets/145137781/c6849cdc-3705-4200-a588-cf5f3b9eaa84">

The 2nd one shouldn't be "lžička Sůl: 1 čaj." but "Sůl: 1 čaj. lžička". But I can just turn it into a one-word unit and it will be fixed!

**Comment by berrnd** [comment] 2024-01-11 08:19
> When there is a unit with 2 words it breaks

Yes, it simply reorders the parts split by `space` into `<amount> <unit> <the rest is the product name>`, so that's the limitation.

**Comment by sebastianjagr** [comment] 2024-01-11 08:23
Already changed the 2 units that were problematic. Thank you so much again! By the way do you need help with the Czech translation? I am actually a translator so I'd be more than happy to!

**Comment by berrnd** [comment] 2024-01-11 08:41
> By the way do you need help with the Czech translation? I am actually a translator so I'd be more than happy to!

I can't do any translation beyond German/English by nature, so I'm personally doesn't need help on that, but everyone can translate everything into any language, see README: https://github.com/grocy/grocy#localization

**Comment by sebastianjagr** [comment] 2024-01-11 08:44
Awesome. The strings don't seem to be reviewed for Czech so I can go through them. Have a great day!
