### ISSUE TITLE
Feature Request: Ability to schedule chores with cron expression

### ISSUE THREAD

**Issue by GlenNicholls** [grocy/grocy#2517] opened 2024-04-12 18:01 UTC
For example, yard maintenance like fertilizing in spring, summer, and fall or blowing out sprinklers and turning them back on depends on location so it doesn't quite follow the same pattern. I think having the ability to use a cron expression would be helpful in these situations so I don't have to have multiple chores or play weird games with the periodicity and activating the chore.

**Comment by berrnd** [comment] 2024-04-12 18:07
Duplicate of #2143 - please be so kind and do just a little search for existing requests before opening new ones.

**Closed by berrnd** 2024-04-12 18:07 UTC
Labels: duplicate

**Comment by GlenNicholls** [comment] 2024-04-12 18:25
My apologies, sorry for the duplicate. I didn't see any hits when searching for cron and didn't see that with the other searches.
