### ISSUE TITLE
Show the stock entries in the product detail view

### ISSUE THREAD

**Issue by white-gecko** [grocy/grocy#1064] opened 2020-10-17 17:33 UTC
I would expect to see the list of stock entries of a certain product listed next to the products detail view. I do not if others have the same expectations.

**Comment by kriddles** [comment] 2020-10-17 17:51
Perhaps to make sure the product card would not be too large if there are quite a few stock entries we could limit the view to first 5 entries sorted by best before date?
And there could be a button to jump into the stock entries page for that product next to the stock journal button.

**Comment by white-gecko** [comment] 2020-10-17 17:54
Yes, something like that. Or treat the current card view just as a preview and provide a detailed product view involving the price history and the list of stock entries (maybe also with a direct link to a pre-filtered stock entries view)

**Comment by berrnd** [comment] 2020-10-17 20:08
Somehow similar to #449.

Stock entries are more or less the "raw" database entries, for example splits happen here on several stock actions - there could be 1 row/entry with the amount of "1000 gram", or 1000 rows with the amount of "1 gram" each (extreme example), both means the same at the end, but the amount of rows would be hugely different.

If it's for #1061, I think this is not the "real solution".
Scanning everything, then going through the same list again to add best before dates and prices is, for me, doing the same thing more or less twice - why not add all infos in the first step. The web UIs shopping list "Add all list items to stock" helps exactly with that. But I don't know how it looks in grocy-android, maybe it's about to improve that there...

So it's somehow ok to add this, but only optionally as most of the time you should not even touch the "stock entries" (I personally only do it if I entered something wrong during purchase and I haven't noticed it immediately - if so, I simply undo the action directly from the success popup on the purchase page and enter it again).

**Comment by Saturo78** [comment] 2022-02-26 18:03
For me it is very important to see the individual stock entries. I have items in different storage locations and need to see which inventory entry is the one e.g. with the next BBD and therefore from which storage location I have to pick. Only to know that there are 5 pieces on stock is not enough for my workflow.

**Comment by berrnd** [comment] 2022-04-02 18:49
Closing this as a duplicate of #449.

[/stockoverview](https://demo.grocy.info/stockoverview) is the "high level" overview which shows one line per product and the corresponding total amount.

[/stockentries](https://demo.grocy.info/stockentries) shows the individual stock entries.

Both pages are accessible pre-filtered to to the corresponding product from the product card or the context-/more-menu on the stock overview page. So everything is already accessible, #449 is about to make this easier by integrating the individual stock entries into the stock overview page.

**Closed by berrnd** 2022-04-02 18:49 UTC
Labels: duplicate

**Comment by Saturo78** [comment] 2022-04-02 19:03
#449 is about showing parent and child items in a collapsable list.

This issue is about showing the raw stock entries of any given product.

In my opinion different things.

**Comment by berrnd** [comment] 2022-04-02 19:23
> #449 is about showing parent and child items in a collapsable list.

When reading more than the title it's definitely about parent-/sub products and stock entries.

> This issue is about showing the raw stock entries of any given product.

Already possible, since kind of ever, just mentioned above about half an hour ago:

> [/stockentries](https://demo.grocy.info/stockentries) shows the individual stock entries.
> 
> Both pages are accessible pre-filtered to to the corresponding product from the product card or the context-/more-menu on the stock overview page. So everything is already accessible, https://github.com/grocy/grocy/issues/449 is about to make this easier by integrating the individual stock entries into the stock overview page.

If my words are unclear, here is additionally a screenvideo:


https://user-images.githubusercontent.com/2161815/161398062-30ba5d4a-e6fb-4cf8-a23f-45081dc1770b.mp4
