### ISSUE TITLE
Feature Request: Using Grocy for more than food - Consumable hardware, electronics and tools for projects?

### ISSUE THREAD

**Issue by b3nd1k** [grocy/grocy#2499] opened 2024-03-17 14:57 UTC
Hey. I don't know if anyone has suggested this, but I would love see an option where you can add a product as either a eatable or non etable product. If you select the non eatable, you are given other field options. 

This would be great for tracking consumable items such as screws, bolts, ethernet cables, glue, sandpaper and other items. As one often works on a project or three this would be a great way to keep track of my inventory and to know whether or not I need to replenish and from where. 

In addition to the "Default Store" input field, it would be great if we could have an option to add a URL to the product on a website for easy re-ordering. Other fields such as energy due date would not be nessearily. 

There is nothing stopping me from doing it now, but I fear Grocy would be confusing and messy if I were to mix the two types of products.

**Comment by berrnd** [comment] 2024-03-17 15:12
> I don't know if anyone has suggested this

What's the problem about doing an easy and quick search for that? Duplicate of #2351.

&nbsp;
> In addition to the "Default Store" input field, it would be great if we could have an option to add a URL to the product on a website

You can add any field you want to any entity you want (= products, chores, a shopping list item, everything) by utilizing Userfields.

**Closed by berrnd** 2024-03-17 15:12 UTC
Labels: duplicate
