### ISSUE TITLE
Bug: "constraint failed: period_interval > 0" on upgrade to v3.2.0 (when having weirdly configured chores)

### ISSUE THREAD

**Issue by cmmtchll** [grocy/grocy#1826] opened 2022-03-22 22:05 UTC
Was running stably on .16.  Only had 3 users and chores populated, nothing else really in use.  

Error source:
```
/var/www/grocy/services/DatabaseService.php:35
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: period_interval > 0
```

Stack trace:
```
#0 /var/www/grocy/services/DatabaseService.php(35): PDO->exec()
#1 /var/www/grocy/services/DatabaseMigrationService.php(63): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/grocy/services/DatabaseMigrationService.php(33): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /var/www/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /var/www/grocy/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /var/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /var/www/grocy/app.php(106): Slim\App->run()
#24 /var/www/grocy/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.2.0",
        "ReleaseDate": "2022-02-11"
    },
    "php_version": "8.0.16",
    "sqlite_version": "3.36.0",
    "os": "Linux 5.10.92-v8 #1 SMP PREEMPT Wed Mar 9 11:34:06 UTC 2022 aarch64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/101.0.4922.0 Safari\/537.36"
}
```

**Comment by cmmtchll** [comment] 2022-03-22 22:11
I realize I was quoting Home Assistant GROCY Add on versions rather than GROCY.  .17 of HA switched to 3.2.0, presumably from 3.1.x

**Comment by berrnd** [comment] 2022-03-22 22:20
A bug needs to be reproducible (mentioned not only on the issue template), that's missing here.

Maybe you had a chore with a negative period interval before (that's maybe an idea to get this reproducible, feel free to do that), whatever the sense of that is.

I would simply check that and try the upgrade again.

If all doesn't help and that's important for you and/or you maybe don't have a backup, feel free to send me your database and I'll see what I can do.

Closing this as invalid unless having a reproducible example.

**Comment by cmmtchll** [comment] 2022-03-22 23:08
@berrnd I can update that to repro, the probel was on chores of type 'Dynamic Regular' (now Adapative).  Those tasks by default (as I didn't change it) had a Period Interval = 0.  I restored backup, changed those to have a period = 1, and then upgraded SUCCESSFULLY.

So I do consider this a bug as 0 was a default.

**Comment by berrnd** [comment] 2022-03-23 07:33
Thanks for providing a reproducible example, will check it and provide a workaround.

Most likely still a problem based on bullshit input:
"Period interval" for former "Dynamic Regular" chores was migrated to "Period Days" (and they are now of type "Daily", not "Adaptive", [changelog ref](https://github.com/grocy/grocy/blob/master/changelog/66_3.2.0_2022-02-11.md#chores), migration [code ref](https://github.com/grocy/grocy/blob/f88bad4bdefeecb91e0c234b38fe3771db675473/migrations/0166.sql#L1-L5)).

Having a "Period Interval" of `0` for former "Dynamic Regular" makes absoluetly no sense in the same manner, because it means "schedule the next execution of this chore at the same the last execution was tracked", don't know where you need this in reality.

**Comment by berrnd** [comment] 2022-03-23 10:48
I took the time and tested it, it is exaclty that:

> Having a "Period Interval" of `0` for former "Dynamic Regular" makes absoluetly no sense in the same manner, because it means "schedule the next execution of this chore at the same the last execution was tracked", don't know where you need this in reality.

**Comment by cmmtchll** [comment] 2022-03-23 10:53
I don’t disagree that it might not make sense, however, it was a VALID entry (and was not blocked at entry).  As a result, the data was in the database and the upgrader failed.  The Diagnosis (from logs) was difficult as it didn’t indicate which record was causing the problem, leading me to restrore from backup and then ‘poke around’ until I found all of the entries.

In my view:

  1.  Since this (this specific field) was an allowed (albeit non-sensical) entry, the upgrader MUST take this into account and not fail.  Is there a way to change the 0 to something better?
  2.  When a consistency check fails, in an upgrader, the system should at least provide more information.

I totally understand the position you have, but the UI allowed the entry…(I am a BRAND NEW user to GROCY) so it might have been an odd entry (I don’t recall changing it to 0)…so blame user, but the system let me do it.

Chris Mitchell
***@***.******@***.***>
Sent with http://outlook.com<http://outlook.com/>

**Comment by berrnd** [comment] 2022-03-23 11:05
grocy is based on on the [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) principal which basically you means, you get bullshit out when you put bullshit in.

However, yes, of course any non-sensical input possibility could be checked and prevented, but grocy doesn't do that for each and every place / input field. So if that is an problem for you, maybe grocy isn't the right thing to use.

And any of those advices how a system should handle things I really like the most, thanks for that - seems that then grocy is entirely broken in general by that.

Whatever, I will provide a workaround to provide a working upgrade path for your problem for the next release, just like for any bug reported so far. Just wait for it if you don't want to fiddle yourself.

**Closed** 2022-03-23 16:35 UTC
Labels: bug
