### ISSUE TITLE
Feature Request: Recipe Triggers Prep Task(s)

### ISSUE THREAD

**Issue by Wordna1** [grocy/grocy#595] opened 2020-03-08 05:57 UTC
Some recipes require prep (eg. move meat from freezer to fridge 2 days prior).  It would be SUPER helpful if adding such a recipe would automatically create the related "prep" task.  It is way too easy to forget to thaw the meat...

**Comment by berrnd** [comment] 2020-03-08 07:39
Duplicate of #371.

**Closed by berrnd** 2020-03-08 07:39 UTC
Labels: duplicate
