### ISSUE TITLE
Feature Request: Maximum stock amount

### ISSUE THREAD

**Issue by WHagenauw** [grocy/grocy#2144] opened 2023-02-20 19:27 UTC
I like to have the option that if groceries are added to my shopping list automatically (because they are below stock) that they are added to the amount of maximum stock. The maximum stock to be defined for each item separately.

E.g. I have space for 10 items X. Below 4 it need to be added to my shopping list until 10 pieces max (minus the ones still in stock). Not by just 1 item. If it is still on my shopping list and I take one out of stock again, also that item need to be added to the shopping list (so still max 10 items will come in stock again after I went shopping and buy the amount on my shopping list).

I don't go for 1 item to the shop (or buy it online for 1 item). Now I have to check each item for the amount I want to buy.

Maybe this already has been requested earlier in about the same way but I did not see it implemented (I use grocy as an integration of Home Assistant).

**Comment by berrnd** [comment] 2023-02-20 19:31
Duplicate of #1305 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-02-20 19:31 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2023-02-20 19:37
Also related to / a duplicate of #1022.
