### ISSUE TITLE
Bug:  Deletion of a Meal Plan makes it so I can't add a new meal plan. 

### ISSUE THREAD

**Issue by blindrain** [grocy/grocy#2459] opened 2024-02-08 05:09 UTC
![grocy](https://github.com/grocy/grocy/assets/11042185/110ebccc-9041-45a9-ac85-1571bb3fa328)
Meal Plan  + button does nothing 

I had created a plan the deleted it.  
I Resolve the issue by making a clean database  but it returns  when I restore the bad data base. 

I have several hours in to my database how do I correct this? 

I Can not recreate this in the pre release demo  and the meal plan I deleted was the first one in my instance. 
I Had not performed a back up before this deletion. 

```text
Version 4.0.3
Released on 2023-09-02 5 months ago

PHP Version 8.1.2-1ubuntu2.14
SQLite Version 3.37.2
OS Linux 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64
Client Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
```

**Comment by berrnd** [comment] 2024-02-08 07:47
Duplicate of #2333 (and #2419) - already fixed, not yet released - doing a little search beforehand would be a super cool thing (mentioned on the issue template), instead of [double posts](https://www.reddit.com/r/grocy/comments/1alopyi).

&nbsp;
> I have several hours in to my database how do I correct this?

Mentioning a fellow user from https://www.reddit.com/r/grocy/comments/16ahkyt/comment/jz8lkqe/?context=3:
_I had the same problem today. Adding a recipe from Recipes to Meal Plan solved it for me._

**Closed by berrnd** 2024-02-08 07:47 UTC
Labels: duplicate

**Comment by blindrain** [comment] 2024-02-19 17:00
This is not resolved,    I upgraded to version 4.1.0  and this issue still exists. if it is corrected on preventing the break, then the functionality is not restored.  is there a way to restore this functionality ?

**Comment by berrnd** [comment] 2024-02-19 17:21
> is there a way to restore this functionality ?

When you provide a reproducible example or at least some concrete error messages, then I maybe can say something more detailed and ultimately, maybe I'm then able to fix something based on that. Don't know how people always think it's possible to guess all the details without providing literally anything at all, can you?

Also, since this was a problem in the past more than often, triple check you cleared your `data/viewcache` directory + restart your your PHP process manager or the whole corresponding machine, just to make sure that's not just a simple caching issue.

It works generally, otherwise this tracker here and [r/grocy subreddit](https://www.reddit.com/r/grocy) would be flooded with corresponding reports, which is not the case.

If it's super duper important for you, you don't have the time or desire to look into this a bit deeper to provide the necessary information and if it's ok for you, send me your `data/grocy.db` file and I will spend my evening debugging your individual problem, of course for free and my pleasure - since this is obviously what I have to do and you wouldn't have this problem, if I hadn't created Grocy, sorry.

**Comment by blindrain** [comment] 2024-02-23 05:14
I Cleared that directory and restarted the system.  it brought it back up like it originally did  but after adding a meal to the meal plan it went blank.  not like after deleting the entry but blank. 
![image](https://github.com/grocy/grocy/assets/11042185/31504e26-be99-4ab7-9caf-2f728132ea0c)

**Comment by berrnd** [comment] 2024-02-23 07:22
4 days later, I still don't have the skill to look behind screenshots.

I'm going to lock this, since I doubt anything useful will come out at all and I'm tired of such type of reports. Restart your Grocy journey (no backup, no mercy) or simply use another software.
