### ISSUE TITLE
Bug: QU conversions for product converts incorrectly when creating a recipe using the conversion units

### ISSUE THREAD

**Issue by rystein** [grocy/grocy#1727] opened 2021-12-29 00:25 UTC
I have a product that is stocked in pounds. I created conversion factors (including the inverse) for Cups to Ounces (1C to 8oz) and Pounds to Ounces (1lb to 16oz). When adding this ingredient to the recipe as 2.25 Cups it indicates this is the same as 18 pounds.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/43422564/147616640-d0ac473b-4b65-4707-ab7d-aaef43644fd1.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/43422564/147616661-74a3e77d-b9b5-41c8-bd69-842b9cdc93c9.png">

**Comment by berrnd** [comment] 2021-12-29 07:34
Duplicate of #1360 (and question-duplicate of #1663) - QU conversions are currently limited to 1 level.

QU stock is always the base, so we need to go from Pounds to Cups for your example (from what I can see from the screenshot, [persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are the better thing to be able to look behind pictures, as also mentioned on the issue template):

Product stock QU _Pound_ **_Level 0_**
&nbsp;&nbsp;Product-QU conversion _Pound_ <-> _Ounce_ **_Level 1_**
&nbsp;&nbsp;&nbsp;&nbsp;Product-QU conversion _Ounce_ <-> _Cup_ **_Level 2  <-- Currently not supported_**

Create a conversion between Cups and Pounds at it will work.

**Closed by berrnd** 2021-12-29 07:34 UTC
Labels: duplicate
