### ISSUE TITLE
Feature Request: Tasks With Time Due Date

### ISSUE THREAD

**Issue by jeremy-green** [grocy/grocy#2363] opened 2023-10-26 03:22 UTC
Greetings! I'm trying to create a one-time task that's, for example, due an hour from creation. Similar to the due date functionality provided for chores. I searched around to see if it was possible but didn't find any information regarding tasks and time formats. Happy to answer any questions I might be missing. Thank you!

**Comment by berrnd** [comment] 2023-10-26 06:59
Tasks currently only support dates for the "Due" field by design.

Grocy is about managing your home. So what's a practical example for the aforementioned target use case where the due time is only a hour ahead and it's not enough to use "today" only?

**Comment by jeremy-green** [comment] 2023-10-26 12:54
I want to dynamically create a task for moving my laundry from the washer to the dryer. I'm using the iCal calendar feature within HA to send me notifications when I have tasks and chores due.

**Comment by berrnd** [comment] 2023-10-26 13:18
For that use case a duplicate of #339.

**Closed by berrnd** 2023-10-26 13:18 UTC
Labels: duplicate
