### ISSUE TITLE
Feature Request: Simplify adding items on /shoppinglist

### ISSUE THREAD

**Issue by wingmanx** [grocy/grocy#2468] opened 2024-02-12 19:29 UTC
Hi.

Nice work with Grocy.

To create items, it could be more simple, just write the name of the product and click "add", it could be some default menu and if we wanted more options, we could in the item add, select "advanced options" for these other options, for example. 

Thanks!

**Comment by wingmanx** [comment] 2024-02-12 21:29
Thanks for changing the title. Yes it is about /shoppinglist.

**Comment by berrnd** [comment] 2024-02-24 19:33
Duplicate of / merged into #716.

**Closed by berrnd** 2024-02-24 19:33 UTC
Labels: duplicate
