### ISSUE TITLE
Bug: Shopping list created by the meal plan functionality doesn't add up needed products

### ISSUE THREAD

**Issue by brobken** [grocy/grocy#2575] opened 2024-09-06 21:14 UTC
> Describe the bug as detailed as possible by providing the exact steps how to reproduce it

When you create a meal plan and the different recipes are holding the same ingredients, only the last added recipe's ingredient is added to the shopping list. It doesn't count up to amount needed for the overall added recipes.
This is when you add the missing ingredients from the meal plan and choose to 'Put missing ingredients on shopping list' feature.

Reproducable on my own environment and in the demo environment.

**Comment by berrnd** [comment] 2024-09-07 06:10
Not everything not behaving exactly like you personally expect it should behave is a bug. Not a bug, works as currently defined. Maybe first ask about how stuff is supposed to work and also being so kind and simply doing an easy and quick search would be supa dupa great - duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789, #1965, #2020, #2174, #2418).

&nbsp;
> It doesn't count up to amount needed

Use the "Put missing ingredients on shopping list"-button on the header of each meal plan week and your "problem" is maybe solved immediately.

**Closed by berrnd** 2024-09-07 06:10 UTC
Labels: duplicate

**Comment by brobken** [comment] 2024-09-07 08:27
> Not everything not behaving exactly like you personally expect it should behave is a bug.

That's right! I didn't look up the closed ones enouogh, but I bet it would hard for me to find them since English isn't my native language 🙃 I do get the way of working now as described in #840.

Thanks for the fast reply, works completely as expected! 👍
