### ISSUE TITLE
Feature Request: Shopping List Add all items to inventory - Use default purchase unit

### ISSUE THREAD

**Issue by rscafidi** [grocy/grocy#1837] opened 2022-03-30 03:14 UTC
Hello, I'm not sure if this is by design, but the "Add all items to stock" on the shopping list view does not use the default purchase unit. Once my inventory for an item drops below the amount I set, I can add the missing items to the list. When I mark the items as done and add them to stock, it only uses the amount added to the list, not the purchase amount that I set in the settings.

For example, here's a scenario of my configuration:
Minimum Inventory Amount for Canned Black Beans: 12
Inventory unit: Can
Purchase unit: Pack
Current Stock Amount: 10 Cans
Needed amount: 2 Cans
Default purchase unit to inventory conversion: 12

Current behavior with adding all items to stock:
Defaults to inventory unit missing, so in this example, 2 Cans are added to inventory

Desired behavior:
In my opinion, it should do the math and select the minimum number of Purchase Units to which the conversion is >= the needed items. So in the example above, it would record a purchase of 1 Pack of canned beans, adding 12 Cans to the inventory.

As I see it behaving now, the inventory will be off if I do a batch purchase. I've tried to streamline our inventory process as much as possible, so we do not scan items into inventory, I only scan on consumption. I was hoping to take advantage of the batch purchase/shopping list feature but if it doesn't smartly add inventory based on my configured purchase unit to inventory unit conversion, then I am forced to manually enter items into inventory.  It'd be great if there was a setting to "prefer purchase units when adding to inventory from shopping list"

**Comment by berrnd** [comment] 2022-03-30 06:57
"Add all items to stock" is supposed to add what's currently on the shopping list, so the exact the amount from the list.

So it would probably make more sense to already use the default purchase unit when adding things to the shopping list: Duplicate of #1355

**Closed by berrnd** 2022-03-30 06:57 UTC
Labels: duplicate
