### ISSUE TITLE
Kohlenhydrate anzeigen für Diabetiker bei Lebensmitteln /Gerichten - show carbohydrates for diabetics at Food/Recipes

### ISSUE THREAD

**Issue by pawido** [grocy/grocy#931] opened 2020-07-27 06:42 UTC
Hi, Community

for me as an diabetic, it is more useful, to see how much carbohydates a food contains - most urgent in Recipes. Therefore calories are not the same as carbohydrates. As an example Fat has 7000 Calories /kg but no carbohydrates and its safe for Diabetics. Sugar has "only" 4000 Calories /kg but roundabout 100 BE carbohydrates /kg and is more dangerous for us.
It would be great if it is possible to add this Unit in Products like Calories and also add this in Recipts, that a Diabetic knows how much Insulin is needed.

Thanks..

**Comment by berrnd** [comment] 2020-07-27 08:35
Duplicate of #467.

See #176 for the generic Userfields feature, summarizing Userfields in recipes is not yet possible, but already tracked in #413.

**Closed by berrnd** 2020-07-27 08:35 UTC
Labels: duplicate, question
