### ISSUE TITLE
Feature Request: easy way of changing one field in multiple products

### ISSUE THREAD

**Issue by jorik41** [grocy/grocy#1831] opened 2022-03-23 17:37 UTC
hey i got a good db of products and i love the new label feature since not all product there barcodes are that great to scan with a phone.
The problem is the default for old and new products is always no labels.
so now i need to manually update all products to set the label printing to label per unit.
same thing if i want to change the default location.
Maybe a faster way to change the same field in multiple or all products can be implemented ?

**Comment by berrnd** [comment] 2022-03-23 17:42
Duplicate of #1020.

**Closed by berrnd** 2022-03-23 17:42 UTC
Labels: duplicate
