### ISSUE TITLE
MYSQL support for Grocy

### ISSUE THREAD

**Issue by prbt2016** [grocy/grocy#2335] opened 2023-09-12 10:10 UTC
Hello @berrnd ,

I checked with the requirements and found that SQLite is needed for Grocy to Install

https://github.com/grocy/grocy#platform-support

Just wanted to know that is MYSQL supported by Grocy or not? . 

Or is there any specific doc to install Grocy using MYSQL, as I couldn't find one .

Kindly let me know regarding the same.

Regards.

**Comment by berrnd** [comment] 2023-09-12 10:22
Duplicate of #89 - please check existing requests before open new ones.

What's the big practically issue about SQLite? Or is just the general "SQLite is no real database"-fear some people (for whatever unintelligible reason) have?

**Closed by berrnd** 2023-09-12 10:22 UTC
Labels: duplicate

**Comment by SerialVelocity** [comment] 2024-04-10 10:30
To answer your question, I think sqlite is plenty good for most use cases, but there are two issues with sqlite (with the second being quite serious):
1. Family; Usually spouses/partners. They usually want things to always be working. Which means HA usually. This is difficult to do with sqlite.
2. Network filesystems. People who use NAS's (especially since it is an easy way for a low tech person to get large data storage and backups) encounter issues when using NFS and samba. These technologies are used more commonly at home rather than in high tech setups which use iSCSI, Ceph RBD, OpenEBS, etc. The biggest issue when using these network filesystems is corruption. I've had it happen multiple times with other self-hosted products where sqlite can either lockup and require manual intervention (I think it was a `.recover` then a `.exit`), or the DB ends up corrupted (It's happened twice to me!). This is not to do with how the products were implemented, this is specifically to do with network filesystems.

**Comment by berrnd** [comment] 2024-04-10 10:48
If you have that much problems with network filesystem, I wonder why you use them - seems you like not working stuff, I on the other prefer stuff to be simple and fast as fuck.

You can recite all the theoretical problems (heard them all too often and all of them are not practical problems, just still the "SQLite is no real database"-fear) thousand times over, it won't change that Grocy will stay to use SQLite now and most likely forever. Nobody is forced to use Grocy, especially if SQLite is the big breaking point. Why not create your own (and then just perfect in every single detail) solution and start doing that right today?

For thousands of people and since about 7 years that all is not a practical problem, they use Grocy and it just works, there was never a single problem caused by the DBMS chosen. That's more than enough, I don't care about you or anyone who has that SQLite fear, maybe a doctor can help better.
