### ISSUE TITLE
Feature Request: Generate "random" meal plan

### ISSUE THREAD

**Issue by slug1121** [grocy/grocy#2566] opened 2024-08-12 18:08 UTC
I believe a cool feature would be the possibility to generate a random meal plan.  The caveat to this is there would likely need to be some sort of recipe category, so an appropriate meal could be added to Breakfast/Lunch/Supper (i.e. you likely wouldn't list a root beer float for breakfast).

**Comment by berrnd** [comment] 2024-08-12 18:36
Duplicate of #310 (or #553, and a whole bunch of other related/duplicate requests, all of them are linked there) - please be so kind and do a little tiny search before opening new requests.

**Closed by berrnd** 2024-08-12 18:36 UTC
Labels: duplicate
