### ISSUE TITLE
Pre-release: Productmanagmet complete broken

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1101] opened 2020-10-26 20:26 UTC
I'm unable to delete Products. It's not possible to add Barcodes. And the UI add other Barcodes at the Product, if i don't add a barcode at the creation.

Here a Video that explains what's happend.
[https://www.dropbox.com/s/y0nvcmxf79lx288/Bildschirmvideo%20aufnehmen%202020-10-26%20um%2021.58.13.mov?dl=0](https://www.dropbox.com/s/y0nvcmxf79lx288/Bildschirmvideo%20aufnehmen%202020-10-26%20um%2021.58.13.mov?dl=0)

Have i forget something?
I used a database from the stable release.

I think, the database-migrations failed. The Server Logs are full of these:
```
PHP Notice:  Undefined variable: product in grocy/data/viewcache/e530....
PHP Notice:  Trying to get property 'id' of non-object in /opt/grocy/data/viewcache/e5307f
PHP Notice:  Trying to get property 'costs' of non-object in /opt/grocy/controllers/RecipesController.php
```
And yes, i deleted the viewcache and the Browser-Cache was disabled...

Sorry for this rly bad english

**Comment by berrnd** [comment] 2020-10-26 21:37
Thanks for testing.

Please don't consider the master branch "stable". Of course there is something broken, because it's just not ready. For example about product deletion handling. We introduced for the next version that products can be archived, because they were problems with deleted products on recipes, the meal plan, and so on. So one open thing is to re-integrate this with the deletion possibility, or do it differently.

So this is normally not a bug, but I'll leave this open to track when particularly this is done.

(And please also note that database migrations do not always work between any commit, they should just work between releases - so please don't use the master branch for any "production" setup if you can't handle that yourself - beside that any and everything can be broken anytime...)

**Comment by sleeplessnight2** [comment] 2020-10-26 22:08
I know that master-branches are in the most cases just a testing place.
I copied the database from my production installation and use this database on a staging system.

But a fact is, that's exactly happening on your demo-prerelease.grocy.info.
This needs more understanding your database-schema for helping on this state.

**Comment by berrnd** [comment] 2020-11-08 21:14
I did some tests / UI review today, this was fixed by any of the commits of today.

**Closed by berrnd** 2020-11-08 21:14 UTC
Labels: ui-bug
