### ISSUE TITLE
Feature Request: Default recipe ingredient costs when no unit conversion exists

### ISSUE THREAD

**Issue by georgegebbett** [grocy/grocy#1693] opened 2021-11-22 16:36 UTC
When a recipe has an ingredient where a quantity unit is being used that is not applicable to that product on the master list, the cost of that ingredient is calculated through multiplying the quantity of the non-standard unit by the price of one standard unit of the product. 

For example - my Grocy instance tracks milk by the bottle, and the cost of the bottle is £1.15. I have a recipe which calls for 300ml of milk, and I have ticked the 'Only check if any amount is in stock' checkbox. The price of the milk ingredient of the recipe is reported to be £345.00. 

Would it be sensible to disable this behaviour entirely if the price factor is not modified?

<img width="628" alt="Screenshot 2021-11-22 at 16 27 25" src="https://user-images.githubusercontent.com/35996500/142899767-47c0cf0d-9f77-4ef8-aad8-2862e53d3e11.png">

**Comment by georgegebbett** [comment] 2021-11-22 16:44
Obviously this behaviour can be rectified by adding unit conversions, but would seem sensible for the default behaviour to be to switch the price to simply be zero rather than throwing the price of the whole recipe out of whack!

**Comment by AndreasSteibl** [comment] 2021-11-22 17:59
Hi the same problem is with the calories, I have a quantity conversion, but the calories are only multiplied.

**Comment by Saturo78** [comment] 2022-12-20 10:58
I have stumbled across the same problem.
Although there is a conversion from pack to gram, the calories of a pack are displayed.

Maybe this could be solved by tracking calories generally per 1 gram instead of per pack?

**Comment by berrnd** [comment] 2022-12-20 11:18
> I have stumbled across the same problem an i can confirm that the issue still exists even when there is a qu conversation.
> I have set a conversion from pack to gram, but the calories of a pack are displayed.

Then please, once again, don't just claim that something doesn't work, simply and finally provide a reproducible example - and of course I did that once more for you by the provided minimal information:

Recipe: https://test-332za5c3vdb5wjemqgt5k4.demo-prerelease.grocy.info/recipes?recipe=7

![grafik](https://user-images.githubusercontent.com/2161815/208654036-0fcfe121-f5b4-4c64-b4f5-a5cb2e1cd6ed.png)

![grafik](https://user-images.githubusercontent.com/2161815/208654183-0fab7e22-1ab4-4fb5-be76-7e81d5dd5539.png)

And if this would be a problem, it's, also once again, completely off-topic here - this here is about doing something with recipe calories and costs, when no corresponding unit conversion exists. Which is practically just bullshit and can be easily rectified by just providing a corresponding unit conversion, since grocy is unable to guess how much Grams a Pack has.

**Comment by Saturo78** [comment] 2022-12-20 15:07
Oh i am very sorry!

I thought this issue is also about the wrong calculation of calories when qu conversation is set as mentionend from
AndreasSteibl on Nov. 22 2021.

Then I would like to open a new issue.

**Comment by berrnd** [comment] 2022-12-20 15:18
> Then I would like to open a new issue.

Then do that, if you have a reproducible example - your above minimal provided information was not reproducible in my example from just 3 hours ago, quoting myself:

> Then please, once again, don't just claim that something doesn't work, simply and finally provide a reproducible example - and of course I did that once more for you by the provided minimal information:
> 
> Recipe: https://test-332za5c3vdb5wjemqgt5k4.demo-prerelease.grocy.info/recipes?recipe=7
> 
> ![grafik](https://user-images.githubusercontent.com/2161815/208654036-0fcfe121-f5b4-4c64-b4f5-a5cb2e1cd6ed.png)
> 
> ![grafik](https://user-images.githubusercontent.com/2161815/208654183-0fab7e22-1ab4-4fb5-be76-7e81d5dd5539.png)

I guess that's just the third (already resolved by #1360, but not yet released (!!!)) example you've reported in 48 hours related to https://github.com/grocy/grocy/issues/2066#issuecomment-1356391853.

**Comment by berrnd** [comment] 2022-12-26 21:02
Nothing will be changed for that.

As mentioned above, if you want to have proper output, put proper things in - here: Quantity unit conversions.

**Closed by berrnd** 2022-12-26 21:02 UTC
Labels: wontfix/out-of-scope
