### ISSUE TITLE
Feature Request: Store APIs

### ISSUE THREAD

**Issue by jasgud** [grocy/grocy#1921] opened 2022-06-16 17:35 UTC
It would be very useful to connect into a stores API. In my area many store APIs can be scrapped from their websites and can be queried via the barcode(sku).  This could allow all kinds of future enhancements such as as shopping list price estimates, sale notifications, automatic price tracking, nutritional information, etc. 

Example Product: https://www.saveonfoods.com/sm/pickup/rsid/4420/product/dairyland-butter-salted-00068700045059
StoreID: 4420
SKU: 00068700045059
Request URL: https://storefrontgateway.saveonfoods.com/api/stores/4420/products/00068700045059
Swagger: https://storefrontgateway.saveonfoods.com/index.html#/Products/get_api_stores__retailerStoreId__products__sku_

**Comment by berrnd** [comment] 2022-06-16 17:37
Duplicate of #158 (and #1136, and #1325, and #1376) - please check existing requests before opening new ones.

It's already possible to implement that yourself using a [BarcodeLookupPlugin](https://github.com/grocy/grocy#barcode-lookup-via-external-services).

Maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

**Closed by berrnd** 2022-06-16 17:37 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2022-06-16 17:43
Also you're provided links are not accessible (at least from here, Germany, probably something about geo blocking/restrictions).

![grafik](https://user-images.githubusercontent.com/2161815/174133034-b05cd1f4-4826-45bc-adad-c6d26b2ac6c5.png)

So even more very specific and therefore a use case for something like a companion / helper tool.
