### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by neilcamilleri** [grocy/grocy#1245] opened 2021-01-02 11:15 UTC
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

Unable to set Saturday and Sunday as Weekly due dates for a chore.

Repro:
1. Create Chore (https://grocy.url/chore/new)
2. Set 'period type' to 'weekly'
3. Attempt to check Saturday or Sunday, Friday will instead be selected

**Comment by berrnd** [comment] 2021-01-02 11:30
Duplicate of #1242, already fixed, not yet released.

Please always try to reproduce bugs on the [pre-release demo](https://demo-prerelease.grocy.info) first, thanks.

**Closed by berrnd** 2021-01-02 11:30 UTC
Labels: duplicate
