### ISSUE TITLE
Feature Request: Shopping list add to list purchase default not stock default

### ISSUE THREAD

**Issue by blindrain** [grocy/grocy#2460] opened 2024-02-08 23:54 UTC
It would be nice if the list pulled  the count and QU of the Default QU Purchase set in settings on the Shopping list page instead of the Default Stock QU  like in the next 2 pictures.   Based on all of this inf the list should say 4 boxes or just under 4 boxes because there is only 1 egg in stock. 
![list](https://github.com/grocy/grocy/assets/11042185/9ebb210c-0a42-4ac9-b24b-aa2820c1fb13)
Above is screen shot of the shopping list below is the default settings for that item. 
![settings](https://github.com/grocy/grocy/assets/11042185/66ba32b6-515e-4aa7-bae6-0049d8667afe)
Below is the QU Conversion Table. 
![QU Conversion](https://github.com/grocy/grocy/assets/11042185/e43e85f9-d7be-4520-a152-4cd7ac023a5b)

**Comment by blindrain** [comment] 2024-02-08 23:58
I Didn't mark this as a bug because it allows you to change it to make more sense.

**Comment by berrnd** [comment] 2024-02-09 07:48
Duplicate of #1355 (and #1615, and #1694, and #1980, and #2091, and #2332) - please check existing requests before opening new ones (and please also don't spam all those other threads, using reactions to express that you're also interested in something is more than enough).

**Closed by berrnd** 2024-02-09 07:48 UTC
Labels: duplicate
