### ISSUE TITLE
Feature Request: add multiple products from a single barcode

### ISSUE THREAD

**Issue by mralext20** [grocy/grocy#1910] opened 2022-06-06 07:29 UTC
some products are packaged as a multi-pack: several different types or flavors purchased as a single barcode. 

two examnples that come to mind are gatorade three flavor packs, or lays 18 / 28 / 42 chip packs.

i'd like to be able to add all of the sub products form the barcode all at once instead of one at a time.

**Comment by berrnd** [comment] 2022-06-06 07:47
Duplicate of #1421.

**Closed by berrnd** 2022-06-06 07:47 UTC
Labels: duplicate
