### ISSUE TITLE
Bug: Conversion Bottle-liter-mililiter

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1314] opened 2021-02-12 10:40 UTC
Setting:
QU 1 Bottle -> 1 Liter
QU 1 Liter -> 1000 Mililiter
QU 1 Mililiter -> 0.001 Liter

Recipe Chocolate Sauce

Milk:
0.25 Liter -> 0.25 Bottles
250 Mililiter -> 250.000 Bottles

I have created a Demo:
https://test-crf4hm3xt3at2wqkrwwfp4g0.demo.grocy.info

**Comment by berrnd** [comment] 2021-02-12 10:50
Duplicate of #1264 (and #1307) - please search existing issues before reporting.

**Closed by berrnd** 2021-02-12 10:50 UTC
Labels: duplicate
