### ISSUE TITLE
Feature Request: Multiple products per barcode, with different amounts

### ISSUE THREAD

**Issue by woju** [grocy/grocy#2244] opened 2023-05-25 19:47 UTC
So today I've encountered this thing:

![IMG_20230525_102642_066](https://github.com/grocy/grocy/assets/1550337/865a6344-5ed5-49a6-864c-48ec449b7a01)

It's a pack of three cartons, but two different juices (the middle one is orange, the two other are apple). It would be convenient (mainly for buying, probably not for consuming) if I could scan this code and it would add two different products in two different amounts.

I'll totally understand if you WONTFIX this, there are "real" barcodes inside that particular wrap, and making this relation N:M sounds like pain.

I've also thought about fixing this by recipe (to have a intermediate product of this pack which a recipewould consume and add to stock those juices), but AFAIU recipes may have only one resulting product.

**Comment by berrnd** [comment] 2023-05-25 20:26
Duplicate of #1421 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-05-25 20:26 UTC
Labels: duplicate
