### ISSUE TITLE
Chore Tracking: "done by" doesn't work

### ISSUE THREAD

**Issue by baschdl78** [grocy/grocy#1295] opened 2021-01-27 19:19 UTC
On the Chore Tracking site you can select a user differing from the locked in one in the "done by" field. If you do so the chore is not marked as done an nothing is tracked...

**Comment by adrigrillo** [comment] 2021-01-27 20:28
Check #1260 so maybe that can fix your problem.

**Comment by berrnd** [comment] 2021-01-27 20:32
Yes, duplicate of #1260, already fixed, not yet released - please check existing issues before reporting.

**Closed by berrnd** 2021-01-27 20:32 UTC
Labels: bug, ui-bug

**Comment by baschdl78** [comment] 2021-01-28 10:56
sorry! i searched for the issue but didn't find it...
