### ISSUE TITLE
Feature Request: Parent product displays its chidren

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2213] opened 2023-05-10 20:30 UTC
On product page, if this item is a parent, it will be interesting a table (on right side?) with its chidren products.
With icons for trash them and set new childrens.

**Comment by berrnd** [comment] 2023-05-10 20:32
Duplicate of #449 - please finally check existing requests before opening new ones. (!)

**Closed by berrnd** 2023-05-10 20:32 UTC
Labels: duplicate
