### ISSUE TITLE
Bug: Shopping List Last Unit Price should be in Purchase QU or Price QU

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2248] opened 2023-06-04 18:26 UTC
First of all, great work, I really like this project.

I am not sure whether this is a bug or intended behavior but seeing that the Stock Overview page shows the last price in Purchase QU, I am reporting it as a bug.

Currently, it seems that the "Last unit price" in the shopping list is using the Stock QU. However, I believe it would make more sense if this price was in Purchase/Price QU since we set those units compared to how markets define their prices. 

In Germany, most markets give their prices in Kilogram/Liter/Piece but usually, our stocks are in Gram/Milliliter/Piece so the prices in our shopping list don't make sense, or for the total prices we have to do simple math in the store when not necessary. Also, Gram and Milliliter prices end up being 0 when shown with 2 decimals places.

Grocy 3.2.2: Stock QU (Gram), Purchase QU (Kilogram)
![image](https://github.com/grocy/grocy/assets/7229627/bdd87579-0b9e-4826-baa7-1677ad4790fa)

Grocy Preview Version seems to have the same behavior.

**Comment by berrnd** [comment] 2023-06-04 18:40
> I believe it would make more sense if this price was in Purchase/Price QU
> I am reporting it as a bug.

A bug is something that reproducibly doesn't work, not something you would like to have (changed).

&nbsp;
> Grocy Preview Version seems to have the same behavior.

There is a separate unit / product option for everything related to prices, see #2225 and the [preview changelog](https://grocy.info/changelog#preview).

&nbsp;
In any case, closing this since it's not a bug. Feel free to open a separate proper Feature Requests if needed while also keeping in mind that Grocy is there to fit everyone, not your specific use case(s) - means a generic idea/description of whatever is the key.

**Closed by berrnd** 2023-06-04 18:40 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by alkuzman** [comment] 2023-06-07 05:54
I reported this issue as a bug because no matter the quantity unit I am using in the shopping list it is using the **Stock** QU price which is different behavior from the Stock Overview page. Purchase QU states that this QU will be used for showing prices which is not true in the shopping list.

![image](https://github.com/grocy/grocy/assets/7229627/f6152ab0-aa80-4e04-938c-e183a9c4f7a7)


![image](https://github.com/grocy/grocy/assets/7229627/973e4322-6717-4a8a-9c4d-5f1feb35f162)

**Comment by berrnd** [comment] 2023-06-07 06:51
> Purchase QU states that this QU will be used for showing prices which is not true in the shopping list.

Have a look at #1355. The prices on the shopping list are related the product's stock QU (as of v3.3.2) and it's nowhere stated otherwise. This also doesn't change no matter how often you call this "bug". I'm open to feature requests, but allergic to stuff you personally would like to have differently and calling this a big bug, maybe with the intention to have that done / added faster. It's really the opposite for me.
