### ISSUE TITLE
Meal Plan Incorrectly Measures Stock Amounts

### ISSUE THREAD

**Issue by seandop** [grocy/grocy#1234] opened 2020-12-30 02:21 UTC
When adding a recipe twice during the same week with differing serving amounts (Say, add the Chocolate Sauce recipe on Monday [1 serving] and again on Tuesday [5 servings]), Meal Plan will indicate that you have enough stock materials to be able to satisfy both meals regardless of whether that is actually true. Further, it will not update the proper price for the second instance either.

**Comment by berrnd** [comment] 2020-12-30 07:19
In general a duplicate of #925.

The meal plan is internally just a nested recipe per day and week and stock fulfillment is only checked on per recipe level - that's why it currently behaves like that.

**Closed by berrnd** 2020-12-30 07:19 UTC
