### ISSUE TITLE
Auth proxy support

### ISSUE THREAD

**Issue by yegle** [grocy/grocy#828] opened 2020-05-04 08:20 UTC
I took a quick look at config-dist.php and don't see anything related to auth proxy and thus this FR.

An auth proxy is an HTTP reverse proxy sits between the client and the web service. The proxy will authenticate user (e.g. requiring Google login) and only forward request when the authentication passes. This is a great way to expose your self hosted service on the public Internet while ensuring only whitelisted person can access.

See https://grafana.com/docs/grafana/latest/auth/auth-proxy/ for more context.

I'm currently using https://pomerium.io as my auth proxy but there are other similar auth proxies out there.

**Comment by berrnd** [comment] 2020-05-04 09:08
Duplicate of #627.

**Closed by berrnd** 2020-05-04 09:08 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2020-08-19 17:35
This is now done by #921 

Excerpt from the changelog:
> ### New feature: Reverse proxy authenticaton support
> - New `config.php` settings `AUTH_CLASS` and `REVERSE_PROXY_AUTH_HEADER`
> - If you set `AUTH_CLASS` to `Grocy\Middleware\ReverseProxyAuthMiddleware` and your reverse proxy sends a username in the HTTP header `REMOTE_USER` (header name can be changed by the setting `REVERSE_PROXY_AUTH_HEADER`), the user is automatically authenticated (and will also be created, if not already present)
> - (Thanks @fipwmaqzufheoxq92ebc for the initial work on this)
