### ISSUE TITLE
Bug: Issue with API field data types (specificially dates)

### ISSUE THREAD

**Issue by addd45** [grocy/grocy#1827] opened 2022-03-23 00:11 UTC
Version: 3.2.0
Running in linux server docker container

--
Apologies in advance if this is an oversight on my part. I have spent hours looking for similar issues and verifying on my end. 

The main issue is that all `Date Time` fields are not returning in a standard ISO 8601-1:2019 format. the API swagger shows that it should, but the actual call is not.

Attaching the screenshot from the swagger ui page for clarity:

example 1:
![image](https://user-images.githubusercontent.com/33461111/159596721-52805830-4c5f-4d71-9a37-3144f26e3b38.png)
![image](https://user-images.githubusercontent.com/33461111/159596794-48b31fda-44f5-496b-b531-69bb54e125bd.png)
notice how the "example" shows the correct date format. I checked the UI and nothing appears configured incorrectly. 

Further, you can see the identifier fields that are supposed to be numerical being returned as strings. Obviously these issues may seem minor but they make consuming the API a non-starter (without a bunch of custom deserializers). 

example 2:
![image](https://user-images.githubusercontent.com/33461111/159596637-751c9dd3-dd7f-433e-b925-f3da38731838.png)

Happy to provide any further detail as necessary. Should be fairly easy to recreate I think.

**Comment by berrnd** [comment] 2022-03-23 07:24
Timezones are currently (and since ever, not a problem of v3.2.0) not handled and therefore any input and output datetimes don't include any timezone information. The examples are random values generated by Swagger UI based on the data type, that doesn't say much. Duplicate of #214 and all the other referenced issues there.

> Further, you can see the identifier fields that are supposed to be numerical being returned as strings.

Also that's the case since ever, with an exception of v3.1.0 - see #1564 for any background information why that's the case if you are interested.

**Closed by berrnd** 2022-03-23 07:24 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2022-03-23 14:43
It is how it is, no timezone information handled anywhere = no timezone information provided in any field anywhere. Again, since [v.0.1.0](https://grocy.info/changelog#v0.1.0), no one had a single problem with that so far. Fun fact: The web frontend uses the API itself for everything.

> Custom date parsers are needed to convert the date string into a datetime object.

Well, any of the apps/integrations out there seem to be able to handle it just fine...

JS: `new Date("2022-03-23 00:01:32")` works
PHP: `strtotime('2022-03-23 00:01:32')` works
Python: `datetime.strptime('2022-03-23 00:01:32', '%Y-%m-%d %H:%M:%S')` works
.Net/C#: `DateTime.Parse("2022-03-23 00:01:32")` works
Java: `new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse("2022-03-23 00:01:32")` works

Sounds like a theoretical problem for me.

**Comment by addd45** [comment] 2022-03-23 15:02
> 

https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#support-for-the-iso-8601-12019-format
> Attempting to deserialize representations that don't conform to the profile will cause [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer) to throw a [JsonException](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonexception):
 
Again, timezone isn't the issue here - you can format the datetime according to standard without having a notion of the timezone.

It does seems odd that C# handles DateTime.parse() fine but the `System.Json.Net` library can't handle the same date time conversion. Seems that Deserializing json has stricter requirements on format. 

I Didn't intend on starting an argument here. Thought it would at least be a good suggestion to make the API return proper standardized formats so the onboarding process wouldn't require unnecessary boilerplate code; but it's not my code and I can't make you want to do it. 
Thanks for your time.

**Comment by addd45** [comment] 2022-03-23 16:06
Yeah, I get not wanting to make a breaking change, I do wonder how breaking it would be though if a client is using standard libraries to parse dates, but I digress... 

FWIW I just wanted to bring up the issue before going with the workaround, but fully understanding it's probably not feasible without some big refactoring and breaking changes. 

Anyway I will use the custom converter as you demonstrated above. Really appreciate you giving that example code. Microsoft documentation as usual couldn't be straightforward and I wasn't in the mood to deep dive into it :)
