### ISSUE TITLE
Feature Request: Grouping of recipes

### ISSUE THREAD

**Issue by JeffersonBledsoe** [grocy/grocy#1968] opened 2022-08-17 10:58 UTC
I've been using a userfield for a while to group my recipes. This makes meal planning a little easier (we can just look at the 'breakfast' recipes), but also allows me to use the recipe list as a 'menu' of sorts, such as being able to see which cocktails I'm able to make based on the products I have in. The products already has the concept of a group, could this be expanded to recipes?

**Comment by berrnd** [comment] 2022-08-17 11:12
Any field (built-in and Userfields) can be used for grouping, sorting and searching (the general search field above each table) in any table.

Having a filter-menu for Userfields is a duplicate of #1850, if that was the question.

Also a question-duplicate of #324 and #1126 and #1930.

**Closed by berrnd** 2022-08-17 11:12 UTC
Labels: duplicate
