### ISSUE TITLE
Feature Request: Export to Excel - Report on Spending

### ISSUE THREAD

**Issue by abideen-a** [grocy/grocy#2447] opened 2024-01-17 08:23 UTC
Hi,

I feel it would great value advantage, if we have feature to export the data like spendings.
So, it would extend the feature and allow us visualise the data and do analyses on it.
Also, by exporting the data to excel, it may serve the purpose of budget and expense tracker.

I hope, my suggestion would be considered.

Thanks
Abid

**Comment by berrnd** [comment] 2024-01-17 08:53
Duplicate of #129 (and #2165, #2043, #895, #1756, #1660) - please be so kind and do a little search beforehand.

**Closed by berrnd** 2024-01-17 08:53 UTC
Labels: duplicate
