### ISSUE TITLE
DB error migrating from 3.3.2 to 4.0.0 on docker

### ISSUE THREAD

**Issue by tmm360** [grocy/grocy#2296] opened 2023-08-05 13:09 UTC
I'm using Grocy on docker with docker. I've upgraded containers, but after upgrade several pages are not accessible.

- `http://<myaddress>/stockoverview`:
Error source:
```
/var/www/packages/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: active (View: /var/www/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /var/www/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/packages/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/packages/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/packages/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /var/www/packages/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/controllers/BaseController.php(182): Slim\Views\Blade->render()
#8 /var/www/controllers/BaseController.php(205): Grocy\Controllers\BaseController->render()
#9 /var/www/controllers/StockController.php(130): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->Overview()
#11 /var/www/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /var/www/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /var/www/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /var/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /var/www/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /var/www/app.php(109): Slim\App->run()
#30 /var/www/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.0",
        "ReleaseDate": "2023-07-29"
    },
    "php_version": "8.1.21",
    "sqlite_version": "3.41.2",
    "os": "Linux 4.14.22 #1 SMP Thu Oct 27 08:01:25 UTC 2022 Build-38 x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/115.0.0.0 Safari\/537.36"
}
```
			
And same for:
- `http://<myaddress>/purchase`
- `http://<myaddress>/transfer`
- `http://<myaddress>/inventory`
- `http://<myaddress>/products`
- and a lot of others...

**Comment by berrnd** [comment] 2023-08-05 13:19
> Grocy on docker with docker

None of the community contributed apps/tools/integrations are maintained here.

&nbsp;
Beside that, why not doing a little search beforehand (as mentioned on the issue template)? Did that for you:

Duplicate of #2284 and #2281 and #2288 - quoting myself from https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049:

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

**Closed by berrnd** 2023-08-05 13:19 UTC
Labels: duplicate
