### ISSUE TITLE
Feature Request: Chain of Chores

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1321] opened 2021-02-12 22:08 UTC
Currently, Chores are limited to daily repeats as a minimum repeat cycle. Yes, you can do chores more than once a day, but it won't be marked as overdue before.

There are certain tasks that depend on other tasks in the household, like:

- "Start a washing machine"
- *2 hours later*
- due chore "move the cloth from the washing machine into the dryer"
- *2 hours later*
- empty the dryer

And for this kind of task, it makes sense to set also an overdue time, like that the task is overdue if not completed after 1 hour - this way someone else might pick up the task since it's overdue.

**Comment by RubenKelevra** [comment] 2021-02-12 22:09
Sorry I selected the wrong category!

**Comment by berrnd** [comment] 2021-02-13 07:50
Please keep it to one topic per request (everything else is untrackable) and check existing requests before reporting.

> Chores are limited to daily repeats as a minimum repeat cycle

Duplicate of #266.

> There are certain tasks that depend on other tasks in the household

Duplicate of #339.

**Closed by berrnd** 2021-02-13 07:50 UTC
Labels: duplicate
