### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by lgnmcrules** [grocy/grocy#2326] opened 2023-08-28 11:22 UTC
Previously, Grocy tracked the date that someone did a chore the moment that they selected that they did a chore.  For example, if a chore was overdue and was due for once per week, but had not been done for 2 weeks, (like clean the bathroom,) then someone did that chore and marked it as done, then that chore would still be marked overdue as that chore had only been said to have been done 2 weeks ago rather than today.  

This feature used to be in Grocy, and I'm not sure why this was removed.

I do not want to use due date rollover as it doesn't show when a chore was really meant to be done unless meticulously checking.

**Comment by berrnd** [comment] 2023-08-28 12:56
Nothing was removed, just how buttons work on [/choresoverview](https://demo.grocy.info/choresoverview) was optimized, please simply check [the changelog](https://grocy.info/changelog#v4.0.0) and existing requests before opening new ones - duplicate of #2311 (and #2313).

Related changelog excerpt:

_Changed the handling of the tracking buttons on the chores overview page_
- _The green button now tracks an execution of the corresponding chore on the next scheduled time, rather than for now/today_
- _New context-/more menu option "Track chore execution now" to track an execution for now/today (so the same what the green button did before)_

**Closed by berrnd** 2023-08-28 12:56 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2024-01-06 20:14
Follow-up: #2424 was created to track adding some configuration options to make possible what was mentioned here.

**Comment by berrnd** [comment] 2025-01-14 18:49
There is now this new settings (chores settings / top right corner settings menu) to swap the "Track next chore schedule" / "Track chore execution now" buttons/menu items on the chores overview page:

![grafik](https://github.com/user-attachments/assets/b8e2846d-c0f5-4f14-9bd1-d709014e8aec)
