### ISSUE TITLE
Grocy.ActiveNav is not available since 4.0.0

### ISSUE THREAD

**Issue by regystro** [grocy/grocy#2289] opened 2023-08-02 10:46 UTC
Hi.

Since 4.0.0, Grocy.ActiveNav is not available. You can check with browser console. All custom scripts (custom_js.html) using e.g. `if (Grocy.ActiveNav == "shoppinglist")` no longer work unless you skip the condition.

I checked the release notes and nothing about that is mentioned. Therefore I guess is a bug.

Thank you.

**Comment by berrnd** [comment] 2023-08-02 11:07
> I checked the release notes and nothing about that is mentioned. Therefore I guess is a bug.

Everything related to [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) is nowhere stated to be a "public API" (and therefore nothing about that will be part of any release notes). So no, that's definitely not a bug. Beside that, on a major release each and every custom integration/tool/whatever can break / need adaptations to whatever changed.

Simply have a look at what's there and (most likely) use `Grocy.View` from now on.

**Closed by berrnd** 2023-08-02 11:07 UTC
Labels: invalid/unreproducible/missing-feedback

**Comment by regystro** [comment] 2023-08-02 11:21
Thanks, already working. I'm glad anyone having trouble and searching for Grocy.ActiveNav in this issue tracker will find my post and your explanation. We'll save them the "nowhere to be found" ;)

**Comment by berrnd** [comment] 2023-08-02 11:26
> anyone having trouble and searching for Grocy.ActiveNav in this issue tracker will find my post and your explanation. We'll save them the "nowhere to be found" ;)

Great idea, most likely won't happen practically - look at all the recent reports, nobody on this planet is using the search functionality.

**Comment by hklages** [comment] 2023-08-24 11:45
Thanks for having that documented here - I was also struggling.
