### ISSUE TITLE
Feature Request: Option to add all items on shopping list to inventory

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#98] opened 2018-10-26 12:01 UTC
It would be great to have an option to add all items currently on the shopping list to the inventory. This could be either an individual button or when clicking on "clear list" the option could popup to ask if all items shall be added.

Very handy would also be a button next to the edit end delete button (is the edit button actually necessary?) - when clicking on it, it would delete the item from the shopping list and add it to the inventory.

**Comment by berrnd** [comment] 2018-10-26 15:33
Great idea, but somewhere inbetween there must be the question for best before date and price (as on the purchase page)...

> is the edit button actually necessary?

You can edit the amount or a note of the shopping list line - if you never need this, you can also always hide everything not needed with [custom CSS](https://github.com/berrnd/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)...

**Comment by Forceu** [comment] 2018-10-28 12:02
Thanks for your reply! I don't mind the edit button, I just don't really use it.

You could use the default expiry dates when adding all ingredients. Otherwise I think the best option would be to have an "Add" button next to the other two which brings you to the purchase form with the item and the quantity filled out already. Once added it should then delete the item from the shopping list.

**Comment by recklessnl** [comment] 2018-11-14 08:57
I second this request, it would really help making this more useful and faster. Prepare the shopping list and when you come back and are finished, press a button to instantly add everything to the inventory. @berrnd any idea if this will be in a release in the near future?

**Comment by berrnd** [comment] 2018-11-14 09:17
Thanks for your input, will of course work on this anytime soon - it's just not 100% clear for me how to do it best.

On the purchase "booking" page currently it is asked for the best before date and the price - best before date is prefilled when there is a default for the product and the price is optional and prefilled with the last one.

So my idea so far is to show a editable table with all shopping list items (popup) and inputs for best before date and price per line, which will be prefilled with the same defaults as now. That's just a little bit complex from the UI side...

**Comment by berrnd** [comment] 2018-11-14 20:42
Great idea, did that, you can give it a try on the [pre-release demo](https://demo-prerelease.grocy.info/shoppinglist) if you want. :)

**Comment by recklessnl** [comment] 2018-11-14 21:11
> Great idea, did that, you can give it a try on the [pre-release demo](https://demo-prerelease.grocy.info/shoppinglist) if you want. :)

Much better! Could you now add a master-button that does the same thing instantly for all the items on the shopping list? This would be fantastic for when you actually bought all the items on the list and come back from the store!

**Comment by berrnd** [comment] 2018-11-15 07:35
> EDIT: I also think there should be a defualt value for BEST BEFORE value. 

That's already possible - see the "Default best before days" field on the product edit page, this will be used to prefill the best before on the purchase page - [pre-release demo with product "Milk"](https://demo-prerelease.grocy.info/purchase?flow=shoppinglistitemtostock&product=23&amount=1&listitemid=9).

**Comment by berrnd** [comment] 2018-11-17 07:13
> Yes, that looks great! However the "OK and back to shoppinglist" button only works if a default date is set for the product. Even when entering a date manually, it is still inactive.

Yes, price is optional - seems that this only is a (general) problem when using the datetimepicker (will be tracked in #108), could not reproduce this when manually entering a date:

![2018-11-17_08-09-07](https://user-images.githubusercontent.com/2161815/48658354-a01f1c00-ea40-11e8-9eb9-161f8f41473b.gif)

**Closed** 2018-11-17 14:01 UTC
Labels: enhancement

**Comment by berrnd** [comment] 2018-11-17 14:05
I finished this now in the following way:
- The button per shopping list item prefills all fields on the purchase page as before, but the page is now shown in a popup
- New "master button" next to the headline which does this for all shopping list items, one by one - the next item is loaded after each booking
  - So when all products have a default best before date, you could just go through all items by clicking OK or pressing enter (I think it's good to be able to review what will get booked or to change the price or best before date)

Let the know if this works for you all or if you have other suggestions, can still be tested on [the pre-release demo](https://demo-prerelease.grocy.info/shoppinglist) (will prepare a new release tomorrow).

**Comment by recklessnl** [comment] 2018-11-21 01:16
You're making great progress with this, thanks @berrnd. My only comment is that there should still be an option to not have the pop-ups appear. Maybe it could be toggable, or maybe the popups will ONLY appear when you don't have a standard pre-set value for best-before.

Just to explain: let's say I use Grocy to prepare the shopping list of today. Part of why Grocy is so great is because it can help auto-fill the shopping list, based on which recipes I want to eat this week (so it will check stock and then add the items for the recipe if it's not in stock). Then if I do my shopping, I come back and have bought everything I needed, I should be able to just press one button to add everything to stock, and that should be the end of it. Imagine your girl using this - instead of pressing OK or NEXT for 10 to 15 times, it should just be added automatically. Then afterwards, you should be able to make edits when necessary, but in daily use this just shouldn't be necessary.

At the very least this should be an option, so that users don't have to click through 10 pop-ups every time they come back from shopping. It's just too cumbersome and defeats the purpose of the app to make grocery shopping faster and efficient.

**Comment by berrnd** [comment] 2018-11-21 06:59
I fully understand that, will be tracked in #110 and #111.

**Comment by berrnd** [comment] 2018-11-21 18:14
The "one click shopping list to stock"-thing is now done like this:

There is a new option to enable this under: Settings icon in the top right corner -> "Stock settings" (defaults to disabled).

If it's enabled, the popup just automatically closes directly after everything is prefilled.
When adding all items, it would stop when there is a product without "Default best before days" set.

You can have a look in the [pre-release demo](https://demo-prerelease.grocy.info/shoppinglist) ("Paprika", "Cucumber" and "Tomato" have "Default best before days" set) if this now works for you better. :)

![2018-11-21_19-11-53](https://user-images.githubusercontent.com/2161815/48860542-7a3ba380-edc1-11e8-80f6-753705acf1b3.gif)

**Comment by Forceu** [comment] 2018-11-23 06:50
Perfect, thank you so much for that! Certainly makes shopping a lot easier now :)

**Comment by krodis3** [comment] 2025-07-03 14:48
For clarity, to utilize this feature you must have the "default due days" set for every item in the shopping list and you must
enable the "Shopping list to stock workflow" setting located under the settings icon in the top right corner -> "Shopping List Settings" -> "Shopping list to stock workflow"

**Comment by berrnd** [comment] 2025-07-03 15:13
> For clarity, to utilize this feature you must have the "default due days" set for every item in the shopping list and you must
enable the "Shopping list to stock workflow" setting located under the settings icon in the top right corner -> "Shopping List Settings" -> "Shopping list to stock workflow"

Only if you want to have defaults for everything. If the due date or the price is different this time that won't work and therefore such a general recommendation without mentioning that is, sorry, bullshit.

**Comment by krodis3** [comment] 2025-07-03 15:26
> > For clarity, to utilize this feature you must have the "default due days" set for every item in the shopping list and you must
> > enable the "Shopping list to stock workflow" setting located under the settings icon in the top right corner -> "Shopping List Settings" -> "Shopping list to stock workflow"
> 
> Only if you want to have defaults for everything. If the due date or the price is different this time that won't work and therefore such a general recommendation without mentioning that is, sorry, bullshit.

Correct, this is just the way I've elected to use the feature.

The purpose of my comment was to communicate that the option to enable the one click feature is located under settings icon in the top right corner -> "Shopping List Settings" -> "Shopping list to stock workflow"; not the stock settings. Apologies.
