### ISSUE TITLE
Feature Request: Randomize Mealplans

### ISSUE THREAD

**Issue by PaganRedCat** [grocy/grocy#1894] opened 2022-05-21 03:10 UTC
grocy on windows

I am a terrible undesive person if it comes to "what to eat". 
My idea would be that i can toggle a button in the meal planner and grocy just fills some recepies for dinner for a week in so i dont have to think again. Also nice if grocy will fill it in with the dishes i didnt eat for a period of time. 
If it was mentioned somewhere else i am sorry, merge then.

**Comment by berrnd** [comment] 2022-05-21 06:18
Duplicate of #553 and #1028.

**Closed by berrnd** 2022-05-21 06:18 UTC
Labels: duplicate
