### ISSUE TITLE
Feature Request: API integration for store products etc

### ISSUE THREAD

**Issue by Pseudo752** [grocy/grocy#2506] opened 2024-03-21 15:58 UTC
I would find it useful for people to be able to integrate Grocery store or any stores product API into the program so people could maybe search products or find the exact product with real time pricing etc

**Comment by berrnd** [comment] 2024-03-21 16:53
Duplicate of #2407 and all the other mentioned existing requests there - please do a little tiny search beforehand.

**Closed by berrnd** 2024-03-21 16:53 UTC
Labels: invalid/unreproducible/missing-feedback
