### ISSUE TITLE
"Speichern" (Save) should save a task but not close the popup

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1775] opened 2022-02-06 15:30 UTC
There are two usability improvements I like to make:

- The save button should be on the lower right, while close should be on the lower left. Otherwise, you break the UX convention of having the default action on the right side. See [Designing for Action: Best Practices for Effective Buttons](https://balsamiq.com/learn/articles/button-design-best-practices/)
- A "save" shouldn't close the popup, but instead, just save it (make a toast output) and clear the form. This allows adding more than one task faster.

![Overview task](https://user-images.githubusercontent.com/614929/152688255-43d1827f-9a5e-47e4-9bba-f83817526c73.png)

**Comment by berrnd** [comment] 2022-02-06 16:01
> There are two usability improvements

You mention "improvements" and label it as `bug` - well, cool.

> The save button should be on the lower right, while close should be on the lower left. Otherwise, you break the UX convention of having the default action on the right side. See [Designing for Action: Best Practices for Effective Buttons](https://balsamiq.com/learn/articles/button-design-best-practices/)

It's the same for any form. grocy is about efficiency and consistency and not about blindly following any random best practice guides. Basically a duplicate of #1367.

> A "save" shouldn't close the popup, but instead, just save it (make a toast output) and clear the form. This allows adding more than one task faster.

Well, probably a good idea. I've moved that to a properly labeled and single-topic (since everything else is untrackable) ticket: => #1776

**Closed by berrnd** 2022-02-06 16:01 UTC
Labels: duplicate, invalid
