### ISSUE TITLE
Mealplan page crashes: Cannot read property 'isEmpty

### ISSUE THREAD

**Issue by freakshock88** [grocy/grocy#873] opened 2020-05-28 20:06 UTC
When I open the mealplan page, I can only see the title of the page and nothing else. The following error shows up in the browser console:

mealplan.js?v=2.7.1:10 Uncaught TypeError: Cannot read property 'isEmpty' of undefined
    at mealplan.js?v=2.7.1:10

I tried using a default config file, same problem. 
Im using the latest version of the linuxserver docker container.
Any clue what's going on here?

**Comment by berrnd** [comment] 2020-05-29 07:28
According to the code reference:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/public/viewjs/mealplan.js#L10

This is probably something about the `config.php` setting `MEAL_PLAN_FIRST_DAY_OF_WEEK` and/or `CALENDAR_FIRST_DAY_OF_WEEK` - how are they set?

**Comment by freakshock88** [comment] 2020-05-29 07:32
Well that's the thing. To debug I deleted my config.php file and restarted grocy. It then generated a default config.php file. The same error occurred, so it shouldn't be caused by the config?

**Comment by berrnd** [comment] 2020-05-29 07:45
As it's only about that config setting at that point (`Grocy.MealPlanFirstDayOfWeek` seems to be `undefined`), I would say that could be the only cause. I'll try to reproduce this, have not noticed that so far with the default `config.php` settings...

**Comment by freakshock88** [comment] 2020-05-29 11:03
Yes that seems to be the problem.

I i change the default config.php settings to either 
`Setting('CALENDAR_FIRST_DAY_OF_WEEK', 1);`
and/or
`Setting('MEAL_PLAN_FIRST_DAY_OF_WEEK', 1);`

The same error still occurs.

The regular calendar works however.

**Comment by freakshock88** [comment] 2020-05-29 12:02
I think it might have something to do with the state of my database.
I spinned up a second docker container, this one has no problems.
I did do some manual editing in the DB.. now what could it be :(

**Comment by berrnd** [comment] 2020-05-29 19:12
If it's ok for you, feel free to send me the database and I'll have a lock at that exact/reproducible state (see https://berrnd.de for any contact information).

**Comment by freakshock88** [comment] 2020-05-30 14:51
Thanks, I sent you an email with the DB!

**Comment by berrnd** [comment] 2020-08-18 15:40
Closing this for now.

Was also not really reproducible with the database which was sent to me...

**Closed by berrnd** 2020-08-18 15:40 UTC
Labels: question
