### ISSUE TITLE
Feature request: Link Grocy to Open Food Facts the free food product database.

### ISSUE THREAD

**Issue by Sjack-Sch** [grocy/grocy#1376] opened 2021-02-21 21:42 UTC
Entering product master data for new products could be faster when the master data is copied/imported from https://world.openfoodfacts.org.
Openfoodfacts provides a simple API with the EAN-13 code as part of the URL and results the product-data in JSON.
for example [https://world.openfoodfacts.org/api/v0/product/5410228201205.json]

**Comment by berrnd** [comment] 2021-02-21 22:02
Duplicate of #158 (and #1136, and #1325) - please check existing requests before opening new ones.

It's already possible to implement that yourself using a [BarcodeLookupPlugin](https://github.com/grocy/grocy#barcode-lookup-via-external-services).

Maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

**Closed by berrnd** 2021-02-21 22:02 UTC
Labels: duplicate
