### ISSUE TITLE
Bug: Meal plan: Enough in stock does not calculate for consumption before the planned meal

### ISSUE THREAD

**Issue by OhlH** [grocy/grocy#2174] opened 2023-03-19 20:49 UTC
Using meal plans is great but if I plan a week, the meal plan stock calculation does not respect the consumption of the ingredients during the week. E. g. if I plan Spaghetti on Tuesday _and_ Friday, assuming one minced meat is left from the weekend: my minced meat is marked as "enough in stock" for **both days**, but it will be gone after my dinner on Tuesday. To prevent multiple shopping rounds per week I need to buy one minced meat, even though I have "enough in stock" for both meals.
![minced meat](https://user-images.githubusercontent.com/50629098/226208073-93f4cb52-0d63-4636-ad2e-d73c30949d91.png)

**Comment by berrnd** [comment] 2023-03-19 22:21
Not a bug, but a feature request - a duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789, #1965, #2020 - please search existing requests first).

&nbsp;
Technical background why it is how it currently is, if you're interested:

https://github.com/grocy/grocy/issues/840#issuecomment-626286880:
> Currently the missing amount is only checked on per recipe level, so when 1 pack is already on the shopping list, that's already fulfilled for the second recipe...

https://github.com/grocy/grocy/issues/925#issuecomment-662279863:
> The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

**Closed by berrnd** 2023-03-19 22:21 UTC
Labels: duplicate
