### ISSUE TITLE
Feature Request: Relate Product Groups to Stores and Generate List by Store

### ISSUE THREAD

**Issue by skinnerstein** [grocy/grocy#2054] opened 2022-11-29 14:59 UTC
Please add the ability to create a relationship between a product group and one or more stores. For example, the product group Vegetables would be associated to all grocery stores, while the product group Hardware would be associated to home improvement stores.

Then, add the ability in the shopping list area to create a list by store. Then, for example, if I'm planning a trip to Kroger I could create a Kroger list and it would include things like celery and potatoes based on that association, but would not include things like nails and lumber, as those would be associated to home improvement stores.

**Comment by berrnd** [comment] 2022-11-29 18:34
Duplicate of #612.

**Closed by berrnd** 2022-11-29 18:34 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2022-11-29 18:36
Also related to #1357.
