### ISSUE TITLE
Bug: same meals with the same missing ingredients wont double the ingredients on the shopping list

### ISSUE THREAD

**Issue by Bontah** [grocy/grocy#1965] opened 2022-08-11 12:58 UTC
Adding the same meal wont let me add the missing products twice. I tried this with the current demo and the Pancakes recipe.
There was one Egg in stock and 3 are missing. The shoppinglist button (for a single meal) added 3 eggs to the shopping list. now the same week  and another day, again pancakes but this time 4 eggs are missing. the shoppinglist button added 4 eggs this time. the next day and same week, again the same recipe but now it didn't let me add anything at all to the shopping list.

creating a shopping list for the entire week based on missing ingredients is not possible with this behavior

**Comment by berrnd** [comment] 2022-08-11 13:21
> creating a shopping list for the entire week based on missing ingredients is not possible with this behavior

It is, when using the button in the header (which adds missing ingredients for the whole week).

And not a bug, but a feature request - a duplicate of #840 (and #402, #1622, #1621, #925, #1848, #1789 - please search existing requests first).

&nbsp;
Technical background why it is how it currently is, if you're interested:

https://github.com/grocy/grocy/issues/840#issuecomment-626286880:
> Currently the missing amount is only checked on per recipe level, so when 1 pack is already on the shopping list, that's already fulfilled for the second recipe...

https://github.com/grocy/grocy/issues/925#issuecomment-662279863:
> The meal plan is internally also a recipe per day and week which just has the added other recipes/products as included recipes/ingredients - this is why the "per recipe check" also applies here. But if you use the "Add to shopping list"-button in the header, this would add all summarized amounts for the whole week onto the shopping list.

**Closed by berrnd** 2022-08-11 13:21 UTC
Labels: duplicate
