### ISSUE TITLE
Not repeating the recipe in the meal plan quest: 

### ISSUE THREAD

**Issue by nuovo10** [grocy/grocy#1575] opened 2021-08-12 10:11 UTC
It would be possible to add an option on the meal plan page, that if the recipe is previously set, it cannot be put back. Also have a list of recipes placed in the meal plan.
I propose this option to know what foods have been put previously and not repeat it.

**Comment by berrnd** [comment] 2021-08-12 10:49
So you want to be able to add a recipe once, and then never again? Or Once per week?

> Also have a list of recipes placed in the meal plan.

The list is basically the meal plan itself...

**Comment by nuovo10** [comment] 2021-08-12 13:53
"google translate"

First, thank you for answering my question.

I try to explain my idea. We all usually have a list of foods separated by type (meat, fish, vegetables, etc.) that is usually repeated after X weeks. You can call this list "the basic food list".

The idea is to be able to distribute the meals weekly until the basic list is finished (there would always be the option of being able to repeat the meal, for example, eliminating it from the "already configured previously" list).

I now explain how I am trying to organize it with an excell.
I have lists by type of food (meat, fish, vegetables). I have a section where I choose the meals that I am going to put in the week (3 meals of meats, 2 of fish, 2 vegetables) and I redistribute it in that week.

 For the next week I do the same. I choose the meals that I am going to put in the week (3 meals of meats, 2 of fish, 2 vegetables). This week does not allow me to choose the one from last week unless in the main list I remove a check. Once the meals have been chosen, to redistribute in that week.

And so successively. The idea is to try to eat a variety of food.

**Comment by berrnd** [comment] 2021-08-12 14:20
So a kind of "meal plan by rules" system in general - that's already covered in #553 and #310, feel free to add your ideas there, closing this as a duplicate.

**Closed as completed by berrnd** 2021-08-12 14:20 UTC
Labels: duplicate

**Comment by nuovo10** [comment] 2021-08-12 16:20
Thank you, I hope you implement it.

**Comment by nuovo10** [comment] 2023-05-16 08:59
Hello,
I hope you implement it.

**Comment by berrnd** [comment] 2023-05-16 09:12
This is still a duplicate of https://github.com/grocy/grocy/issues/553 and https://github.com/grocy/grocy/issues/310 as mentioned above.

Please use a simple 👍 reaction to express that you're also interested instead of spamming threads, thanks.
