### ISSUE TITLE
Option to add meal to mealplan without picking from recpies

### ISSUE THREAD

**Issue by skorvek** [grocy/grocy#2024] opened 2022-10-16 23:37 UTC
I don’t think i will use the recipe function much. Even if I do I know how to cook and don’t often follow a specific recipe. I just cook with what I have and I adapt as I go using known techniques.

Therefore, I would like to be able to list a meal in the mealplan without tying it to a detailed recipe. Ad it stands- say I wanted to create a meal for Monday called “swordfish.” I know I have the item, I know it is in the fridge and I know I need to use it in this week. I don’t need to decide exactly the recipe or all of the ingredients ahead of time.

Yet if I want to decided on a meal of swordfish with cherry peppers, arugula, and corona beans, I cannot just put those are free text items on the mealplan. I need to create a recipe for each (with nothing in the recipe) to be able to list them in the plan. So I might as well just put them on the kitchen whiteboard.

And the meal plan never goes as designed. Let me move things around days of week. I consume as I go, so I can remove items from stock when I adapt a recipe to what I actually have.

**Comment by berrnd** [comment] 2022-10-17 06:14
> I need to create a recipe for each (with nothing in the recipe) to be able to list them in the plan.

Not true, it's possible to add recipes, products and arbitrary free text ("Note") (since [v2.6.0](https://grocy.info/changelog#v2.6.0), so since almost 3 years) to the meal plan - so just use a note.

![grafik](https://user-images.githubusercontent.com/2161815/196101928-e3a1365e-4428-4dea-a75a-fed9609ba0fb.png)

Duplicate of #477.

**Closed by berrnd** 2022-10-17 06:14 UTC
Labels: duplicate

**Comment by skorvek** [comment] 2022-10-17 10:58
Thanks- missed the little down arrow on my tablet. Not easy to hit.
