### ISSUE TITLE
Unable to add barcode while editing product

### ISSUE THREAD

**Issue by kk7ds** [grocy/grocy#1219] opened 2020-12-24 19:41 UTC
I cannot add a barcode to a product itself, I can only add it during inventory or purchase with "add to existing product."

Steps:
1. Create a product
2. Go to the "barcodes" section of the product, click "Add"
3. New barcode dialog appears, click the camera button in the barcode field
4. Camera appears, scan the barcode
5. Camera disappears, nothing is in the barcode field

I've tried this on Chrome and Firefox on Android, and Firefox 84 on MacOS. On the latter, I had the JS console open during the whole process, but see nothing relevant (like an error message). It seems to me like it's just not taking the result of the barcode scan and putting it into the field. If I do this during a purchase workflow, I can scan the barcode, it shows it to me and lets me add it to an existing product. That works, but I want to go add barcodes of my existing stock so that the next purchase goes easily.

**Comment by berrnd** [comment] 2020-12-24 22:03
Duplicate of #1210, already fixed, not yet release - please search existing issues and/or try to reproduce the problem on the [pre-release demo](https://demo-prerelease.grocy.info) first.

**Closed by berrnd** 2020-12-24 22:03 UTC

**Comment by kk7ds** [comment] 2020-12-24 22:06
Thanks, I did search, but a few days ago and only today got around to reporting it, so I missed the other issue from only a couple days ago.
