### ISSUE TITLE
Bug: Calendar error on pre-release

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2234] opened 2023-05-17 19:34 UTC
**When I click on https://en.demo-prerelease.grocy.info/calendar:**

Error source:
```
/var/www/demo-prerelease.grocy.info/services/TasksService.php:7
```

Error message:
```
syntax error, unexpected token "class", expecting "," or ";"
```

Stack trace:
```
#0 /var/www/demo-prerelease.grocy.info/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#1 /var/www/demo-prerelease.grocy.info/services/BaseService.php(57): Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/demo-prerelease.grocy.info/services/CalendarService.php(43): Grocy\Services\BaseService->getTasksService()
#3 /var/www/demo-prerelease.grocy.info/controllers/CalendarController.php(13): Grocy\Services\CalendarService->GetEvents()
#4 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\CalendarController->Overview()
#5 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#7 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#8 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /var/www/demo-prerelease.grocy.info/middleware/AuthMiddleware.php(48): Slim\Routing\RouteRunner->handle()
#11 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#12 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#14 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#16 /var/www/demo-prerelease.grocy.info/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#18 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#20 /var/www/demo-prerelease.grocy.info/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#21 /var/www/demo-prerelease.grocy.info/app.php(106): Slim\App->run()
#22 /var/www/demo-prerelease.grocy.info/public/index.php(45): require_once('...')
#23 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "pre-release-629333e1",
        "ReleaseDate": "2023-05-14 17:05:28"
    },
    "php_version": "8.1.18",
    "sqlite_version": "3.34.1",
    "os": "Linux 5.15.107-1-pve #1 SMP PVE 5.15.107-1 (2023-04-20T10:05Z) x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/113.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment] 2023-05-17 19:40
Just a general side note, not specifically for this one:

The [pre-release demo](https://demo-prerelease.grocy.info) is the current development state and there can be times where unfinished work was committed, which is not really worth it be reported as a bug.

**Comment by berrnd** [comment] 2023-05-17 19:50
Turns out: Duplicate of #2230 (already fixed, merged just some minutes ago).

So another side note:

The [pre-release demo](https://demo-prerelease.grocy.info) is reloaded / pulls the `master` branch from GitHub 10 minutes past every hour ([README ref](https://github.com/grocy/grocy#localization))

This was committed at 21:04 CEST, so it's normally live at 21:10 CEST. Sometimes GitHub has some hickups, like now (at least here), that's why the pull at 21:10 CEST failed. Not a big problem, since it's then just done again one hour later, like every hour. Concludes to: Sometimes just some patience is needed. Spin up your own development environment if you need instant preview of localizations or whatever.

**Closed by berrnd** 2023-05-17 19:50 UTC
Labels: duplicate
