### ISSUE TITLE
Feature Request: Optimized Shopping - Default Shopping List in Product - Sortorder of Categories

### ISSUE THREAD

**Issue by sebmuc99** [grocy/grocy#1688] opened 2021-11-16 15:37 UTC
Hello together, 

just started to use grocy but i'm really unhappy about my shopping process. 
Usually i go to my preferred Store and buy the Items from my Shopping list. 

I created for each Store an separate Shopping-Lists but now i miss two functions:

1. It would be awesome to have a defined Shopping List in the Productmasterdata so when i use the Button "Add products below min Stock" automatically added to the correct Shopping List. 

2. It would be perfect to be able to have a defined sortorder into Productgroups Data that i can order the Groups on my Shoppinglist like they appear in the store (of course possible with an description workaround but would be more comfortable to have it seperated.

Anyone else with these needs?

**Comment by berrnd** [comment] 2021-11-16 16:26
> 1. It would be awesome to have a defined Shopping List in the Productmasterdata so when i use the Button "Add products below min Stock" automatically added to the correct Shopping List.

Duplicate of #1357.

> 2. It would be perfect to be able to have a defined sortorder into Productgroups Data that i can order the Groups on my Shoppinglist like they appear in the store (of course possible with an description workaround but would be more comfortable to have it seperated.)

Product groups are meant for that and [the demo](https://demo.grocy.info/shoppinglist) shopping utilizes this for such an example - that "description workaround" works, so don't know why not to use it by that manner. Alternatively create a product Userfield, show that on the shopping list, group/sort the list by that field.

**Closed by berrnd** 2021-11-16 16:26 UTC
Labels: duplicate, question
