### ISSUE TITLE
Bug: Consume product api issue with Parent products

### ISSUE THREAD

**Issue by Robjgt** [grocy/grocy#1767] opened 2022-01-30 23:33 UTC
Consuming an item from a parent product from the gui either decreases the parent product amount by the consume amount or, if this is or becomes zero, it will decrease the parents sub product items to bring the product total into balance, this consume event works a treat.
However attempting to do the same using the consume api call meets with failure when the parent product has less than consume amount.
It appears that the api call is unable to trigger the consumption of parent/sub products in the same way the gui consume operates.
If a parent product has been created and is used to accumulate the total quantities of sub products and its own total remains 0 it appears that the consume api call will fail when targeting this type of parent item.

**Comment by berrnd** [comment] 2022-01-31 07:32
> It appears that the api call is unable to trigger the consumption of parent/sub products in the same way the gui consume operates

Can't be the case for anything, since the UI uses the API for everything.

The [`/stock/products/{productId}/consume`](https://demo.grocy.info/api#/Stock/post_stock_products__productId__consume) endpoint has an optional request body parameter `allow_subproduct_substitution`:
&nbsp;
![grafik](https://user-images.githubusercontent.com/2161815/147953760-7bd0a8c3-c6fa-4735-9b8d-0b7e65ccef5c.png)

A very simple way to check what the UI does exactly is to use e.g. your browsers developer tools.

Also a duplicate of #1731.

**Closed by berrnd** 2022-01-31 07:32 UTC
Labels: invalid
