### ISSUE TITLE
Feature Request: Use different domains of quantity units for simplifying conversions

### ISSUE THREAD

**Issue by z0rgster** [grocy/grocy#1960] opened 2022-07-26 20:55 UTC
This topic is related to #1360, but I think this is a more general approach and worth it's own issue.

I want to suggest to introduce a concept of different unit domains: `weight units`, `volume units` and `other units`

`Weight units` would be: mg, g, kg, oz, lb, stone, tons, ...

`Volume units` would be: mL, L, floz, US-Cups, UK-Cups, pints, gallons, ...

`Other units` would be: piece, pack, glass, jar, can, tray, bunch, .... (everything that does not have a defined volume or weight)

Conversions **inside** the `weight` and `volume` domain can be defined **globally** and *should not be necessary per product*. Maybe these can even be **predefined** (finally!) as they will always be the same. Users could have the possibility to edit them like every other unit though if they want to account for the exact volume of **their** specific tea-/tablespoons. Global conversions inside the `other units` **could** be predefined but I can't think of many general examples here. Counting units like a *dozen* could be a thing. I think that should be up to the user though.

Conversions **between the domains** should always be made **per product** as they are tied to the specfic physical properties of the product. The user would just have to enter an example conversion between `weight` and `volume` and call it a day. That could be done in the main fields when creating the product. The unit conversion section of the product would then be used for conversions to and from `other units` and overriding conversions between `volume` and `weight`. That would be the case if a user notices that a tablespoon has a nominal volume of 15 mL but when scooping sugar with it a larger volume of 20 mL or a larger mass than the equivalent of 15 mL sugar is measured.
Another idea (but this might be a little over the top) would be to add different `weight` to `volume` conversions depending on a definable `state` of the product. Liquified butter has another density than solid butter for example.

Regarding the **creation process of a new quantity unit**, the user would have to set the domain per dropdown. Not sure if it is necessary to introduce more that the three suggested domains. That's probybly a topic for dicussion.
Regarding the **migration process of older versions** without this concept I would suggest to make all existing quantity units `other units` and allow the user to change the domain unit by unit. Redundant per-product conversions should then be checked and removed in this step.

**Comment by berrnd** [comment] 2022-07-26 21:17
This would change nothing about how unit conversions need to be done technically and not solve #1360, it's rather completely unrelated to that. But it would make entering unit conversions a lot more complex as it already is right now.

You can already define global or product specific or both conversions. I don't really see the point to restrict the product specific conversions to a group of QUs you call "other units".

A big part of what you want seems to be predefined conversions: Duplicate of #912.
The world is not standardized.

If you want to give quantity units that category/group/whatever you call it, use Userfields.

&nbsp;
> The user would just have to enter an example conversion between weight and volume and call it a day. 

If it's a global/general conversion, create the global conversion between the QUs.
If it's a product specific conversion, because product specific properties need to be taken into account, a product specific conversion is necessary.
That is and will always be the same in the very end.

**Closed by berrnd** 2022-07-26 21:17 UTC
Labels: wontfix/out-of-scope
