### ISSUE TITLE
Bug: stock entries: dropdown-menu hidden, and can't clear filter

### ISSUE THREAD

**Issue by afv** [grocy/grocy#1129] opened 2020-11-15 12:37 UTC
Hi @berrnd,

Lots of commits in the last days! Thanks! 😀 (the feature of having quantities and locations related with a barcode will be very useful)

I'm opening this issue as I noticed that at the stock entries page, when the table is small, the menu does not show fully:

![image](https://user-images.githubusercontent.com/1532245/99184955-a420ca00-273e-11eb-82d3-bf4e973a7198.png)

Also, when clearing the filter I was expecting to see the full stock entries list, but it expects a product:

![image](https://user-images.githubusercontent.com/1532245/99184970-bef33e80-273e-11eb-91d0-8cde93669e00.png)

Kind regards

**Comment by berrnd** [comment] 2020-11-15 13:47
Thanks for testing.

That the dropdown menu is now hidden when the table is too small was already fixed in https://github.com/grocy/grocy/commit/b15740bdede5a799bcf89d11433184554e46a663 for all other pages, somehow I missed the stock entries page (was caused by that the tables are now horizontally scrollable on small screens, instead of hiding columns behind that "+" icon).

The same goes for the clear filter button, which we have now on all pages + proper mobile view (collapsed filter).

Both is fixed in the commits referenced below (just manually clearing the product picker field is also possible).

**Closed** 2020-11-15 13:49 UTC
Labels: ui-bug
