### ISSUE TITLE
Feature Request: Ability to add Ingredient groups to recipe rather than specific ingredient

### ISSUE THREAD

**Issue by SamKemp** [grocy/grocy#1869] opened 2022-04-22 11:19 UTC
When creating a recipe it would be really useful to be able to sometimes add more of a generic category rather than a specific product and then when you go to select the recipe as made/consume ingredients it asks which one from the category you used.

For example, making a pasta dish and the type of pasta really doesn't make a difference, however, I still want them all stock managed separately

**Comment by berrnd** [comment] 2022-04-22 11:25
Already kind of possible by using parent/child products.
Generic "Pasta" parent products, specific "xy Pasta" child product, use the parent product as a recipe ingredient.

For the rest a duplicate of #385 and #548.

**Closed by berrnd** 2022-04-22 11:25 UTC
Labels: duplicate
