### ISSUE TITLE
Feature Request: Medicine cabinet

### ISSUE THREAD

**Issue by zunami** [grocy/grocy#2229] opened 2023-05-16 18:44 UTC
### I would like to have a medicine cabinet for Grocy.
**The goal is to manage the medicines you have at home, with a personal filter.**

- Personal filter: When creating a medicine, you can enter users who are allowed to take it and those who are not allowed to take it. Not allowed to take because of age or allergies.
- Medication package insert, save information
- Categories for a better search e.g. headache, fever, allergy ...
- Expiration date

I think this would be a great addition to the program.

I have screenshots of an app I use as an example. But unfortunately this has not been developed for 2 years. I think this app is great because I have a 6 person household from small children to adults. Then when a small child has a fever for example at 3am. Then I click on the child and enter fever and know exactly which ones to give. I have tried a few apps but this one is the best for large families and faster regarding age or allergy.

Sorry, screenshot is unfortunately only in German and you can not switch to English.

### First view and main view of the drug inventory
![First view](https://github.com/grocy/grocy/assets/4697822/d98ee0c6-2580-4bae-81e7-3709463d64b3)

### Filtered view
I have selected "6 Child and what my child's symptoms are.
![Filtered view](https://github.com/grocy/grocy/assets/4697822/93dd5844-ba6e-4003-aed8-d79f0317e935)
### 
Detail view
here you can see who is allowed to take this medicine and who is NOT allowed to take this medicine.
Notes, categories/main symptoms and information from the package insert.
Expiration date of the medicine
Amount that is still available.
General warning
![Detail view](https://github.com/grocy/grocy/assets/4697822/0514dc2f-a38d-47a5-806a-f62e57625373)

**Comment by berrnd** [comment] 2023-05-16 18:58
1. You can use Userfields to add any field to any existing entity (= products, a shopping list item, a chore, everything else) you want and based and that, Userentities can be created to create entire custom lists to track anything you want in grocy.
2. Most of grocy users, including me, track medicine just like normal products (at a separate location if this meets reality), because medicine is not that different than regular food items in regards to what's needed for tracking capabilities.
3. grocy's goal is to manage your fridge and household, not every aspect of your personal life - a project needs goals, this won't ever be a tool to manage each and every aspect of your life. Probably Excel fits better if you search for such a tool.
4. This is a duplicate of #1479 (and #1644) - please check existing requests before opening new ones.

**Closed as completed by berrnd** 2023-05-16 18:58 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2023-05-16 19:16
> I have screenshots of an app I use as an example. But unfortunately this has not been developed for 2 years. I think this app is great because I have a 6 person household from small children to adults. Then when a small child has a fever for example at 3am. Then I click on the child and enter fever and know exactly which ones to give. I have tried a few apps but this one is the best for large families and faster regarding age or allergy.

Sounds for me like the best option to use for what you want and that it obviously works practically pretty well.

Guess the only argument is then _"has not been developed for 2 years"_, whatever that means practically - seems at least not that it's about that it doesn't work, by what you've described here.

Guess what: Parts of grocy (you maybe use daily, when you use grocy) have not been developed for probably 5 years and they still work (great), even tomorrow and maybe also next week (if we all have luck, since I guess there will be no new release until then). If that's most important for you, I won't look that deep into any other app on this planet to not destroy illusions.

**Comment by zunami** [comment] 2023-05-16 20:02
Since the github search, failed I have searched for these entries.

I know this function and use it for something else.

Only I think there are: food, chires overview, tasks batteries overview, equipment
Why then not make a medicine chest area for all grocy users? _Order must be._
In addition, one can take over this area better in the Android app.

Maybe a **poll** on what others think would be a good idea to include something like this.

**Comment by berrnd** [comment] 2023-05-16 21:01
> Maybe a poll on what others think

Not needed. Since this here is my project, I define the goals and already have decided a longer time ago (ref, again, #1479) that this won't be added. Beside that, I'm the one who builds stuff here, at least that was the case for everything (at the end) so far, so if that poll says "build it" I have to build it (for free, in my spare time, just for my personal pleasure)? Cool idea.

Also just once again: Kind of all grocy users (check many threads about that topic on the [r/grocy subreddit](https://www.reddit.com/r/grocy) if you need "poll prove") track medicine just like normal product and it just works fine practically. Everything beyond stock management for medicine is definitely out of scope of this project, it can't be the solution for everything and the world.

But that here is all Open Source and I make it available to the world under a very permissive licence. Fork it, build that medicine cabinet, be happy. Or don't use grocy if that all doesn't satisfies you and start your complete own solution to manage, as just mentioned, everything and the world.
