### ISSUE TITLE
Feature Request: Sum values for parent products

### ISSUE THREAD

**Issue by elegantiron** [grocy/grocy#2184] opened 2023-03-28 17:46 UTC
I would like the Stocks screen to display the summed value of parent products. I am using grocy to track electronics components, and it would be useful (read: interesting to me) to be able to see e.g. the total value of all resistors I have. For my use case, all of my parent products have their individual stock disabled.

**Comment by berrnd** [comment] 2023-03-28 17:47
Duplicate of #1704.

**Closed by berrnd** 2023-03-28 17:47 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2023-03-28 17:50
And just for reference:

[/stockoverview](https://demo-prerelease.grocy.info/stockoverview) already does that:

![grafik](https://user-images.githubusercontent.com/2161815/228325054-e0bd7573-947c-4431-8ac7-9f186ae67b16.png)

The product card already does that:

![grafik](https://user-images.githubusercontent.com/2161815/228325199-4ae80720-24d2-46ff-a8ed-e04eddc6e23b.png)

**Comment by elegantiron** [comment] 2023-03-28 17:55
Hello,

Thank you for the quick response. I have already properly set up my parent products to sum their children's quantities.

As you can see, the values are not summed:
![image](https://user-images.githubusercontent.com/128913032/228326372-c804d29b-e442-49fe-aaf5-56ba1eb44d67.png)

**Comment by berrnd** [comment] 2023-03-28 17:59
> As you can see, the values are not summed:

Yes, I can see it, but I'm unable to look behind screenshots and therefore can't see every detail / option of every product, quantity unit and everything else involved in calculating that value, so I can't say anything at all.

Provide a reproducible example on a [persistent/private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) if you want me to look into it.

Beside that, this is the tracker for reproducible Bugs and Feature Requests, not for individual help questions: https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests

**Comment by elegantiron** [comment] 2023-03-28 18:04
> And please also note what the help tooltips say: The amount is summed up, not the value, which is another duplicate of #721.
The resolution to #721 indicates that this was added?

>So let's add that the parent products average costs (+ last price and everything else) are based on the child products costs when "Disable own stock" is enabled.

This is the *exact* behavior I want, and it is also the *exact* set up I have.

I will have to investigate further. Thank you for your time.

**Comment by berrnd** [comment] 2023-03-28 18:06
> The resolution to https://github.com/grocy/grocy/issues/721 indicates that this was added?

When something is done, the corresponding Issue / Feature Request is closed - #721 is not yet closed, so not yet done. My comment there is a simple reminder what to do when I (or someone else) start working on that at some time.
