### ISSUE TITLE
Bug: Disable own stock text and button masked by save and continue block.  

### ISSUE THREAD

**Issue by thystra** [grocy/grocy#2178] opened 2023-03-20 22:28 UTC
![grocy bug](https://user-images.githubusercontent.com/6511337/226478420-30eed62c-c732-46b6-84be-b071e869aca6.png)
Disable own stock at bottom of add product page is covered by save dialog box. 
Vivaldi browser vivaldi-stable/stable,now 5.7.2921.63-1

**Comment by berrnd** [comment] 2023-03-20 22:34
Duplicate of #2104, already fixed, not yet released.

Please try to reproduce problems on the [pre-release demo](https://demo-prerelease.grocy.info) (= current development state) first (as also mentioned on the issue template) and don't report everything as a bug by the first sight.

**Closed by berrnd** 2023-03-20 22:34 UTC
Labels: duplicate
