### ISSUE TITLE
Trying to filter Chores by Userfield in API

### ISSUE THREAD

**Issue by Galapagon** [grocy/grocy#1994] opened 2022-09-09 17:14 UTC
I'm trying to filter chores (eg: Vacuum, windows, counters) by a Room userfield (eg: Bedroom, bathroom, Kitchen). 

From the API:
 I can use /objects/chores to pull the userfields, but not due dates (exc.)
 I can use /chores to pull the due dates (exc.) but not userfields
 
Reading through the code, I believe the section that handles /chores starts on this line.
https://github.com/grocy/grocy/blob/ff056f8d81fbd1e696abf46599e965bffe04ad48/grocy.openapi.json#L5514-5548

I believe adding userfields to this section would allow them to be visible when attempting an API Get for /chores.

**Comment by berrnd** [comment] 2022-09-09 17:28
Duplicate of #1484.

**Closed by berrnd** 2022-09-09 17:28 UTC
Labels: duplicate
