### ISSUE TITLE
Bug: Recipe cost does not use child product prices when no stock is available

### ISSUE THREAD

**Issue by Rapatas** [grocy/grocy#2420] opened 2024-01-04 16:14 UTC
Demo instance: https://test-uz352i5r39zvgljr0x5bc.demo-prerelease.grocy.info/recipes

### Steps to reproduce
1. Create parent product
    - Quantity unit: "Pack"
    - Check "Disable own stock"
2. Create child product
    - Quantity unit: "Pack"
    - Check "Never show on stock overview"
3. Purchase child product with price 10$ per pack
4. Consume all of child product
5. Create recipe and add ingredient 1 pack of parent product

### Expected result
The recipe price is 10$

### Actual result
The recipe price is zero

### Other notes
If the child product has stock, the price is correct

**Comment by berrnd** [comment] 2024-01-04 16:22
It's nowhere stated that parent products somehow magically inherit prices of any child product, so this can't be a bug at all, even if you personally expect that this should be the case.

Duplicate of #721 - please check existing requests before opening new ones.

**Closed by berrnd** 2024-01-04 16:22 UTC
Labels: duplicate
