### ISSUE TITLE
Feature request: Fridge camera with ai object recognition

### ISSUE THREAD

**Issue by coolbombom** [grocy/grocy#2486] opened 2024-03-02 13:32 UTC
Hi

Would love to see ai object recognition, to automatically add items to my shopping list.

source for idea:
https://youtu.be/UrKvM-84e7M?t=37
https://www.youtube.com/watch?v=LKMaUHASTLw

open source project:
https://lezg.in/fridge-cam-with-home-assistant-and-machine-learning/#pre-requierments-id

Hope to see this implemented some day.

kind regards
c_bb

**Comment by berrnd** [comment] 2024-03-02 13:36
Duplicate of #917 - please check existing requests before opening new ones.

**Closed by berrnd** 2024-03-02 13:36 UTC
Labels: duplicate
