### ISSUE TITLE
Feature Request: Edit products faster

### ISSUE THREAD

**Issue by slimline33** [grocy/grocy#2049] opened 2022-11-22 18:59 UTC
Hi! I'm new to 
Hello, I am brand new on the road with grocy and I have now already invented my first products. Simply an ingenious concept.

It is quite tedious when you want to change something that applies to 80% of the created items. Therefore I have the following wish and I hope it is realizable:

It must be possible to change the data of a product under master data faster. Location, minimum stock, unit of measure, category...

Best of all it would be for a quick change on the web page /products with a double click in the table. Just tap on it or even better a selection menu. 

Will probably be very complex to implement, but an enormous relief when editing many articles.

Thanks Christoph

**Comment by berrnd** [comment] 2022-11-22 19:28
Everything is technically possible but what you suggested is, as you've also already mentioned, not implemented in 5 minutes - feel free to start it.

Duplicate of #1020 - please check existing requests first.

**Closed by berrnd** 2022-11-22 19:28 UTC
Labels: duplicate

**Comment by slimline33** [comment] 2022-11-23 07:21
Sorry, I guess I wasn't searching with the right terms.
