### ISSUE TITLE
Feature Request: Use Open Food Facts to get barcode information and contribute

### ISSUE THREAD

**Issue by kossm0** [grocy/grocy#2215] opened 2023-05-11 17:21 UTC
Open Food Facts is a food products database made by everyone, for everyone. Is a non-profit project developed by thousands of volunteers from around the world. [Discover](https://world.openfoodfacts.org/discover)

They have an API that could be quickly integrated into Grocy. Being able to obtain data and contribute to Open Food Facts for those new products:

[Wiki API information](https://wiki.openfoodfacts.org/API)

[GitHub API information](https://openfoodfacts.github.io/api-documentation/)

**Comment by berrnd** [comment] 2023-05-11 17:29
Duplicate of #158 (and #1136, and #1325, and #1376, #1921) - please check existing requests before opening new ones.

Also maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

**Closed by berrnd** 2023-05-11 17:29 UTC
Labels: duplicate

**Comment by DoinStuff35** [comment] 2024-01-06 15:07
> Also maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

The function is severely limited due to an API restriction:

https://github.com/Forceu/barcodebuddy/issues/227

@Forceu 

Any chance to change this?

**Comment by berrnd** [comment] 2024-01-06 15:18
@DoinStuff35: Please don't spam random threads with off-topic content.

Since the web frontend uses the API for everything, everything what's possible there is possible via the API. In fact it's not impossible to add barcodes to any product ([API endpoint ref](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/post_objects__entity_)), would be cool if you could avoid spreading incorrect claims - example:

```
POST objects/product_barcodes

{
  "product_id": 13,
  "barcode": "xx123"
}
```
