### ISSUE TITLE
Bug: Accidentally deleted Pack and Piece variables within the Product specifc QU conversions area when editing a Product + Blank dialogue when attempting to add QU conversions

### ISSUE THREAD

**Issue by bryandesrosiers** [grocy/grocy#2453] opened 2024-01-29 00:07 UTC
I am new to Grocy, so when I was fiddling around with an Product I had added into the system I naively deleted variables that were found in the Product specifc QU conversions section of the specific Product I was in. This has now affected the other Products I have input into the system.  See the screenshot with the red rectangle:
![image](https://github.com/grocy/grocy/assets/1483955/4963fc0e-16c4-485b-8d95-870c2149cbb7)

Then when I clicked "Add" beside that sections title bar, I got hit with a blank dialogue. See screenshot:
![image](https://github.com/grocy/grocy/assets/1483955/a04ecf90-7a50-49e2-847e-95fcc5ccfda2)

Looking for some insight on where to go.

**Comment by HammyHavoc** [comment] 2024-01-29 00:08
Can you rename the title to include `Blank dialogue when attempting to add QU conversions`?

**Comment by berrnd** [comment] 2024-01-29 03:19
The dialog problem is simply a duplicate of #2421, please be so kind and do a little search beforehand.

Grocy is built around [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), means not everything which could go wrong is technically prevented. If you deleted a somewhere used/referenced quantity unit, which just like never makes any sense at all, this potentially fucked up things badly - restore your backup or start over.

**Closed by berrnd** 2024-01-29 03:19 UTC
Labels: duplicate
