### ISSUE TITLE
Feature request: Select children product on recipe consumption

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#605] opened 2020-03-12 11:27 UTC
When creating recipes that use parent products as ingredients, it would be cool to be able to select which of the different children products to consume.

Probably related to https://github.com/grocy/grocy/issues/548

**Comment by berrnd** [comment] 2020-03-12 14:52
And releated to #385.

**Comment by organismen** [comment] 2020-05-12 10:25
Exactly what I was looking for!

It make sense to me after you click "Consume all products" that in the confirm modal that appears a list of all products to consume would appear with the ability to pick sub products to consume instead of parent product.

**Comment by berrnd** [comment] 2022-02-09 21:40
Duplicate of / merge into #548.

**Closed by berrnd** 2022-02-09 21:40 UTC
Labels: duplicate

**Comment by lyz-code** [comment] 2022-02-10 07:48
Thanks @berrnd for the feature and for maintaining `grocy` :)

**Comment by berrnd** [comment] 2022-02-10 07:49
Just if you got it wrong, "merged into" doesn't mean this is done, it will be further tracked in #548, which is about the same.
