### ISSUE TITLE
Feature request: Quantity unit hierarchy more than 1 level

### ISSUE THREAD

**Issue by ArchdukeTim** [grocy/grocy#1360] opened 2021-02-19 22:02 UTC
I current have a unit Liter that is linked to milliliters and gallons directly. Gallon is linked to Quarts, Quarts to Pints, Pints to Cups, etc. 

I should be able to choose 'Teaspoon' as a unit for my product when adding to recipe because there is a conversion path between Liters (the stock unit) and 'Teaspoon'. I currently can access 'teaspoon' by checking the 'only check if any amount is in stock' option, but this seems more like a bad hack than a proper solution.

**Comment by berrnd** [comment] 2021-02-20 07:49
Duplicate of #1217, please check existing requests/issues before opening new ones.

**Comment by berrnd** [comment] 2021-02-20 07:51
Sorry, was the wrong issue - this is more about that you want to have more than one level of nested QU conversions - that's currently limited to 1 level (like parent/child products), will rename the issue accordingly to track that there.

**Comment by Lykos153** [comment] 2022-09-30 15:52
I'd really love to see this feature in Grocy! Would you accept a PR on this? I briefly glanced at the code and saw that a lot of the logic is done on the SQL side (with which I don't have that much experience yet, unfortunately). Would you mind sharing where you would start if you were to implement this feature?

**Comment by berrnd** [comment] 2022-09-30 16:39
> Would you accept a PR on this?

Every contribution was and is accepted, as long as it works, doesn't break anything else and doesn't introduce whole new concepts (like e.g. [rewriting the whole project](https://github.com/grocy/grocy/pull/1510), just because the tech-stack used and the tech-design-decisions made are not up to someones personally likings - something like that is better fits in an [own](https://github.com/HouseHold/HouseHold) [fork](https://github.com/mistressofjellyfish/not-grocy)).

&nbsp;
> saw that a lot of the logic is done on the SQL side

That's one of those base-tech-design-decisions for grocy and should stay, unless it's really not possible by that approach.

&nbsp;
> Would you mind sharing where you would start if you were to implement this feature?

The central SQL view which resolves QU conversions is [`quantity_unit_conversions_resolved`](https://github.com/grocy/grocy/blob/e8f76e5694f2defb69435bccfaeb8de96870322c/migrations/0189.sql) (the "final list", used everywhere else, which holds all possible conversions/factors per product).

So this somehow needs to be extended to use a recursive approach (while not introducing endless loops due to e.g. bad user data; [SQLite docs ref](https://www.sqlite.org/lang_with.html#recursive_common_table_expressions), [practical grocy example](https://github.com/grocy/grocy/blob/e8f76e5694f2defb69435bccfaeb8de96870322c/migrations/0174.sql) used for resolving unlimited levels of nested recipes) to resolve the then unlimited conversion hierarchy instead of the currently fixed defined 4 options / 1 level.

Then every place / other SQL views where this view is used need to be checked, but probably that's already all. The web fontend currently doesn't enforce the 1 level hierarchy, more levels just don't resolve.

**Closed** 2022-12-04 12:12 UTC
Labels: enhancement
