### ISSUE TITLE
Feature Request: Simple Import/Export options

### ISSUE THREAD

**Issue by fortepc** [grocy/grocy#1756] opened 2022-01-23 05:39 UTC
As I'm getting started in Grocy after discovering the Home Assistant add-on and I'm finding myself doing a lot of really basic set up that I feel many people before me have done before. Setting up my master data. And it would be so much more helpful if some of this starting work was able to be shared. 

I'm also starting to recommend a family member of mine to use grocy, and it would make it way easier to recommend it if I could export my master data as a starting point for them. 

I saw #644, and that may also be a decent alternative solution to this as well. But I still think simple import/export options would be a better solution because there are plenty of circumstances where I may want to share master data as a snapshot rather than a ongoing share.

**Comment by berrnd** [comment] 2022-01-23 08:22
Duplicate of #129.

**Closed by berrnd** 2022-01-23 08:22 UTC
Labels: duplicate
