### ISSUE TITLE
Recipe: quantity below <1 not saved in R-ingredients

### ISSUE THREAD

**Issue by Melvidor** [grocy/grocy#909] opened 2020-07-05 10:59 UTC
Hi,
I am playing with Grocy 2.7.1 and trying "cook" china noodles. Basicly for 4 portion I need half china noodles, 1 spoon soyce and half of frozen vegetable. I am adding ingredients to recipe as 0,5 but after saving it shows that I need 0 of each. _(even Grocy says it cant be less than 0,01)

Allowed partial unit, Factor QU 1

I could use Factor QU for noodles and vegetable but that Stock overview doesn't shows package but only factors QU. 

EDIT:
Another example (maybe better): a cake.
Setting Product: flour (1bag=1kg), shoping unit 1Piece (bag), store unit 1 kg. Conversion 1kg = 1000g

Adding ingredients: 250g flour. Selected grams, grocy says in Blue thats equel to 0,25kg.  OK. 
Save&refresh and when I look to recipe summary then I need 0g Flour and I have it on stock. (I have not buy it)

This exampled tested with and without Allowed partial unit.

Same result.

Michal

**Comment by berrnd** [comment] 2020-07-06 06:35
If you could reproduce this on the [demo](https://demo.grocy.info), would be great.

Maybe related to #794.

**Comment by Melvidor** [comment] 2020-07-06 16:18
Done. Created Melvidor_cake/kg/g/flour. 

I'll make a demonstration of China recipe next week. I am off

**Comment by berrnd** [comment] 2020-07-06 17:17
Thanks, so seems to be just a display issue on the recipes page, the saved values are correct.

So the problem is somewhere here:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/views/recipeform.blade.php#L171-L192

**Comment by Melvidor** [comment] 2020-07-06 17:31
I dont thinks. Melvidor_flour is 0 in stock and recipe overview says Enough ingredients.

**Comment by berrnd** [comment] 2020-07-06 17:47
Most probably the same issue (something about rounding) - the value is saved for sure, when you edit the ingredient `250` (`0.25` in the database because it's always related to the products stock QU) is there.

To verify this when the demo gets recreated in a couple of hours, here is a snapshot of the current demo database:
[grocy.db.zip](https://github.com/grocy/grocy/files/4880454/grocy.db.zip)

**Comment by berrnd** [comment] 2020-08-18 17:48
Seems to be also fixed by #876.

**Closed by berrnd** 2020-08-18 17:48 UTC
Labels: ui-bug
