### ISSUE TITLE
Feature Request: Adding a 'Quick Buy' Button on 'Stock Overview' Page for Easier Use

### ISSUE THREAD

**Issue by othmanalikhan** [grocy/grocy#2022] opened 2022-10-11 11:02 UTC
#### Problem

I have users in my household that are very bad at using computers (consider elderly parents). So I plan on deploying a tablet in the kitchen with Grocy running on the "Stock Overview" page.

The "Stock Overview" page itself is easy use to use for consuming items since there are two green/red buttons to consume items, however, there isn't an adjacent button to them to add items to stock (there is though the triple dot button, then you can add items but that is too hard for my parents).

Another issue is that before I go for shopping, I like double checking my stock. Using the "Stock Overview" page, it is very easy to deplete items by pressing the red/green consume buttons. But adding items is a slight nuisance since it requires four actions (press triple dots button > Purchase > Modify Amount > Ok button). This is especially problematic when doing this for a lot of items.

#### Solution/Feature

Similar to the "Shopping List" page, adding a "Quick Add" button would be very helpful. This will allow Grocy users (and hence my parents and myself too) to quickly add and consume items directly from the "Stock Overview" page.

#### Implementation

I've started working on implementing this button on my local instance of Grocy (see screenshot below). I'd like to know what are your thoughts on this feature request @berrnd.

Currently I've added added the button to the frontend, calls the relevant API on the backend, and everything works. But it needs a bit more code tweaking to be generalized (e.g. Need to create a new entry in the DB to store the 'quick_purchase_amount' variable).

![image](https://user-images.githubusercontent.com/5261295/195070239-3b1e4c96-8933-4c73-aba9-8d77ed8f13e0.png)

**Comment by othmanalikhan** [comment] 2022-10-11 11:11
Oh one more thing, unless I've missed it, are there any automated tests for Grocy? If not, is there any formal test checklist or equivalent? It would be nice to have some form of automated testing since I'm new to the Grocy codebase.

**Comment by berrnd** [comment] 2022-10-11 11:22
There has been a lot of discussion in the past about what buttons/actions should be directly in the first table column and which in the more/context menu. At the end that's personal preference and nothing about that will be changed, use [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to change anything to your personal likings without having to maintain your own fork or something like that.

Also a duplicate of #1997.

&nbsp;
> But adding items is a slight nuisance since it requires four actions (press triple dots button > Purchase > Modify Amount > Ok button).

Well, a purchase transaction requires usually more data than just an amount...

&nbsp;
> are there any automated tests for Grocy? If not, is there any formal test checklist or equivalent?

No and this project doesn't need that.

**Closed by berrnd** 2022-10-11 11:22 UTC
Labels: wontfix/out-of-scope

**Comment by othmanalikhan** [comment] 2022-10-11 11:37
Thank you for the super speedy reply.

> There has been a lot of discussion in the past about what buttons/actions should be directly in the first table column and which in the more/context menu. At the end that's personal preference and nothing about that will be changed, use [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to change anything to your personal likings without having to maintain your own fork or something like that.

Missed that one. I would imagine the custom JS should meet my needs since I can modify the table after it renders (or before if possible).

> Well, a purchase transaction requires usually more data than just an amount...

Yes, that is true. The idea at least was to use last inputted data if available to fill the other information, otherwise fill only the bare minimum needed.
