### ISSUE TITLE
Feature request: Stockoverview table options extension

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1393] opened 2021-03-01 21:39 UTC
Hello togehter,

it would be great, to get the default location visualized on stockoverview.

![grafik](https://user-images.githubusercontent.com/39962016/109562683-febc1700-7ade-11eb-9a91-6650fd9f1558.png)

Best regards,

Phil

**Comment by berrnd** [comment] 2021-03-01 21:43
Duplicate of #1351 - please check existing requests before opening new ones.

**Closed by berrnd** 2021-03-01 21:43 UTC
Labels: enhancement

**Comment by berrnd** [comment] 2021-03-01 21:45
> please check existing requests before opening new ones

Even more important when it's your own request... ;D

**Comment by horphi0815** [comment] 2021-03-01 21:59
embarrassing.....please ignore me in  the future... :-P
