### ISSUE TITLE
Feature Request: UI improvement - move the "Save" button next to "Cancel"

### ISSUE THREAD

**Issue by monsieurhannes** [grocy/grocy#2182] opened 2023-03-26 10:01 UTC
Hi,

Adding product groups and so on in master data, there are multiple situations where the "save" button is in the content field while the "cancel" button is on the bottom of the window. Intuitively it's very likely to click on the cancel button, just when you finished adding all your information (maybe I'm the only one doing that, but I can't imagine...)
It's good that "save" is green, that highlights it well and I noticed that most save buttons in Grocy are on the lower left side (relatively new user, like it so far), good to stay with that everywhere.

Here are two examples:
![image](https://user-images.githubusercontent.com/20651440/227768195-3220f2ec-b260-41dc-9711-75853d525d24.png)

This one even has the save button hidden unless scrolling down.
![image](https://user-images.githubusercontent.com/20651440/227768210-b5178582-f30b-47c3-8003-78f85df1a632.png)

I'd suggest to keep the save/cancel interface separate from the content interface by having both under the little separation line - if possible.
![image](https://user-images.githubusercontent.com/20651440/227768432-bfcdd547-34a3-4d10-bbba-c7bd567b2810.png)

Thank you for this great app!

**Comment by berrnd** [comment] 2023-03-26 10:07
Duplicate of #1367 - please check existing requests before opening new ones.

**Closed by berrnd** 2023-03-26 10:07 UTC
Labels: duplicate
