### ISSUE TITLE
Bug: ReverseProxyAuthMiddleware - Cannot login

### ISSUE THREAD

**Issue by Gsyltc** [grocy/grocy#1563] opened 2021-08-05 04:28 UTC
Hi,

I tried to use the ReverseProxyAuthMiddleware, but functionnality dos not work

ReverseProxy : Traefik V2 with ForwardAuth
SSO : Authelia
User Header : "Remote-User" 
Version Docker : V3.0.1 (V3.1.0 don't work properly for me)

Here the stack trace 
Error source:
```
/app/grocy/middleware/ReverseProxyAuthMiddleware.php:47
```

Error message:
```
Not implementedArray
```

Stack trace:
```
#0 /app/grocy/controllers/LoginController.php(28): Grocy\Middleware\ReverseProxyAuthMiddleware::ProcessLogin()
#1 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin()
#2 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#3 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#4 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#5 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#6 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#7 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#8 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#9 /app/grocy/middleware/AuthMiddleware.php(36): class@anonymous->handle()
#10 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#11 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#13 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#14 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#15 /app/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#16 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#18 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#19 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#20 /app/grocy/app.php(94): Slim\App->run()
#21 /app/grocy/public/index.php(45): require_once('/app/grocy/app....')
#22 {main}
```

Config file  :  

```
Setting('DISABLE_AUTH', true); (// same result with false)
Setting('AUTH_CLASS', 'Grocy\Middleware\ReverseProxyAuthMiddleware');
Setting('REVERSE_PROXY_AUTH_HEADER', 'Remote-User');
```

Here my SSO logs : 
```
time="2021-08-05T04:11:51Z" level=debug msg="Check authorization of subject username= groups= ip=10.0.0.6 and object https://grocy.mydomain.com/login (method GET)."

time="2021-08-05T04:11:51Z" level=info msg="Access to https://grocy.mydomain.com/login (method GET) is not authorized to user <anonymous>, redirecting to https://auth.mydomain.com?rd=https%3A%2F%2Fgrocy.mydomain.comh%2Flogin&rm=GET" method=GET path=/api/verify remote_ip=10.0.0.6

time="2021-08-05T04:12:01Z" level=debug msg="Check authorization of subject username=sylvain groups= ip=10.0.0.6 and object https://grocy.mydomain.com/login (method GET)."

time="2021-08-05T04:12:01Z" level=debug msg="Required level for the URL https://grocy.mydomain.com/login is 1" method=POST path=/api/firstfactor remote_ip=10.0.0.6

time="2021-08-05T04:12:01Z" level=debug msg="Redirection URL https://grocy.mydomain.com/login is safe" method=POST path=/api/firstfactor remote_ip=10.0.0.6

time="2021-08-05T04:12:02Z" level=debug msg="Check authorization of subject username=sylvain groups= ip=10.0.0.6 and object https://grocy.mydomain.com/login (method GET)."

time="2021-08-05T04:12:02Z" level=debug msg="Check authorization of subject username=sylvain groups= ip=10.0.0.6 and object https://grocy.mydomain.com/node_modules/@danielfarrell/bootstrap-combobox/css/bootstrap-combobox.css?v=3.0.1 (method GET)."

time="2021-08-05T04:12:03Z" level=debug msg="Check authorization of subject username=sylvain groups= ip=10.0.0.6 and object https://grocy.mydomain.com/node_modules/datatables.net-colreorder-bs4/js/colReorder.bootstrap4.min.js?v=3.0.1 (method GET)."

time="2021-08-05T04:12:03Z" level=debug msg="Check authorization of subject username=sylvain groups= ip=10.0.0.6 and object https://grocy.mydomain.com/node_modules/datatables.net/js/jquery.dataTables.min.js?v=3.0.1 (method GET)."

time="2021-08-05T04:12:03Z" level=debug msg="Check authorization of subject **username=sylvain** groups= ip=10.0.0.6 and object https://grocy.mydomain.com/js/extensions.js?v=3.0.1 (method GET)."

time="2021-08-05T04:12:03Z" level=debug msg="Check authorization of subject **username=** groups= ip=10.0.0.6 and object https://grocy.mydomain.com/img/appicons/site.webmanifest?v=3.0.1 (method GET)."

```

I could see two problems. 
1° The user name is lost during the call in Grocy. 
2° The Authenticate method is not called

Thanks

**Comment by berrnd** [comment] 2021-08-05 09:59
Sounds strange since `ReverseProxyAuthMiddleware->ProcessLogin` should never be called because this middleware doesn't provide a login page, code ref:
https://github.com/grocy/grocy/blob/1891bc6f3256fe3fa3dd820e48e553f782510f65/middleware/ReverseProxyAuthMiddleware.php#L42-L45

Personally don't use that so I need to create a test environment first to be able to debug that...

Just a rough guess: Does this maybe only happen on the `/login` route and you access that explicitly/manually? There should be no redirect to `/login` when using `ReverseProxyAuthMiddleware`...

**Comment by Gsyltc** [comment] 2021-08-05 13:09
When I connect to my login page (Authelia), I arrive on the Grocy login page.

For this reason, I even tried to disable the login page with the Setting('DISABLE_AUTH', true) property;
But it didn't change anything,. The login page of Grocy was still displayed.

I have a "prod" environment and 1 "test" environment. I will try to find out where the problem comes from.
It may be a problem with the configuration of my SSO/ReverseProxy. I didn't look too hard on this side because I have 7 other services behind my SSO, and I don't have any problem. But you never know.


Translated with www.DeepL.com/Translator (free version)

**Comment by Gsyltc** [comment] 2021-08-21 22:56
Update : 
Grocy version updated from linuxserver.io/grocy:V3.0.1 to linuxserver.io/grocy:V3.1.0
Same problem

Call the grocy page => Authelia page for login => Login OK => Grocy login page.

Will try the V3.1.1 as soon as possible.

**Comment by berrnd** [comment] 2021-08-22 10:54
I've tested that now myself, very basic `ReverseProxyAuthMiddleware` test case:

config.php (changed values only):
```
Setting('AUTH_CLASS', 'Grocy\Middleware\ReverseProxyAuthMiddleware');
```

nginx site config (passes a user named "test1" for all requests; of course this not something for real setups; grocy runs on `http://localhost:30005` in that example):
```
location / {
	proxy_pass http://localhost:30005;
	proxy_set_header Remote-User test1;
}
```

=> No login page is shown by grocy and all requests are authenticated in context of `test1` user.

&nbsp;

I don't have any experience with Authelia, but even when the `REVERSE_PROXY_AUTH_HEADER` header (`Remote-User` by default) is not passed, grocy displays a corresponding error page and never redirects to the login page. So don't have any clue what's going on on your setup.

However, not a bug, so closing this - maybe try the [subreddit](https://www.reddit.com/r/grocy/) for any help on setting this up.

I've searched around a bit and found that LinuxServer.io has an example for exactly grocy + Authelia - [this](https://github.com/linuxserver/reverse-proxy-confs/blob/master/grocy.subdomain.conf.sample) file (which also references [this](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/authelia-server.conf) and [that](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/authelia-location.conf) via includes).

**Closed by berrnd** 2021-08-22 10:54 UTC
Labels: question

**Comment by Gsyltc** [comment] 2021-08-22 13:59
Hi,

Tested and it works with Treafik with the new version

Have a nice day.


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Bernd ***@***.***>
Envoyé le :dimanche 22 août 2021 06:54
À : ***@***.***>
Cc : Sylvain ***@***.***>; ***@***.***>
Objet :Re: [grocy/grocy] Bug: ReverseProxyAuthMiddleware - Cannot login (#1563)


I've tested that now myself, very basic ReverseProxyAuthMiddleware test case:

config.php (changed values only):

Setting('AUTH_CLASS', 'Grocy\Middleware\ReverseProxyAuthMiddleware');



nginx site config (passes a user named "test1" for all requests; of course this not something for real setups; grocy runs on http://localhost:30005 in that example):

location / {



        proxy_pass http://localhost:30005;



        proxy_set_header Remote-User test1;



}



=> No login page is shown by grocy and all requests are authenticated in context of test1 user.



I don't have any experience with Authelia, but even when the REVERSE_PROXY_AUTH_HEADER header (Remote-User by default) is not passed, grocy displays a corresponding error page and never redirects to the login page. So don't have any clue what's going on on your setup.

However, not a bug, so closing this - maybe try the subreddit<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fgrocy%2F&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636333741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JnAfslZmeqXfAVBnTyu2BvaQm8QhNTI9gjUs3m%2FRC3I%3D&reserved=0> for any help on setting this up.

I've searched around a bit and found that LinuxServer.io has an example for exactly grocy + Authelia - this<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinuxserver%2Freverse-proxy-confs%2Fblob%2Fmaster%2Fgrocy.subdomain.conf.sample&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636343696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6N2vWS1QFlUE%2BsZuSgGrnQgCDCLmfQ3XN5iw0%2BAN588%3D&reserved=0> file (which also references this<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinuxserver%2Fdocker-swag%2Fblob%2Fmaster%2Froot%2Fdefaults%2Fauthelia-server.conf&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636343696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TWi7hA2WgdldrzZFkl1f8M7NMQ0MDN8C0GriC0GgUoU%3D&reserved=0> and that<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinuxserver%2Fdocker-swag%2Fblob%2Fmaster%2Froot%2Fdefaults%2Fauthelia-location.conf&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636348676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=thtF%2BlQPfydful5GOW4kBL5vygZ8tH2NL30vYc%2BH3OU%3D&reserved=0> via includes).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrocy%2Fgrocy%2Fissues%2F1563%23issuecomment-903249816&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636353652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oW1vGa7TicOvUMvbuMjow7NGHcS0fdfdA3L4t5vQwHE%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEZY7BJT7QWYXY7JYI7RBCLT6DJN3ANCNFSM5BSTVHOA&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636358633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RhBHAEZmZ9eRLQ%2BuDotd2%2FTTPyxIcjDuQ2CFyaRxzGo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636363611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rRiC8fv9KI%2Fqbm1jRfuKXQNEUp7q%2BejnPqTd247byzc%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C66f54f036c9b4aabd2b708d9655b331b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637652264636368588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DP4EHul8fWPht%2BycqU1ugwJzPEHJaWyVuEOkodixhXo%3D&reserved=0>.
