### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by coderunway** [grocy/grocy#1853] opened 2022-04-10 10:06 UTC
"Transfer" Option - 

1. I created two locations - 'Medicine' ,  'Room' 
2. Added an item with a quantity (amount) of 17 via Purchase,  under Location 'Medicine'
3. Verified I can see the item and  the quantity (amount) of 17 under 'Medicine' in the Stock Overview Page 
4. I transfer 7 quantities of this item from Location 'Medicine' to  Location 'Room', via the 'Transfer' page. It's successful. 
5. Expectation - This should leave only 10 quantities in the 'Store' and 7 quantities in 'Room' Location
6. I go to Stock Overview, I see 17 quantities listed for the item in 'Room' and also in 'Medicine'
7. Expectation - It should show only 7 quantities if I filter Location as 'Room'. 

See screenshot 
![image](https://user-images.githubusercontent.com/22704812/162613122-bdab6d44-54b6-4c7d-bd73-d7d5eb727779.png)

**Comment by berrnd** [comment] 2022-04-10 10:19
Not a bug, the /stockoverview page shows an overview of your stock, not the details of every single stock entry. Simply look at the /stockentries page if you want to see the details.

Also just a duplicate of #1531, #1259, #682 and https://www.reddit.com/r/grocy/comments/g44dm2 - just read through them to clarify any misunderstandings.

**Closed by berrnd** 2022-04-10 10:19 UTC
Labels: duplicate
